### DISCUSSION TITLE
Firebase phone auth not working

### DISCUSSION THREAD

**Discussion by ibragimazizli** [firebase/flutterfire#12581] [Q&A]
Hello everyone.

I added firebase phone auth in my app. but it's not sending sms codes to devices. ( real device) sometimes test numbers works fine. but after couple of hours it stop working.

I've added sha1 sha256 keys from google console and local keys and it still not working. I've done all the things internet says about it but it still not working:

Flutter doctor:

```

flutter doctor -v 
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-AZ)
    • Flutter version 3.19.5 on channel stable at /Users/ibrahimebdulezizli/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (7 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ibrahimebdulezizli/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/ibrahimebdulezizli/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone (mobile)             • 00008110-001C10A922D9401E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 123.0.6312.106
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

Pubspec:

```

version: 1.0.1+6

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cache:
    path: packages/cache
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.13.6
  connectivity_plus: ^6.0.1
  country_flags: ^2.2.0
  country_picker: ^2.0.24
  cupertino_icons: ^1.0.2
  dashed_circular_progress_bar: ^0.0.6
  device_info_plus: ^10.0.1
  device_preview: ^1.1.0
  dlibphonenumber: any
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  firebase_analytics: ^10.8.10
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.0
  flow_builder: ^0.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^6.0.4
  flutter_local_notifications: ^17.0.0
  flutter_notification_channel: ^3.1.0
  flutter_otp_text_field: ^1.1.1
  flutter_prevent_screen_capture: ^0.0.2
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_storage_path: ^1.0.4
  flutter_story_view: ^0.0.3
  flutter_svg_provider: ^1.0.7
  font_awesome_flutter: ^10.6.0
  geolocator: ^11.0.0
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  gradient_borders: ^1.0.0
  http: ^1.1.2
  image_picker: ^1.0.5
  intl: ^0.18.1
  libphonenumber: ^2.0.2
  loader_overlay: ^4.0.0
  location: ^5.0.3
  lottie: any
  meta: any
  otp_pin_field: ^1.2.2
  pay: ^2.0.0
  permission_handler: ^11.0.1
  persistent_bottom_nav_bar: ^5.0.2
  sentry_flutter: ^7.14.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sizer: ^2.0.15
  skeletonizer: ^1.0.1
  sliding_drawer: ^1.0.2
  story_view: ^0.16.0
  svg_flutter: ^0.0.1
  telephony: ^0.2.0
  transparent_image: ^2.0.1
  url_launcher: ^6.2.5

dependency_overrides:
  image_picker_android: 0.8.4+13

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

```

build.gradle:
```

dependencies {
    // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:32.8.0')
    implementation 'com.android.billingclient:billing:6.2.0'
    // Add the dependencies for the App Check libraries
    implementation 'com.android.support:multidex:2.0.1'
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation("com.google.firebase:firebase-appcheck-playintegrity")
    implementation("com.google.firebase:firebase-auth-ktx") -----> ( I've used auth and auth-ktx nothing changes)
    implementation("com.google.firebase:firebase-appcheck-debug:16.0.0-beta01")
    implementation ("com.google.android.play:integrity:1.3.0")
    implementation 'com.facebook.android:facebook-login:latest.release'
    implementation("com.google.firebase:firebase-analytics")
    implementation("com.google.firebase:firebase-crashlytics")
    implementation("com.google.firebase:firebase-perf")
    // local notification
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
    implementation 'androidx.browser:browser:1.3.0' 
    implementation 'com.google.android.gms:play-services-safetynet:18.0.1'
    implementation 'androidx.window:window:1.1.0-alpha04'
    implementation 'androidx.window:window-java:1.0.0'


}
```

Debug console ( With test number): 

```

I/zzb     (13716): ForceRecaptchaV2Flow from phoneAuthOptions = false, ForceRecaptchav2Flow from firebaseSettings = false
W/System  (13716): Ignoring header X-Firebase-Locale because its value was null.
D/TrafficStats(13716): tagSocket(95) with statsTag=0xffffffff, statsUid=-1
W/LocalRequestInterceptor(13716): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.
D/TrafficStats(13716): tagSocket(167) with statsTag=0xffffffff, statsUid=-1
E/zzb     (13716): Failed to initialize reCAPTCHA config: No Recaptcha Enterprise siteKey configured for tenant/project *
W/System  (13716): Ignoring header X-Firebase-Locale because its value was null.
W/LocalRequestInterceptor(13716): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
D/TrafficStats(13716): tagSocket(161) with statsTag=0xffffffff, statsUid=-1
I/PlayCore(13716): UID: [10215]  PID: [13716] IntegrityService : requestIntegrityToken(IntegrityTokenRequest{nonce=zUUiZ9D4qbTngoXq3A_IIPVDuS527zX2Y9eqoEW17jY, cloudProjectNumber=551503664846, network=null})
I/PlayCore(13716): UID: [10215]  PID: [13716] IntegrityService : Initiate binding to the service.
I/PlayCore(13716): UID: [10215]  PID: [13716] IntegrityService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.integrityservice.IntegrityService})
I/PlayCore(13716): UID: [10215]  PID: [13716] IntegrityService : linkToDeath
I/PlayCore(13716): UID: [10215]  PID: [13716] OnRequestIntegrityTokenCallback : onRequestIntegrityToken
I/PlayCore(13716): UID: [10215]  PID: [13716] IntegrityService : Unbind from service.
W/System  (13716): Ignoring header X-Firebase-Locale because its value was null.
W/LocalRequestInterceptor(13716): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.
W/JavaBinder(13716): BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.play.integrity.internal.u
I/BpBinder(13716): onLastStrongRef automatically unlinking death recipients: 
D/TrafficStats(13716): tagSocket(179) with statsTag=0xffffffff, statsUid=-1
W/FirebaseAuth(13716): [SmsRetrieverHelper] Timed out waiting for SMS.
```

Debug console with real number:

```
zzb     (13716): ForceRecaptchaV2Flow from phoneAuthOptions = false, ForceRecaptchav2Flow from firebaseSettings = false
W/System  (13716): Ignoring header X-Firebase-Locale because its value was null.
W/LocalRequestInterceptor(13716): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.
E/zzb     (13716): Failed to initialize reCAPTCHA config: No Recaptcha Enterprise siteKey configured for tenant/project *
I/PlayCore(13716): UID: [10215]  PID: [13716] IntegrityService : requestIntegrityToken(IntegrityTokenRequest{nonce=91bF6l0749j1CTK2pEMWqlPTQDwalBapNxb_4qGbuVw, cloudProjectNumber=551503664846, network=null})
I/PlayCore(13716): UID: [10215]  PID: [13716] IntegrityService : Initiate binding to the service.
I/PlayCore(13716): UID: [10215]  PID: [13716] IntegrityService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.integrityservice.IntegrityService})
I/PlayCore(13716): UID: [10215]  PID: [13716] IntegrityService : linkToDeath
I/PlayCore(13716): UID: [10215]  PID: [13716] OnRequestIntegrityTokenCallback : onRequestIntegrityToken
I/PlayCore(13716): UID: [10215]  PID: [13716] IntegrityService : Unbind from service.
W/System  (13716): Ignoring header X-Firebase-Locale because its value was null.
W/LocalRequestInterceptor(13716): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
E/FirebaseAuth(13716): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17028 Invalid app info in play_integrity_token
D/FirebaseAuth(13716): Invoking original failure callbacks after phone verification failure for +994559559356, error - This app is not authorized to use Firebase Authentication. Please verify that the correct package name, SHA-1, and SHA-256 are configured in the Firebase Console. [ Invalid app info in play_integrity_token ]
[log] This app is not authorized to use Firebase Authentication. Please verify that the correct package name, SHA-1, and SHA-256 are configured in the Firebase Console. [ Invalid app info in play_integrity_token ]
```
in addition google console shows play integrity incomplete :

<img width="727" alt="image" src="https://github.com/firebase/flutterfire/assets/97028411/fbc174b9-ddf3-47bc-9811-bfdb629cfc5f">
