### DISCUSSION TITLE
Flutterfire dependencies from git

### DISCUSSION THREAD

**Discussion by sollyow** [firebase/flutterfire#12682] [Q&A] [answered]
I can't set my pubspec to use FlutterFire dependencies from a forked git repo:
```
firebase_storage:
    git:
      url: https://github.com/etc/flutterfire
```

**Comment by SoroushBeigi** [comment, marked as answer]
You should define the path as well, like so:
```
firebase_storage:
    git:
      url: https://github.com/etc/flutterfire
      path: packages/firebase_storage/firebase_storage
```
