### DISCUSSION TITLE
[firebase_messaging] FCM not working in Release Mode

### DISCUSSION THREAD

**Discussion by sageata** [firebase/flutterfire#3880] [Q&A]
Since iOS 14 and the new Stable, the FCM doesn't work in Release Mode.

Does anyone faces this issue?

I do use flutter_local_notifications as well and they are both configured correctly as in the Debug Mode, everything works well.

Unfortunately I cannot test with xCode since xCode 12 and iOS 14.

I am quite stuck here.

```
name: App Name
description: The best eCrew App

version: 3.3.0+40

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_platform_widgets: ^0.32.4
  in_app_purchase: ^0.3.4+15
  flutter_redux: ^0.6.0
  redux: ^4.0.0
  cloud_firestore: ^0.14.0+3
  firebase_auth: ^0.18.0+2
  firebase_core: ^0.5.0
  flutter_calendar: ^0.0.9
  device_info: ^0.4.1+5
  json_annotation: ^3.1.0
  package_info: ^0.4.0+14
  firebase_remote_config: ^0.3.0+1 
  http: ^0.12.0+4
  flutter_svg: ^0.18.0
  path_provider: ^1.6.21
  url_launcher: ^5.7.5
  shared_preferences: ^0.5.6+2
  timezone: ^0.5.7
  connectivity: ^0.4.8+1
  share_extend: ^1.1.1
  devtools: ^0.1.10
  font_awesome_flutter: ^8.10.0
  flare_flutter: ^2.0.1
  sticky_headers: ^0.1.8+1
  draggable_flutter_list: ^1.0.3
  cached_network_image: ^2.0.0
  firebase_analytics: ^5.0.11
  admob_flutter: ^1.0.0
  crypto: ^2.1.3
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^2.0.1
  background_fetch: ^0.6.0
  firebase_crashlytics: ^0.1.3+3
  store_redirect: ^1.0.2
  device_calendar: ^3.0.0+3
  auto_size_text: ^2.1.0
  webview_flutter:
    git: https://github.com/sageata/webview_pull_to_refresh
  firebase_storage: ^4.0.1
  image_picker: ^0.6.3+4
  html: ^0.14.0+3
  xml2json: ^4.4.0
  flutter_form_builder: ^3.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  
targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: true
          create_factory: true
          create_to_json: true
          explicit_to_json: false
          field_rename: none
          nullable: true


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/img/icon.png"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/login_logo.png
    - assets/img/app_store_icon.png
    - assets/img/log_ten_pro.svg
    - assets/img/play_store.png
    - assets/white_logo_transparent.svg
    - assets/img/ThankYou500.png
    - packages/timezone/data/latest_all.tzf
    - assets/animations/success.flr 
    - assets/animations/wood-trophy.flr
    - assets/animations/gold-trophy.flr
    - assets/animations/silver-trophy.flr
    - assets/animations/coin.flr

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: WorkSansSemiBold
    #   fonts:
    #     - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    # - family: WorkSansBold
    #   fonts:
    #     - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    # - family: WorkSansMedium
    #   fonts:
    #     - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
    - family: MyIcons
      fonts:
        - asset: assets/fonts/MyIcons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```

I do have the Proxy Set to False in Plist.info:

```
<key>FirebaseAppDelegateProxyEnabled</key>
<false/>
```

Also the UNUserNotifications delegate is set in the AppDelegate.swift
```
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }
```

Everything worked fine in my previous release, however, all of a sudden it's not working any longer.

I tried stable, dev, beta and master channels, all with same result.

I archived and installed it with App Distribution.

Am I missing something?

I am hard stuck at this issue for a few days now, please help.

Please help!
