### DISCUSSION TITLE
Null Safety [Update: All packages now migrated.]

### DISCUSSION THREAD

**Discussion by Yegorisa** [firebase/flutterfire#4182] [Feature request] [answered]
Since Null Safety is in beta, it is time to update Flutter Firebase libraries to support null safety. Are there any timelines on this? Thanks!

----

EDIT (@Salakar): All packages are now migrated - thanks everyone 🙂

**Comment by Salakar** [comment, marked as answer]
Yes! All the reworked plugins are currently being migrated to nullsafety.

----

## Progress

### Remove deprecated APIs (COMPLETE)

 - [x] Core; PR https://github.com/FirebaseExtended/flutterfire/pull/4591
 - [x] Firestore; PR https://github.com/FirebaseExtended/flutterfire/pull/4594
 - [x] Authentication; PR https://github.com/FirebaseExtended/flutterfire/pull/4590
 - [x] Functions; PR https://github.com/FirebaseExtended/flutterfire/pull/4592
 - [x] Storage; PR https://github.com/FirebaseExtended/flutterfire/pull/4593
 - [x] Crashlytics; PR https://github.com/FirebaseExtended/flutterfire/pull/4595

----

### Nullsafety Migration

 - [x] Analytics (now available as a dev release)
 - [x] Authentication; PR https://github.com/FirebaseExtended/flutterfire/pull/4633
 - [x] Core; PR https://github.com/FirebaseExtended/flutterfire/pull/4656
 - [x] Crashlytics; PR https://github.com/FirebaseExtended/flutterfire/pull/4715
 - [x] Dynamic Links (now available as a dev release)
 - [x] Firestore; PR #4780
 - [x] Functions; PR https://github.com/FirebaseExtended/flutterfire/pull/4691
 - [x] Messaging; PR #4909
 - [x] Performance Monitoring; PR #5540
 - [x] Storage; PR #4753
 - [x]  Remote Config; #5686
 - [x] ML Vision; #5474
 - [x] In app messaging; #5676
 - [x] Database; #5441

### Other PRs/blockers
 
 - [x] Auth Example app using packages that have no nullsafety releases, refactor to remove usages;
    - `flutter_signin_button` , `google_sign_in` & `google_sign_in_web`
 - [x]  https://github.com/FirebaseExtended/flutterfire/pull/4209 (significant changes to Firestore to improve multi-isolate behaviour)
 - [x] https://github.com/FirebaseExtended/flutterfire/pull/4263 (blocking testing stability on Auth without this)
 - [x] https://github.com/FirebaseExtended/flutterfire/pull/4249
 - [x] Docs: update FlutterFire plugin rework migration guide to note versions where deprecated APIs were removed entirely.
 - [x] Web e2e tests on CI currently failing on all branches ('cannot find device `web`')

----

We'll update this as we go along.

**Reply by Ehesp** [reply]
Update on this:

- We're first going to run a mock migration, adding hints where necessary. This will be merged in (non-versioned since it's hints only)
  - Auth: https://github.com/FirebaseExtended/flutterfire/pull/4370
  - Firestore: https://github.com/FirebaseExtended/flutterfire/pull/4350
- Once complete, we'll create a `nullsafety` version / branch of the packages, keeping them in sync with main repo and packages.

Whenever null safety officially lands, these will be graduated to new major versions (since it's breaking change with the minimum required version).

**Reply by ovestoerholt** [reply]
Will there be a testable beta on pub.dev?

**Reply by Ehesp** [reply]
Yep, very soon we're hoping.

**Reply by ovestoerholt** [reply]
Awesome! Thanks!

**Reply by IchordeDionysos** [reply]
@Salakar @Ehesp what about the non-reworked plugins, like
- Performance Monitoring
- Dynamic Links

or recently reworked plugins like:
- Analytics
- Remote Config

Do you have updates when these will be migrated?

**Reply by ammaratef45** [reply]
Any updates on Remote Config?

**Comment by mehmetf** [comment]
Target date was EOY. Any updates please?

**Reply by Levi-Lesches** [reply]
```
SyntaxError: unexpected EOY while working
```

**Comment by Salakar** [comment]
Hey all, apologies there's been some delays - we've had to revisit our approach on applying the migrations and had a few blockers but we've now brought in additional resource/team members on board to help with this migration so I imagine things will move pretty quickly again.

I've updated my original comment with more specifics for tracking progress.

**Comment by DevNico** [comment]
Is there any timeline on when [firebase_ml_vision](https://pub.dev/packages/firebase_ml_vision) will be migrated to null safety?

EDIT: Fixed link - I apparently forgot how to md for a second there...

**Reply by Salakar** [reply]
cc @kroikie

**Reply by AlexHartford** [reply]
I have a PR out for this: https://github.com/FirebaseExtended/flutterfire/pull/5474
You can pull from my branch in your pubspec.yaml until it gets merged and a new version is published. As it is pending review be wary of breaking changes but shouldn't be anything major.

**Reply by Salakar** [reply]
This was released today. Thanks :)

**Comment by Purus** [comment]
There is lot of version issues when using packages with null-safety and packages without null safety. Would love to see the updates for firestore.

**Reply by Salakar** [reply]
Hopefully landing later today or tomorrow, going through final review at the moment.

**Reply by Salakar** [reply]
This landed last night, see https://firebase.flutter.dev/docs/null-safety/

**Reply by DaveWillie** [reply]
Is there any news on when the Firebase Realtime Database support for web in Flutter will be?

**Comment by jlubeck** [comment]
Is there no work being done for Analytics null safety? I don't see it on the list

**Reply by muhlba91** [reply]
same here and i believe many are using analytics - hence, this is a real blocker for upgrading to full nnbd.

**Reply by Bilonik** [reply]
Same 👍

**Reply by rahulraj64** [reply]
@Salakar @Ehesp Any updates on analytics plugin null safety? This is a blocker! If you can share an ETA, we can plan accordingly. Thanks

**Reply by pinpong** [reply]
It's the last package before compile null safety. It's also important for all of my projects.

**Reply by IchordeDionysos** [reply]
@pinpong you may want to pull the changes from my branch :) 
https://github.com/FirebaseExtended/flutterfire/pull/5341

This includes null-safety, but bear in mind that there might be breaking changes depending on @Salakar and @Ehesp review :)

**Reply by pinpong** [reply]
@IchordeDionysos not able to build. Can you paste how to add to pubspec please?

**Reply by IchordeDionysos** [reply]
@pinpong I hope this works :D I am fairly confident but did this in the browser :) 

Let me know if it does. If not I'll again test it myself first and will update my example then.

```yaml
dependencies:
  firebase_analytics:
    git:
      url: https://github.com/simpleclub-extended/flutterfire.git
      ref: feature/analytics-null-safety
      path: packages/firebase_analytics/firebase_analytics
      
# Might also have to add this :)
dependency_overrides:
  firebase_analytics_platform_interface:
    git: https://github.com/simpleclub-extended/flutterfire.git
    ref: feature/analytics-null-safety
    path: packages/firebase_analytics/firebase_analytics_platform_interface
  firebase_analytics_web:
    git: https://github.com/simpleclub-extended/flutterfire.git
    ref: feature/analytics-null-safety
    path: packages/firebase_analytics/firebase_analytics_web
```

**Reply by abegehr** [reply]
@IchordeDionysos, I think the dependency_overrides should be like this:

```yaml
#TODO https://github.com/FirebaseExtended/flutterfire/pull/5341
dependency_overrides:
  firebase_analytics_platform_interface:
    git:
      url: https://github.com/simpleclub-extended/flutterfire.git
      ref: feature/analytics-null-safety
      path: packages/firebase_analytics/firebase_analytics_platform_interface
  firebase_analytics_web:
    git:
      url: https://github.com/simpleclub-extended/flutterfire.git
      ref: feature/analytics-null-safety
      path: packages/firebase_analytics/firebase_analytics_web
```
