### DISCUSSION TITLE
Firebase Analytics not compatible with null safety

### DISCUSSION THREAD

**Discussion by a-v-ebrahimi** [firebase/flutterfire#5108] [Q&A]
I tried to move my project to new new Dart and make it null safety compatible but seems firebase_analytics is still not ready.
How can I bypass this error, are they going to release firebase_analytics null safety soon?

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^0.8.0-1.0.nullsafety.2
  firebase_messaging: ^9.0.0-1.0.nullsafety.1
  firebase_analytics: ^7.0.1
  firebase_crashlytics: ^0.5.0-1.0.nullsafety.3
```

When I compile I get this error :

```
Because firebase_analytics >=7.0.1 depends on firebase_core ^0.7.0 and ketab depends on firebase_core ^0.8.0-1.0.nullsafety.2, firebase_analytics >=7.0.1 is forbidden.
So, because yourapp depends on firebase_analytics ^7.0.1, version solving failed.
pub get failed (1; So, because yourapp depends on firebase_analytics ^7.0.1, version solving failed.)
```
