### DISCUSSION TITLE
Cloud_Firestore module not found when building debug.

### DISCUSSION THREAD

**Discussion by amatier** [firebase/flutterfire#5648] [Q&A]
I have been trying to build my app but keep getting the error from both flutter and Xcode that Module 'cloud_firestore' was not found

Xcode error:
ios/Runner/GeneratedPluginRegistrant.m:10:9: Module 'cloud_firestore' not found

Flutter error:
ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'cloud_firestore' not found
    @import cloud_firestore;
     ~~~~~~~^~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

I've searched up all over this page and all over stackoverflow as well what could cause this issue. I was told that running `pod deintegrate` and `pod install` would fix it and it didn't. I've run `flutter clean` a bunch and nothing. I've deleted my Pods folder and my Podfile.lock numerous times. I've updated my dependencies to the newest and still no luck. So I'm just wondering if anyone else has had this issue.

Below you can find my pubspec.yaml, podfile, error output and my flutter doctor -v

pubspec.yaml
```
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0

  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  firebase_storage: ^8.0.1
  firebase_analytics: ^7.1.1
  firebase_messaging: ^9.1.0
  

  form_field_validator: ^1.0.1

  provider: ^5.0.0

  material_design_icons_flutter: ^4.0.5855
  auto_size_text: ^2.1.0
  flutter_glow: ^0.2.0

  uuid: ^3.0.3
  image_picker: ^0.7.4
  image_cropper: ^1.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
```


podfile

```
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

# Add the Firebase pod for Google Analytics
  # flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))


  pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  # pod 'Firebase/Firestore'
  pod 'FirebaseFirestore', :git=>'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag=>'7.3.0'



post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
end
```

error output
```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/alexm/carebloom/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'cloud_firestore' not found
    @import cloud_firestore;
     ~~~~~~~^~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.
```

Flutter Doctor -v
```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.2 20D80 darwin-x64, locale en-US)
    • Flutter version 2.0.3 at /Users/alexm/flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/alexm/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Alex’s iPhone (mobile)     • 00008030-00040C3801EA802E            • ios            • iOS 14.5
    • iPhone 12 Pro Max (mobile) • 680F5865-7F31-4C5F-8371-D2FFA74129DB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

If you need any other information from me just let me know and I'll provide as much as I can! I'm honestly stumped. 

Also I know this may look like a duplicate of another issue but every other issue dealing with the 'cloud_firestore' error I've found the fixes that worked for them have not worked for me so its possible my issue is different.
