### DISCUSSION TITLE
URGENT :  -> Could not find com.google.firebase:firebase-bom:26.2.0. Error coming

### DISCUSSION THREAD

**Discussion by RageshAntony** [firebase/flutterfire#5762] [Q&A]
I am having a problem in building 

Getting error : 

```
Building plugin firebase_core...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   21.5s


FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':generateReleaseRFile'.
> Could not resolve all files for configuration ':releaseRuntimeClasspath'.
   > Could not find com.google.firebase:firebase-bom:26.2.0.
     Searched in the following locations:
       - https://storage.googleapis.com/download.flutter.io/com/google/firebase/firebase-bom/26.2.0/firebase-bom-26.2.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/google/firebase/firebase-bom/26.2.0/firebase-bom-26.2.0.jar
     Required by:
         project :
   > Could not find com.google.firebase:firebase-common:.
     Required by:
         project :
   > Could not find androidx.annotation:annotation:1.1.0.
     Searched in the following locations:
       - https://storage.googleapis.com/download.flutter.io/androidx/annotation/annotation/1.1.0/annotation-1.1.0.pom
       - https://storage.googleapis.com/download.flutter.io/androidx/annotation/annotation/1.1.0/annotation-1.1.0.jar
     Required by:
         project :

```

**DETAILS** : 

Flutter Version : 2.0.3 Stable 

**Pubspec.yaml** : 
```
name: driver
description: A Driver application.
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_crashlytics: ^2.0.0
  firebase_messaging: ^9.1.1
  firebase_core: ^1.0.3
  gen_lang: ^0.1.3
  shared_preferences: ^2.0.5
  graphql_flutter: ^5.0.0-nullsafety.2
  permission_handler: ^6.1.1
  http: ^0.13.1
  connectivity: ^3.0.3
  http_parser: ^4.0.0
  cached_network_image: ^3.0.0
  adhara_socket_io:
    # ^0.4.2+1
    path: ./adhara_socket_io-0.4.2+1_changed/
  flutter_google_places: ^0.3.0
  flutter_svg: ^0.21.0+1
  page_transition: ^1.1.7+6
  flutter_html: ^2.0.0-nullsafety.0
  google_maps_flutter: ^2.0.3
  flutter_polyline_points: ^0.2.6
  google_maps_webservice: ^0.0.19
  geolocator: ^7.0.2
  package_info: ^2.0.0
  flutter_local_notifications: ^5.0.0+1
  vector_math: ^2.1.0
  flutter_spinkit: ^5.0.0
  lottie: ^1.0.1
  flutter_webview_plugin: ^0.3.11
  geocoding: ^2.0.0
  location: ^4.1.1
  url_launcher: ^6.0.3
  image_picker: ^0.7.4
  app_settings: ^4.1.0
  rxdart: ^0.26.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  cached_network_image: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - res/
    - res/drawable/
    - res/drawable/flags/
    - res/graphql/
    - assets/cities.json
    - assets/map_style.txt
    - assets/lottieloader.json

  fonts:
    - family: Circular
      fonts:
        - asset: font/poppins.ttf
```

**Project  build.gradle** 

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.apollographql.apollo:apollo-gradle-plugin:2.2.3"
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.3.0'

    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }

    configurations.all {
        resolutionStrategy.force "androidx.core:core:1.0.2"
        resolutionStrategy {
            force 'androidx.fragment:fragment:1.0.0'
            force 'com.google.android.material:material:1.0.0'
            force "com.google.android.gms:play-services-ads:19.3.0"
            force "com.google.android.gms:play-services-base:17.3.0"
            force "com.google.android.gms:play-services-basement:17.3.0"
            force "com.google.android.gms:play-services-location:17.0.0"
            force "com.google.android.gms:play-services-maps:17.0.0"
            force 'com.android.support:support-annotations:27.1.1'
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**app build.gradle** 

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '2'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0.1'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.apollographql.apollo'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.firebase.crashlytics'
android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.driver.driver"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 22
        versionName '1.8.2'
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug

        }
    }
}
configurations.all {
    exclude group: 'org.json', module: 'json'
    resolutionStrategy.force "com.google.android.gms:play-services-ads:19.3.0"
    resolutionStrategy.force "com.google.android.gms:play-services-base:17.3.0"
    resolutionStrategy.force "com.google.android.gms:play-services-basement:17.3.0"
    resolutionStrategy.force "com.google.android.gms:play-services-location:17.0.0"
    resolutionStrategy.force "com.google.android.gms:play-services-maps:17.0.0"
    resolutionStrategy.force 'com.android.support:support-annotations:27.1.1'
}

flutter {
    source '../..'
}

configurations.all {
    resolutionStrategy.force "com.google.android.gms:play-services-ads:19.3.0"
    resolutionStrategy.force "com.google.android.gms:play-services-base:17.3.0"
    resolutionStrategy.force "com.google.android.gms:play-services-basement:17.3.0"
    resolutionStrategy.force "com.google.android.gms:play-services-location:17.0.0"
    resolutionStrategy.force "com.google.android.gms:play-services-maps:17.0.0"
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.android.gms:play-services-auth:16.0.0'
    implementation 'com.google.firebase:firebase-messaging:20.0.1'
    implementation "com.google.android.gms:play-services-location:15.0.1"
    implementation "com.apollographql.apollo:apollo-runtime:2.2.3"
    implementation "com.apollographql.apollo:apollo-coroutines-support:2.2.3"
    def lifecycle_version = "2.2.0"
    implementation 'com.github.nkzawa:socket.io-client:0.6.0'
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    implementation 'com.stripe:stripe-android:16.5.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.0.0'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation platform('com.google.firebase:firebase-bom:25.12.0')
    implementation 'com.google.android.gms:play-services-auth:18.1.0'
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation 'com.google.firebase:firebase-messaging:20.0.1'
    implementation 'androidx.annotation:annotation:1.0.0'
    implementation 'com.airbnb.android:lottie:2.7.0'
    implementation 'com.google.guava:guava:27.0.1-android'
}

```

Please help me to resolve this issue . I am in urgency
