### DISCUSSION TITLE
Snapshot dont get updated ?

### DISCUSSION THREAD

**Discussion by userdontknow** [firebase/flutterfire#6198] [Q&A]
I have a problem with my snapshot . Im using a streambuilder on one page and the snapshot in another but the snapshot dont gets updated . I cannot figure out why . This is first where I declare the stream 
```

class Comments2N extends StatefulWidget {
  final snapshot;
  final String id;
  final VoidCallback onTaps;


  final int index;
  final FocusNode myFocusNode;

  const Comments2N(
      {Key key,
      this.snapshot,
      this.comment,
      this.id,
      this.index,
      @required this.onTaps,
      this.myFocusNode})
      : super(key: key);
  @override
  _Comments2NState createState() => _Comments2NState();
}

class _Comments2NState extends State<Comments2N> {
  String currentcomment;
  Stream stream;
  Stream stream2;



  @override
  void initState() {
    super.initState();
    stream = FirebaseFirestore.instance
        .collection('meinprofilsettings')
        .doc(widget.snapshot.data.docs[widget.index].data()["uid"])
        .snapshots();
    stream2 = FirebaseFirestore.instance
        .collection('videos')
        .doc(widget.id)
        .collection('comments')
        .doc(
          widget.comment.data()['id'],
        )
        .collection("commentlikes")
        .doc(uid)
        .snapshots();
  }


  likecomment(String id, String timestamp) async {
 -----
    }
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
        stream: stream,
        builder: (context, _snapshot) {
          if (_snapshot.connectionState == ConnectionState.waiting) {
            return SizedBox.shrink();
          } else {
            return StreamBuilder(
                stream: stream2,
                builder: (context, snapshot) {
              
                  if (snapshot.connectionState == ConnectionState.waiting) {
                    return SizedBox.shrink();
                  } else {
                    return 
                 CommentsWidget(
                      
                      ----
                          snapshot: snapshot,
                      
                          
                          liking: () {
                       
                            likecomment(widget.comment.data()['id'],
                                DateTime.now().toString());
                             
                          },
                        ));
                  }
                });
```
And then using the snapshot in the commentswidget 
```
class CommentsWidget extends StatefulWidget {
  final snapshot;
  final VoidCallback liking;

  const CommentsWidget(
    
    @required this.liking,
    @required this.snapshot,
  });

  @override
  _CommentsWidgetState createState() => _CommentsWidgetState();
}



class _CommentsWidgetState extends State<CommentsWidget> {  

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      Container(
          child: ListTile(
        leading: GestureDetector(
----- 
trailing: InkWell(
          onTap: () {
            widget.liking();
         
          },
          child: widget.snapshot.data.exists
              ? Icon(
                  Icons.star,
                  size: 25,
                  color: Colors.yellow,
                )
              : Icon(
                  Icons.star_border_outlined,
                  size: 25,
                ),
        ),

```
So as you can I call the callback to liked a post when user press the star icon. And that works fine but displaying the star in yellow if the user liked the video does not work correctly . This is only working when I leave the page and come back then I get the correct data . And thats the only case for what im using the snapshot . Hope anyone can help if you need more information please leave a comment 

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale
    de-DE)
    • Flutter version 2.0.6 at /Users/yavuzatmaca/flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/yavuzatmaca/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

Heres the pubsec 
```

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_functions: ^1.0.0
  firebase_core_web: ^1.0.0
  provider: ^5.0.0
  flutter_svg: ^0.19.3
  flutter_spinkit: ^5.0.0
  auto_size_text: ^2.1.0
  firebase_core: ^1.0.0
  get_it: ^6.0.0
  flutter_staggered_grid_view: ^0.3.4
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  firebase_storage: ^8.0.6
  http: ^0.13.0
  random_string: ^2.1.0
  timeago: ^3.0.2
  video_player: ^2.1.0
  video_compress: ^3.0.0
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  get: ^4.1.4
  audioplayers: ^0.18.3
  share: ^2.0.1
  get_storage: ^2.0.2
  dropdown_search: ^0.5.0
  dropdownfield: ^1.0.3
  firebase_analytics: ^8.0.1
  visibility_detector: ^0.2.0
  flutter_share: ^2.0.0
  url_launcher: ^6.0.3
  flutter_datetime_picker: ^1.5.1
  dismissible_page: ^0.6.1
  flutter_switch: ^0.3.1
  rflutter_alert: ^2.0.2
  shimmer: ^2.0.0
  firebase_messaging: ^9.1.4
  
  
```
