### DISCUSSION TITLE
[cloud_firestore] See if a key and value exist in a map in an array in a field in a collection

### DISCUSSION THREAD

**Discussion by prawnydagrate** [firebase/flutterfire#6289] [Q&A]
My Cloud Firestore database is structured like this:
```yml
chats (collection)
  - xxxxxxxxx (field with id)
    - users: list<string>
    - messages: list<map<string, dynamic>>
      - 0
        - sender: string
        - body: string
        - timestamp: int
        - id: string
users (collection)
  ...
```

How do I look for a message throughout the whole `chats` collection with a certain `id`? Because each time a user sends a message, I need to generate an `id` for the message but also make sure that no other message has the exact same `id`.
