### DISCUSSION TITLE
[firebase_crashlytics: ^2.0.2]libc.so (missing)

### DISCUSSION THREAD

**Discussion by Shubhankt1** [firebase/flutterfire#6306] [Q&A]
I am working on a product and we have our flutter app where I am using `webview_plugin: ^2.0.4`. While the user is inside the webview and uses it for sometime, either the app crashes or the webview page gets closed.

The problem is, after crash when I see the Crashlytics dashboard, there isn't any meaningful data for the crash.
**NOTE: This happens in Samsung devices only.**

## Steps to Reproduce
1.  Open the app and open the webview page.
2. Use it for a while and wait for the crash to happen.

**Expected results:** 
I should get meaningful crash reports in the Crashlytics.
**Actual results:** 

```
Crashed: Thread :  SIGTRAP  0x0000288c0000235c
#00 pc 0x78557278a4 libmonochrome.so 
#01 pc 0x7855727750 libmonochrome.so 
#02 pc 0x7856d71f00 libmonochrome.so 
#03 pc 0x7854447aa4 libmonochrome.so 
#04 pc 0x7855df2240 libmonochrome.so 
#05 pc 0x7855d53be4 libmonochrome.so 
#06 pc 0x78566505bc libmonochrome.so 
#07 pc 0x7856650580 libmonochrome.so 
#08 pc 0x7856650508 libmonochrome.so 
#09 pc 0x793c119da8 libutils.so 
#10 pc 0x793c1199ac libutils.so 
#11 pc 0x793c35d020 libandroid_runtime.so 
#12 pc 0x73663b80 boot-framework.oat 
#13 pc 0x709e39c0 boot.oat 
#14 pc 0x736603e8 boot-framework.oat 
#15 pc 0x78b7e7da88 libart.so 
#16 pc 0x733fc400 boot-framework.oat 
#17 pc 0x78b7e757e8 libart.so 
#18 pc 0x78b7eeaa94 libart.so 
#19 pc 0x78b829fc64 libart.so 
#20 pc 0x7938cd8bd4 libc.so 
#21 pc 0x793c3b5aec libandroid_runtime.so 
#22 pc 0x731de610 boot-framework.oat 
#23 pc 0x73a928f8 boot-framework.oat 
#24 pc 0x78b821efd0 libart.so 
#25 pc 0x709cc6f4 boot.oat 
#26 pc 0x73a8f068 boot-framework.oat 
#27 pc 0x73a9903c boot-framework.oat 
#28 pc 0x78b7e757e8 libart.so 
#29 pc 0x78b7eeaa94 libart.so 
#30 pc 0x78b7e0a6ec libart.so 
#31 pc 0x78b829e6a0 libart.so 
#32 pc 0x78b829eb54 libart.so 
#33 pc 0x78b83f6ffc libart.so 
#34 pc 0x78b7dd252e libart.so 
#35 pc 0x78b7df0e4f libart.so 
#36 pc 0x78b7deeed1 libart.so 
#37 pc 0x78b8182afc libart.so 
#38 pc 0x78b7dfc766 libart.so 
#39 pc 0x793c2e2424 libandroid_runtime.so 
#40 pc 0x793c3ecffc libandroid_runtime.so 
#41 pc 0x793c3ecffc libandroid_runtime.so 
#42 pc 0x793c3ed4a4 libandroid_runtime.so 
#43 pc 0x793c2ea244 libandroid_runtime.so 
#44 pc 0x793c3ecffc libandroid_runtime.so 
#45 pc 0x57f7bfac11 app_process64 
#46 pc 0x7938cd8ea0 libc.so 
#47 pc 0x7938cd8bd4 libc.so 
#48 pc 0x793c116fdc libutils.so 
#49 pc 0x793c2e6784 libandroid_runtime.so 
#50 pc 0x57f7bfc594 app_process64 
#51 pc 0x57f7c00084 app_process64 
#52 pc 0x57f7c00084 app_process64 
#53 pc 0x57f7c00044 app_process64 
#54 pc 0x793c3d3d7c libandroid_runtime.so 
#55 pc 0x57f7c00084 app_process64 
```

```
ANR caused by:
Thread
#00 pc 0x7938d6a8a8 libc.so 
#01 pc 0x783bdd3b40 libflutter.so 
```

<details>
  <summary>Logs</summary>

`flutter doctor -v`:

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.4 20F71 darwin-x64, locale
    en-IN)
    • Flutter version 2.0.5 at /Users/shubhanktyagi/Developer/flutter
    • Framework revision adc687823a (7 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/shubhanktyagi/Library/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/shubhanktyagi/Library/Android/Sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 9E1F9CAF-3CB6-4237-ABC6-6F4C8B88022A • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

</details>

<details>
  <summary>Files</summary>

`pubspec.yaml`:

```yaml
name: tipotapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dio: ^4.0.0
  get: ^3.25.4
  path: ^1.7.0
  mime: ^0.9.7
  http: ^0.13.1
  lottie: ^1.0.1
  encrypt: ^5.0.0
  sqflite: ^1.3.2+2
  archive: ^3.1.2
  location: ^4.1.1
  uni_links: ^0.4.0
  jwt_decode: ^0.2.0
  # local_auth: ^0.6.3+4
  connectivity: ^3.0.3
  path_provider: ^2.0.1
  pin_code_fields: ^6.1.0
  webview_flutter: ^2.0.4
  cupertino_icons: ^0.1.2
  progress_dialog: ^1.2.4
  cloud_firestore: ^1.0.7
  string_validator: ^0.1.4
  onesignal_flutter: ^2.6.2
  shared_preferences: ^2.0.5
  firebase_analytics: ^8.0.4
  cached_network_image: ^2.5.0
  firebase_crashlytics: ^2.0.2
  flutter_inappwebview: ^5.3.2
  flutter_secure_storage: ^3.3.5
  flutter_statusbarcolor: ^0.2.3
  firebase_dynamic_links: ^2.0.2
  # flutter_webview_plugin: ^0.3.11
  flutter_barcode_scanner: ^1.0.2
  amazon_cognito_identity_dart_2: ^1.0.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  #adaptive_icon_background: "#ffffff" # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "#ffffff" # only available for Android 8.0 devices and above


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/mobile-loading.json
   - assets/images/
   - assets/images/safetyapps/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CodecCold
      fonts:
        - asset: assets/fonts/Codec-Cold-Regular-trial.ttf
        - asset: assets/fonts/Codec-Cold-ExtraBold-trial.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

`build.gradle`:

```Gradle
buildscript {
    ext.kotlin_version = '1.3.61'
    repositories {
        google()
        jcenter()
        // maven {
        //    url 'https://maven.fabric.io/public'
        // }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.4'
        classpath 'com.google.gms:google-services:4.3.4'
        // classpath 'io.fabric.tools:gradle:1.31.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
    project.configurations.all {
	resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.drawerlayout' &&
	       !details.requested.name.contains('androidx')) {
		details.useVersion "1.0.0"
            }
            if (details.requested.group == 'androidx.core' &&
	       !details.requested.name.contains('androidx')) {
		details.useVersion "1.1.0"
            }
            if (details.requested.group == 'androidx.appcompat' &&
	       !details.requested.name.contains('androidx')) {
		details.useVersion "1.0.2"
            }
	}
    }    
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

`app/build.gradle`:

```Gradle
buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'kotlin-android'
// apply plugin: 'io.fabric'

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 29

    lintOptions {
        disable 'InvalidPackage'
    }

    sourceSets {
        main {
            res.srcDirs = [keystoreProperties['resourcePath']]
        }
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId keystoreProperties['applicationId']
        minSdkVersion 21
        targetSdkVersion 29
        versionCode keystoreProperties['versionCode'].toInteger()
        versionName keystoreProperties['versionName']
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }  
        resValue "string", "app_name", keystoreProperties['applicationName']
    }

    splits {
        abi {
            reset()
            enable false
            universalApk false
            include "armeabi-v7a", "arm64-v8a"
        }
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            // android.enableR8 true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            /* Add the firebaseCrashlytics extension (by default,
            * it's disabled to improve build speeds) and set
            * nativeSymbolUploadEnabled to true. */
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
                unstrippedNativeLibsDir "$buildDir/intermediates/merged_native_libs/release/out/lib"
                strippedNativeLibsDir "$buildDir/intermediates/stripped_native_libs/release/out/lib"
            }
        }

        debug {
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
                unstrippedNativeLibsDir "$buildDir/intermediates/merged_native_libs/debug/out/lib"
                strippedNativeLibsDir "$buildDir/intermediates/stripped_native_libs/debug/out/lib"
            }
        }
    }
}

tasks.whenTaskAdded { task ->
  if (task.name.startsWith('assemble') && task.name != "assembleReleaseAndroidTest" && task.name != "assembleDebugAndroidTest") {
    // if (task.name.endsWith('Release')) {
        task.finalizedBy "uploadCrashlyticsSymbolFile" + task.name.substring('assemble'.length())
    // }
    println task.name
  }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0-beta01'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0-beta01'
    implementation 'com.android.support:multidex:1.0.3'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-crashlytics-ndk:17.3.0'
}
```
