### DISCUSSION TITLE
When Upgrade cloud_firestore to  ^2.4.0

### DISCUSSION THREAD

**Discussion by monxarat** [firebase/flutterfire#6835] [Q&A]
Hi guys,

how to resolve this is a problem.

```
Launching lib/main.dart on Pixel 3a in debug mode...
Running Gradle task 'assembleDebug'...
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java:19: error: cannot find symbol
import com.google.firebase.firestore.LoadBundleTaskProgress;
                                    ^
  symbol:   class LoadBundleTaskProgress
  location: package com.google.firebase.firestore
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java:158: error: cannot find symbol
      ByteArrayOutputStream stream, LoadBundleTaskProgress snapshot) {
                                    ^
  symbol:   class LoadBundleTaskProgress
  location: class FlutterFirebaseFirestoreMessageCodec
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/streamhandler/LoadBundleStreamHandler.java:6: error: cannot find symbol
import com.google.firebase.firestore.LoadBundleTask;
                                    ^
  symbol:   class LoadBundleTask
  location: package com.google.firebase.firestore
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java:292: error: cannot find symbol
          Query query = Tasks.await(firestore.getNamedQuery(name));
                                             ^
  symbol:   method getNamedQuery(String)
  location: variable firestore of type FirebaseFirestore
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java:80: error: cannot find symbol
    } else if (value instanceof LoadBundleTaskProgress) {
                                ^
  symbol:   class LoadBundleTaskProgress
  location: class FlutterFirebaseFirestoreMessageCodec
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java:81: error: cannot find symbol
      writeLoadBundleTaskProgress(stream, (LoadBundleTaskProgress) value);
                                           ^
  symbol:   class LoadBundleTaskProgress
  location: class FlutterFirebaseFirestoreMessageCodec
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java:166: error: package LoadBundleTaskProgress does not exist
    LoadBundleTaskProgress.TaskState taskState = snapshot.getTaskState();
                          ^
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java:170: error: cannot find symbol
      case RUNNING:
           ^
  symbol:   variable RUNNING
  location: class FlutterFirebaseFirestoreMessageCodec
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java:173: error: cannot find symbol
      case SUCCESS:
           ^
  symbol:   variable SUCCESS
  location: class FlutterFirebaseFirestoreMessageCodec
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java:176: error: cannot find symbol
      case ERROR:
           ^
  symbol:   variable ERROR
  location: class FlutterFirebaseFirestoreMessageCodec
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/streamhandler/LoadBundleStreamHandler.java:25: error: cannot find symbol
    LoadBundleTask task = firestore.loadBundle(bundle);
    ^
  symbol:   class LoadBundleTask
  location: class LoadBundleStreamHandler
/Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/streamhandler/LoadBundleStreamHandler.java:25: error: cannot find symbol
    LoadBundleTask task = firestore.loadBundle(bundle);
                                   ^
  symbol:   method loadBundle(byte[])
  location: variable firestore of type FirebaseFirestore
Note: /Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/test/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.4.0/android/src/main/java/io/flutter/plugins/firebase/firestore/streamhandler/TransactionStreamHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cloud_firestore:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Exception: Gradle task assembleDebug failed with exit code 1

```

pubspec.yaml

```
name: test
description: test

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1+2

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # english_words,
  english_words: ^4.0.0

  # staggered grid view
  # https://pub.dartlang.org/packages/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.4.0

  # https://pub.dartlang.org/packages/flutter_sparkline#-installing-tab-
  #flutter_sparkline: ^0.1.0
  chart_sparkline: ^1.0.3

  # https://pub.dev/packages/charts_flutter#-installing-tab-
  # charts_flutter: ^0.10.0

  # sqflite
  # https://pub.dartlang.org/packages/sqflite
  sqflite: ^2.0.0+3

  # path_provider package to get the commonly used location such as TemporaryDirectory
  # and ApplicationDocumentsDirectory
  path_provider: ^2.0.1

  # https://pub.dartlang.org/packages/flutter_tags
  flutter_tags: ^1.0.0-nullsafety.1

  # https://pub.dartlang.org/packages/camera
  camera: ^0.8.1

  #image_picker: 0.4.12+1

  http: ^0.13.1

  # https://pub.dartlang.org/packages/shared_preferences
  shared_preferences: ^2.0.5

  # https://github.com/mmcc007/modal_progress_hud
  #modal_progress_hud: ^0.1.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0


  # https://pub.dartlang.org/packages/datetime_picker_formfield
  datetime_picker_formfield: ^2.0.0

  # https://pub.dartlang.org/packages/fluttertoast
  #fluttertoast: ^8.0.3

  #https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.0.0

  # localization
  #intl_translation: ^0.17.10+1
  font_awesome_flutter: ^9.0.0
  firebase_auth: ^3.0.1
  google_sign_in: ^5.0.7
  cloud_firestore: ^2.4.0
  firebase_database: ^7.1.2
  firebase_storage: ^10.0.1
  fluttertoast: ^8.0.3
  #flutter_material_color_picker: ^1.0.5
  flutter_colorpicker: ^0.4.0
  #intl: ^0.16.0
  back_button_interceptor: ^5.0.0
  firebase_core: ^1.4.0
  # Add localization dependencies
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/
  - assets/img/login_logo.png

  fonts:
  - family: WorkSansSemiBold
    fonts:
    - asset: assets/fonts/WorkSans-SemiBold.ttf

  - family: WorkSansBold
    fonts:
    - asset: assets/fonts/WorkSans-Bold.ttf

  - family: WorkSansMedium
    fonts:
    - asset: assets/fonts/WorkSans-Medium.ttf
flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
  localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/flutter-localization-workflow
    project_id: # Get it from the https://app.localizely.com/projects page.
    branch: # Get it from the “Branches” page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
    download_empty_as: # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false
```
