### DISCUSSION TITLE
once i add firebase_analytics to pubspec.yaml ios wan't run

### DISCUSSION THREAD

**Discussion by egphp** [firebase/flutterfire#6891] [Q&A]
once i add firebase_analytics to pubspec.yaml ios wan't run

my build platform :ios, '10.0'

and when just add firebase_analytics i get error my build 8.0 not 10.0

my podfile

```

# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
ENV['SWIFT_VERSION'] = '5'
use_frameworks!
use_modular_headers!

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

$FirebaseAnalyticsWithoutAdIdSupport = true

pod 'Firebase/Analytics'
pod 'Firebase/Messaging'




def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end





post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
     # config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
     flutter_additional_ios_build_settings(target)
    end
  end
end

```

my  pubspec.yaml

```

name: ex
description:  Website


version: 50.0.0+50

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  responsive_container: ^0.0.1
  http: ^0.13.0
  flutter_pagewise: ^2.0.1
  share: ^2.0.4
  firebase_messaging: ^10.0.5
  flutter_local_notifications: ^8.1.1+1
  flutter_signin_button: ^2.0.0
  url_launcher: ^6.0.9
  cloud_firestore: ^2.5.0
  font_awesome_flutter: ^9.1.0
  nice_button: ^0.1.7
  flutter_share_me: ^1.0.0
  package_info: ^2.0.2
  flutter_html: ^2.1.1
  youtube_player_iframe: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/banner.png
    - images/logo.png
    - images/anonymous-user.png
    - images/splashCh.png
    - images/menu-photo.png
    - images/loogoch.png
    - images/egphp.png
```
