### DISCUSSION TITLE
[firebase_core] CSP support on Flutter web

### DISCUSSION THREAD

**Discussion by atoka93** [firebase/flutterfire#9222] [Feature request]
Goal: make Firebase Analytics work on web and avoid adding `unsafe-inline` to `script-src`.

The content security policy for `script-src` is failing with `Content Security Policy blocks inline execution of scripts` at `t1.head.appendChild(script);`, `_injectSrcScript$body$FirebaseCoreWeb`.

_Tested with: `firebase_core: 1.20.0` and `firebase_analytics: 9.3.0`._

Including a fixed version of the `firebase-app.js`, `firebase-analytics.js` and using the old initializer used to work, but with the updated Firebase initialization (`Firebase.initializeApp(options: ...)`), which became mandatory to use, and automatic abstracted Firebase web initialization I didn't manage to make it work anymore and I can't think of a workaround.

Latest version of the dependencies that worked (right before the JS Firebase SDK version was updated from 8.10.1 to 9+):
```yaml
  firebase_analytics: 9.1.12
  firebase_analytics_platform_interface: 3.1.10
  firebase_analytics_web: 0.4.0+17
  firebase_core: 1.19.1
  firebase_core_platform_interface: 4.4.3
  firebase_core_web: 1.6.6
```
