### DISCUSSION TITLE
[firebase_analytics] Flutter Web - Uncaught MissingPluginException

### DISCUSSION THREAD

**Discussion by pawelpetruch** [firebase/flutterfire#9882] [Q&A]
Logging events works fine when debugging the Flutter web app locally in Chrome.

```
FirebaseAnalytics analytics = FirebaseAnalytics.instance;
analytics.logEvent(
      name: 'test_web',
    );
```

When I try to log events on the deployed app I get the following in the console:
`Uncaught MissingPluginException(No implementation found for method Analytics#logEvent on channel plugins.flutter.io/firebase_analytics)`

**Comment by karrarfalih** [comment]
Same issue here

**Comment by Justus-M** [comment]
same here

**Comment by auggernaut** [comment]
Same here

**Comment by auggernaut** [comment]
The solution here fixed my issue: https://github.com/firebase/flutterfire/discussions/10109

**Comment by kfieldi5** [comment]
This did not work for me

**Comment by jozzer182** [comment]
i compare this documentation [example](https://github.com/firebase/quickstart-flutter/tree/main/analytics) (that works), upgrade my SDK and packages versions, and run "flutter clean" on my terminal.. then works.
in case is dead link, this is the pubspec.yaml:

```
name: analytics_quickstart
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
```
