### ISSUE TITLE
[firebase_core ]can't build iOS app after add this plugin 

### ISSUE THREAD

**Issue by kotran88** [firebase/flutterfire#10350]
```
[!] Failed to load 'firebase_core' podspec: 
[!] Invalid `firebase_core.podspec` file: [!] Unsupported version requirements. [nil] is not valid..

 #  from /Users/pedrojung/.pub-cache/hosted/pub.dev/firebase_core-2.4.1/ios/firebase_core.podspec:36
 #  -------------------------------------------
 #    # Firebase dependencies
 >    s.dependency 'Firebase/CoreOnly', firebase_sdk_version
 #  
 #  -------------------------------------------
```

when I add firebase_core, 
it cause error above. 
can't build iOS

my whole pub spec.yaml is as below
```
name: moaboda
description: Demonstrates how to use the photo_manager plugin.
version: 2.5.1+22
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sticky_header: ^0.6.5
  google_ml_kit: ^0.13.0
  http: ^0.13.5
  ionicons: ^0.2.2
  oktoast: ^3.1.0
  barcode_widget: ^2.0.3
  painter: ^2.0.0
  path_provider: ^2.0.5
  expandable_page_view: ^1.0.17
  smooth_page_indicator: ^1.0.0+2
  flutter_bloc: ^8.1.1

  photo_manager: ^2.5.2
  provider: ^6.0.0
  video_player: ^2.1.14
  carousel_slider: ^4.2.1
  html: ^0.15.1
  firebase_core: ^2.4.1
  

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true

```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-arm64,
    locale ko-KR)
[!] Android toolchain - develop for Android devices (Android SDK version
    33.0.1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more
      details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup
      for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.70.2)
[✓] VS Code (version 1.66.2)

**Comment by darshankawar** [comment]
> flutter: ">=2.2.0"

@kotran88 What does this represent ? You probably don't need to add this entry in your pubspec.yaml as usually you'll have something like below:

```
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
```

The conflict could be due to other third party plugins (ex: google_ml_kit) you have which might be colliding with `firebase_core` pubspec.
Have you tried deleting the `podfile` and then running it again ?
