### ISSUE TITLE
🐛 [FirebaseAuth] cant get or set photoUrl on iOS

### ISSUE THREAD

**Issue by yostrokon** [firebase/flutterfire#10430]
## Bug report

**Describe the bug**
FirebaseAuth photoUrl is always null on IOS devices.

I'm trying to use photoUrl with anonymous and password authorization.
On android device can set and get correct values, on IOS photoUrl is always null even after is setted up on android.

### Steps to reproduce

await FirebaseAuth.instance.currentUser!.updatePhotoURL("aa||bb||cc");
await FirebaseAuth.instance.currentUser!.reload();
print(FirebaseAuth.instance.currentUser);
print(FirebaseAuth.instance.currentUser!.providerData);

This is only on ios, on android everything works as expected.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.0.1 22A400 darwin-x64, locale en-BG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.75.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
  assets_audio_player: ^3.0.6
  beep_player: ^0.0.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.6
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_ui_firestore: ^1.2.3
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^13.0.0
  flutter_speed_dial: ^6.2.0
  flutter_svg: ^2.0.0+1
  google_mobile_ads: ^2.3.0
  intl: ^0.17.0
  provider: ^6.0.5
  random_color: 1.0.6-nullsafety
  shared_preferences: ^2.0.17
  uuid: ^3.0.7
  vibration: ^1.7.5
```

</details>

---
