### ISSUE TITLE
🐛 [firebase_crashlytics] Dependency resolves to version 2.9.0 in pubspec.lock

### ISSUE THREAD

**Issue by BunnyBuddy** [firebase/flutterfire#10457]
We are trying to integrated Firebase_crashlytics in our App but because our App is built on an older version of Flutter (it doesn't support Null Safety) so we can't use the latest version. Then we decided to integrate version 2.7.1 or lower but the pubspec.lock file always resolves the version to 2.9.0 which is null safe and it throws build error for our App not being null safe.
 
Can anybody guide me as to what should I do or not do in this regard?

This is our **Pubspec.yaml**,

```
name: ------
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at

# ios
version: 0.1.1+1

# android
#version: 0.1.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
  firebase_core_platform_interface: 4.2.0

dependencies:
  flutter:
    sdk: flutter
#  braintree_device_data:
#    path: ../braintree_device_data
  flutter_braintree:
    path: ./flutter-braintree-master
  onesignal_flutter:
    path: ./flutter-onesignal
#  flutter_facebook_auth:
#    git:
#      url: https://github.com/darwin-morocho/flutter-facebook-auth.git
#      ref: master
#      path: facebook_auth/


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.1.2
  carousel_slider: ^3.0.0
  email_validator: ^2.0.1
  tab_indicator_styler: ^1.0.0
  flutter_rating_bar:
  flutter_staggered_grid_view: ^0.3.4
  dotted_border: ^2.0.0
  http: ^0.13.1
  shimmer: ^2.0.0
  flutter_slidable: ^0.6.0
  google_sign_in: ^5.0.3
#  flutter_facebook_auth: ^3.5.2 #// used as old facebook auth but due to an update we cant use it anymore
#  flutter_facebook_auth: ^4.4.1+1 #// use this if you're using mac with an intel chip or the team is big
  flutter_facebook_auth: ^5.0.7
  sign_in_with_apple: ^3.2.0
  sqflite: ^2.0.0+3
  google_place: ^0.4.0
  shared_preferences: ^2.0.6
  nuts_activity_indicator: ^0.1.1
  graphql_flutter: ^5.0.0
#  flutter_braintree: ^2.0.0
  flutter_html: ^2.2.1
  equatable: ^2.0.3
  pull_to_refresh: ^2.0.0
  badges: ^2.0.1
  image_picker: ^0.8.4+1
#  image_picker: ^0.8.6 // requires gradle to be updated to 7.2 which may break some packages and gradle 7.2 doesn't work with OneSignal
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.3
  firebase_performance: ^0.6.0+2
#  firebase_performance: ^0.8.3+3
#  url_launcher: ^6.0.10
#  url_launcher: ^6.1.7
  url_launcher: ^6.1.5
  dio: ^4.0.0
  flutter_svg: ^0.22.0
  syncfusion_flutter_datepicker: ^19.3.45
  flutter_typeahead: ^3.2.1
  lottie: ^1.2.1
  google_fonts: ^2.1.0
  flutter_screenutil: ^5.0.0+2
  app_tracking_transparency: ^2.0.2+1
  #  new_version: ^0.3.1
  new_version_plus: ^0.0.1+4
  uni_links: ^0.5.1
  #  app_links: ^2.2.0
  app_links: ^3.4.1
  flutter_phoenix: ^1.0.0
  device_info_plus: ^4.0.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  pusher_channels_flutter: ^2.0.1
  intl: ^0.17.0
  social_share: ^2.2.1
  share_plus: ^4.5.3
  upgrader: ^4.7.0
  photo_view: ^0.14.0
  file_picker: ^4.6.1
  flutter_native_splash:
  multi_image_picker2: ^5.0.2
#  firebase_crashlytics: ^2.5.2
#  cloudflare: ^1.3.0+11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/JSON/
    - assets/JSON/No_Message/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

This is the result of **Flutter doctor -v**,

```
MacBooks-MacBook-Pro:marketplace-mobile-app macbookpro$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.6.3 21G419 darwin-x64, locale en-PK)
    • Flutter version 2.10.4 at /Users/macbookpro/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/macbookpro/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • Infinix X6811 (mobile) • 07363251BU000513 • android-arm64  • Android 11 (API 30)
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
