### ISSUE TITLE
[📚] melos.yaml has an incorrect description for the format command

### ISSUE THREAD

**Issue by ryanhanks-bestow** [firebase/flutterfire#10641]
I noticed the melos.yaml has an incorrect description for the `format` command. https://github.com/firebase/flutterfire/blob/master/melos.yaml#L56-L65
```yaml
  format:
    run: |
      dart pub global run flutter_plugin_tools format && \
      swiftformat .
    description: |
      Build a specific example app for Android.
       - Requires `flutter_plugin_tools` (`dart pub global activate flutter_plugin_tools`).
       - Requires `clang-format` (can be installed via Brew on macOS).
       - Requires `swiftformat` (can be installed via Brew on macOS).
```

It looks like the original description was lost in a PR: https://github.com/firebase/flutterfire/blame/477c8c2ba45f0af3342efbe7433fdcdc784787b2/melos.yaml#L20

```yaml
  # Formats the code of all packages (Java, Objective-C, and Dart).
  #  - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
  #  - Requires `git`.
  #  - Requires `clang-format` (can be installed via Brew on MacOS).
```
