### ISSUE TITLE
🐛 [firebase_analytics]  FATAL EXCEPTION: ScionFrontendApi

### ISSUE THREAD

**Issue by MatteoAntolini** [firebase/flutterfire#10722]
## Bug report

Same issue as #9376 
---

## Additional context

Upgrading from 
android/app/build.gradle
```gradle
dependencies {
    implementation platform('com.google.firebase:firebase-bom:31.2.3')
    implementation 'com.google.android.material:material:1.5.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```
pubspec.yaml
```yaml
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.1
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  firebase_analytics: ^10.1.4
  cloud_functions: ^4.0.11
  firebase_dynamic_links: ^5.0.15
  firebase_messaging: ^14.2.5
  firebase_crashlytics: ^3.0.15
```
to:
android/app/build.gradle
```gradle
dependencies {
    implementation platform('com.google.firebase:firebase-bom:31.4.0')
    implementation 'com.google.android.material:material:1.5.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```
pubspec.yaml
```yaml
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.0.2
  firebase_storage: ^11.1.0
  firebase_analytics: ^10.2.0
  cloud_functions: ^4.1.0
  firebase_dynamic_links: ^5.1.0
  firebase_messaging: ^14.4.0
  firebase_crashlytics: ^3.1.0
```
<details><summary>Cause this crash, but only in release mode</summary>

```
E/AndroidRuntime(28063): FATAL EXCEPTION: ScionFrontendApi
E/AndroidRuntime(28063): Process: com.hoongry.user, PID: 28063
E/AndroidRuntime(28063): java.lang.ExceptionInInitializerError
E/AndroidRuntime(28063): 	at com.google.android.gms.measurement.internal.Q2.<init>(Unknown Source:34)
E/AndroidRuntime(28063): 	at com.google.android.gms.measurement.internal.S1.<init>(SourceFile:3)
E/AndroidRuntime(28063): 	at com.google.android.gms.measurement.internal.S1.G(SourceFile:2)
E/AndroidRuntime(28063): 	at com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize(SourceFile:2)
E/AndroidRuntime(28063): 	at com.google.android.gms.internal.measurement.w0.a(SourceFile:4)
E/AndroidRuntime(28063): 	at com.google.android.gms.internal.measurement.P0.run(Unknown Source:12)
E/AndroidRuntime(28063): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(28063): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(28063): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(28063): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: k3.a.values []
E/AndroidRuntime(28063): 	at java.lang.Enum.enumValues(Enum.java:270)
E/AndroidRuntime(28063): 	at java.lang.Enum.access$000(Enum.java:61)
E/AndroidRuntime(28063): 	at java.lang.Enum$1.create(Enum.java:277)
E/AndroidRuntime(28063): 	at java.lang.Enum$1.create(Enum.java:275)
E/AndroidRuntime(28063): 	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(28063): 	at java.lang.Enum.getSharedConstants(Enum.java:289)
E/AndroidRuntime(28063): 	at java.lang.Class.getEnumConstantsShared(Class.java:2428)
E/AndroidRuntime(28063): 	at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
E/AndroidRuntime(28063): 	at java.util.EnumMap.<init>(EnumMap.java:138)
E/AndroidRuntime(28063): 	at k3.b.<init>(Unknown Source:7)
E/AndroidRuntime(28063): 	at k3.b.<clinit>(Unknown Source:3)
E/AndroidRuntime(28063): 	... 9 more
E/AndroidRuntime(28063): Caused by: java.lang.NoSuchMethodException: k3.a.values []
E/AndroidRuntime(28063): 	at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime(28063): 	at java.lang.Class.getDeclaredMethod(Class.java:2050)
E/AndroidRuntime(28063): 	at java.lang.Enum.enumValues(Enum.java:267)
E/AndroidRuntime(28063): 	... 19 more

```
</details>

Removing `firebase_analytics` solved this issue

All libraries are the latest version

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.7.9, on Microsoft Windows [Versione 10.0.19045.2728], locale it-IT)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default
      components
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.76.0)
[√] Connected device (5 available)
[√] HTTP Host Availability
```

</details>
