### ISSUE TITLE
[cloud_firestore/permission-denied] Missing or insufficient permissions (Flutter Web only)

### ISSUE THREAD

**Issue by Aziz-cs** [firebase/flutterfire#10821]
Bug report

When I do any write query (update / delete / set) from my Flutter web Admin Panel it throws this although all read queries works fine:
```
Error: [cloud_firestore/permission-denied] Missing or insufficient permissions.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 355:28            _throw
dart-sdk/lib/core/errors.dart 120:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1385:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
```

> My Security rules:
    match /{document=**} {
       allow read, write: if true;
    }

However, the strange thing that the same queries works just fine from Mobile apps (Android / iOS) linked to the same Firebase/Firestore with the same security rules.

```
### pubspec.yaml
name: admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  firebase_database: ^10.0.5
  firebase_storage: ^11.0.5
  cloud_firestore: ^4.0.5
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  get: ^4.6.5
  url_launcher: ^6.1.7
  file_picker: ^4.6.1
  http: ^0.13.4
  intl: ^0.17.0
  fl_chart: ^0.55.2
  just_audio: ^0.9.18
  emoji_picker_flutter: ^1.5.1
  lazy_load_scrollview: ^1.3.0
  auto_direction: ^0.0.6
  firebase_performance: ^0.9.0+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
```

### Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
```
[✓] Flutter (Channel stable, 3.7.11, on macOS 12.3.1 21E258 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

web folder > index.html
```
</script>
  <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-database.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-firestore.js"></script>
  <!-- <script src="main.dart.js" type="application/javascript"></script> -->
  <script>
    import "firebase/performance";

    var firebaseConfig = {
    apiKey: "------",
    authDomain: "childroo-c2c50.firebaseapp.com",
    databaseURL: "https://childroo-c2c50-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "childroo-c2c50",
    storageBucket: "childroo-c2c50.appspot.com",
    messagingSenderId: "----",
    appId: "----",
    measurementId: "G-HPH3DH7R9F"
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    // Initialize Performance Monitoring and get a reference to the service
    const perf = firebase.performance();
  </script>
```
-----
Side notes: It was working fine, but I think maybe after upgrading to Flutter 3.7.11 that happened but I am not sure.
I also live in Egypt (if that issue is relating to IP address)
