### ISSUE TITLE
🐛 [firebase] Unhandled Exception: type '_Map<Object?, Object?>' is not a subtype of type 'List<Object?>' in type cast

### ISSUE THREAD

**Issue by lizhuoyuan** [firebase/flutterfire#10909]
```
 E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type '_Map<Object?, Object?>' is not a subtype of type 'List<Object?>' in type cast
                                                                                                    #0      PigeonInitializeResponse.decode (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:126)
                                                                                                    #1      _FirebaseCoreHostApiCodec.readValueOfType (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:158)
                                                                                                    #2      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:479)
                                                                                                    #3      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:524)
                                                                                                    #4      _FirebaseCoreHostApiCodec.readValueOfType (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:160)
                                                                                                    #5      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:479)
                                                                                                    #6      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:531)
                                                                                                    #7      _FirebaseCoreHostApiCodec.readValueOfType (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:160)
                                                                                                    #8      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:479)
                                                                                                    #9      StandardMessageCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:343)
                                                                                                    #10     BasicMessageChannel.send (package:flutter/src/services/platform_channel.dart:197)
                                                                                                    <asynchronous suspension>
                                                                                                    #11     FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:208)
                                                                                                    <asynchronous suspension>
                                                                                                    #12     MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29)
                                                                                                    <asynchronous suspension>
                                                                                                    #13     MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73)
                                                                                                    <asynchronous suspension>
                                                                                                    #14     Firebase.initializeApp (package:firebase_core/src/firebase.dart:43)
                                                                                                    <asynchronous suspension>
                                                                                                    #15     main (package:juno/main.dart:23)
                                                                                                    <asynchronous suspension>
```

version: 2.7.1

**Comment by nestortotembear** [comment]
It has happened to me after adding firebase_analytics ^10.3.0, need help as well

**Comment by michaelmartins09** [comment]
I had the same problem.

To resolve this problem, go to pubspec.yaml and do upgrade firebase dependencies:

My before versions:
```
  firebase_core: 2.9.0
  firebase_analytics: 10.2.0
```

My new versions:
```
  firebase_core: 2.11.0
  firebase_analytics: 10.2.1
```

I hope I've helped! ;)

**Comment by ben-yolabs** [comment]
https://pub.dev/packages/firebase_core_platform_interface/versions/4.7.0 rolled out 9hr ago, at time of writing.

It seems `firebase_core` references `firebase_core_platform_interface` by caret syntax –

https://github.com/firebase/flutterfire/blob/5cfec10916b4eb15cc4c6147de2669dea8d4ac96/packages/firebase_core/firebase_core/pubspec.yaml#L16

<details><summary>Relevant portion of our application's pubspec.lock</summary>
<p>

```
  firebase_core:
    dependency: "direct main"
    description:
      name: firebase_core
      sha256: be13e431c0c950f0fc66bdb67b41b8059121d7e7d8bbbc21fb59164892d561f8
      url: [REDACTED]
    source: hosted
    version: "2.5.0"
  firebase_core_platform_interface:
    dependency: "direct main"
    description:
      name: firebase_core_platform_interface
      sha256: "0df0a064ab0cad7f8836291ca6f3272edd7b83ad5b3540478ee46a0849d8022b"
      url: [REDACTED]
    source: hosted
    version: "4.6.0"
  firebase_core_web:
    dependency: transitive
    description:
      name: firebase_core_web
      sha256: "347351a8f0518f3343d79a9a0690fa67ad232fc32e2ea270677791949eac792b"
      url: [REDACTED]
    source: hosted
    version: "2.3.0"
  firebase_dynamic_links:
    dependency: transitive
    description:
      name: firebase_dynamic_links
      sha256: "6db5fca5e0013d5c26ef6fa40ba6525253aec14209cdde397acc6db5d2df6bc9"
      url: [REDACTED]
    source: hosted
    version: "5.0.12"
  firebase_dynamic_links_platform_interface:
    dependency: transitive
    description:
      name: firebase_dynamic_links_platform_interface
      sha256: "91171dc24b3d3388f259650aa98ffc44c423d0a7ad115e7a9f4c66b66acf7913"
      url: [REDACTED]
    source: hosted
    version: "0.2.3+27"
  firebase_messaging:
    dependency: transitive
    description:
      name: firebase_messaging
      sha256: dbccddc62fef6f3745ba83062bfd1fbf2eb6a931db4c73d03f85c5772dfdec7f
      url: [REDACTED]
    source: hosted
    version: "14.2.2"
  firebase_messaging_platform_interface:
    dependency: transitive
    description:
      name: firebase_messaging_platform_interface
      sha256: "564a47ea76db9cd2d17e7d95790428ad3de9d0075795d14c4c901ba0bf518e1a"
      url: [REDACTED]
    source: hosted
    version: "4.2.11"
  firebase_messaging_web:
    dependency: transitive
    description:
      name: firebase_messaging_web
      sha256: "76291494583a003d4ce0d613c41cb87c58fab25773317daa66a245f537e1c3f7"
      url: [REDACTED]
    source: hosted
    version: "3.2.12"
```

</p>
</details> 

Today when our CD pipeline spat out today's build, it seems `firebase_core_platform_interface` was being upgraded to the newly published version, despite that the `firebase_core_platform_interface` has its `version` pinned / specified as `4.6.0`

There may be a complicating factor or two that could give rise to this upgrade happening in our environment –

* the application has direct dependencies on library packages that also depend on Firebase libraries
  * though they also pin `firebase_core_platform_interface` to a version
* lockfile not being strictly honored in CD environment for some reason

but the intricacies of Dart package version resolution might be lost on us as well 😄 

To rectify this, our workaround was to specify a direct dependency on `firebase_core_platform_interface` like so in our application's `pubspec.yaml`:

```
firebase_core_platform_interface: 4.6.0
```
