### ISSUE TITLE
🐛 [firebase_ui_auth] Cannot upgrade intl package

### ISSUE THREAD

**Issue by jaredsburrows** [firebase/flutterfire#11121]
Can't upgrade to 0.18.1 because of `firebase_ui_auth`

**Comment by darshankawar** [comment]
@jaredsburrows 
I was able to add `intl` package in `firebase_ui_auth` plugin example.

<img width="385" alt="Screenshot 2023-06-13 at 4 16 21 PM" src="https://github.com/firebase/flutterfire/assets/67046386/2ab83aab-733c-436b-a34e-6836c8180a91">

Can you provide the error log you are getting ?

**Comment by jaredsburrows** [comment]
Here is the issue I am seeing:
```
❯ flutter upgrade
flutter pub get
flutter pub upgrade
Flutter is already up to date on channel stable
Flutter 3.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 682aa387cf (8 days ago) • 2023-06-05 18:04:56 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1
Resolving dependencies... 
Because every version of firebase_ui_auth depends on flutter_localizations from sdk which depends on intl 0.18.0, every
  version of firebase_ui_auth requires intl 0.18.0.
So, because your-project depends on both firebase_ui_auth ^1.4.1 and intl ^0.18.1, version solving failed.
Resolving dependencies... 
Because every version of firebase_ui_auth depends on flutter_localizations from sdk which depends on intl 0.18.0, every
  version of firebase_ui_auth requires intl 0.18.0.
So, because your-project depends on both firebase_ui_auth ^1.4.1 and intl ^0.18.1, version solving failed.
```

pubspec.yaml
```
dependencies:
  # Official
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # https://pub.dev/packages/cupertino_icons
  firebase_core: ^2.13.0 # https://pub.dev/packages/firebase_core
  firebase_analytics: ^10.4.0 # https://pub.dev/packages/firebase_analytics
  firebase_auth: ^4.6.1 # https://pub.dev/packages/firebase_auth
  firebase_ui_auth: ^1.4.1 # https://pub.dev/packages/firebase_ui_auth
  firebase_ui_oauth: ^1.1.0 # https://pub.dev/packages/firebase_ui_oauth
  firebase_ui_oauth_google: ^1.2.1 # https://pub.dev/packages/firebase_ui_oauth_google
  intl: ^0.18.1 # https://pub.dev/packages/intl, can't upgrade to 0.18.1 because of firebase_ui_auth
```
