### ISSUE TITLE
🐛 [google_sign_in] Version conflict firebase_auth & google_sign_in

### ISSUE THREAD

**Issue by VladislavYakonyuk** [firebase/flutterfire#11145]
I have a problem when updating versions of firebase with the google_sign_In package (version conflict)

```
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.6.3, which depends on
      Firebase/Auth (= 10.10.0) was resolved to 10.10.0, which depends on
        FirebaseAuth (~> 10.10.0) was resolved to 10.10.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    google_sign_in (from `.symlinks/plugins/google_sign_in/ios`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 5.0) was resolved to 5.0.2, which depends on
        GTMAppAuth (~> 1.0) was resolved to 1.3.1, which depends on
          GTMSessionFetcher/Core (< 3.0, >= 1.5)

    google_sign_in (from `.symlinks/plugins/google_sign_in/ios`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 5.0) was resolved to 5.0.2, which depends on
        GTMSessionFetcher/Core (~> 1.1)
```

My pubscpec.yml
```yml
  google_sign_in: 5.0.4
 
  firebase_core: 2.14.0
  firebase_analytics: 10.4.3
  firebase_auth: 4.6.3
  firebase_messaging: 14.6.3
  firebase_crashlytics: 3.3.3
```

**Comment by darshankawar** [comment]
@VladislavYakonyuk 
Can you try deleting podfile.lock, run pod install and see if it helps ?

**Comment by proshin-roman** [comment]
@darshankawar @VladislavYakonyuk I've got exactly the same problem and Google went me here.

I've tried deleting the `Podfile.lock` file and executing `pod install --repo-update` (`--repo-update` wasn't necessary though) - and that fixed the issue! Thank you for the tip!

**Comment by VladislavYakonyuk** [comment]
not working for me removing Podfile.lock

**Comment by darshankawar** [comment]
@VladislavYakonyuk 
I noticed that the plugin versions you mentioned in original description uses specific versions of the plugins, ie, you are not using caret ^.

Can you try using the same for each plugin version and try again ?

**Comment by VladislavYakonyuk** [comment]
doesn't work for me

```yaml
  google_sign_in: ^5.0.4
  
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.3
  firebase_crashlytics: ^3.3.3
```

```
$ pod install

[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.6.3, which depends on
      Firebase/Auth (= 10.10.0) was resolved to 10.10.0, which depends on
        FirebaseAuth (~> 10.10.0) was resolved to 10.10.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    google_sign_in (from `.symlinks/plugins/google_sign_in/ios`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 5.0) was resolved to 5.0.2, which depends on
        GTMAppAuth (~> 1.0) was resolved to 1.3.1, which depends on
          GTMSessionFetcher/Core (< 3.0, >= 1.5)

    google_sign_in (from `.symlinks/plugins/google_sign_in/ios`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 5.0) was resolved to 5.0.2, which depends on
        GTMSessionFetcher/Core (~> 1.1)
```
