### ISSUE TITLE
🐛 [firebase_dynamic_links] getting random link in onGenerateRoute when first time installing app specially iOS

### ISSUE THREAD

**Issue by DevendraFlutterDev** [firebase/flutterfire#11279]
## getting random link in onGenerateRoute when first time installing app specially iOS

**getting random link in onGenerateRoute when first time installing app specially iOS**
I am using firebase_dynamic_links: ^5.3.3 and for navigation using named routing navigator 2.0 
when application running first time it is generating route "/" and after that automatically generating route "link?request_ip_version=IP%5FV6&match_message=No%20pre%2Dinstall%20link%20matched%20for%20this%20device%2E" like this.
I don't know why this is happining.

this issue is specially in iOS, in Android it's working fine. 

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F82 darwin-x64, locale
    en-IN)
    • Flutter version 3.10.6 on channel stable at
      /Users/ankurverma/Documents/Flutter Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (20 hours ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ankurverma/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.79.2)
    • VS Code at /Users/ankurverma/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 9F13BB69-A501-4F68-B6DB-2AE98CFBC120 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • macOS 13.4.1 22F82 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
name: kaauh
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  intl: ^0.18.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.17
  get_it: ^7.2.0
  dio: ^4.0.6
  connectivity_plus: ^3.0.2
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  firebase_dynamic_links: ^5.3.3
  dartz: ^0.10.1
  url_launcher: ^6.1.8
  lottie: ^2.2.0
  qr_code_scanner:
    path: qr_code_scanner
  image_picker: ^0.8.7+4
  image_cropper: ^3.0.3
  carousel_slider: ^4.2.1
  file_picker: ^5.2.11
  #  cloud_firestore: ^4.4.3
  #  firebase_database: ^10.0.14
  syncfusion_flutter_calendar: ^20.4.53
  firebase_messaging: ^14.4.0
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.2
#  flutter_local_notifications: ^13.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/anim/
  fonts:
    - family: sf_pro_display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf


flutter_intl:
  enabled: true

```

</details>

---
