### ISSUE TITLE
🐛 [FIREBASE_AUTH] java.lang.NullPointerException - Attempt to invoke interface method 'void f4.c.e(java.lang.String, f4.c$a)' on a null object reference

### ISSUE THREAD

**Issue by martinpelli** [firebase/flutterfire#11313]
## Bug report

**Describe the bug**
I am facing this exception in crashlytics, saw various reports but are closed and solution is to upgrade firebase auth to latest version and I already have it.

My pubspec:
![image](https://github.com/firebase/flutterfire/assets/63437171/55f15da6-0b59-44d0-9ef6-f6f10837945a)

Error .txt log 
[com.clickbox.clickboxapp_issue_17dae57941d740e4d94636c8a5fc1091_crash_session_64B5C674031400021D84303247D16BDE_DNE_0_v2_stacktrace.txt](https://github.com/firebase/flutterfire/files/12079657/com.clickbox.clickboxapp_issue_17dae57941d740e4d94636c8a5fc1091_crash_session_64B5C674031400021D84303247D16BDE_DNE_0_v2_stacktrace.txt)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[pelli@PelliArch flutter_wiplay_app]$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on Arch Linux 6.4.3-arch1-1, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
[pelli@PelliArch flutter_wiplay_app]$ flutter pub deps -- --style=compact
Dart SDK 3.0.6
Flutter SDK 3.10.6
clickbox 1.0.2+3

dependencies:
- another_flushbar 1.12.30 [flutter]
- bloc 8.1.2 [meta]
- collection 1.17.1
- cupertino_icons 1.0.5
- data_table_2 2.5.4 [flutter async]
- date_picker_timeline 1.2.5 [flutter intl]
- dio 5.2.1+1 [async http_parser meta path]
- dropdown_search 5.0.6 [flutter]
- firebase_auth 4.7.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.15.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.3.4 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 14.6.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- fl_chart 0.63.0 [equatable flutter]
- fluro 2.0.5 [flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_app_badger 1.5.0 [flutter]
- flutter_bloc 8.1.3 [bloc flutter provider]
- flutter_dotenv 5.1.0 [flutter]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_local_notifications 15.1.0+1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localization 0.1.12 [flutter flutter_web_plugins flutter_localizations plugin_platform_interface shared_preferences]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_native_splash 2.3.1 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- image_picker 1.0.1 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.18.0 [clock meta path]
- json_annotation 4.8.1 [meta]
- month_picker_dialog 2.0.2 [flutter flutter_localizations provider intl]
- non_uniform_border 1.0.0 [flutter]
- numberpicker 2.1.2 [flutter infinite_listview]
- retrofit 4.0.1 [dio meta]
- shared_preferences 2.2.0 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- time_picker_spinner 0.0.1 [flutter]
- time_range_picker 2.2.0 [flutter]
- url_launcher 6.1.12 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- wheel_slider 1.1.1 [flutter wheel_chooser]

dev dependencies:
- build_runner 2.4.6 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 2.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- retrofit_generator 7.0.8 [analyzer build built_collection code_builder dart_style dio retrofit source_gen tuple]

transitive dependencies:
- _fe_analyzer_shared 62.0.0 [dart_internal meta]
- _flutterfire_internals 1.3.4 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.0.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.2.1 [analyzer async build collection crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.2.10 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.6.1 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.0 [meta path]
- clock 1.1.1
- code_builder 4.5.0 [built_collection built_value collection matcher meta]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+4 [js meta]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dart_internal 0.2.8
- dart_style 2.3.2 [analyzer args path pub_semver source_span]
- dbus 0.7.8 [args ffi meta xml]
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.2
- file 6.1.4 [meta path]
- file_selector_linux 0.9.2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.0 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3 [cross_file file_selector_platform_interface flutter]
- firebase_auth_platform_interface 6.16.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.6.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.4 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.1.0
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.15 [flutter]
- frontend_server_client 3.2.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- graphs 2.3.1 [collection]
- html 0.15.4 [csslib source_span]
- http 1.1.0 [async http_parser meta]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.0.17 [archive meta xml]
- image_picker_android 0.8.7+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.8.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- infinite_listview 1.1.0 [flutter]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- lints 2.1.1
- logging 1.2.0
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- mime 1.0.4
- nested 1.0.0 [flutter]
- package_config 2.1.0 [path]
- path 1.8.3
- path_provider_linux 2.1.11 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.7 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.4 [meta]
- pointycastle 3.7.3 [collection convert js]
- pool 1.5.1 [async stack_trace]
- provider 6.0.5 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- shared_preferences_android 2.2.0 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.4.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.9.2 [path]
- timing 1.0.1 [json_annotation]
- tuple 2.0.2
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.0.36 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.18 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.7 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- watcher 1.1.0 [async path]
- web_socket_channel 2.4.0 [async crypto stream_channel]
- wheel_chooser 1.1.2 [flutter]
- win32 5.0.5 [ffi]
- xdg_directories 1.0.1 [meta path]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @martinpelli, kindly share the full crash report in text form instead of as a screenshot.

**Comment by martinpelli** [comment]
> Hi @martinpelli, kindly share the full crash report in text form instead of as a screenshot.

Hi, sorry, sure I edited the post

**Comment by fischja** [comment]
I have the same issue. Affecting the majority of users in Crashlytics. App seems to crash regularly on open, then works fine after starting the 2nd or 3rd time.

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {XXXXXXXXXXXXXXXXXX}: java.lang.NullPointerException: Attempt to invoke interface method 'void b9.c.f(java.lang.String, b9.c$a)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5121)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5151)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
```

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void b9.c.f(java.lang.String, b9.c$a)' on a null object reference
       at io.flutter.plugin.common.BasicMessageChannel.setMessageHandler(BasicMessageChannel.java:37)
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.onDetachedFromEngine(FlutterFirebaseAuthPlugin.java:10)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:121)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:16)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:11)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:10)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:31)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:98)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:18)
       at android.app.Activity.performDestroy(Activity.java:8239)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1583)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5106)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5151)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by danagbemava-nc** [comment]
Hi @fischja, can you try updating to `firebase_auth: ^4.7.1` to see if the crash still reproduces? A similar issue was reported recently in https://github.com/firebase/flutterfire/issues/11291 and has since been fixed by https://github.com/firebase/flutterfire/pull/11296 which is available in 4.7.1

**Comment by fischja** [comment]
@danagbemava-nc Yes, i have upgraded and the issues still persists

**Comment by martinpelli** [comment]
> Hi @fischja & @martinpelli, can you try updating to `firebase_auth: ^4.7.1` to see if the crash still reproduces? A similar issue was reported recently in #11291 and has since been fixed by #11296 which is available in 4.7.1

For now, crashs stopped after using this in pubspec `firebase_auth: 4.6.3
firebase_auth_platform_interface: 6.15.3`
 Will try with latest version now, so tomorrow I will confirm

**Comment by danagbemava-nc** [comment]
Hi @fischja, just for confirmation, please share your pubspec.yaml & pubspec.lock content that shows the flutterfire package versions.

**Comment by fischja** [comment]
Hi @danagbemava-nc , here is my pubspec.yaml:

```
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.5
  firebase_crashlytics: ^3.3.4
```

pubspec.lock

```
  firebase_auth:
    dependency: "direct main"
    description:
      name: firebase_auth
      sha256: acfbe55bc23e94ccc7228b7fc7b9abc0005597c1de226f6e3a0103ac29728fbe
      url: "https://pub.dev"
    source: hosted
    version: "4.7.1"
  firebase_auth_platform_interface:
    dependency: transitive
    description:
      name: firebase_auth_platform_interface
      sha256: "4ab0a8997994db2b76bf0652689d7908ca935a99314857c683251bc23d31c287"
      url: "https://pub.dev"
    source: hosted
    version: "6.16.0"
  firebase_auth_web:
    dependency: transitive
    description:
      name: firebase_auth_web
      sha256: "2e694a612a0739c0cf5f426d515dda37ee5827bab211d16e76bcad6a082925eb"
      url: "https://pub.dev"
    source: hosted
    version: "5.6.1"
  firebase_core:
    dependency: "direct main"
    description:
      name: firebase_core
      sha256: "2e9324f719e90200dc7d3c4f5d2abc26052f9f2b995d3b6626c47a0dfe1c8192"
      url: "https://pub.dev"
    source: hosted
    version: "2.15.0"
  firebase_core_platform_interface:
    dependency: transitive
    description:
      name: firebase_core_platform_interface
      sha256: b63e3be6c96ef5c33bdec1aab23c91eb00696f6452f0519401d640938c94cba2
      url: "https://pub.dev"
    source: hosted
    version: "4.8.0"
  firebase_core_web:
    dependency: transitive
    description:
      name: firebase_core_web
      sha256: "0fd5c4b228de29b55fac38aed0d9e42514b3d3bd47675de52bf7f8fccaf922fa"
      url: "https://pub.dev"
    source: hosted
    version: "2.6.0"
  firebase_crashlytics:
    dependency: "direct main"
    description:
      name: firebase_crashlytics
      sha256: "3607b46342537f98df18b130b6f5ab25cee6981a3a782e1a7b121d04dfea3caa"
      url: "https://pub.dev"
    source: hosted
    version: "3.3.4"
  firebase_crashlytics_platform_interface:
    dependency: transitive
    description:
      name: firebase_crashlytics_platform_interface
      sha256: c63abeb87b18f6e6d4bf6bb3977f15d2d9281a049d93fe098e83e56dcbf7da06
      url: "https://pub.dev"
    source: hosted
    version: "3.6.4"
  firebase_messaging:
    dependency: "direct main"
    description:
      name: firebase_messaging
      sha256: "8ac91d83a028eef050de770f1dc98421e215714d245f34de7b154d436676fbd0"
      url: "https://pub.dev"
    source: hosted
    version: "14.6.5"
  firebase_messaging_platform_interface:
    dependency: transitive
    description:
      name: firebase_messaging_platform_interface
      sha256: b2995e3640efb646e9ebf0e2fa50dea84895f0746a31d7e3af0e5e009a533a1a
      url: "https://pub.dev"
    source: hosted
    version: "4.5.4"
  firebase_messaging_web:
    dependency: transitive
    description:
      name: firebase_messaging_web
      sha256: "5d8446a28339124a2cb4f57a6ca454a3aca7d0c5c0cdfa5707afb192f7c830a7"
      url: "https://pub.dev"
    source: hosted
    version: "3.5.4"
  firebase_storage:
    dependency: "direct main"
    description:
      name: firebase_storage
      sha256: "4b747005aee0c611242cdd553f58795f51e1567d2dfd4f75692fac3f67c8c336"
      url: "https://pub.dev"
    source: hosted
    version: "11.2.5"
  firebase_storage_platform_interface:
    dependency: transitive
    description:
      name: firebase_storage_platform_interface
      sha256: c77c7b6b7d283280993c81ea8ac95552b2ae521a7bb46a95181c1482e62d1633
      url: "https://pub.dev"
    source: hosted
    version: "4.4.4"
  firebase_storage_web:
    dependency: transitive
    description:
      name: firebase_storage_web
      sha256: "6906245579f1af225e43df0395c9d9631cb3135cbfa3521a839196d3383bb89a"
      url: "https://pub.dev"
    source: hosted
    version: "3.6.5"
```

I have attached the stack trace from Crashlytics for reference.

[issue_10820c7c03a9ac15f05741b4df042138_crash_session_64B9B9C8024D00015576E8EE7E67467B_DNE_0_v2_stacktrace.txt](https://github.com/firebase/flutterfire/files/12114664/issue_10820c7c03a9ac15f05741b4df042138_crash_session_64B9B9C8024D00015576E8EE7E67467B_DNE_0_v2_stacktrace.txt)
