### ISSUE TITLE
🐛 [Firestore_cloud] Flutter app crashes during the build phase and gives an error that says Firestore Cloud Error

### ISSUE THREAD

**Issue by AbedSameer** [firebase/flutterfire#11497]
I've been working on a project for several months now, and I want to add some features, but now when I try to debug the app on the phone or on the emulator, it throws the following error. I tried to change the version of the accreditation, but to no avail. I also deleted the old build and made a new one, but the problem also appeared again.

```

Resolving dependencies...
Got dependencies!
Launching lib\main.dart on SM A325F in debug mode...
Building with Flutter multidex support enabled.
Note: C:\Users\abedSameer\AppData\Local\Pub\Cache\hosted\pub.dev\cloud_firestore-4.8.5\android\src\main\java\io\flutter\plugins\firebase\firestore\FlutterFirebaseFirestoreMessageCodec.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
√  Built build\app\outputs\flutter-apk\app-debug.apk.
E/AndroidRuntime(31986): FATAL EXCEPTION: main
E/AndroidRuntime(31986): Process: com.AbedSameer.tahfeez_app, PID: 31986
E/AndroidRuntime(31986): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.AbedSameer.tahfeez_app/com.AbedSameer.tahfeez_app.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.AbedSameer.tahfeez_app.MainActivity" on path: DexPathList[[zip file "/data/app/~~dM4GMFVavjf_yoNNCfeXsQ==/com.AbedSameer.tahfeez_app-KXqSdU-aI2G6JIPuRHIY8w==/base.apk"],nativeLibraryDirectories=[/data/app/~~dM4GMFVavjf_yoNNCfeXsQ==/com.AbedSameer.tahfeez_app-KXqSdU-aI2G6JIPuRHIY8w==/lib/arm64, /data/app/~~dM4GMFVavjf_yoNNCfeXsQ==/com.AbedSameer.tahfeez_app-KXqSdU-aI2G6JIPuRHIY8w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
```

and the pubspec.yaml file
```

name: tahfeez_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  flutter_screenutil: ^5.5.4
  excel: 2.0.0-null-safety-3
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  file_picker: ^5.2.1
  intl: ^0.17.0
  searchfield: ^0.7.1
  permission_handler: ^10.1.0
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: 
  url_launcher:
  provider: ^6.0.5
  age_calculator: ^1.0.0
  quickalert: ^1.0.1
  sentry_flutter: ^7.7.0
  flutter_launcher_icons: ^0.9.2
  firebase_storage: ^11.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"


  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icon/

```
