### ISSUE TITLE
🐛 [cloud_firestore] update pre-compiled framework instructions

### ISSUE THREAD

**Issue by jmw11x** [firebase/flutterfire#11526]
## Bug report

**Describe the bug**

I went to firebase online website to connect to flutter. It did not work and the time to build had exceeded 1 hour. I added the github line in podfile and it does not work at all.

[!] CocoaPods could not find compatible versions for pod "FirebaseFirestore":
  In Podfile:
    FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.15.0`)

    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 4.9.0, which depends on
      Firebase/Firestore (= 10.12.0) was resolved to 10.12.0, which depends on
        FirebaseFirestore (~> 10.12.0) 

is the error that is yielded when trying to pod install in ios.

### Steps to reproduce

Follow instructions from here https://firebase.google.com/docs/firestore/quickstart (They don't work)

Using the amount of lines the codebase is to justify wait is very unexpected from a company such as google. My mac mini won't even build at all and makes my computer so hot it may burn something. 

2. '...'
3. See error or incorrect behavior

    [!] CocoaPods could not find compatible versions for pod
    "FirebaseFirestore":
      In Podfile:
        FirebaseFirestore (from
        `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag
        `8.15.0`)

        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was
        resolved to 4.9.0, which depends on
          Firebase/Firestore (= 10.12.0) was resolved to 10.12.0, which depends
          on
            FirebaseFirestore (~> 10.12.0)

### STEPS TO FIX (disable the above error)

**⚠️ Note: where the tag says 7.11.0 this should be changed to the pod version of Firebase/Firestore that you or your dependencies are using - in the format X.X.X, for FlutterFire the version that is being used can be seen [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb), for React Native Firebase [here](https://github.com/invertase/react-native-firebase/blob/master/packages/app/package.json#L70). If no version is specified on your current Firebase/Firestore pod then you can omit , :tag => '7.11.0' from the line above and use the latest version on master.**

This should be on the firebase website instructions to avoid new tickets like this being created

### Expected behavior

flutter run should run the application after the above fixes are made to remove the error and allow flutter run to work

(It reduced to 67 seconds)

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

flutter run after adding lines in pod file does not work literally the basic file with just that added while installing the following yaml

<details>
<summary> pubspec.yaml</summary>

```
name: youreasypm
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  firebase_database: ^10.2.5
  cloud_firestore: ^4.9.0
  cloud_functions: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
</details>

---

## Additional context

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Run `flutter doctor` and paste the output below:
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.4.1 22F770820d darwin-x64,
    locale en-US)
    • Flutter version 3.13.1 on channel stable at /Users/mac/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (7 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.64.2)
    • VS Code at /Users/mac/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] VS Code (version 1.64.2)
    • VS Code at /Users/mac/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.70.0

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 769855C9-B655-4A4E-BD5E-735A0AD27F73 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Run `flutter pub deps -- --style=compact` and paste the output below:

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  firebase_database: ^10.2.5
  cloud_firestore: ^4.9.0
  cloud_functions: ^4.4.0
```

</details>

---
