### ISSUE TITLE
🐛 [cloud_firestore] Only iOS does not return a response for transaction get. 

### ISSUE THREAD

**Issue by hukusuke1007** [firebase/flutterfire#11755]
## Bug report

Only iOS does not return a response for transaction get. Android returns correctly.

## Additional context

cloud_firestore: 4.11.0 => NG, No response.
cloud_firestore: 4.9.3 => OK, Correct.

```dart
Future<void> func() async {
  await FirebaseFirestore.instance.runTransaction<void>((transaction) async {
    final ref = ...;
    final res = await transaction.get(ref); // no response and stop process.
  });
}
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on macOS 13.5.2 22G91 darwin-arm64, locale
    ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (6 available)
    ! Error: Browsing on the local area network for Apple Vision. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac. (code -27)
[✓] Network resources
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report @hukusuke1007 
I am unable to replicate this using plugin example running on iOS. Can you provide complete runnable code sample that we can directly use to verify it further ?

**Comment by sma** [comment]
I think, I've the same problem, too and I see this runtime error in the console:
```
2023-10-23 10:28:04.592 Tellorium[2074:9385894] -[NSError init] called; this results in an invalid NSError instance. It will raise an exception in a future release. Please call errorWithDomain:code:userInfo: or initWithDomain:code:userInfo:. This message shown only once.
```

I searched the source and [this could be the origin](https://github.com/firebase/flutterfire/blob/895da052207d832d30c9eeceafabac3051e1dabb/packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m#L646) The line was changed last week.

**Comment by bgetsug** [comment]
I'm having the same issue on macOS. My app freezes when calling `transaction.get(ref)`, and I see the same error as reported by @sma in my console.

The `get` call works as expected after rolling back to `cloud_firestore: 4.9.3`.

My code is similar to this:
```dart
    final ref = _firestore.collection("events").doc(id);

    try {
      await _firestore.runTransaction<void>((tx) async {
        await tx.get(ref);
        
        tx.set(ref, event);
      });
    } catch (e, t) {
      // logging
    }
```

**Comment by zifnap** [comment]
I have same problem too . It works fine with android bud ios freezes. do any of you know when will they fix this issue

**Comment by hukusuke1007** [comment]
@darshankawar The problem is reproduced when referring to a document that does not exist in Firestore.

**Comment by darshankawar** [comment]
Thanks for the update and reports. Using the plugin example and adding the code snippet as mentioned in original description and also as shown [here](https://github.com/firebase/flutterfire/issues/11755#issuecomment-1775645495), I did see the `likes` getting stuck while tapping on them and also saw below log in the console:

`2023-10-24 16:38:02.743276+0530 Runner[22998:248562] -[NSError init] called; this results in an invalid NSError instance. It will raise an exception in a future release. Please call errorWithDomain:code:userInfo: or initWithDomain:code:userInfo:. This message shown only once.
`

**Comment by Lyokone** [comment]
Hello, I couldn't reproduce this issue with both an existing document

```
  await FirebaseFirestore.instance.runTransaction<void>((transaction) async {
    final ref = FirebaseFirestore.instance
        .collection('firestore-example-app')
        .doc('test');
    final res = await transaction.get(ref); // no response and stop process.
    print(res.data());
  });
```

And a non-existing document
```
  await FirebaseFirestore.instance.runTransaction<void>((transaction) async {
    final ref = FirebaseFirestore.instance
        .collection('firestore-example-app')
        .doc('not-existing');
    final res = await transaction.get(ref); // no response and stop process.
    print(res.data());
  });
```

@darshankawar how were you able to reproduce it?

@hukusuke1007 could you share a complete sample?

**Comment by darshankawar** [comment]
> how were you able to reproduce it?

@Lyokone Attached is the video for reference. I saw it getting stuck during first run.


https://github.com/firebase/flutterfire/assets/67046386/1a41c97a-1955-4b4c-ba06-043a9fc5f662

**Comment by Lyokone** [comment]
@darshankawar Can you attach the full code so I can see it on my side? I see that you are using ios 15.2n do you reproduce the same thing with iOS 17?

**Comment by darshankawar** [comment]
Sure, here's the full code:

<details>
<summary> runnable code sample </summary>

```

// Copyright 2020, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';

/// Requires that a Firestore emulator is running locally.
/// See https://firebase.flutter.dev/docs/firestore/usage#emulator-usage
bool shouldUseFirestoreEmulator = false;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  if (shouldUseFirestoreEmulator) {
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  }

  final ref = FirebaseFirestore.instance;
  final documentRef = ref.collection('firestore-example-app').doc('Tenet');
  final documentSnap = await documentRef.get();
  print(documentSnap);

  runApp(FirestoreExampleApp());
}

/// A reference to the list of movies.
/// We are using `withConverter` to ensure that interactions with the collection
/// are type-safe.
final moviesRef = FirebaseFirestore.instance
    .collection('firestore-example-app')
    .withConverter<Movie>(
  fromFirestore: (snapshots, _) => Movie.fromJson(snapshots.data()!),
  toFirestore: (movie, _) => movie.toJson(),
);

/// The different ways that we can filter/sort movies.
enum MovieQuery {
  year,
  likesAsc,
  likesDesc,
  rated,
  sciFi,
  fantasy,
}

extension on Query<Movie> {
  /// Create a firebase query from a [MovieQuery]
  Query<Movie> queryBy(MovieQuery query) {
    switch (query) {
      case MovieQuery.fantasy:
        return where('genre', arrayContainsAny: ['fantasy']);

      case MovieQuery.sciFi:
        return where('genre', arrayContainsAny: ['sci-fi']);

      case MovieQuery.likesAsc:
      case MovieQuery.likesDesc:
        return orderBy('likes', descending: query == MovieQuery.likesDesc);

      case MovieQuery.year:
        return orderBy('year', descending: true);

      case MovieQuery.rated:
        return orderBy('rated', descending: true);
    }
  }
}

/// The entry point of the application.
///
/// Returns a [MaterialApp].
class FirestoreExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firestore Example App',
      theme: ThemeData.dark(),
      home: const Scaffold(
        body: Center(child: FilmList()),
      ),
    );
  }
}

/// Holds all example app films
class FilmList extends StatefulWidget {
  const FilmList({Key? key}) : super(key: key);

  @override
  _FilmListState createState() => _FilmListState();
}

class _FilmListState extends State<FilmList> {
  MovieQuery query = MovieQuery.year;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            const Text('Firestore Example: Movies'),

            // This is a example use for 'snapshots in sync'.
            // The view reflects the time of the last Firestore sync; which happens any time a field is updated.
            StreamBuilder(
              stream: FirebaseFirestore.instance.snapshotsInSync(),
              builder: (context, _) {
                return Text(
                  'Latest Snapshot: ${DateTime.now()}',
                  style: Theme.of(context).textTheme.bodySmall,
                );
              },
            ),
          ],
        ),
        actions: <Widget>[
          PopupMenuButton<MovieQuery>(
            onSelected: (value) => setState(() => query = value),
            icon: const Icon(Icons.sort),
            itemBuilder: (BuildContext context) {
              return [
                const PopupMenuItem(
                  value: MovieQuery.year,
                  child: Text('Sort by Year'),
                ),
                const PopupMenuItem(
                  value: MovieQuery.rated,
                  child: Text('Sort by Rated'),
                ),
                const PopupMenuItem(
                  value: MovieQuery.likesAsc,
                  child: Text('Sort by Likes ascending'),
                ),
                const PopupMenuItem(
                  value: MovieQuery.likesDesc,
                  child: Text('Sort by Likes descending'),
                ),
                const PopupMenuItem(
                  value: MovieQuery.fantasy,
                  child: Text('Filter genre fantasy'),
                ),
                const PopupMenuItem(
                  value: MovieQuery.sciFi,
                  child: Text('Filter genre sci-fi'),
                ),
              ];
            },
          ),
          PopupMenuButton<String>(
            onSelected: (_) => _resetLikes(),
            itemBuilder: (BuildContext context) {
              return [
                const PopupMenuItem(
                  value: 'reset_likes',
                  child: Text('Reset like counts (WriteBatch)'),
                ),
              ];
            },
          ),
        ],
      ),
      body: StreamBuilder<QuerySnapshot<Movie>>(
        stream: moviesRef.queryBy(query).snapshots(),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Center(
              child: Text(snapshot.error.toString()),
            );
          }

          if (!snapshot.hasData) {
            return const Center(child: CircularProgressIndicator());
          }

          final data = snapshot.requireData;

          return ListView.builder(
            itemCount: data.size,
            itemBuilder: (context, index) {
              return _MovieItem(
                data.docs[index].data(),
                data.docs[index].reference,
              );
            },
          );
        },
      ),
    );
  }

  Future<void> _resetLikes() async {
    final movies = await moviesRef.get(
      const GetOptions(
        serverTimestampBehavior: ServerTimestampBehavior.previous,
      ),
    );

    WriteBatch batch = FirebaseFirestore.instance.batch();

    for (final movie in movies.docs) {
      batch.update(movie.reference, {'likes': 0});
    }
    await batch.commit();
  }
}

/// A single movie row.
class _MovieItem extends StatelessWidget {
  _MovieItem(this.movie, this.reference);

  final Movie movie;
  final DocumentReference<Movie> reference;

  /// Returns the movie poster.
  Widget get poster {
    return SizedBox(
      width: 100,
      child: Image.network(movie.poster),
    );
  }

  /// Returns movie details.
  Widget get details {
    return Padding(
      padding: const EdgeInsets.only(left: 8, right: 8),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          title,
          metadata,
          genres,
          Likes(
            reference: reference,
            currentLikes: movie.likes,
          ),
        ],
      ),
    );
  }

  /// Return the movie title.
  Widget get title {
    return Text(
      '${movie.title} (${movie.year})',
      style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
    );
  }

  /// Returns metadata about the movie.
  Widget get metadata {
    return Padding(
      padding: const EdgeInsets.only(top: 8),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.only(right: 8),
            child: Text('Rated: ${movie.rated}'),
          ),
          Text('Runtime: ${movie.runtime}'),
        ],
      ),
    );
  }

  /// Returns a list of genre movie tags.
  List<Widget> get genreItems {
    return [
      for (final genre in movie.genre)
        Padding(
          padding: const EdgeInsets.only(right: 2),
          child: Chip(
            backgroundColor: Colors.lightBlue,
            label: Text(
              genre,
              style: const TextStyle(color: Colors.white),
            ),
          ),
        ),
    ];
  }

  /// Returns all genres.
  Widget get genres {
    return Padding(
      padding: const EdgeInsets.only(top: 8),
      child: Wrap(
        children: genreItems,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 4, top: 4),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          poster,
          Flexible(child: details),
        ],
      ),
    );
  }
}

/// Displays and manages the movie 'like' count.
class Likes extends StatefulWidget {
  /// Constructs a new [Likes] instance with a given [DocumentReference] and
  /// current like count.
  Likes({
    Key? key,
    required this.reference,
    required this.currentLikes,
  }) : super(key: key);

  /// The reference relating to the counter.
  final DocumentReference<Movie> reference;

  /// The number of current likes (before manipulation).
  final int currentLikes;

  @override
  _LikesState createState() => _LikesState();
}

class _LikesState extends State<Likes> {
  /// A local cache of the current likes, used to immediately render the updated
  /// likes count after an update, even while the request isn't completed yet.
  late int _likes = widget.currentLikes;

  final ref = FirebaseFirestore.instance.collection('firestore-example-app').doc('Tenet');

  Future<void> _onLike() async {
    final currentLikes = _likes;

    // Increment the 'like' count straight away to show feedback to the user.
    setState(() {
      _likes = currentLikes + 1;
    });

    try {
      // Update the likes using a transaction.
      // We use a transaction because multiple users could update the likes count
      // simultaneously. As such, our likes count may be different from the likes
      // count on the server.

      await FirebaseFirestore.instance.runTransaction<void>((transaction) async {
        final ref = FirebaseFirestore.instance
            .collection('firestore-example-app')
            .doc('not-existing');
        final res = await transaction.get(ref); // no response and stop process.
        print(res.data());
      });

      int newLikes = await FirebaseFirestore.instance
          .runTransaction<int>((transaction) async {
        DocumentSnapshot<Movie> movie =
        await transaction.get<Movie>(widget.reference);

        if (!movie.exists) {
          throw Exception('Document does not exist!');
        }

        int updatedLikes = movie.data()!.likes + 1;
        transaction.update(widget.reference, {'likes': updatedLikes});
        final res = await transaction.get(movie as DocumentReference<Object?>);
        print(res);
        return updatedLikes;



      });

      // Update with the real count once the transaction has completed.
      setState(() => _likes = newLikes);
    } catch (e, s) {
      print(s);
      print('Failed to update likes for document! $e');

      // If the transaction fails, revert back to the old count
      setState(() => _likes = currentLikes);
    }
  }

  @override
  void didUpdateWidget(Likes oldWidget) {
    super.didUpdateWidget(oldWidget);
    // The likes on the server changed, so we need to update our local cache to
    // keep things in sync. Otherwise if another user updates the likes,
    // we won't see the update.
    if (widget.currentLikes != oldWidget.currentLikes) {
      _likes = widget.currentLikes;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        IconButton(
          iconSize: 20,
          onPressed: _onLike,
          icon: const Icon(Icons.favorite),
        ),
        Text('$_likes likes'),
      ],
    );
  }
}

@immutable
class Movie {
  Movie({
    required this.genre,
    required this.likes,
    required this.poster,
    required this.rated,
    required this.runtime,
    required this.title,
    required this.year,
  });

  Movie.fromJson(Map<String, Object?> json)
      : this(
    genre: (json['genre']! as List).cast<String>(),
    likes: json['likes']! as int,
    poster: json['poster']! as String,
    rated: json['rated']! as String,
    runtime: json['runtime']! as String,
    title: json['title']! as String,
    year: json['year']! as int,
  );

  final String poster;
  final int likes;
  final String title;
  final int year;
  final String runtime;
  final String rated;
  final List<String> genre;

  Map<String, Object?> toJson() {
    return {
      'genre': genre,
      'likes': likes,
      'poster': poster,
      'rated': rated,
      'runtime': runtime,
      'title': title,
      'year': year,
    };
  }
}

```

</details>


Also, I don't have iOS 17 to replicate the behavior currently.

**Comment by hukusuke1007** [comment]
@Lyokone iOS17.0.1

**Comment by Lyokone** [comment]
I don't see any freeze or error in both iOS 15 and 17.0.1.
@hukusuke1007 could you give me a complete sample project so I can investigate it more in depth? Could you also provide your pubspec.yaml?
Thanks

**Comment by hukusuke1007** [comment]
Maybe it has something to do with the Firestore region. The region I have reproduced is the Tokyo region (asia-northeast1).

**Comment by bgetsug** [comment]
I use the Invertase iOS SDK frameworks in both my iOS and macOS projects where I experienced this issue... could that have something to do with it? 

`Podfile` excerpt:
```ruby
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # https://firebase.flutter.dev/docs/overview#improve-ios-build-times
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.15.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

**Comment by arnab** [comment]
> I use the Invertase iOS SDK frameworks in both my iOS and macOS projects where I experienced this issue... could that have something to do with it?

FWIW, we use it too. But I tried with and without that (the pre-compiled `invertase/firestore-ios-sdk-frameworks 10.15.0`) and it kept freezing.

Once I downgraded and pinned the `cloud_firestore: 4.9.3` the freezing goes away. I am continuing to use `invertase/firestore-ios-sdk-frameworks` (as I was before).

**Comment by batmanonabike** [comment]
I use:
`  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.15.0'`

It's not that, I use it too.
I tried many [different things ](https://www.reddit.com/r/flutterhelp/comments/17drftg/macos_and_ios_builds_hanging_after_updates/)to resolve it, including rebuilds without the pre-build binary.

**Comment by batmanonabike** [comment]
> I use the Invertase iOS SDK frameworks in both my iOS and macOS projects where I experienced this issue... could that have something to do with it?

Off topic but, how do you accomplish the pre-build for MacOS?  Last I read, it wasn't supported.

**Comment by russellwheatley** [comment]
@hukusuke1007 - could you provide the contents of your `pubspec.lock` and your `Podfile.lock`, please?

**Comment by batmanonabike** [comment]
@russellwheatley Are you not able to reproduce?  It happens every time for me.  If you want any pod info then let me know.  Or I can create a new project with just the bug.

**Comment by sma** [comment]
This minimal app hangs on macOS 14.0, Xcode 15.0.1, Flutter 3.16.0-15.0.pre.42 with cloud_firestore 4.11 and 4.12.  It correctly runs with cloud_firestore 4.9. I cannot compile with 4.10. 

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/widgets.dart';

import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  final ref = FirebaseFirestore.instance.collection('foo').doc('1235');
  print('start transaction');
  await ref.firestore.runTransaction((transaction) async {
    print('begin transaction');
    print(await transaction.get(ref));
  });
  print('end transaction');
}
```

It prints 

```
flutter: start transaction
flutter: begin transaction
2023-10-25 10:31:41.452 Tellorium[65091:11106237] -[NSError init] called; this results in an invalid NSError instance. It will raise an exception in a future release. Please call errorWithDomain:code:userInfo: or initWithDomain:code:userInfo:. This message shown only once.
```

It never reaches the `end transaction`.

**Comment by batmanonabike** [comment]
Rebuilding with the same yaml is [not consistent](https://www.reddit.com/r/flutterhelp/comments/17drftg/comment/k63qa64/?utm_source=share&utm_medium=web2x&context=3).

**Comment by russellwheatley** [comment]
I am not able to reproduce. @batmanonabike - if you want to create a new project with the bug, we would be grateful. Thanks.

**Comment by batmanonabike** [comment]
> I am not able to reproduce. @batmanonabike - if you want to create a new project with the bug, we would be grateful. Thanks.

It looks like @sma beat me to it! ^^^

**Comment by russellwheatley** [comment]
@batmanonabike  I've tested that, it worked for me.

**Comment by sma** [comment]
> @batmanonabike I've tested that, it worked for me.

My system hangs (with or without that collection).

Without the transaction (simply running `print(await ref.get());`), it works. So I'm pretty sure the transaction call it responsible.

In the unlikely case the firebase region matters: I'm using `europe-west3`.

**Comment by batmanonabike** [comment]
> > @batmanonabike I've tested that, it worked for me.
> 
> My system hangs (with or without that collection).
> 
> Without the transaction (simply running `print(await ref.get());`), it works. So I'm pretty sure the transaction call it responsible.
> 
> In the unlikely case the firebase region matters: I'm using `europe-west3`.

Please supply yaml, pubspec.lock, Podfile.lock for @russellwheatley ? 
It's gonna be dependencies.

**Comment by sma** [comment]
I attached a debugger and here the process hangs:

<img width="1164" alt="image" src="https://github.com/firebase/flutterfire/assets/14989/f6d49b14-5d12-4684-8fd6-ab117c49be44">

**Comment by russellwheatley** [comment]
<details>
<summary>flutter doctor</summary>

[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2020.1.1)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

</details>

<details>
<summary>Podfile.lock</summary>

```bash


PODS:
  - cloud_firestore (4.12.0):
    - Firebase/Firestore (= 10.16.0)
    - firebase_core
    - Flutter
    - nanopb (< 2.30910.0, >= 2.30908.0)
  - Firebase/CoreOnly (10.16.0):
    - FirebaseCore (= 10.16.0)
  - Firebase/Firestore (10.16.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 10.16.0)
  - firebase_core (2.20.0):
    - Firebase/CoreOnly (= 10.16.0)
    - Flutter
  - FirebaseCore (10.16.0):
    - FirebaseCoreInternal (~> 10.0)
    - GoogleUtilities/Environment (~> 7.8)
    - GoogleUtilities/Logger (~> 7.8)
  - FirebaseCoreInternal (10.16.0):
    - "GoogleUtilities/NSData+zlib (~> 7.8)"
  - FirebaseFirestore (10.16.0):
    - FirebaseFirestore/AutodetectLeveldb (= 10.16.0)
  - FirebaseFirestore/AutodetectLeveldb (10.16.0):
    - FirebaseFirestore/Base
    - FirebaseFirestore/WithLeveldb
  - FirebaseFirestore/Base (10.16.0)
  - FirebaseFirestore/WithLeveldb (10.16.0):
    - FirebaseFirestore/Base
  - Flutter (1.0.0)
  - GoogleUtilities/Environment (7.11.5):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.11.5):
    - GoogleUtilities/Environment
  - "GoogleUtilities/NSData+zlib (7.11.5)"
  - integration_test (0.0.1):
    - Flutter
  - nanopb (2.30909.0):
    - nanopb/decode (= 2.30909.0)
    - nanopb/encode (= 2.30909.0)
  - nanopb/decode (2.30909.0)
  - nanopb/encode (2.30909.0)
  - PromisesObjC (2.3.1)

DEPENDENCIES:
  - cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`)
  - firebase_core (from `.symlinks/plugins/firebase_core/ios`)
  - FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `10.16.0`)
  - Flutter (from `Flutter`)
  - integration_test (from `.symlinks/plugins/integration_test/ios`)

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseCore
    - FirebaseCoreInternal
    - GoogleUtilities
    - nanopb
    - PromisesObjC

EXTERNAL SOURCES:
  cloud_firestore:
    :path: ".symlinks/plugins/cloud_firestore/ios"
  firebase_core:
    :path: ".symlinks/plugins/firebase_core/ios"
  FirebaseFirestore:
    :git: https://github.com/invertase/firestore-ios-sdk-frameworks.git
    :tag: 10.16.0
  Flutter:
    :path: Flutter
  integration_test:
    :path: ".symlinks/plugins/integration_test/ios"

CHECKOUT OPTIONS:
  FirebaseFirestore:
    :git: https://github.com/invertase/firestore-ios-sdk-frameworks.git
    :tag: 10.16.0

SPEC CHECKSUMS:
  cloud_firestore: 843f8a06ac49a1177b73a2a2475cc3918593478e
  Firebase: 25899099b77d255a636e3579c3d9dce10ec150d5
  firebase_core: 2e0e89436a00b664a23bebb08859e5fede7215e9
  FirebaseCore: 65a801af84cca84361ef9eac3fd868656968a53b
  FirebaseCoreInternal: 26233f705cc4531236818a07ac84d20c333e505a
  FirebaseFirestore: a78fa6e8bd3644023c22d5212e7afee9d7522194
  Flutter: f04841e97a9d0b0a8025694d0796dd46242b2854
  GoogleUtilities: 13e2c67ede716b8741c7989e26893d151b2b2084
  integration_test: 13825b8a9334a850581300559b8839134b124670
  nanopb: b552cce312b6c8484180ef47159bc0f65a1f0431
  PromisesObjC: c50d2056b5253dadbd6c2bea79b0674bd5a52fa4

PODFILE CHECKSUM: ae3157f4977dd383b17d4a5a86c4a623bfc0a331

COCOAPODS: 1.13.0


```

</details>

I am using packages from `master` which is essentially the latest release from yesterday afternoon. 
<details>
<summary>pubspec.lock</summary>

```yaml


# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  _flutterfire_internals:
    dependency: "direct overridden"
    description:
      path: "../../../_flutterfire_internals"
      relative: true
    source: path
    version: "1.3.10"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: "04a925763edad70e8443c99234dc3328f442e811f1d8fd1a72f1c8ad0f69a605"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.0"
  clock:
    dependency: transitive
    description:
      name: clock
      sha256: cb6d7f03e1de671e34607e909a7213e31d7752be4fb66a86d29fe1eb14bfb5cf
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
  cloud_firestore:
    dependency: "direct main"
    description:
      path: ".."
      relative: true
    source: path
    version: "4.12.0"
  cloud_firestore_platform_interface:
    dependency: "direct overridden"
    description:
      path: "../../cloud_firestore_platform_interface"
      relative: true
    source: path
    version: "6.0.2"
  cloud_firestore_web:
    dependency: "direct overridden"
    description:
      path: "../../cloud_firestore_web"
      relative: true
    source: path
    version: "3.8.2"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: f092b211a4319e98e5ff58223576de6c2803db36221657b46c82574721240687
      url: "https://pub.dev"
    source: hosted
    version: "1.17.2"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      sha256: "511392330127add0b769b75a987850d136345d9227c6b94c96a04cf4a391bf78"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.1"
  file:
    dependency: transitive
    description:
      name: file
      sha256: "1b92bec4fc2a72f59a8e15af5f52cd441e4a7860b49499d69dfa817af20e925d"
      url: "https://pub.dev"
    source: hosted
    version: "6.1.4"
  firebase_core:
    dependency: "direct main"
    description:
      path: "../../../firebase_core/firebase_core"
      relative: true
    source: path
    version: "2.20.0"
  firebase_core_platform_interface:
    dependency: "direct overridden"
    description:
      path: "../../../firebase_core/firebase_core_platform_interface"
      relative: true
    source: path
    version: "5.0.0"
  firebase_core_web:
    dependency: "direct overridden"
    description:
      path: "../../../firebase_core/firebase_core_web"
      relative: true
    source: path
    version: "2.8.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_driver:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  fuchsia_remote_debug_protocol:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  http:
    dependency: "direct main"
    description:
      name: http
      sha256: "6aa2946395183537c8b880962d935877325d6a09a2867c3970c05c0fed6ac482"
      url: "https://pub.dev"
    source: hosted
    version: "0.13.5"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      sha256: "2aa08ce0341cc9b354a498388e30986515406668dbcc4f7c950c3e715496693b"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.2"
  integration_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  js:
    dependency: transitive
    description:
      name: js
      sha256: f2c445dce49627136094980615a031419f7f3eb393237e4ecd97ac15dea343f3
      url: "https://pub.dev"
    source: hosted
    version: "0.6.7"
  matcher:
    dependency: transitive
    description:
      name: matcher
      sha256: "1803e76e6653768d64ed8ff2e1e67bea3ad4b923eb5c56a295c3e634bad5960e"
      url: "https://pub.dev"
    source: hosted
    version: "0.12.16"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      sha256: "9528f2f296073ff54cb9fee677df673ace1218163c3bc7628093e7eed5203d41"
      url: "https://pub.dev"
    source: hosted
    version: "0.5.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "3c74dbf8763d36539f114c799d8a2d87343b5067e9d796ca22b5eb8437090ee3"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.1"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "8829d8a55c13fc0e37127c29fedf290c102f4e40ae94ada574091fe0ff96c917"
      url: "https://pub.dev"
    source: hosted
    version: "1.8.3"
  platform:
    dependency: transitive
    description:
      name: platform
      sha256: "4a451831508d7d6ca779f7ac6e212b4023dd5a7d08a27a63da33756410e32b76"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.0"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      sha256: dbf0f707c78beedc9200146ad3cb0ab4d5da13c246336987be6940f026500d3a
      url: "https://pub.dev"
    source: hosted
    version: "2.1.3"
  process:
    dependency: transitive
    description:
      name: process
      sha256: "53fd8db9cec1d37b0574e12f07520d582019cb6c44abf5479a01505099a34a09"
      url: "https://pub.dev"
    source: hosted
    version: "4.2.4"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "53e943d4206a5e30df338fd4c6e7a077e02254531b138a15aec3bd143c1a8b3c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      sha256: c3c7d8edb15bee7f0f74debd4b9c5f3c2ea86766fe4178eb2a18eb30a0bdaed5
      url: "https://pub.dev"
    source: hosted
    version: "1.11.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      sha256: "83615bee9045c1d322bbbd1ba209b7a749c2cbcdcb3fdd1df8eb488b3279c1c8"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  sync_http:
    dependency: transitive
    description:
      name: sync_http
      sha256: "7f0cd72eca000d2e026bcd6f990b81d0ca06022ef4e32fb257b30d3d1014a961"
      url: "https://pub.dev"
    source: hosted
    version: "0.3.1"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  test_api:
    dependency: transitive
    description:
      name: test_api
      sha256: "75760ffd7786fffdfb9597c35c5b27eaeec82be8edfb6d71d32651128ed7aab8"
      url: "https://pub.dev"
    source: hosted
    version: "0.6.0"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      sha256: "26f87ade979c47a150c9eaab93ccd2bebe70a27dc0b4b29517f2904f04eb11a5"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.1"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  vm_service:
    dependency: transitive
    description:
      name: vm_service
      sha256: c620a6f783fa22436da68e42db7ebbf18b8c44b9a46ab911f666ff09ffd9153f
      url: "https://pub.dev"
    source: hosted
    version: "11.7.1"
  web:
    dependency: transitive
    description:
      name: web
      sha256: dc8ccd225a2005c1be616fe02951e2e342092edf968cf0844220383757ef8f10
      url: "https://pub.dev"
    source: hosted
    version: "0.1.4-beta"
  webdriver:
    dependency: transitive
    description:
      name: webdriver
      sha256: "3c923e918918feeb90c4c9fdf1fe39220fa4c0e8e2c0fffaded174498ef86c49"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.2"
sdks:
  dart: ">=3.1.0-185.0.dev <4.0.0"



```

</details>
