### ISSUE TITLE
🐛 [firebase_auth] Android app crashed when recived sms code if timeout is not setted

### ISSUE THREAD

**Issue by guvanch07** [firebase/flutterfire#12170]
## Bug report

**Describe the bug**
Android app crashed when recived sms code if timeout is not setted

RuntimeException
Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.alephexpress.mobile (has extras) } in com.google.android.gms.internal.firebase-auth-api.zzady@a70f551

### Steps to reproduce

Create new firebase project and add phone provider
call verifyPhoneNumber method  from FirebaseAuth
and don't set timeout

1. Write your phone number and send it
2. Recive sms code
3. Crash

### Expected behavior
Recive sms code and paste it to textfilds

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.16.5, on macOS 13.5 22G74 darwin-arm64, locale en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  intl: ^0.18.1
  slang: ^3.26.2
  slang_flutter: ^3.26.2
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0
  sentry_flutter: ^7.13.2
  sentry_dio: ^7.13.2
  flutter_svg: ^2.0.9
  crypto: ^3.0.3
  get_it: ^7.6.4
  email_validator: ^2.1.17
  mask_text_input_formatter: ^2.7.0
  cupertino_icons: ^1.0.6
  pull_to_refresh: ^2.0.0
  device_preview: ^1.1.0
  url_launcher: ^6.2.2
  permission_handler: ^11.1.0
  fast_cached_network_image: ^1.2.0
  modal_bottom_sheet: ^3.0.0-pre
  keyboard_actions: ^4.2.0
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0
  reorderable_grid: ^1.0.10
  uuid: ^3.0.7
  webview_flutter: ^4.4.2
  collection: ^1.17.2
  logger: ^2.0.2
  flutter_slidable: ^3.0.1
  share_plus: ^7.0.2
  grouped_list: ^5.1.2
  idkit_inputformatters: ^0.0.1
  jwt_decoder: ^2.0.1
  jiffy: ^6.2.1
  package_info_plus: ^5.0.1
  regexed_validator: ^2.0.0+1
  google_fonts: ^6.0.0
  cupertino_will_pop_scope: ^1.2.1
  dotted_border: ^2.1.0
  dotted_decoration: ^2.0.0
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.2.0
  firebase_analytics: ^10.7.4
  shimmer: ^3.0.0
  go_router: ^12.1.1
  flutter_facebook_auth: ^6.0.3
  ios_willpop_transition_theme: ^0.0.6
  badges: ^3.1.2
  freshchat_sdk: ^0.10.10
  retry: ^3.1.2
  slide_action: ^0.0.2
  loop_page_view: ^1.2.5
  path_provider: ^2.1.1
  video_thumbnail: ^0.5.3
  video_player: ^2.8.1
  flick_video_player: ^0.7.0
  visibility_detector: ^0.4.0+2
  uni_links: ^0.5.1
  app_tracking_transparency: ^2.0.4
  connectivity_plus: ^5.0.2
  flutter_linkify: ^6.0.0
  device_info_plus: ^9.0.1
  flutter_inappwebview:
    git:
      url: https://github.com/LuckyWins/flutter_inappwebview.git
      ref: v5.7.2+3-xcode-fix
  flutter_image_compress: ^2.1.0
  path: ^1.8.3
  pinput: ^3.0.1
  firebase_auth: ^4.15.3
  # phone_numbers_parser: ^8.0.0 // maybe will use
  facebook_app_events: ^0.19.0
  audio_waveforms: ^1.0.4
  any_link_preview: ^3.0.1
  audio_session: ^0.1.18
  multi_split_view: ^2.4.0
  wechat_assets_picker: 9.0.0-dev.2
  lottie: ^2.7.0
  upgrader: ^8.3.0
  appsflyer_sdk: ^6.12.2
  flutter_smartlook: ^4.1.14
  # ffmpeg_kit_flutter: ^6.0.3
  ffmpeg_kit_flutter_audio: ^6.0.3
  chucker_flutter: ^1.6.0
  flutter_libphonenumber: ^2.1.5
  sliver_tools: ^0.2.12
  flex_color_picker: ^3.3.0
  clock: ^1.1.1
```

</details>

---
