### ISSUE TITLE
🐛 [firebase_in_app_messaging] Import says "Target of URI doesn't exist: 'package:firebase_in_app_messaging/firebase_in_app_messaging.dart'."

### ISSUE THREAD

**Issue by danielgomezrico** [firebase/flutterfire#12483]
## Bug report

**Describe the bug**
The documentation says that I must import this:
<img width="918" alt="image" src="https://github.com/firebase/flutterfire/assets/76348/b9325d30-4f16-4840-aec2-285c08b8c760">

But after importing the linter says:
```dart
Target of URI doesn't exist: 'package:firebase_in_app_messaging/firebase_in_app_messaging.dart'. (
Documentation)
```

### Steps to reproduce

1. Create an empty project
Include this:
```yaml
  firebase_core: 2.27.1
  firebase_crashlytics: 3.4.19
  firebase_performance: 0.9.3+18
  firebase_remote_config: 4.3.18
  firebase_in_app_messaging: 0.7.4+18
```
2. Follow documentation steps:
   ![image](https://github.com/firebase/flutterfire/assets/76348/049d41c0-12ca-4565-9a09-326664c21a51)

### Expected behavior

The linter should not appear or the documentation should be updated, the import is not required to make it work.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.2.1 23C71 darwin-arm64, locale en-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Community Edition (version 2023.3.4)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

---
