### ISSUE TITLE
[FirebaseAuth]: Windows app crashes when trying to verify email

### ISSUE THREAD

**Issue by sharprogramming** [firebase/flutterfire#12505]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Windows

### Description

When I try to verify a email for a user the app crashes with the following exception.

Unhandled exception at 0x00007FFC14BB829C (ucrtbased.dll) in verify_test.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.

 I have posted the log output below.

### Reproducing the issue

1. Download the example code
2. Create account.
3. Try to verify email. 

### Firebase Core version

2.27.1

### Flutter Version

3.19.2

### Relevant Log Output

```shell
ucrtbased.dll!00007ffc14bb829c()	Unknown
>	verify_test.exe!std::bad_variant_access::_Doraise() Line 404	C++
 	verify_test.exe!stdext::exception::_Raise() Line 117	C++
 	verify_test.exe!std::_Throw_bad_variant_access() Line 409	C++
 	verify_test.exe!std::get<12,std::monostate,bool,int,__int64,double,std::string,std::vector<unsigned char,std::allocator<unsigned char>>,std::vector<int,std::allocator<int>>,std::vector<__int64,std::allocator<__int64>>,std::vector<double,std::allocator<double>>,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue>>,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue>>>,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>>(const std::variant<std::monostate,bool,int,__int64,double,std::string,std::vector<unsigned char,std::allocator<unsigned char>>,std::vector<int,std::allocator<int>>,std::vector<__int64,std::allocator<__int64>>,std::vector<double,std::allocator<double>>,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue>>,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue>>>,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>> & _Var) Line 1216	C++
 	verify_test.exe!std::get<flutter::CustomEncodableValue,std::monostate,bool,int,__int64,double,std::string,std::vector<unsigned char,std::allocator<unsigned char>>,std::vector<int,std::allocator<int>>,std::vector<__int64,std::allocator<__int64>>,std::vector<double,std::allocator<double>>,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue>>,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue>>>,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>>(const std::variant<std::monostate,bool,int,__int64,double,std::string,std::vector<unsigned char,std::allocator<unsigned char>>,std::vector<int,std::allocator<int>>,std::vector<__int64,std::allocator<__int64>>,std::vector<double,std::allocator<double>>,std::vector<flutter::EncodableValue,std::allocator<flutter::EncodableValue>>,std::map<flutter::EncodableValue,flutter::EncodableValue,std::less<flutter::EncodableValue>,std::allocator<std::pair<flutter::EncodableValue const ,flutter::EncodableValue>>>,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>> & _Var) Line 1251	C++
 	verify_test.exe!firebase_auth_windows::FirebaseAuthUserHostApi::SetUp::__l48::<lambda>(const flutter::EncodableValue & message, const std::function<void __cdecl(flutter::EncodableValue const &)> & reply) Line 3626	C++
 	verify_test.exe!std::invoke<void <lambda>(const flutter::EncodableValue &, const std::function<void __cdecl(flutter::EncodableValue const &)> &) &,flutter::EncodableValue const &,std::function<void __cdecl(flutter::EncodableValue const &)> const &>(firebase_auth_windows::FirebaseAuthUserHostApi::SetUp::__l48::void <lambda>(const flutter::EncodableValue &, const std::function<void __cdecl(flutter::EncodableValue const &)> &) & _Obj, const flutter::EncodableValue & _Arg1, const std::function<void __cdecl(flutter::EncodableValue const &)> & <_Args2_0>) Line 1754	C++
 	verify_test.exe!std::_Func_impl_no_alloc<void <lambda>(const flutter::EncodableValue &, const std::function<void __cdecl(flutter::EncodableValue const &)> &),void,flutter::EncodableValue const &,std::function<void __cdecl(flutter::EncodableValue const &)> const &>::_Do_call(const flutter::EncodableValue & <_Args_0>, const std::function<void __cdecl(flutter::EncodableValue const &)> & <_Args_1>) Line 909	C++
 	verify_test.exe!std::_Func_class<void,flutter::EncodableValue const &,std::function<void __cdecl(flutter::EncodableValue const &)> const &>::operator()(const flutter::EncodableValue & <_Args_0>, const std::function<void __cdecl(flutter::EncodableValue const &)> & <_Args_1>) Line 952	C++
 	verify_test.exe!flutter::BasicMessageChannel<flutter::EncodableValue>::SetMessageHandler::__l2::<lambda>(const unsigned char * binary_message, const unsigned __int64 binary_message_size, const std::function<void __cdecl(unsigned char const *,unsigned __int64)> & binary_reply) Line 119	C++
 	[External Code]	
 	verify_test.exe!flutter::`anonymous namespace'::ForwardToHandler(FlutterDesktopMessenger * messenger, const FlutterDesktopMessage * message, void * user_data) Line 76	C++
 	[External Code]	
 	verify_test.exe!wWinMain(HINSTANCE__ * instance, HINSTANCE__ * prev, wchar_t * command_line, int show_command) Line 39	C++
 	[External Code]
```

### Flutter dependencies

  <details>
  <summary>Expand <code>Flutter dependencies</code> snippet</summary>
  <br>

```yaml

Dart SDK 3.3.0
Flutter SDK 3.19.2
verify_test 0.0.0

dependencies:
- barcode_widget 2.0.4 [barcode flutter]
- firebase_auth 4.17.9 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.27.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.7.20 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_facebook_auth 6.1.1 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web facebook_auth_desktop]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_dartio 0.3.0 [flutter google_sign_in google_sign_in_platform_interface shared_preferences shared_preferences_foundation shared_preferences_linux url_launcher url_launcher_macos crypto http html_unescape]

dev dependencies:
- http 1.2.1 [async http_parser meta web]

transitive dependencies:
- _flutterfire_internals 1.3.26 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- barcode 2.2.6 [meta qr]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- crypto 3.0.3 [typed_data]
- facebook_auth_desktop 1.0.3 [flutter http flutter_secure_storage flutter_facebook_auth_platform_interface]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- firebase_auth_platform_interface 7.1.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.10.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.12.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_messaging_platform_interface 4.5.28 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.7.0 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta web]
- flutter_facebook_auth_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 5.0.0 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_secure_storage 9.0.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_secure_storage_linux 1.2.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.0.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.1.2 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.0.0 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- font_awesome_flutter 9.2.0 [flutter]
- google_identity_services_web 0.3.1+1 [meta web]
- google_sign_in_android 6.1.22 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.4 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- html_unescape 2.0.0
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- path 1.9.0
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- qr 3.0.1 [meta]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.3.0 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- url_launcher 6.2.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.5.1
- win32 5.3.0 [ffi]
- xdg_directories 1.0.4 [meta path]


```

</details>

### Additional context and comments

I didn't change any of the code provided in the example code provided here https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example, I downloaded all the files from the lib folder, as well as copy pasted almost everything from the pubspec.yaml, leaving only the following lines from my project in the pubspec.yaml folder

```
name: verify_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
```
