### ISSUE TITLE
[firebase_auth]: Failure to Properly Unlink Google Authentication Provider from User Account.

### ISSUE THREAD

**Issue by matsuyani556** [firebase/flutterfire#12538]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android

### Description

When linking a Google authentication provider to an anonymous account and then unlinking it, the user's Identifier remains in the system. Attempting to link this Google account to a different anonymous account results in an error stating that the account is already linked. Furthermore, signing in with the same Google account after unlinking it still links it to the previous account.

### Reproducing the issue

**Code sample**

<details><summary>main.dart</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart' as auth;
import 'package:firebase_core/firebase_core.dart';
import 'package:google_sign_in/google_sign_in.dart';

import 'firebase_options.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  StreamSubscription<auth.User?>? _firebaseSubscription;
  GoogleSignIn get _googleSignIn => GoogleSignIn(
        signInOption: SignInOption.standard,
      );

  bool _initialized = false;

  Future<void> _initWithFirebase() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.android,
    );

    _firebaseSubscription =
        auth.FirebaseAuth.instance.userChanges().listen(_onFirebaseUserChanged);
  }

  void _onFirebaseUserChanged(auth.User? firebaseUser) async {
    if (firebaseUser == null) {
      await auth.FirebaseAuth.instance.signInAnonymously();
      return;
    }

    if (mounted) {
      setState(() {
        _initialized = true;
      });
    }
  }

  @override
  void initState() {
    super.initState();
    _initWithFirebase();
  }

  @override
  void dispose() {
    _firebaseSubscription?.cancel();
    super.dispose();
  }

  Future<void> _linkOrSignInGoogle(bool link) async {
    if (link && auth.FirebaseAuth.instance.currentUser == null) {
      throw Exception('FirebaseAuth currentUser is null');
    }

    try {
      final tGoogleUser = await _googleSignIn.signIn();

      if ((link && auth.FirebaseAuth.instance.currentUser == null) ||
          tGoogleUser == null) {
        throw Exception('Could not get Google user');
      }

      final tGoogleAuth = await tGoogleUser.authentication;

      final tCredential = auth.GoogleAuthProvider.credential(
        accessToken: tGoogleAuth.accessToken,
        idToken: tGoogleAuth.idToken,
      );

      if (link && auth.FirebaseAuth.instance.currentUser == null) {
        throw Exception('FirebaseAuth user gone while processing');
      }

      await (link
          ? _linkWithCredential(tCredential)
          : _signInWithCredential(tCredential));
    } catch (e, stackTrace) {
      debugPrintStack(
        label: e.toString(),
        stackTrace: stackTrace,
      );
    }

    if (mounted) {
      setState(() {});
    }
  }

  Future<void> _unlinkGoogle() async {
    await auth.FirebaseAuth.instance.currentUser
        ?.unlink(auth.GoogleAuthProvider.PROVIDER_ID);

    await _googleSignIn.signOut();

    await auth.FirebaseAuth.instance.currentUser?.reload();

    if (mounted) {
      setState(() {});
    }
  }

  Future<bool> _linkWithCredential(auth.AuthCredential credential) async {
    final tUserCredential = await auth.FirebaseAuth.instance.currentUser!
        .linkWithCredential(credential);

    return tUserCredential.credential != null;
  }

  Future<bool> _signInWithCredential(auth.AuthCredential credential) async {
    final tUserCredential =
        await auth.FirebaseAuth.instance.signInWithCredential(credential);

    return tUserCredential.credential != null;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            if (_initialized) ...[
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Text(
                  'FirebaseAuth UID: ${auth.FirebaseAuth.instance.currentUser?.uid ?? 'null'}',
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Text(
                  'ProviderIds: ${auth.FirebaseAuth.instance.currentUser?.providerData.map((e) => e.providerId).join(',') ?? 'null'}',
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: ElevatedButton(
                  onPressed: () {
                    _linkOrSignInGoogle(true);
                  },
                  child: const Text(
                    'Link Google',
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: ElevatedButton(
                  onPressed: () {
                    _linkOrSignInGoogle(false);
                  },
                  child: const Text(
                    'SignIn Google',
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: ElevatedButton(
                  onPressed: () {
                    _unlinkGoogle();
                  },
                  child: const Text(
                    'Unlink Google',
                  ),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}
```

</details>

<details><summary>pubspec.yaml</summary>

```yaml
dependencies:
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
```

</details>

**Step:**

1. Create a Firebase project and set up Firebase Authentication to be usable.
    - Specify Anonymous and Google as the Sign-in providers.
2. Follow the [documentation](https://firebase.google.com/docs/flutter/setup?hl=en&platform=android) to configure a Flutter app.
3. Execute the sample code.
    - Upon app launch, a new Anonymous account will be created.
4. Tap Link Google.
    - Sign in with a Google account.
    - The account gets linked to the Google account.
5. Tap Unlink Google.
    - The Google account is supposed to be unlinked, but an Identifier remains in Firebase.
6. Uninstall and then reinstall the app.
    - Upon app launch, a new Anonymous account will be created.
7. Tap Link Google.
    - Sign in with the same Google account as in Step 4.
    - Linking fails due to an error: The email address is already in use by another account.
8. Tap SignIn Google.
    - Sign in with the same Google account as in Step 4.
    - This results in linking to the User from Step 4.

Screenshots of Firebase and the app at each step are included in the Additional context and comments section.

### Firebase Core version

2.27.1

### Flutter Version

3.19.3

### Relevant Log Output

```shell
Launching lib/main.dart on SO 53B in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:62019/iju7WeyKFyQ=/ws
D/CompatibilityChangeReporter(26067): Compat change id reported: 183155436; UID 10456; state: ENABLED
I/FirebaseApp(26067): Device unlocked: initializing all Firebase APIs for app [DEFAULT]
W/System  (26067): Ignoring header X-Firebase-Locale because its value was null.
W/Parcel  (26067): Expecting binder but got null!
D/TrafficStats(26067): tagSocket(135) with statsTag=0xffffffff, statsUid=-1
W/System  (26067): Ignoring header X-Firebase-Locale because its value was null.
D/FirebaseAuth(26067): Notifying id token listeners about user ( nZU8tl5zAsPj4hvWIB4hyl8f2Au2 ).
D/FirebaseAuth(26067): Notifying auth state listeners about user ( nZU8tl5zAsPj4hvWIB4hyl8f2Au2 ).
W/Parcel  (26067): Expecting binder but got null!
D/CompatibilityChangeReporter(26067): Compat change id reported: 78294732; UID 10456; state: ENABLED
W/System  (26067): Ignoring header X-Firebase-Locale because its value was null.
W/System  (26067): Ignoring header X-Firebase-Locale because its value was null.
D/FirebaseAuth(26067): Notifying id token listeners about user ( nZU8tl5zAsPj4hvWIB4hyl8f2Au2 ).
W/System  (26067): Ignoring header X-Firebase-Locale because its value was null.
W/System  (26067): Ignoring header X-Firebase-Locale because its value was null.
W/System  (26067): Ignoring header X-Firebase-Locale because its value was null.
Lost connection to device.

Exited.

Launching lib/main.dart on SO 53B in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:62383/f62Oq6hvP0g=/ws
D/CompatibilityChangeReporter(30691): Compat change id reported: 183155436; UID 10457; state: ENABLED
I/FirebaseApp(30691): Device unlocked: initializing all Firebase APIs for app [DEFAULT]
W/System  (30691): Ignoring header X-Firebase-Locale because its value was null.
D/TrafficStats(30691): tagSocket(130) with statsTag=0xffffffff, statsUid=-1
W/Parcel  (30691): Expecting binder but got null!
W/System  (30691): Ignoring header X-Firebase-Locale because its value was null.
D/FirebaseAuth(30691): Notifying id token listeners about user ( PHpNyb298BhFyCBKrVAfMRfKT4p2 ).
D/FirebaseAuth(30691): Notifying auth state listeners about user ( PHpNyb298BhFyCBKrVAfMRfKT4p2 ).
Error executing devicectl: ProcessException: Process exited abnormally with exit code 2:
ERROR: Command timeout of 5.0 seconds exceeded. Assuming command got stuck and aborting.
  Command: /usr/bin/arch -arm64e xcrun devicectl list devices --timeout 5 --json-output /var/folders/sf/14g10s_s7z510qn9gl5hqc600000gq/T/flutter_tools.ibJNVq/core_devices.tMKD3C/core_device_list.json
Error executing devicectl: ProcessException: Process exited abnormally with exit code 2:
ERROR: Command timeout of 5.0 seconds exceeded. Assuming command got stuck and aborting.
  Command: /usr/bin/arch -arm64e xcrun devicectl list devices --timeout 5 --json-output /var/folders/sf/14g10s_s7z510qn9gl5hqc600000gq/T/flutter_tools.ibJNVq/core_devices.J554YO/core_device_list.json
Error executing devicectl: ProcessException: Process exited abnormally with exit code 2:
ERROR: Command timeout of 5.0 seconds exceeded. Assuming command got stuck and aborting.
  Command: /usr/bin/arch -arm64e xcrun devicectl list devices --timeout 5 --json-output /var/folders/sf/14g10s_s7z510qn9gl5hqc600000gq/T/flutter_tools.ibJNVq/core_devices.INtLnc/core_device_list.json

W/Parcel  (30691): Expecting binder but got null!
D/CompatibilityChangeReporter(30691): Compat change id reported: 78294732; UID 10457; state: ENABLED
W/System  (30691): Ignoring header X-Firebase-Locale because its value was null.
I/flutter (30691): [firebase_auth/email-already-in-use] The email address is already in use by another account.
I/flutter (30691): #0      FirebaseAuthUserHostApi.linkWithCredential (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:1629:7)
I/flutter (30691): <asynchronous suspension>
I/flutter (30691): #1      MethodChannelUser.linkWithCredential (package:firebase_auth_platform_interface/src/method_channel/method_channel_user.dart:73:22)
I/flutter (30691): <asynchronous suspension>
I/flutter (30691): #2      User.linkWithCredential (package:firebase_auth/src/user.dart:190:9)
I/flutter (30691): <asynchronous suspension>
I/flutter (30691): #3      _MyHomePageState._linkWithCredential (package:flutter_application_5/main.dart:134:29)
I/flutter (30691): <asynchronous suspension>
I/flutter (30691): #4      _MyHomePageState._linkOrSignInGoogle (package:flutter_application_5/main.dart:105:7)
I/flutter (30691): <asynchronous suspension>
W/app.test.auth(30691): Cleared Reference was only reachable from finalizer (only reported once)
W/Parcel  (30691): Expecting binder but got null!
W/System  (30691): Ignoring header X-Firebase-Locale because its value was null.
W/System  (30691): Ignoring header X-Firebase-Locale because its value was null.
D/FirebaseAuth(30691): Notifying id token listeners about user ( nZU8tl5zAsPj4hvWIB4hyl8f2Au2 ).
D/FirebaseAuth(30691): Notifying auth state listeners about user ( nZU8tl5zAsPj4hvWIB4hyl8f2Au2 ).
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
Dart SDK 3.3.1
Flutter SDK 3.19.3
flutter_application_5 1.0.0+1

dependencies:
- cupertino_icons 1.0.6
- firebase_auth 4.17.9 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.27.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]

dev dependencies:
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.26 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 7.1.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.10.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.12.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- google_identity_services_web 0.3.1+1 [meta web]
- google_sign_in_android 6.1.22 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.4 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- http 1.2.1 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.5.1

```

</details>

### Additional context and comments

In this issue, we are using `firebase_auth: 4.17.9`, but we have confirmed that it also occurs with `4.18.0`.

---

flutter doctor
---

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.19.3, on macOS 13.6.6 22G630 darwin-arm64, locale ja-JP)
    • Flutter version 3.19.3 on channel stable at /Users/name/development/flutter_3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (3 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/name/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode_15_0.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)            
    • SO 53B (mobile) • QV782DXWA6 • android-arm64  • Android 13 (API 33)
    • macOS (desktop) • macos      • darwin-arm64   • macOS 13.6.6 22G630 darwin-arm64
    • Chrome (web)    • chrome     • web-javascript • Google Chrome 123.0.6312.59

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

---

Screenshot
---

The masked part of the image will contain the Gmail address used with the Google account.

|At Step 3|At Step 4|At Step 5|At Step 6,7|At Step 8|
|:-:|:-:|:-:|:-:|:-:|
|<image src="https://github.com/firebase/flutterfire/assets/69038535/b136d355-4b4a-4aa1-ad30-56499f759ee7" width=320>|<image src="https://github.com/firebase/flutterfire/assets/69038535/46018fdb-2974-461f-a6e8-2406567707ea" width=320>|<image src="https://github.com/firebase/flutterfire/assets/69038535/7b5af791-e48a-4f67-b540-c54500567159" width=320>|<image src="https://github.com/firebase/flutterfire/assets/69038535/23a4ec6c-9681-44d1-b38f-ce2215a36099" width=320>|<image src="https://github.com/firebase/flutterfire/assets/69038535/6ab50a03-95f6-4417-a954-bb2a2517cbd9" width=320>|
|<image src="https://github.com/firebase/flutterfire/assets/69038535/bb6a70af-4ac7-4ddb-86c0-74dce530f437" height= 320>|<image src="https://github.com/firebase/flutterfire/assets/69038535/543bc69e-35de-433e-be1d-b9be44723f01" height=320>|<image src="https://github.com/firebase/flutterfire/assets/69038535/7bce23a8-b19c-493d-985c-8e58e563e00e" height=320>|<image src="https://github.com/firebase/flutterfire/assets/69038535/be64f3fd-7d4c-400e-9529-caece068bc47" height=320>|<image src="https://github.com/firebase/flutterfire/assets/69038535/73978780-587d-4568-94cf-1d514c84c9fe" height=320>|
