### ISSUE TITLE
[firebase messaging]: Crash on getToken function call

### ISSUE THREAD

**Issue by TarunPal3551** [firebase/flutterfire#12540]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

Android

### Description

<img width="1141" alt="image" src="https://github.com/firebase/flutterfire/assets/33154835/ef6acbef-7a04-4c33-9385-b73fec7eb856">

App Crashed on calling of getToken function,

### Reproducing the issue

You can reproduce it by calling getToken function in main.dart

### Firebase Core version

^2.14.0

### Flutter Version

3.19.4

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.3.2
Flutter SDK 3.19.4
apnabillbook 4.0.10+66

dependencies:
- audioplayers 4.1.0 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- blue_thermal_printer 1.2.3 [flutter]
- bouncing_widget 2.0.0 [flutter]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- carousel_slider 4.2.1 [flutter]
- contained_tab_bar_view 0.8.0 [flutter container_tab_indicator]
- crypto 3.0.3 [typed_data]
- cupertino_icons 1.0.6
- device_info_plus 8.2.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32]
- dio 4.0.6 [http_parser path]
- dio_logging_interceptor 1.0.1 [dio]
- dotted_border 2.1.0 [flutter path_drawing]
- dropdown_plus 0.0.9 [flutter]
- easy_autocomplete 1.6.0 [flutter]
- esc_pos_utils 1.1.0 [flutter hex gbk_codec image]
- excel 3.0.0 [archive xml collection equatable]
- expand_widget 3.1.1 [flutter]
- facebook_app_events 0.19.1 [flutter]
- file_picker 5.2.10 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_analytics 10.9.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.27.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.20 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.4.19 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 14.7.21 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.9.3+19 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- fl_chart 0.55.2 [flutter equatable]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_animarker 3.2.0 [flutter google_maps_flutter_platform_interface vector_math]
- flutter_barcode_scanner 2.0.0 [flutter flutter_plugin_android_lifecycle]
- flutter_inappwebview 5.8.0 [flutter]
- flutter_keyboard_visibility 5.4.1 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_local_notifications 15.1.3 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_native_contact_picker 0.0.6 [flutter]
- flutter_screenutil 5.9.0 [flutter]
- flutter_share_me 1.4.0 [flutter lint]
- flutter_staggered_grid_view 0.4.1 [flutter]
- flutter_svg 2.0.9 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_tutorial 1.1.1 [flutter]
- fluttertoast 8.2.4 [flutter flutter_web_plugins]
- font_awesome_flutter 9.2.0 [flutter]
- geocoder2 1.4.0 [flutter http]
- geocoding 2.2.2 [flutter geocoding_platform_interface geocoding_android geocoding_ios]
- geolocator 10.1.1 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get 4.6.6 [flutter]
- get_it 7.6.7 [async collection]
- google_fonts 4.0.4 [flutter http path_provider crypto]
- google_maps_flutter 2.6.0 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- http 0.13.6 [async http_parser meta]
- image_cropper 3.0.3 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_gallery_saver 1.7.1 [flutter]
- image_picker 0.8.9 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_update 4.2.2 [flutter]
- infinite_scroll_pagination 3.2.0 [flutter sliver_tools]
- intl 0.18.1 [clock meta path]
- local_auth 2.2.0 [flutter local_auth_android local_auth_darwin local_auth_platform_interface local_auth_windows]
- location 5.0.3 [flutter location_platform_interface location_web]
- lottie 2.7.0 [archive flutter path vector_math]
- marquee 2.2.3 [fading_edge_scrollview flutter]
- otp_autofill 3.0.0 [flutter]
- otp_text_field 1.1.3 [flutter]
- otpless_flutter 2.0.0 [flutter uni_links plugin_platform_interface]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 10.4.5 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- phonepe_payment_sdk 2.0.1 [flutter plugin_platform_interface]
- pretty_dio_logger 1.2.0-beta-1 [dio]
- qr_flutter 4.0.0 [flutter qr]
- scan 1.6.0 [flutter]
- share 2.0.4 [meta mime flutter]
- share_plus 6.3.4 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 2.0.0 [flutter]
- showcaseview 2.0.3 [flutter]
- smart_usb 0.4.2 [flutter plugin_platform_interface ffi libusb_new]
- syncfusion_flutter_charts 21.1.37 [flutter intl vector_math syncfusion_flutter_core]
- syncfusion_flutter_core 21.1.41 [vector_math flutter]
- url_launcher 6.2.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 4.7.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_wkwebview 3.13.0 [flutter path webview_flutter_platform_interface]
- whatsapp_share 2.0.2 [flutter]
- widgets_to_image 0.0.2 [flutter]
- youtube_player_flutter 8.1.2 [flutter flutter_inappwebview]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

dependency overrides:
- esc_pos_utils 1.1.0 [flutter hex gbk_codec image]
- esc_pos_utils_plus 2.0.3 [flutter image html]
- image 3.3.0 [archive meta xml]

transitive dependencies:
- _flutterfire_internals 1.3.27 [collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- audioplayers_android 3.0.2 [audioplayers_platform_interface flutter]
- audioplayers_darwin 4.1.0 [audioplayers_platform_interface flutter]
- audioplayers_linux 2.1.0 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 5.0.1 [flutter meta plugin_platform_interface]
- audioplayers_web 3.1.0 [audioplayers_platform_interface flutter flutter_web_plugins js]
- audioplayers_windows 2.0.2 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.1 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- container_tab_indicator 0.3.0 [flutter]
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+1 [meta web]
- csslib 1.0.0 [source_span]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- equatable 2.0.5 [collection meta]
- fading_edge_scrollview 3.0.0 [flutter]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 6.1.4 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.10.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.6 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.13.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_crashlytics_platform_interface 3.6.27 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+27 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.29 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.7.1 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta web]
- firebase_performance_platform_interface 0.1.4+27 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.5 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js web]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- gbk_codec 0.4.0 [html]
- geocoding_android 3.3.0 [flutter geocoding_platform_interface]
- geocoding_ios 2.3.0 [flutter geocoding_platform_interface]
- geocoding_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- geolocator_android 4.3.1 [flutter geolocator_platform_interface uuid]
- geolocator_apple 2.3.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.2 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.2.1 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.2.3 [flutter geolocator_platform_interface]
- google_maps 7.1.0 [js js_wrapping meta web]
- google_maps_flutter_android 2.7.0 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.5.0 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.6.0 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.6+2 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform web]
- hex 0.2.0
- html 0.15.4 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_cropper_for_web 1.0.3 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 3.0.3 [flutter plugin_platform_interface http]
- image_picker_android 0.8.9+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.4 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- libusb_new 1.0.0 [ffi]
- lint 1.10.0
- lints 2.1.1
- local_auth_android 1.0.37 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_darwin 1.2.2 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.10 [flutter plugin_platform_interface]
- local_auth_windows 1.0.10 [flutter local_auth_platform_interface]
- location_platform_interface 3.1.2 [flutter plugin_platform_interface]
- location_web 4.2.0 [flutter flutter_web_plugins http_parser js location_platform_interface]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- octo_image 2.0.0 [flutter]
- path 1.9.0
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.3.6 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.12.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.3 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.4 [collection convert js]
- qr 2.1.0 [meta]
- rxdart 0.27.7
- sanitize_html 2.1.0 [html meta]
- share_plus_platform_interface 3.4.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.3.0 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- sliver_tools 0.2.12 [flutter]
- source_span 1.10.0 [collection path term_glyph]
- sqflite 2.3.2 [flutter sqflite_common path]
- sqflite_common 2.5.4 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.2 [path]
- typed_data 1.3.2 [collection]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_graphics 1.1.10+1 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.10+1
- vector_graphics_compiler 1.1.10+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.5.1
- webview_flutter_android 3.16.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- win32 3.1.4 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]


```

</details>
