### ISSUE TITLE
[firebase_analytics: ^10.9.0]: <Not able to build in iOS side>

### ISSUE THREAD

**Issue by sahilpasha912** [firebase/flutterfire#12557]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

iOS

### Description

![Screenshot 2024-04-01 at 4 11 14 PM](https://github.com/firebase/flutterfire/assets/39743126/5a3999c8-6d94-46f5-8f65-350bf03b9ff6)
![Screenshot 2024-04-01 at 4 11 21 PM](https://github.com/firebase/flutterfire/assets/39743126/dcfd2288-58da-4c7e-a5e1-e197342fa512)
![Screenshot 2024-04-01 at 4 11 47 PM](https://github.com/firebase/flutterfire/assets/39743126/98301784-b1aa-4c8f-9c70-0189dd9e2183)
![Screenshot 2024-04-01 at 4 11 58 PM](https://github.com/firebase/flutterfire/assets/39743126/efa5e95c-5b9b-45ed-b50a-b0ea4ac41958)
<img width="1127" alt="Screenshot 2024-04-01 at 4 12 12 PM" src="https://github.com/firebase/flutterfire/assets/39743126/a7fa350a-6b98-406b-a0fd-55e7bb490500">

i have installed the analytics frame work in flutter, android side working fine, but iOS side facing above issues.

can some one help me out from this issue.

thanks.

### Reproducing the issue

i have added firebase_analytics to project, for android it is working fine, in iOS facing issue.

### Firebase Core version

2.27.2

### Flutter Version

3.19.4

### Relevant Log Output

```shell
Launching lib/main_development.dart on iPhone 15 Pro in debug mode...
Xcode build done.                                           26.7s
Failed to build iOS app
Error (Xcode): Undefined symbol: _pb_decode

Error (Xcode): Undefined symbol: _pb_decode_varint

Error (Xcode): Undefined symbol: _pb_encode

Error (Xcode): Undefined symbol: _pb_encode_string

Error (Xcode): Undefined symbol: _pb_encode_submessage

Error (Xcode): Undefined symbol: _pb_encode_tag_for_field

Error (Xcode): Undefined symbol: _pb_encode_varint

Error (Xcode): Undefined symbol: _pb_istream_from_buffer

Error (Xcode): Undefined symbol: _pb_ostream_from_buffer

Error (Xcode): Undefined symbol: _pb_read

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

 firebase_analytics: ^10.9.0

app_repository:
    path: packages/app_repository
  app_ui:
    path: packages/app_ui
  appinio_video_player: ^1.2.2
  audio_video_progress_bar: ^2.0.1
  bloc: ^8.0.3

  cached_network_image: ^3.2.3
  card_swiper: ^3.0.1
  carousel_slider: ^4.2.1
  change_app_package_name: ^1.1.0
  chewie: ^1.7.1
  croppy: ^1.1.4
  dartz: ^0.10.1
  # dio: ^5.3.2
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  dropdown_button2: ^2.3.9
  easy_mask: ^2.0.1
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17

  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.4
  flutter_date_pickers: ^0.4.2
  flutter_expanded_tile: ^0.3.7
  flutter_inappwebview: ^5.8.0
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^9.0.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.9
  flutter_widget_from_html: ^0.14.7
  get_it: ^7.6.0
  go_router: ^8.0.2
  gradient_circular_progress_indicator: ^0.0.4
  html: ^0.15.4
  http: ^1.2.1
  image: ^4.1.3
  image_cropper: ^5.0.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  intl: ^0.18.0
  just_audio: ^0.9.36
  just_audio_background: any
  lottie: ^2.5.0
  marquee: ^2.2.3
  open_store: ^0.5.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  persistent_bottom_nav_bar: ^5.0.2
  quill_html_converter: ^9.0.3
  rxdart: ^0.27.7
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  super_tooltip: ^2.0.7
  timezone: ^0.9.2
  url_launcher: ^6.2.1
  video_player: ^2.8.1
  gradient_borders: ^1.0.0

  linked_scroll_controller: ^0.2.0
  fl_chart: 0.63.0
  safe_device: ^1.1.4
  accordion: ^2.6.0
  flutter_cached_pdfview: ^0.4.2 #added by sahil
  # accordion: ^2.6.0
  dio: ^5.4.0
  flutter_app_badger: ^1.5.0
 

  #Firebase: -
  firebase_core: ^2.27.2
  firebase_crashlytics: ^3.4.18
  firebase_messaging: ^14.7.20
  firebase_analytics: ^10.9.0

```

</details>

### Additional context and comments

already i have attached images , nothing i want to say.
