### ISSUE TITLE
[firebase_storage, firebase_auth]: storage and auth stopped working after version 11.2.7. - Permission denied when uploading file

### ISSUE THREAD

**Issue by mr-jstraub** [firebase/flutterfire#12570]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Auth, Storage

### Which platforms are affected?

Android, iOS

### Description

firebase_storage in combination with firebase_auth stopped working on Android and IOS after upgrading to latest versions of plugins. When uploading a picture from flutter app to firebase storage, we are receiving a permission denied error (see below). 
The FB storage security rule has not been changed between versions.
Tested with profile and release build, iOS (simulator) and Android (emulator+real device). 
AppCheck is not enforced btw.

Flutter: 3.19.x

## pubspec.yaml (partial) - upload works
```
firebase_auth: 4.10.0
firebase_core: 2.16.0
firebase_storage: 11.2.7
```

## pubspec.yaml (partial) - upload doesn't work
```
firebase_core: 2.27.2
firebase_auth: 4.18.0
firebase_storage: 11.6.11
```

### Reproducing the issue

1. Create new Flutter project using the following plugin versions (versions of other modules shouldn't matter)
```
firebase_core: 2.27.2
firebase_auth: 4.18.0
firebase_storage: 11.6.11
```
Complete pubspec.yaml
```
name: flutter_storage_issue
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # doesn't work
  #firebase_core: 2.27.2
  #firebase_auth: 4.18.0
  #firebase_storage: 11.6.11

  # works
  firebase_auth: 4.10.0
  firebase_core: 2.16.0
  firebase_storage: 11.2.7
  
  # supporting packages for test
  path_provider: ^2.1.2
  camera: ^0.10.5+9
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
```

2. Setup Firebase for Flutter app => https://firebase.google.com/docs/flutter/setup?platform=ios
3. Add method to sign in a user via password and mail => https://firebase.google.com/docs/auth/flutter/password-auth#sign_in_a_user_with_an_email_address_and_password
4. Implement a method to take a picture that we can upload => https://docs.flutter.dev/cookbook/plugins/picture-using-camera
5. Implement method to upload file =>https://firebase.google.com/docs/storage/flutter/upload-files
```
uploadFile(String path) async {
    try {
      final storageRef = FirebaseStorage.instance.ref();
      final imgRef = storageRef.child("users/$uid/profile.png");
      final File file = File(path);
      debugPrint('Uploading file: $path');
      await imgRef.putFile(file);
    }catch(e){
      debugPrint(e.toString());
    }
  }
```
6. Setup storage security rule in firebase

```
rules_version='2';
service firebase.storage {
  match /b/{bucket}/o {
    match /users/{userId}/{allPaths=**}{
      allow create, update: if request.auth != null
                               && request.auth.uid == userId
                               && request.resource.contentType.matches('image/.+');
      allow get: if request.auth != null
                    && request.auth.uid == userId
                    && (resource.contentType.matches('image/.+') || resource == null);
      allow delete: if request.auth != null
       && request.auth.uid == userId;
    }
  }
}
```
7. Run the app, login (mail + password) and upload a picture via firebase_storage plugin

### Firebase Core version

2.2.7.2

### Flutter Version

3.19.4

### Relevant Log Output

```shell
D/FirebaseAuth(25226): Notifying id token listeners about user ( .... ).
D/EGL_emulation(25226): app_time_stats: avg=822.38ms min=0.80ms max=30378.05ms count=37
I/Camera  (25226): runPictureAutoFocus
I/Camera  (25226): lockAutoFocus
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 4 | aeState: 2
I/Camera  (25226): captureStillPicture
D/Camera  (25226): Updating builder with feature: ExposureLockFeature
D/Camera  (25226): Updating builder with feature: ExposurePointFeature
D/Camera  (25226): Updating builder with feature: ZoomLevelFeature
D/Camera  (25226): Updating builder with feature: AutoFocusFeature
D/Camera  (25226): Updating builder with feature: NoiseReductionFeature
I/Camera  (25226): updateNoiseReduction | currentSetting: fast
D/Camera  (25226): Updating builder with feature: FocusPointFeature
D/Camera  (25226): Updating builder with feature: ResolutionFeature
D/Camera  (25226): Updating builder with feature: SensorOrientationFeature
D/Camera  (25226): Updating builder with feature: FlashFeature
D/Camera  (25226): Updating builder with feature: ExposureOffsetFeature
D/Camera  (25226): Updating builder with feature: FpsRangeFeature
I/Camera  (25226): sending capture request
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
D/CameraCaptureCallback(25226): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
I/Camera  (25226): unlockAutoFocus
I/Camera  (25226): refreshPreviewCaptureSession
I/Camera  (25226): onImageAvailable
I/flutter (25226): Uploading file: /data/user/0/com.example.flutter_storage_issue/cache/CAP7908972818050777547.jpg
W/StorageUtil(25226): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: No AppCheckProvider installed.
D/TrafficStats(25226): tagSocket(169) with statsTag=0xffffffff, statsUid=-1
D/UploadTask(25226): Waiting 0 milliseconds
W/StorageUtil(25226): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: No AppCheckProvider installed.
D/UploadTask(25226): Resetting chunk size to 262144
E/StorageException(25226): StorageException has occurred.
E/StorageException(25226): User does not have permission to access this object.
E/StorageException(25226):  Code: -13021 HttpResult: 403
E/StorageException(25226): The server has terminated the upload session
E/StorageException(25226): java.io.IOException: The server has terminated the upload session
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.serverStateValid(UploadTask.java:359)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.shouldContinue(UploadTask.java:325)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.run(UploadTask.java:249)
E/StorageException(25226): 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7$com-google-firebase-storage-StorageTask(StorageTask.java:1077)
E/StorageException(25226): 	at com.google.firebase.storage.StorageTask$$ExternalSyntheticLambda7.run(Unknown Source:2)
E/StorageException(25226): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor.lambda$decorate$0$com-google-firebase-concurrent-LimitedConcurrencyExecutor(LimitedConcurrencyExecutor.java:65)
E/StorageException(25226): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(25226): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/StorageException(25226): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/StorageException(25226): 	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
E/StorageException(25226): 	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(25226): 	at java.lang.Thread.run(Thread.java:1012)
E/StorageException(25226): Caused by: java.io.IOException: {  "error": {    "code": 403,    "message": "Permission denied."  }}
E/StorageException(25226): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:415)
E/StorageException(25226): 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:432)
E/StorageException(25226): 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:423)
E/StorageException(25226): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:265)
E/StorageException(25226): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:282)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.send(UploadTask.java:519)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.delaySend(UploadTask.java:452)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.uploadChunk(UploadTask.java:478)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.run(UploadTask.java:248)
E/StorageException(25226): 	... 9 more
E/StorageException(25226): StorageException has occurred.
E/StorageException(25226): User does not have permission to access this object.
E/StorageException(25226):  Code: -13021 HttpResult: 403
E/StorageException(25226): The server has terminated the upload session
E/StorageException(25226): java.io.IOException: The server has terminated the upload session
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.serverStateValid(UploadTask.java:359)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.shouldContinue(UploadTask.java:325)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.run(UploadTask.java:249)
E/StorageException(25226): 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7$com-google-firebase-storage-StorageTask(StorageTask.java:1077)
E/StorageException(25226): 	at com.google.firebase.storage.StorageTask$$ExternalSyntheticLambda7.run(Unknown Source:2)
E/StorageException(25226): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor.lambda$decorate$0$com-google-firebase-concurrent-LimitedConcurrencyExecutor(LimitedConcurrencyExecutor.java:65)
E/StorageException(25226): 	at com.google.firebase.concurrent.LimitedConcurrencyExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(25226): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/StorageException(25226): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/StorageException(25226): 	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
E/StorageException(25226): 	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/StorageException(25226): 	at java.lang.Thread.run(Thread.java:1012)
E/StorageException(25226): Caused by: java.io.IOException: {  "error": {    "code": 403,    "message": "Permission denied."  }}
E/StorageException(25226): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:415)
E/StorageException(25226): 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:432)
E/StorageException(25226): 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:423)
E/StorageException(25226): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:265)
E/StorageException(25226): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:282)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.send(UploadTask.java:519)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.delaySend(UploadTask.java:452)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.uploadChunk(UploadTask.java:478)
E/StorageException(25226): 	at com.google.firebase.storage.UploadTask.run(UploadTask.java:248)
E/StorageException(25226): 	... 9 more
I/flutter (25226): [firebase_storage/unauthorized] User is not authorized to perform the desired action.
E/StorageException(25226): StorageException has occurred.
E/StorageException(25226): The operation was cancelled.
E/StorageException(25226):  Code: -13040 HttpResult: 0
W/StorageUtil(25226): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: No AppCheckProvider installed.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.3.2
Flutter SDK 3.19.4
flutter_storage_issue 1.0.0+1

dependencies:
- camera 0.10.5+9 [camera_android camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle]
- cupertino_icons 1.0.6
- firebase_auth 4.18.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.27.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 11.6.11 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- path 1.9.0
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]

dev dependencies:
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.27 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- camera_android 0.10.8+18 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]
- camera_avfoundation 0.9.14+1 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.7.4 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.2+4 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- cross_file 0.3.4+1 [meta web]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- firebase_auth_platform_interface 7.2.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.10.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.14.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_storage_platform_interface 5.1.14 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.8.1 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta web]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- http 1.2.1 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.5.1
- win32 5.3.0 [ffi]
- xdg_directories 1.0.4 [meta path]


```

</details>

### Additional context and comments

Flutter Doctor:
Doctor summary (to see all details, run flutter doctor -v):
```
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.3.1 23D60 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
[✓] Connected device (3 available)            
[✓] Network resources

• No issues found!
```
