### ISSUE TITLE
[firebase_messaging]: Have an error when listen messaging when open web 

### ISSUE THREAD

**Issue by saunptit97** [firebase/flutterfire#12572]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

Web

### Description

When I push a notification have an error with message:
Instance of 'LinkedMap<Object?, Object?>': type 'LinkedMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>?'
I run example https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging same error. Please check it for me 

![image](https://github.com/firebase/flutterfire/assets/32449963/7f6d2a75-350b-4c99-a5ea-4d45dc5db6e4)

### Reproducing the issue

+ I run example firebase_messaging 
+ Change setup firebase with my project 
+ Push notification when open web and show error above
Please check it for me. Thanks 

### Firebase Core version

2.20.0

### Flutter Version

3.19.3

### Relevant Log Output

```shell
errors.dart:297 Uncaught (in promise) Error: TypeError: Instance of 'LinkedMap<Object?, Object?>': type 'LinkedMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>?'
    at Object.throw_ [as throw] (errors.dart:297:3)
    at Object._failedAsCheck (rti.dart:1385:3)
    at dart_rti.Rti.new._generalNullableAsCheckImplementation (rti.dart:1375:3)
    at get data (messaging.dart:124:31)
    at Object.messagePayloadToMap (utils.dart:50:21)
    at firebase_messaging_web.dart:35:41
    at _RootZone.runUnaryGuarded (zone.dart:1594:9)
    at [_sendData] (stream_impl.dart:339:5)
    at [_add] (stream_impl.dart:271:7)
    at [_sendData] (broadcast_stream_controller.dart:377:24)
    at _SyncBroadcastStreamController.new.add (broadcast_stream_controller.dart:244:5)
    at messaging.dart:83:20
    at Object._checkAndCall (operations.dart:550:37)
    at Object.dcall (operations.dart:555:39)
    at Object.ret [as next] (js_allow_interop_patch.dart:17:11)
    at messageEventListener (window-listener.ts:51:39)
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by TarekkMA** [comment]
Thank you @saunptit97, I can replicate it.

**Comment by juppdes** [comment]
Hello, how to update this? Is it already available?

**Comment by saunptit97** [comment]
@TarekkMA  Please tell me when It available

**Comment by TarekkMA** [comment]
It will be available in the next release.

**Comment by JoydS** [comment]
Hello,
When is the next release available ? Because it still doesn't work on 2.28.0

**Comment by TarekkMA** [comment]
It would be avialbe next week, but until then you can use git references in your pubspec.yaml

https://dart.dev/tools/pub/dependencies#git-packages

**Comment by JoydS** [comment]
When 
```
  firebase_core: ^2.22.0
  firebase_analytics: ^10.8.9
  firebase_crashlytics: ^3.4.18
  firebase_messaging: ^14.7.19
  firebase_performance: ^0.9.3+8
  firebase_app_check: ^0.2.1+17
  firebase_messaging_web:
    git:
      url: https://github.com/firebase/flutterfire.git
      ref: master
      path: packages/firebase_messaging/firebase_messaging_web
      

Because firebase_messaging >=14.7.19 <14.7.20 depends on firebase_messaging_web ^3.6.8 and firebase_messaging >=14.7.20 <14.7.21 depends on firebase_messaging_web ^3.7.0, firebase_messaging >=14.7.19 <14.7.21 requires firebase_messaging_web ^3.6.8.
And because firebase_messaging >=14.7.21 <14.8.0 depends on firebase_messaging_web ^3.7.1 and firebase_messaging >=14.8.0 depends on firebase_messaging_web ^3.8.0, firebase_messaging >=14.7.19 requires firebase_messaging_web from hosted.
So, because yumi depends on both firebase_messaging ^14.7.19 and firebase_messaging_web from git, version solving failed.
```

And 
```
  firebase_core:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: master
  firebase_analytics:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_analytics/firebase_analytics
      ref: master
  firebase_crashlytics:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_crashlytics/firebase_crashlytics
      ref: master
  firebase_messaging:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_messaging/firebase_messaging
      ref: master
  firebase_performance:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_performance/firebase_performance
      ref: master
  firebase_app_check:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_app_check/firebase_app_check
      ref: master
  firebase_messaging_web:
    git:
      url: https://github.com/firebase/flutterfire.git
      ref: master
      path: packages/firebase_messaging/firebase_messaging_web


Because every version of firebase_messaging_web from git depends on firebase_core from hosted and yumi depends on firebase_core from git, firebase_messaging_web from git is forbidden.
So, because yumi depends on firebase_messaging_web from git, version solving failed.
```
