### ISSUE TITLE
[firebase_remote_config_web]: TypeError during web initialization with getAll()

### ISSUE THREAD

**Issue by smp27768** [firebase/flutterfire#12598]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Remote Config

### Which platforms are affected?

Web

### Description

A TypeError occurs when initializing Firebase Remote Config settings on web builds, preventing initialization. Initialization code still works fine on non-web app builds.

```
Error: TypeError: Instance of 'LinkedMap<Object?,
Object?>': type 'LinkedMap<Object?, Object?>' is not a
subtype of type 'List<String>'

...

packages/firebase_remote_config_web/src/interop/firebas
e_remote_config.dart 110:59  getAll
packages/firebase_remote_config_web/firebase_remote_con
fig_web.dart 127:22          getAll
packages/firebase_remote_config/src/firebase_remote_con
fig.dart 95:22               getAll

...

```

### Reproducing the issue

```
final FirebaseRemoteConfig remoteConfig = FirebaseRemoteConfig.instance;
await remoteConfig.setConfigSettings(
  RemoteConfigSettings(
    fetchTimeout: const Duration(seconds: 10),
    // fetch on startup for most-recent configurations
    minimumFetchInterval: const Duration(seconds: 1),
  ),
);
await remoteConfig.fetchAndActivate();
final Map<String, RemoteConfigValue> remoteSettings = remoteConfig.getAll(); // issue is here, based on log output
```

### Firebase Core version

2.28.0

### Flutter Version

3.19.5

### Relevant Log Output

```shell
Error: TypeError: Instance of 'LinkedMap<Object?,
Object?>': type 'LinkedMap<Object?, Object?>' is not a
subtype of type 'List<String>'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runti
me/errors.dart 297:3         throw_
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1385:3
_failedAsCheck
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1363:3
_generalAsCheckImplementation
packages/firebase_remote_config_web/src/interop/firebas
e_remote_config.dart 110:59  getAll
packages/firebase_remote_config_web/firebase_remote_con
fig_web.dart 127:22          getAll
packages/firebase_remote_config/src/firebase_remote_con
fig.dart 95:22               getAll
packages/[MY_APP_NAME]/config/segments/remote_config.dart
95:34                        initialize
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch
.dart 45:50                  <fn>
dart-sdk/lib/async/zone.dart 1661:54
runUnary
dart-sdk/lib/async/future_impl.dart 162:18
handleValue
dart-sdk/lib/async/future_impl.dart 838:44
handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13
_propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5
[_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7
callback
dart-sdk/lib/async/schedule_microtask.dart 40:11
_microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5
_startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch
.dart 181:7                  <fn>
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

dependencies:
- app_links 4.0.1 [flutter plugin_platform_interface web flutter_web_plugins gtk]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- camera 0.10.5+9 [camera_android camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle]
- carousel_slider 4.2.1 [flutter]
- cloud_firestore 4.16.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 4.7.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cool_alert 2.0.1 [flare_flutter flutter lottie vector_math]
- crypto 3.0.3 [typed_data]
- cupertino_icons 1.0.6
- device_info_plus 10.0.1 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- encrypt 5.0.3 [args asn1lib clock collection crypto pointycastle]
- equatable 2.0.5 [collection meta]
- faker 2.1.0 [crypto]
- firebase_app_check 0.2.2 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.19.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_web 5.11.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core 2.28.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_web 2.14.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_messaging 14.8.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_messaging_web 3.8.0 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_remote_config 4.4.0 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_storage 11.7.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- firebase_storage_web 3.9.0 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http meta web]
- fl_chart 0.67.0 [equatable flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.5 [bloc flutter provider]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_dotenv 5.1.0 [flutter]
- flutter_google_places_sdk 0.3.7 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_ios flutter_google_places_sdk_web flutter_google_places_sdk_android flutter_google_places_sdk_windows flutter_google_places_sdk_linux flutter_google_places_sdk_macos]
- flutter_image_compress 2.2.0 [flutter flutter_image_compress_platform_interface flutter_image_compress_common flutter_image_compress_web flutter_image_compress_macos flutter_image_compress_ohos]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_multi_formatter 2.12.4 [flutter collection base58check bech32]
- flutter_native_splash 2.4.0 [args flutter flutter_web_plugins html image meta path universal_io xml yaml ansicolor]
- flutter_slidable 3.1.0 [flutter]
- flutter_staggered_animations 1.1.1 [flutter]
- flutter_staggered_grid_view 0.7.0 [flutter]
- flutter_star_prnt 2.4.1 [collection flutter]
- flutter_stripe 10.1.1 [flutter meta stripe_android stripe_ios stripe_platform_interface]
- flutter_stripe_web 5.1.0 [flutter flutter_web_plugins freezed_annotation stripe_platform_interface js stripe_js]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- geocoding 3.0.0 [flutter geocoding_platform_interface geocoding_android geocoding_ios]
- geolocator 11.0.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- go_router 13.2.2 [collection flutter flutter_web_plugins logging meta]
- google_maps_flutter 2.5.3 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- google_maps_flutter_web 0.5.4+3 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- http 1.2.1 [async http_parser meta web]
- image_picker 1.0.7 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_review 2.0.9 [flutter in_app_review_platform_interface]
- internet_connection_checker_plus 2.3.0 [connectivity_plus flutter http]
- intl 0.18.1 [clock meta path]
- lat_lng_to_timezone 0.2.0
- like_button 2.0.5 [flutter]
- map_launcher 3.2.0 [flutter]
- material_design_icons_flutter 7.0.7296 [flutter]
- mek_stripe_terminal 3.4.0 [flutter meta collection recase mek_data_class one_for_all]
- mobile_scanner 4.0.1 [flutter flutter_web_plugins js]
- package_info_plus 6.0.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- pay 2.0.0 [flutter flutter_localizations pay_android pay_ios pay_platform_interface meta]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- pinput 4.0.0 [flutter smart_auth universal_platform]
- pointycastle 3.8.0 [collection convert js]
- qr_flutter 4.1.0 [flutter qr]
- screen_brightness 1.0.0 [flutter screen_brightness_platform_interface screen_brightness_android screen_brightness_ios screen_brightness_macos screen_brightness_windows]
- scroll_to_index 3.0.1 [flutter]
- scrollable_positioned_list 0.3.8 [flutter collection]
- share_plus 8.0.2 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- shimmer 3.0.0 [flutter]
- sign_in_with_apple 6.0.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sliver_tools 0.2.12 [flutter]
- stripe_js 3.4.0 [freezed_annotation js json_annotation meta]
- timezone 0.9.2 [path]
- universal_html 2.2.4 [async csslib charcode collection html meta source_span typed_data universal_io]
- url_launcher 6.2.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- version 3.0.2
- video_player 2.8.5 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- visibility_detector 0.4.0+2 [flutter]
- webview_flutter 4.7.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- dependency_validator 3.2.3 [args build_config checked_yaml glob io json_annotation logging package_config path pub_semver pubspec_parse yaml]
- flutter_lints 3.0.2 [lints]

transitive dependencies:
- _flutterfire_internals 1.3.28 [collection firebase_core firebase_core_platform_interface flutter meta]
- ansicolor 2.0.2
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- asn1lib 1.5.2
- async 2.11.0 [collection meta]
- base58check 2.0.0 [crypto collection]
- bech32 0.2.2 [convert]
- bloc 8.1.4 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.1 [cached_network_image_platform_interface flutter flutter_cache_manager]
- camera_android 0.10.9 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]
- camera_avfoundation 0.9.15 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.7.4 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.3 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.3.0
- charcode 1.3.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- class_to_string 1.0.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.12 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.11.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- cloud_functions_platform_interface 5.5.22 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.9.0 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- collection 1.18.0
- connectivity_plus 6.0.1 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm]
- connectivity_plus_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+1 [meta web]
- csslib 1.0.0 [source_span]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_app_check_platform_interface 0.1.0+22 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.1.2 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_auth_platform_interface 7.2.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.30 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_platform_interface 1.4.28 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.6.0 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- firebase_storage_platform_interface 5.1.15 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- fixnum 1.1.0
- flare_flutter 3.0.2 [collection flutter meta]
- flutter_google_places_sdk_android 0.1.8 [flutter flutter_google_places_sdk_platform_interface]
- flutter_google_places_sdk_http 0.1.4 [flutter http latlong2 flutter_google_places_sdk_platform_interface freezed_annotation json_annotation]
- flutter_google_places_sdk_ios 0.1.4 [flutter flutter_google_places_sdk_platform_interface]
- flutter_google_places_sdk_linux 0.1.4 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_http]
- flutter_google_places_sdk_macos 0.1.4 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_http]
- flutter_google_places_sdk_platform_interface 0.2.7 [flutter freezed_annotation json_annotation plugin_platform_interface]
- flutter_google_places_sdk_web 0.1.6 [flutter flutter_web_plugins flutter_google_places_sdk_platform_interface js google_maps collection]
- flutter_google_places_sdk_windows 0.1.4 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_http]
- flutter_image_compress_common 1.0.5 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_macos 1.0.2 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_ohos 0.0.2 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_platform_interface 1.0.5 [flutter plugin_platform_interface cross_file]
- flutter_image_compress_web 0.1.4+1 [flutter flutter_web_plugins flutter_image_compress_platform_interface js]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- geocoding_android 3.3.0 [flutter geocoding_platform_interface]
- geocoding_ios 3.0.1 [flutter geocoding_platform_interface]
- geocoding_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- geolocator_android 4.5.4 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.2 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 3.0.0 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.2.3 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.3.1+1 [meta web]
- google_maps 6.3.0 [js js_wrapping meta]
- google_maps_flutter_android 2.7.0 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.5.2 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.6.0 [collection flutter plugin_platform_interface stream_transform]
- google_sign_in_android 6.1.22 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.5 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- gtk 2.1.0 [ffi flutter meta]
- html 0.15.4 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.7 [archive meta xml]
- image_picker_android 0.8.9+5 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.3 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.9+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.4 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_review_platform_interface 2.0.5 [flutter url_launcher plugin_platform_interface platform]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- json_annotation 4.8.1 [meta]
- latlong2 0.9.1 [intl]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- logging 1.2.0
- lottie 2.7.0 [archive flutter path vector_math]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- mek_data_class 1.4.0 [class_to_string meta collection]
- meta 1.11.0
- mime 1.0.5
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.0.0 [flutter]
- one_for_all 1.0.0 [meta]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- pay_android 2.0.0 [flutter flutter_localizations pay_platform_interface]
- pay_ios 1.0.11 [flutter pay_platform_interface]
- pay_platform_interface 1.0.4 [flutter yaml]
- permission_handler_android 12.0.5 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.4 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.2.1 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- provider 6.1.2 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.1 [meta]
- recase 4.1.0
- rxdart 0.27.7
- sanitize_html 2.1.0 [html meta]
- screen_brightness_android 1.0.0 [flutter screen_brightness_platform_interface]
- screen_brightness_ios 1.0.0+1 [flutter screen_brightness_platform_interface]
- screen_brightness_macos 1.0.0 [flutter screen_brightness_platform_interface]
- screen_brightness_platform_interface 1.0.0 [flutter plugin_platform_interface]
- screen_brightness_windows 1.0.0 [flutter screen_brightness_platform_interface]
- share_plus_platform_interface 3.4.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 2.0.0 [flutter flutter_web_plugins sign_in_with_apple_platform_interface]
- sky_engine 0.0.99
- smart_auth 2.0.0 [flutter flutter_web_plugins]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.3 [flutter sqflite_common path]
- sqflite_common 2.5.4 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- stripe_android 10.1.1 [flutter]
- stripe_ios 10.1.0 [flutter]
- stripe_platform_interface 10.1.1 [flutter freezed_annotation json_annotation meta plugin_platform_interface]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- universal_platform 1.0.0+1
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- video_player_android 2.4.12 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.6 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.3.0 [flutter flutter_web_plugins video_player_platform_interface web]
- vm_service 13.0.0
- web 0.5.1
- webview_flutter_android 3.16.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.13.0 [flutter path webview_flutter_platform_interface]
- win32 5.4.0 [ffi]
- win32_registry 1.1.2 [ffi win32]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>
