### ISSUE TITLE
[firebase_auth]: Microsoft OAuthProvider ignoring provided tenant

### ISSUE THREAD

**Issue by noahjoshua** [firebase/flutterfire#12606]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Web

### Description

I am completely stuck as where to go with this. I have two applications running live for which this code has always been working, however now, when testing locally, `firebase_auth` opens the `/common` endpoint instead of the` /<tenant_id> `endpoint, ignoring the tenant provided.
I've pushed this to a staging server and it is not a local issue, but my live applications are running fine. So it must be on my machines end. 

```
final provider = OAuthProvider('microsoft.com');

provider.setCustomParameters({
  'prompt': 'select_account',
  'tenant': Env.tenantId,
});

UserCredential userCredential = await _auth.signInWithPopup(provider);
```

This is what I've always used, and it has always worked. I've tried going back to earlier commits, clearing all dependencies, trying different versions of them, everything. I can't wrap my head around how this would suddenly stop working, on both of my applications. 

### Reproducing the issue

```
final provider = OAuthProvider('microsoft.com');

provider.setCustomParameters({
  'prompt': 'select_account',
  'tenant': Env.tenantId,
});

UserCredential userCredential = await _auth.signInWithPopup(provider);
```
`firebase_auth` launches `login.microsoftonline.com/common/oauth2/v2.0/`, when the 'common' has always and should be replaced by the tenantID. 

### Firebase Core version

2.28.0

### Flutter Version

3.19.2

### Relevant Log Output

```shell
[firebase_auth/invalid-credential] Error getting verification code from microsoft.com response: error=invalid_request&error_description=AADSTS50194:%20Application%20'c6caa214-0fb7-4713-b22e-30d441ad13f5'(MY_APPLICATION_NAME)%20is%20not%20configured%20as%20a%20multi-tenant%20application.%20Usage%20of%20the%20/common%20endpoint%20is%20not%20supported%20for%20such%20applications%20created%20after%20'10/15/2018'.%20Use%20a%20tenant-specific%20endpoint%20or%20configure%20the%20application%20to%20be%20multi-tenant.%20Trace%20ID:%20fe00149e-5c0b-4e2f-93f8-5d05de956b00%20Correlation%20ID:%2015425340-2de5-4b2b-a792-b5700a4163d1%20Timestamp:%202024-04-08%2014:20:26Z&state=AMbdmDmo92uXMXrbXje4Djkn3Qgj12fJAEQn6RD99F4NDW6tD8tcPFAl1yN9xsoaQ6uNQkUXcVlj__FDRj9jkcu_05msjXtpPwedXpejR6dpYaAAIzDswnPBtX17rkmPHbqMQ-WKGb4gkLzpmGHj5ilV_-4LRkWSrNJpykieznlTa-vhIbUFTJnE8ODPX1bWEbdv412JXjM73sJsZaB-tXQJj9yOAOHaRDuvFWl4DZJxg0Gv1Lv0I82Wn3GVMiABP6bMA4uDVl9r73bX-2Pi4bVzW4woCnkhMm-h2daZ1f_smUBDk4bOTlwdg2n4GfIQyj_wmD_0NX9wdEB0LC8KGK67wA
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

dependencies:
- azblob 4.0.0 [http http_parser crypto]
- cloud_firestore 4.16.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- envied 0.5.4+1
- file_picker 8.0.0+1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file]
- firebase_analytics 10.10.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.2.2 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.19.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.28.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_animate 4.5.0 [flutter flutter_shaders]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- get 4.6.6 [flutter]
- http 1.2.1 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.19.0 [clock meta path]
- mime 1.0.5
- openai_dart 0.1.7 [fetch_client freezed_annotation http json_annotation meta]
- record 5.0.5 [flutter uuid record_platform_interface record_web record_windows record_linux record_android record_darwin]
- url_launcher 6.2.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- build_runner 2.4.9 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- envied_generator 0.5.4+1 [envied build code_builder dart_style source_gen analyzer recase equatable]
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.28 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.12 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.11.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+1 [meta web]
- crypto 3.0.3 [typed_data]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- fetch_api 1.0.3 [js]
- fetch_client 1.0.2 [fetch_api http]
- ffi 2.1.2
- file 7.0.0 [meta path]
- firebase_analytics_platform_interface 3.10.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.7 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_app_check_platform_interface 0.1.0+22 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.1.2 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_auth_platform_interface 7.2.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.11.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.14.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- fixnum 1.1.0
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_shaders 0.1.2 [flutter vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- graphs 2.3.1 [collection]
- http_multi_server 3.2.1 [async]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- package_config 2.1.0 [path]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- petitparser 6.0.2 [meta]
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- recase 4.1.0
- record_android 1.1.0 [flutter record_platform_interface]
- record_darwin 1.0.1 [flutter record_platform_interface]
- record_linux 0.7.1 [flutter record_platform_interface]
- record_platform_interface 1.0.2 [flutter plugin_platform_interface]
- record_web 1.0.5 [flutter flutter_web_plugins js record_platform_interface]
- record_windows 1.0.2 [flutter record_platform_interface path]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 13.0.0
- watcher 1.1.0 [async path]
- web 0.5.1
- web_socket_channel 2.4.4 [async crypto stream_channel web]
- win32 5.4.0 [ffi]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

### Additional context and comments

I have two live applications that are running perfectly still - it takes me to the tenant login page and works fine. When I push an update to my staging server, just as locally it still doesn't work. Thus my assumption is a package or something locally changed, but I have been clearing my pubcache and trying all sorts of versions.
