### ISSUE TITLE
[flutterfire]: looses configuration after flutter clean

### ISSUE THREAD

**Issue by KurtLa** [firebase/flutterfire#12619]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

macOS

### Description

I added Firebase dependencies into my pubspec.yaml, which triggered alerts about the build target being too low and needing an upgrade to at least version 10.15. To address these dependency conflicts, I underwent a series of troubleshooting steps involving Xcode configurations and CocoaPods installation/updates. This process eventually resolved the versioning conflicts. However, I then faced issues with Flutter's build process when executing `flutter clean`and `flutter pub get`, which led to multiple problems. The solution is to always run `flutterfire configure --project my-project-xxxxx --yes`, which resolves these build issues until next flutter clean.

### Reproducing the issue

flutter clean
flutter pub get

### Firebase Core version

2.28.0

### Flutter Version

3.19.5

### Relevant Log Output

```shell
After flutter clean, flutter pub get:

Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006020-001E484C0C33C01E }
{ platform:macOS, arch:x86_64, id:00006020-001E484C0C33C01E }
ld: warning: ignoring duplicate libraries: '-lc++'
/Users/user/Documents/FlutterProjekte/app/macos/Pods/FirebaseAuth/FirebaseAuth/Sources/AuthProvider/GameCenter/FIRGameCenterAuthProvider.m:76:79: warning: 'playerID' is deprecated: first deprecated in macOS 10.15 - Use either the gamePlayerID or teamPlayerID property to identify a player. [-Wdeprecated-declarations]
            [[FIRGameCenterAuthCredential alloc] initWithPlayerID:localPlayer.playerID
                                                                              ^
In module 'GameKit' imported from /Users/user/Documents/FlutterProjekte/app/macos/Pods/FirebaseAuth/FirebaseAuth/Sources/AuthProvider/GameCenter/FIRGameCenterAuthProvider.m:18:
@property(readonly, nonnull, retain, NS_NONATOMIC_IOSONLY)  NSString *playerID API_DEPRECATED("Use either the gamePlayerID or teamPlayerID property to identify a player.",ios(4.1,13.0),tvos(9.0,13.0),macos(10.8,10.15));
                                                                      ^
1 warning generated.
/Users/user/.pub-cache/hosted/pub.dev/firebase_auth-4.19.0/macos/Classes/FLTPhoneNumberVerificationStreamHandler.m:8:17: warning: method definition for 'initWithAuth:arguments:' not found [-Wincomplete-implementation]
@implementation FLTPhoneNumberVerificationStreamHandler {
                ^
In file included from /Users/user/.pub-cache/hosted/pub.dev/firebase_auth-4.19.0/macos/Classes/FLTPhoneNumberVerificationStreamHandler.m:5:
- (instancetype)initWithAuth:(FIRAuth *)auth arguments:(NSDictionary *)arguments;
^
1 warning generated.
/Users/user/.pub-cache/hosted/pub.dev/firebase_auth-4.19.0/macos/Classes/FLTFirebaseAuthPlugin.m:114:72: warning: sending 'FLTFirebaseAuthPlugin *__strong' to parameter of incompatible type 'id<FLTFirebasePlugin> _Nonnull'
    [[FLTFirebasePluginRegistry sharedInstance] registerFirebasePlugin:self];
                                                                       ^~~~
In module 'firebase_core' imported from /Users/user/.pub-cache/hosted/pub.dev/firebase_auth-4.19.0/macos/Classes/FLTFirebaseAuthPlugin.m:7:
- (void)registerFirebasePlugin:(id<FLTFirebasePlugin> _Nonnull)firebasePlugin;
                                                               ^
/Users/user/.pub-cache/hosted/pub.dev/firebase_auth-4.19.0/macos/Classes/FLTFirebaseAuthPlugin.m:1087:9: warning: 'fetchSignInMethodsForEmail:completion:' is deprecated: This method is deprecated and will be removed in a future release. This method returns an empty list when Email Enumeration Protection is enabled. [-Wdeprecated-declarations]
  [auth fetchSignInMethodsForEmail:email
        ^
In module 'FirebaseAuth' imported from /Users/user/Documents/FlutterProjekte/app/macos/Pods/Headers/Public/Firebase/Firebase.h:34:
    DEPRECATED_MSG_ATTRIBUTE(
    ^
In module 'Darwin' imported from /Users/user/.pub-cache/hosted/pub.dev/firebase_auth-4.19.0/macos/Classes/FLTFirebaseAuthPlugin.m:6:
            #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                               ^
/Users/user/.pub-cache/hosted/pub.dev/firebase_auth-4.19.0/macos/Classes/FLTFirebaseAuthPlugin.m:1885:16: warning: 'updateEmail:completion:' is deprecated: This method is deprecated and will be removed in a future release. Use sendEmailVerification(beforeUpdatingEmail email: String) instead. [-Wdeprecated-declarations]
  [currentUser updateEmail:newEmail
               ^
In module 'FirebaseAuth' imported from /Users/user/Documents/FlutterProjekte/app/macos/Pods/Headers/Public/Firebase/Firebase.h:34:
    NS_SWIFT_NAME(updateEmail(to:completion:)) DEPRECATED_MSG_ATTRIBUTE(
                                               ^
In module 'Darwin' imported from /Users/user/.pub-cache/hosted/pub.dev/firebase_auth-4.19.0/macos/Classes/FLTFirebaseAuthPlugin.m:6:
            #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                               ^
/Users/user/.pub-cache/hosted/pub.dev/firebase_auth-4.19.0/macos/Classes/FLTFirebaseAuthPlugin.m:87:17: warning: class 'FLTFirebaseAuthPlugin' does not conform to protocols 'MultiFactorUserHostApi', 'MultiFactoResolverHostApi', 'MultiFactorTotpHostApi', ... [-Wprotocol]
@implementation FLTFirebaseAuthPlugin {
                ^
@implementation FLTFirebaseAuthPlugin {
                ^
/Users/user/.pub-cache/hosted/pub.dev/firebase_auth-4.19.0/macos/Classes/FLTFirebaseAuthPlugin.m:576:13: warning: unused function 'handleAppleAuthResult' [-Wunused-function]
static void handleAppleAuthResult(FLTFirebaseAuthPlugin *object, AuthPigeonFirebaseApp *app,
            ^
5 warnings generated.
ld: warning: ignoring duplicate libraries: '-lc++'
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')

2024-04-09 21:29:43.448 app[1370:822604] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
Connecting to VM Service at ws://127.0.0.1:64540/LnaBtD0_YPk=/ws

------------------------------------------

After flutterfire configure --project my-project-xxxxx --yes
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006020-001E484C0C33C01E }
{ platform:macOS, arch:x86_64, id:00006020-001E484C0C33C01E }
ld: warning: ignoring duplicate libraries: '-lc++'

2024-04-09 21:47:47.193 app[3412:838121] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
Connecting to VM Service at ws://127.0.0.1:65470/J5J-RJWuSew=/ws
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.3.3
Flutter SDK 3.19.5
appversion 0.2.0

dependencies:
- audioplayers 5.2.1 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- cupertino_icons 1.0.6
- firebase_auth 4.19.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.28.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 10.5.0 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- flame 1.17.0 [collection flutter meta ordered_set vector_math]
- flame_audio 2.10.1 [audioplayers flame flutter synchronized]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hive 2.2.3 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- nanoid 1.0.0

dev dependencies:
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.28 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- audioplayers_android 4.0.3 [audioplayers_platform_interface flutter]
- audioplayers_darwin 5.0.2 [audioplayers_platform_interface flutter]
- audioplayers_linux 3.1.0 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 6.1.0 [flutter meta plugin_platform_interface]
- audioplayers_web 4.1.0 [audioplayers_platform_interface flutter flutter_web_plugins js]
- audioplayers_windows 3.1.0 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- crypto 3.0.3 [typed_data]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- firebase_auth_platform_interface 7.2.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.11.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.14.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_database_platform_interface 0.2.5+28 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.5 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins]
- fixnum 1.1.0
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- google_identity_services_web 0.3.1+1 [meta web]
- google_sign_in_android 6.1.22 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.5 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- http 1.2.1 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- ordered_set 5.0.2
- path 1.9.0
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- uuid 4.4.0 [crypto sprintf meta fixnum]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.5.1
- win32 5.4.0 [ffi]
- xdg_directories 1.0.4 [meta path]

```

</details>

### Additional context and comments

`ld: warning: ignoring duplicate libraries: '-lc++'` is new and maybe related to executing `flutterfire configure` that often?
