### ISSUE TITLE
[firebase_auth]: `signInWithCredential` crash on Windows when no `accessToken` is specified

### ISSUE THREAD

**Issue by Skyost** [firebase/flutterfire#12613]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Windows

### Description

When trying to use `signInWithCredential`, it crashes without any additional information. By using the Visual Studio debugger, I've seen it occurs at the following line :

![image](https://github.com/firebase/flutterfire/assets/3882599/407d55f2-1598-47fe-87f9-00c7c4348c4c)

I was using the following code :

```dart
FirebaseAuth.instance.signInWithCredential(
  GoogleAuthProvider.credential(
    idToken: 'my id token',
  ),
);
```

It also crashes with a blank access token :

```dart
FirebaseAuth.instance.signInWithCredential(
  GoogleAuthProvider.credential(
    idToken: 'my id token',
    accessToken: '',
  ),
);
```

Note that it also affects OAuth providers like `MicrosoftAuthProvider`.

### Reproducing the issue

On Windows :

* Sends an OOB code by email using `https://identitytoolkit.googleapis.com/v1/accounts:sendOobCode`.
* Use that OOB code to sign in using `https://identitytoolkit.googleapis.com/v1/accounts:signInWithEmailLink`. You should get an `idToken`.
* Run : `FirebaseAuth.instance.signInWithCredential(GoogleAuthProvider.credential(idToken: idToken));`.

### Firebase Core version

2.28.0

### Flutter Version

3.19.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.3.3
Flutter SDK 3.19.5
open_authenticator 1.0.0+1

dependencies:
- animations 2.0.11 [flutter]
- camera 0.10.5+9 [camera_android camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle]
- cloud_firestore 4.16.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- drift 2.16.0 [async convert collection js meta stream_channel sqlite3 path stack_trace web]
- equatable 2.0.5 [collection meta]
- firebase_app_check 0.2.2 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.19.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.28.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.5.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.5.0 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- flex_color_scheme 7.3.1 [flex_seed_scheme flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_riverpod 2.5.1 [collection flutter meta riverpod state_notifier]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- google_mlkit_barcode_scanning 0.10.0 [flutter google_mlkit_commons]
- http 1.2.1 [async http_parser meta web]
- intl 0.18.1 [clock meta path]
- local_auth 2.2.0 [flutter local_auth_android local_auth_darwin local_auth_platform_interface local_auth_windows]
- package_info_plus 6.0.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32]
- path 1.9.0
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- purchases_flutter 6.25.0 [flutter freezed_annotation json_annotation]
- purchases_ui_flutter 6.25.0 [purchases_flutter flutter plugin_platform_interface]
- qr_flutter 4.1.0 [flutter qr]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- simple_secure_storage 0.3.0 [flutter simple_secure_storage_platform_interface simple_secure_storage_android simple_secure_storage_darwin simple_secure_storage_windows simple_secure_storage_linux simple_secure_storage_web]
- slang 3.30.2 [collection csv json2yaml watcher yaml]
- slang_flutter 3.30.0 [flutter slang]
- sqlite3 2.4.2 [collection ffi js meta path]
- sqlite3_flutter_libs 0.5.20 [flutter]
- totp 0.0.1 [hotp]
- url_launcher 6.2.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]      
- uuid 4.3.3 [crypto sprintf meta fixnum]
- webcrypto 0.5.6 [ffi meta flutter_web_plugins flutter]
- window_manager 0.3.8 [flutter path screen_retriever]

dev dependencies:
- build_runner 2.4.9 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob grap
hs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- drift_dev 2.16.0 [charcode collection recase meta path json_annotation stream_transform args logging cli_util yaml io drift sqlite3 sqlparser analyzer analyzer_plugin source_span package_config pub_semver build build_resolvers build_config dart_style source_gen string_scanner]
- flutter_lints 3.0.2 [lints]
- slang_build_runner 3.30.0 [build glob slang]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.28 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.11.3 [analyzer collection dart_style pub_semver yaml]
- args 2.4.2
- async 2.11.0 [collection meta]
- base32 2.1.3
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]  
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- camera_android 0.10.9 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]
- camera_avfoundation 0.9.15 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.7.4 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.3 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.3.0
- charcode 1.3.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.12 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.11.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+1 [meta web]
- crypto 3.0.3 [typed_data]
- csv 6.0.0
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- firebase_app_check_platform_interface 0.1.0+22 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.1.2 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_auth_platform_interface 7.2.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.11.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.14.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.28 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+28 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- fixnum 1.1.0
- flex_seed_scheme 1.5.0 [collection flutter meta]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- google_mlkit_commons 0.6.1 [flutter]
- graphs 2.3.1 [collection]
- hotp 0.0.2 [base32 crypto]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- idb_shim 2.4.1+1 [sembast collection path js meta web]
- io 1.0.4 [meta path string_scanner]
- js 0.7.1
- json2yaml 3.0.1 [meta]
- json_annotation 4.8.1 [meta]
- just_throttle_it 2.1.0
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- local_auth_android 1.0.37 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_darwin 1.2.2 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.10 [flutter plugin_platform_interface]
- local_auth_windows 1.0.10 [flutter local_auth_platform_interface]
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.1 [meta]
- recase 4.1.0
- riverpod 2.5.1 [collection meta stack_trace state_notifier]
- screen_retriever 0.1.9 [flutter]
- sembast 3.7.1 [meta path synchronized]
- sembast_web 2.3.0 [web sembast idb_shim synchronized]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.3.0 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- simple_secure_storage_android 0.2.0 [flutter simple_secure_storage_platform_interface]
- simple_secure_storage_darwin 0.2.0 [flutter simple_secure_storage_platform_interface]
- simple_secure_storage_linux 0.2.0 [flutter simple_secure_storage_platform_interface]
- simple_secure_storage_platform_interface 0.2.0 [flutter meta plugin_platform_interface]
- simple_secure_storage_web 0.2.0 [flutter flutter_web_plugins just_throttle_it sembast sembast_web simple_secure_storage_platform_interface webcrypto]
- simple_secure_storage_windows 0.3.0 [flutter simple_secure_storage_platform_interface]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqlparser 0.34.1 [meta collection source_span charcode]
- stack_trace 1.11.1 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 13.0.0
- watcher 1.1.0 [async path]
- web 0.5.1
- web_socket_channel 2.4.4 [async crypto stream_channel web]
- win32 5.4.0 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>
