### ISSUE TITLE
[firebase_messaging]: Firebase push notification service worker hinders flutter's default SW registration

### ISSUE THREAD

**Issue by AnayShri** [firebase/flutterfire#12638]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

Web

### Description

On service worker registrations i.e. on index.html, the firebase-messaging-sw.js is not registered with a scope and is assigned the scope after initialization. Since the scope is not defined on registration itself, it does not allow Flutter's default SW to be updated and keeps it hanging at the "waiting to activate" phase

### Reproducing the issue

Define the Firebase messaging service worker on index.html with Flutter's pre-defined SW and hit reload after the website initializes. 

Without adding the scope at registration: 
<img width="1094" alt="Screenshot 2024-04-14 at 4 14 26 PM" src="https://github.com/firebase/flutterfire/assets/163650575/78ce5d9a-d549-49b9-ae9c-86d83b12a1c4">

With the scope : 
<img width="1092" alt="Screenshot 2024-04-14 at 4 14 00 PM" src="https://github.com/firebase/flutterfire/assets/163650575/ae4da8ca-a9c0-4183-930e-0cb386bfb041">

### Firebase Core version

2.29.0

### Flutter Version

3.19.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.3.0
Flutter SDK 3.19.0
firebase_messaging 14.8.1

dependencies:
- firebase_core 2.29.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.31 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.8.1 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- meta 1.11.0

dev dependencies:
- async 2.11.0 [collection meta]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- mockito 5.4.4 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- plugin_platform_interface 2.1.8 [meta]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.29 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.5.0
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- characters 1.3.0
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- fake_async 1.3.1 [clock collection]
- file 7.0.0 [meta path]
- firebase_core_web 2.15.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- fixnum 1.1.0
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- glob 2.1.2 [async collection file path string_scanner]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- package_config 2.1.0 [path]
- path 1.9.0
- pub_semver 2.1.4 [collection meta]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- vm_service 13.0.0
- watcher 1.1.0 [async path]
- web 0.5.1
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>
