### ISSUE TITLE
[firebase_crashlytics]: <ANR problem caused by CrashlyticsController. HandleUncaughtException>

### ISSUE THREAD

**Issue by zhanzengyu** [firebase/flutterfire#12680]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

Android

### Description

An ANR appeared in my project. I analyzed the ANR file and found that the main thread was waiting for an object held by firebase.

### Reproducing the issue

We found this in monkey testing, so there is no stable reproducing step

### Firebase Core version

2.24.2

### Flutter Version

3.13.0

### Relevant Log Output

```shell
Subject: Input dispatching timed out (c05a694 com.xxx.xxx/com.xxx.xxx.MainActivity (server) is not responding. Waited 5004ms for KeyEvent(action=UP))

"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x7275af78 self=0xb4000071e66b6c00
  | sysTid=17116 nice=-10 cgrp=top-app sched=0/0 handle=0x71e7d144f8
  | state=S schedstat=( 23359971172 6105573652 44258 ) utm=1677 stm=658 core=2 HZ=100
  | stack=0x7ff7544000-0x7ff7546000 stackSize=8188KB
  | held mutexes=
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(unavailable:0)
  - waiting to lock <0x03ddad21> (a com.google.firebase.crashlytics.internal.common.CrashlyticsController) held by thread 928
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:181)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController$1.onUncaughtException(CrashlyticsController.java:168)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:54)
  at com.umeng.analytics.pro.p.uncaughtException(CrashHandler.java:37)
  at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-TrichromeWebViewGoogle.aab-stable-506012933:41)
  at com.uc.crashsdk.e.a(ProGuard:4008)
  at com.uc.crashsdk.e.uncaughtException(ProGuard:3822)
  at cn.jiguang.b.a.uncaughtException(unavailable:65)
  at cn.jiguang.cd.h.uncaughtException(unavailable:20)
  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
  at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)

"pool-12-thread-825" prio=5 tid=928 TimedWaiting
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x14ac82f8 self=0xb40000701d5b2000
  | sysTid=22345 nice=0 cgrp=top-app sched=0/0 handle=0x69b177fcb0
  | state=S schedstat=( 1744479 0 2 ) utm=0 stm=0 core=7 HZ=100
  | stack=0x69b167c000-0x69b167e000 stackSize=1039KB
  | held mutexes=
  at jdk.internal.misc.Unsafe.park(Native method)
  - waiting on an unknown object
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
  at com.google.firebase.crashlytics.internal.common.Utils.awaitEvenIfOnMainThread(Utils.java:123)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:255)
  - locked <0x03ddad21> (a com.google.firebase.crashlytics.internal.common.CrashlyticsController)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsController.logFatalException(CrashlyticsController.java:456)
  at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.logFatalException(CrashlyticsCore.java:403)
  at com.google.firebase.crashlytics.FlutterFirebaseCrashlyticsInternal.recordFatalException(FlutterFirebaseCrashlyticsInternal.java:22)
  at io.flutter.plugins.firebase.crashlytics.FlutterFirebaseCrashlyticsPlugin.lambda$recordError$4$io-flutter-plugins-firebase-crashlytics-FlutterFirebaseCrashlyticsPlugin(FlutterFirebaseCrashlyticsPlugin.java:182)
  at io.flutter.plugins.firebase.crashlytics.FlutterFirebaseCrashlyticsPlugin$$ExternalSyntheticLambda5.run(unavailable:6)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
  at java.lang.Thread.run(Thread.java:1012)
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.1.0
Flutter SDK 3.13.0
neutral_app 1.0.0+34

dependencies:
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cupertino_icons 1.0.6
- dots_indicator 3.0.0 [flutter]
- firebase_analytics 10.8.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.24.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.9 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_native_splash 2.3.7 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml ansicolor]
- get 4.6.6 [flutter]
- image_cropper 5.0.1 [flutter image_cropper_platform_interface]
- image_picker 1.0.7 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- lib_analytics 0.0.1 [flutter plugin_platform_interface firebase_core firebase_analytics umeng_common_sdk]
- lib_config_network 0.0.1 [flutter lib_http lib_analytics lib_log socket_io_client flutter_blue_plus permission_handler location geolocator encrypt crypto wifi_iot network_info_plus app_settings]
- lib_data_storage 0.0.1 [flutter path_provider shared_preferences sqflite_sqlcipher synchronized]
- lib_http 0.0.1 [flutter dio collection crypto encrypt package_info_plus device_info_plus]
- lib_plugin_umeng 0.0.1 [flutter umeng_apm_sdk umeng_common_sdk package_info_plus plugin_platform_interface]
- lib_sweeper_map 0.0.1 [flutter flutter_web_plugins plugin_platform_interface protobuf flutter_map latlong2 crypto raw_image_provider ffi lib_log]
- lib_ui 0.0.1 [flutter]
- module_add_device 1.0.0+1 [flutter cupertino_icons get flutter_blue_plus dio cached_network_image lib_ui lib_log lib_http lib_analytics lib_config_network lib_data_storage module_login module_common module_device module_locale]
- module_common 0.0.1 [flutter device_info_plus flutter_inappwebview path_provider get flutter_easyloading flutter_slidable crypto encrypt connectivity_plus url_launcher package_info_plus module_locale jpush_flutter lottie easy_refresh flutter_markdown umeng_push_sdk flutter_keyboard_visibility lib_ui lib_mqtt lib_http lib_log lib_analytics typed_data]
- module_device 1.0.0+1 [flutter flutter_native_splash cupertino_icons dots_indicator cached_network_image flutter_picker intl sprintf flutter_markdown lib_ui lib_http lib_mqtt lib_analytics dio module_common module_locale module_login lib_sweeper_map lib_data_storage lib_log module_add_device module_device_share module_person]
- module_device_share 1.0.0+1 [flutter cupertino_icons dio cached_network_image lib_ui lib_log lib_http lib_data_storage module_common module_login module_locale]
- module_locale 0.0.1 [flutter flutter_localizations module_common lib_data_storage]
- module_login 1.0.0+1 [flutter flutter_native_splash fluwx dio device_info_plus package_info_plus rf_section_listview flutter_markdown geocoding geolocator permission_handler location lib_ali_auth lib_ui lib_http lib_data_storage module_locale lib_config_network module_common cupertino_icons]
- module_person 1.0.0+1 [flutter image_picker image_cropper package_info_plus permission_handler video_player image video_compress cupertino_icons lib_ui module_login lib_http lib_config_network module_common module_locale module_device_share lib_data_storage module_splash module_device path_provider archive get intl video_thumbnail]
- module_splash 1.0.0+1 [flutter cupertino_icons video_player flutter_test flutter_lints flutter_native_splash shared_preferences module_common module_person lib_http lib_data_storage module_login]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

dependency overrides:
- http 1.1.0 [async http_parser meta]

transitive dependencies:
- _flutterfire_internals 1.3.16 [collection firebase_core firebase_core_platform_interface flutter meta]
- ansicolor 2.0.2
- app_settings 5.1.1 [flutter plugin_platform_interface]
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- asn1lib 1.5.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.1 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- charcode 1.3.1
- clock 1.1.1
- collection 1.17.2
- connectivity_plus 4.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+7 [js meta]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus 9.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- dio 4.0.6 [http_parser path]
- easy_refresh 3.3.4 [flutter path_drawing]
- encrypt 5.0.3 [args asn1lib clock collection crypto pointycastle]
- event_bus 2.0.0
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.9.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+12 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.10.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.16 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- fixnum 1.1.0
- flutter_blue_plus 1.32.1 [flutter]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_easyloading 3.0.5 [flutter flutter_spinkit]
- flutter_inappwebview 5.8.0 [flutter]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_map 6.1.0 [async collection flutter http latlong2 logger meta polylabel proj4dart vector_math]
- flutter_markdown 0.6.14 [flutter markdown meta path]
- flutter_picker 2.1.0 [flutter]
- flutter_plugin_android_lifecycle 2.0.18 [flutter]
- flutter_slidable 3.1.0 [flutter]
- flutter_spinkit 5.2.1 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- fluwx 4.5.5 [flutter flutter_web_plugins plugin_platform_interface]
- geocoding 2.2.2 [flutter geocoding_platform_interface geocoding_android geocoding_ios]
- geocoding_android 3.3.0 [flutter geocoding_platform_interface]
- geocoding_ios 2.3.0 [flutter geocoding_platform_interface]
- geocoding_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- geolocator 11.0.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple]
- geolocator_android 4.5.2 [flutter geolocator_platform_interface uuid]
- geolocator_apple 2.3.6 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.2 [flutter plugin_platform_interface vector_math meta]
- html 0.15.4 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.7 [archive meta xml]
- image_cropper_platform_interface 5.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.9+5 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.2 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.3 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- intl 0.18.1 [clock meta path]
- jpush_flutter 2.5.0 [platform flutter]
- js 0.6.7 [meta]
- latlong2 0.9.0 [intl]
- lib_ali_auth 1.2.0 [flutter flutter_web_plugins plugin_platform_interface js]
- lib_log 0.0.1 [flutter archive crypto encrypt intl path_provider stack_trace]
- lib_mqtt 0.0.1 [flutter mqtt_client mqtt5_client synchronized typed_data lib_analytics]
- lints 2.1.1
- lists 1.0.1 [meta]
- location 5.0.0 [flutter location_platform_interface location_web]
- location_platform_interface 3.1.2 [flutter plugin_platform_interface]
- location_web 4.2.0 [flutter flutter_web_plugins http_parser js location_platform_interface]
- logger 2.2.0
- logging 1.2.0
- lottie 1.4.3 [archive flutter path vector_math]
- markdown 7.2.1 [args meta]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- mgrs_dart 2.0.0 [unicode]
- mime 1.0.4
- mqtt5_client 4.2.2 [typed_data event_bus path universal_html crypto meta]
- mqtt_client 9.8.1 [typed_data event_bus path crypto meta]
- network_info_plus 4.1.0 [collection nm flutter flutter_web_plugins meta network_info_plus_platform_interface win32 ffi]
- network_info_plus_platform_interface 1.1.3 [flutter meta plugin_platform_interface]
- nm 0.5.0 [dbus]
- octo_image 2.0.0 [flutter]
- package_info_plus 4.2.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.3 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler 11.0.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- permission_handler_android 11.1.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.12.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.3 [flutter permission_handler_platform_interface]
- petitparser 5.4.0 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.8.0 [collection convert js]
- polylabel 1.0.1 [collection]
- proj4dart 2.1.0 [mgrs_dart wkt_parser meta]
- protobuf 3.1.0 [collection fixnum meta]
- raw_image_provider 0.2.0 [flutter crypto]
- rf_section_listview 0.0.3 [flutter]
- rxdart 0.27.7
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.1 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- socket_io_client 2.0.3+1 [logging socket_io_common js]
- socket_io_common 2.0.3 [logging]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.2 [flutter sqflite_common path]
- sqflite_common 2.5.3 [synchronized path meta]
- sqflite_sqlcipher 2.2.1 [flutter synchronized path sqflite_common]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- umeng_apm_sdk 2.2.1 [flutter http]
- umeng_common_sdk 1.2.7 [flutter]
- umeng_push_sdk 2.2.0 [flutter umeng_common_sdk]
- unicode 0.3.1 [lists]
- universal_html 2.2.4 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher 6.2.4 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.2.0 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.2.2 [crypto sprintf meta]
- vector_math 2.1.4
- video_compress 3.1.2 [flutter]
- video_player 2.8.3 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.4.12 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.2 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.1.3 [flutter flutter_web_plugins video_player_platform_interface]
- video_thumbnail 0.5.3 [flutter]
- web 0.1.4-beta
- wifi_iot 0.3.19 [flutter]
- win32 5.1.1 [ffi]
- win32_registry 1.1.2 [ffi win32]
- wkt_parser 2.0.0
- xdg_directories 1.0.4 [meta path]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]


```

</details>
