### ISSUE TITLE
[firebase_core][firebase_auth]: Execution failed for task ':app:mergeLibDexDebug'.

### ISSUE THREAD

**Issue by ndson040496** [firebase/flutterfire#12704]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Auth

### Which platforms are affected?

Android

### Description

My project couldn't build to Android after adding `firebase_core` and `firebase_auth`. iOS and Web can still build and run just fine.

- Logs for ``flutter build apk --debug --verbose`: 
[Terminal Saved Output.txt](https://github.com/firebase/flutterfire/files/15107475/Terminal.Saved.Output.txt)

- What I tried:
  - Changing `minSdkVersion` to 21
  - Adding `multidex` with `implementation 'com.android.support:multidex:2.0.1'` and `multiDexEnabled true` (not required by SDK 21, but I still tried).

### Reproducing the issue

- My `build.gradle`:
```
plugins {
    id "com.android.application"
    // START: FlutterFire Configuration
    id 'com.google.gms.google-services'
    // END: FlutterFire Configuration
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.sseo.app_incent"
    compileSdk flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.sseo.app_incent"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 21
        targetSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {}

```

- My pubspec.yaml
```
name: app_incent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: 4.19.4
  firebase_core: 2.30.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: 14.0.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

flutter:
  assets:
    - assets/images/misc/
  uses-material-design: true
  generate: true

```

### Firebase Core version

2.30.1

### Flutter Version

3.19.6
