### ISSUE TITLE
BUG: unhandled exception No address associated with hostname

### ISSUE THREAD

**Issue by joukhar** [firebase/flutterfire#12715]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

App Check

### Which platforms are affected?

Android

### Description

this error occurs when user has no internet connection, i believe it's (Socket exception) 
on this function :
```dart
await appCheckInstance.getToken();
```
unhandled exception No address associated with hostname

### Reproducing the issue

call `await appCheckInstance.getToken();` with no source of internet in your device.

### Firebase Core version

2.27.0

### Flutter Version

3.19.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  firebase_crashlytics: ^3.4.18
  firebase_analytics: ^10.10.4
  firebase_app_check: ^0.2.2+1

```

</details>
