### ISSUE TITLE
[remote_config]: setConfigSettings on windows raises an exception

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [firebase/flutterfire#12744]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Remote Config

### Which platforms are affected?

Windows

### Description

I similar problem on windows, maybe, I think? When I run the app on it, I get this exception
![image](https://github.com/firebase/flutterfire/assets/90481654/855277b0-97d7-4ad1-9498-362f0ec30e2c)

In the remoteconfig code, it appears there is an empty map causing this exception
![image](https://github.com/firebase/flutterfire/assets/90481654/7aea4ef4-d79b-4dae-aaae-205cb0aec1ff)

After the exception, the app does not open

### Reproducing the issue

this is the code to reproduce it: 
```dart
void main() async {
  runApp(const MyApp());

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseRemoteConfig remoteConfig = FirebaseRemoteConfig.instance;
  await remoteConfig.setConfigSettings(
    RemoteConfigSettings(
      fetchTimeout: const Duration(minutes: 1),
      minimumFetchInterval: const Duration(hours: 1),
    ),
  );
  await remoteConfig.setDefaults(const {
    "minimum_version": "1.0.0",
  });
}
```

### Firebase Core version

2.30.1

### Flutter Version

3.19.6

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.3.4
Flutter SDK 3.19.6
exampleapp 1.0.0+1

dependencies:
- cupertino_icons 1.0.8
- firebase_core 2.30.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_remote_config 4.4.4 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.32 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.16.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_remote_config_platform_interface 1.4.32 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.6.4 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.5.1

```

</details>

### Additional context and comments

I saw this issue which could be related? https://github.com/firebase/flutterfire/issues/12496
