### ISSUE TITLE
[Firebase_Database]: <Error: Exception: Unknown event type: DatabaseEventType.value>

### ISSUE THREAD

**Issue by fahrezahaydar** [firebase/flutterfire#12759]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

Web

### Description

Just Simple Update with button like this : 
```
FilledButton(
  onPressed: () {
    FirebaseDatabase.instance.ref().child("Connection/Test").set(false);
  },
  child: const Text("Check"),
), 
```
Will execute perfectly firstly but make after couple tries will return error like this. I try using async, change set to update but still give this error
```
Error: Exception: Unknown event type: DatabaseEventType.value
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3                                       throw_
packages/firebase_database_platform_interface/src/platform_interface/platform_interface_database_event.dart 51:5  eventTypeToString
packages/firebase_database_web/src/database_event_web.dart 15:24                                                  new
packages/firebase_database_web/src/utils/snapshot_utils.dart 13:10                                                webEventToPlatformEvent
packages/firebase_database_web/src/query_web.dart 130:46                                                          <fn>
dart-sdk/lib/async/stream_pipe.dart 213:31                                                                        [_handleData]
dart-sdk/lib/async/stream_pipe.dart 153:5                                                                         [_handleData]
dart-sdk/lib/async/zone.dart 1594:9                                                                               runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:5                                                                         [_sendData]
dart-sdk/lib/async/stream_impl.dart 515:13                                                                        perform
dart-sdk/lib/async/stream_impl.dart 620:10                                                                        handleNext
dart-sdk/lib/async/stream_impl.dart 591:7                                                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7   
```

### Reproducing the issue

```
FilledButton(
  onPressed: () {
    FirebaseDatabase.instance.ref().child("Connection/Test").set(false);
  },
  child: const Text("Check"),
), 
```

### Firebase Core version

^2.31.0

### Flutter Version

3.19.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

dependencies:
  animated_check: ^1.0.5
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.2
  dartx: ^1.2.0
  dartz: ^0.10.1
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_database: ^10.5.5
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_web_plugins:
    sdk: flutter
  flutter_widget_from_html_core: ^0.14.11
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  internet_connection_checker_plus: ^2.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  qr_flutter: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

```

</details>
