### ISSUE TITLE
[firebase_auth]: error.credential is null on credential-already-in-use exception during apple sign in in web

### ISSUE THREAD

**Issue by BogsBalangat** [firebase/flutterfire#12771]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Web

### Description

Firebase auth in **web** returns a null credential value on a "credential-already-in-use" FirebaseAuthException during **apple sign in**.
This prevents the web app from being able to recover and continue with the sign in flow.

Notes:
This issue only happens on flutter web. 
This does not happen during Google Sign in on flutter web.
It is working as expected (error.credential is not null) in flutter mobile (both android & ios) 

### Reproducing the issue

Make sure that you already have a firebase user linked to an apple account.

Then run the following code.
A new anonymous user will be created and make sure to sign in to the same apple account.

Here is a sample code:
```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MaterialApp(
    home: const App(),
  ));
}

class App extends StatefulWidget {
  const App({super.key});

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  final auth = FirebaseAuth.instance;
  @override
  void initState() {
    super.initState();
    _createAnonymousAccount();
  }

  Future<void> _createAnonymousAccount() async {
    if (auth.currentUser == null) {
      await auth.signInAnonymously();
    }
  }

  Future<void> _signIn() async {
    try {
      await auth.currentUser!.linkWithPopup(AppleAuthProvider());
      print('Link successful');
    } on FirebaseAuthException catch (e) {
      if (e.code == 'credential-already-in-use') {
        final cred = e.credential!;
        await auth.signInWithCredential(cred);
        print('Sign in successful');
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: _signIn,
          child: const Text('Sign in'),
        ),
      ),
    );
  }
}
```
### Firebase Core version

2.30.1

### Flutter Version

3.19.5

### Relevant Log Output

```shell
Error: Unexpected null value.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 806:18  nullCheck
packages/test/main.dart 44:34                                               _signIn
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 60:31                <fn>
dart-sdk/lib/async/zone.dart 1666:54                                              runBinary
dart-sdk/lib/async/future_impl.dart 177:22                                        handleError
dart-sdk/lib/async/future_impl.dart 850:46                                        handleError
dart-sdk/lib/async/future_impl.dart 871:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 651:5                                         [_completeError]
dart-sdk/lib/async/future_impl.dart 737:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                <fn>
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.3.3
Flutter SDK 3.19.5
colabrador 1.4.0+92

dependencies:
- cupertino_icons 1.0.6
- firebase_auth 4.19.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.30.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- localization 2.1.0 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.32 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 7.2.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.11.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.16.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.18.1 [clock meta path]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.5.1


```

</details>

### Additional context and comments

Here is a screenshot showing actual values of the FirebaseAutghException.
<img width="1317" alt="Screenshot 2024-05-13 at 10 13 40 AM" src="https://github.com/firebase/flutterfire/assets/29452246/a2965fdf-3e7b-433c-be5a-ce4a339a4f47">

*Shows that credential is null
