### ISSUE TITLE
[firebase_analytics]: <firebase_analytics does not work in Android, after migrating build.gradle >

### ISSUE THREAD

**Issue by tekink** [firebase/flutterfire#12789]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics, Crashlytics

### Which platforms are affected?

Android

### Description

Android app not working after build.gradle update.
It gives the error firebase_analytics: missing google_id.
Firebase_analytics and crashlytics records are not shown on the firebase console screen.

### Reproducing the issue

Actually there was no problem before the build.gradle update. It stopped working after the update.

### Firebase Core version

2.31.0

### Flutter Version

3.19.4

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies
name: app
description: app

publish_to: 'none' 

version: 3.75.0+75

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter

  #google
  cloud_firestore: ^4.17.3
  firebase_analytics: ^10.10.5
  firebase_app_check: ^0.2.2+5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  firebase_storage: ^11.7.5
  firebase_analytics_web: ^0.5.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.
- badges 3.1.2 [flutter]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_i
mage]
- cloud_firestore 4.17.3 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_in
terface flutter meta]
- cupertino_icons 1.0.8
- d_chart 2.6.9 [flutter community_charts_flutter community_charts_common]
- delta_to_html 0.2.2
- device_info_plus 10.1.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry] 
- dropdown_button2 2.3.9 [flutter meta]
- easy_refresh 3.3.5+1 [flutter path_drawing]
- excel 4.0.3 [archive xml collection equatable]
- expand_widget 3.1.1 [flutter]
- file_picker 8.0.3 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_fi
le web]
- firebase_analytics 10.10.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_int
erface flutter]
- firebase_analytics_web 0.5.7+5 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flut
ter flutter_web_plugins]
- firebase_app_check 0.2.2+5 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_int
erface flutter]
- firebase_core 2.31.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.5.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_
trace]
- firebase_storage 11.7.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web 
flutter]
- flex_color_scheme 7.3.1 [flex_seed_scheme flutter meta]
- flutter_local_notifications 17.1.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interfac
e timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_native_splash 2.4.0 [args flutter flutter_web_plugins html image meta path universal_io xml yaml ansicolor]
- flutter_quill 9.3.11 [flutter flutter_localizations intl dart_quill_delta collection quiver equatable meta html flutter_colorpick
er markdown html2md charcode url_launcher flutter_keyboard_visibility device_info_plus super_clipboard]
- flutter_widget_from_html 0.15.0 [flutter flutter_widget_from_html_core fwfh_cached_network_image fwfh_chewie fwfh_just_audio fwfh
_svg fwfh_url_launcher fwfh_webview html]
- fluttertoast 8.2.5 [flutter flutter_web_plugins]
- get 4.6.6 [flutter]
- getwidget 4.0.0 [flutter]
- group_button 5.3.4 [flutter]
- html_to_pdf_plus 1.0.5 [flutter]
- http 1.2.1 [async http_parser meta web]
- image_picker 1.1.1 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos imag
e_picker_platform_interface image_picker_windows]
- loader_overlay 4.0.0 [flutter back_button_interceptor]
- omni_datetime_picker 1.1.0 [flutter]
- onesignal_flutter 5.1.6 [flutter]
- open_app_file 4.0.2 [flutter ffi]
- path_provider 2.1.3 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface 
path_provider_windows]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_ha
ndler_windows permission_handler_platform_interface]
- persistent_bottom_nav_bar 5.0.2 [flutter]
- scrollable_positioned_list 0.3.8 [flutter collection]
- selectable_autolink_text 2.6.0 [flutter]
- shared_preferences 2.2.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_prefer
ences_platform_interface shared_preferences_web shared_preferences_windows]
- simple_ripple_animation 0.0.9 [flutter hyper_lint]
- timelines 0.1.0 [flutter]
- url_launcher 6.2.6 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_int
erface url_launcher_web url_launcher_windows]

dev dependencies:
- flutter_lints 4.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boo
lean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel stri
ng_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.33 [collection firebase_core firebase_core_platform_interface flutter meta]
- ansicolor 2.0.2
- archive 3.4.9 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- audio_session 0.1.18 [flutter flutter_web_plugins rxdart meta]
- back_button_interceptor 7.0.2 [collection flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.1 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- charcode 1.3.1
- chewie 1.7.5 [cupertino_icons flutter provider video_player wakelock_plus]
- clock 1.1.1
- cloud_firestore_platform_interface 6.2.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.12.3 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web 
flutter flutter_web_plugins]
- collection 1.18.0
- community_charts_common 1.0.2 [intl collection meta vector_math]
- community_charts_flutter 1.0.2 [collection meta community_charts_common flutter]
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+1 [meta web]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dart_quill_delta 9.3.5 [collection diff_match_patch quiver]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.10.6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]       
- firebase_app_check_platform_interface 0.1.0+27 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]     
- firebase_app_check_web 0.1.2+5 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flut
ter flutter_web_plugins web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.33 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_inte
rface]
- firebase_storage_platform_interface 5.1.20 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interfac
e]
- firebase_storage_web 3.9.5 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flut
ter flutter_web_plugins http meta web]
- fixnum 1.1.0
- flex_seed_scheme 1.4.0 [collection flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_colorpicker 1.0.3 [flutter]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_
keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories] 
- flutter_local_notifications_platform_interface 7.1.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- flutter_widget_from_html_core 0.14.12 [csslib flutter html logging]
- fwfh_cached_network_image 0.14.2 [cached_network_image flutter flutter_cache_manager flutter_widget_from_html_core]
- fwfh_chewie 0.14.7 [chewie flutter flutter_widget_from_html_core video_player]
- fwfh_just_audio 0.14.3 [flutter flutter_widget_from_html_core just_audio]
- fwfh_svg 0.8.1 [flutter flutter_svg flutter_widget_from_html_core]
- fwfh_url_launcher 0.9.0+4 [flutter flutter_widget_from_html_core url_launcher]
- fwfh_webview 0.15.0 [flutter flutter_widget_from_html_core logging web webview_flutter webview_flutter_android webview_flutter_wk
webview]
- html 0.15.4 [csslib source_span]
- html2md 1.3.1 [html collection]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- hyper_lint 0.0.2 [flutter]
- image 4.1.7 [archive meta xml]
- image_picker_android 0.8.9+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.2 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]        
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]        
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]    
- intl 0.18.1 [clock meta path]
- irondash_engine_context 0.5.2 [flutter plugin_platform_interface]
- irondash_message_channel 0.6.0 [flutter ffi]
- js 0.6.7 [meta]
- just_audio 0.9.36 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta fl
utter]
- just_audio_platform_interface 4.2.2 [flutter plugin_platform_interface]
- just_audio_web 0.4.9 [just_audio_platform_interface flutter flutter_web_plugins]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- logging 1.2.0
- markdown 7.2.2 [args meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- nested 1.0.0 [flutter]
- octo_image 2.0.0 [flutter]
- package_info_plus 4.2.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 12.0.5 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.4 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.2.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- pixel_snap 0.1.5 [flutter]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.4 [collection convert js]
- provider 6.1.2 [collection flutter nested]
- quiver 3.2.1 [matcher]
- rxdart 0.27.7
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platfor
m_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.3.0 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_pla
tform_interface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.2 [flutter sqflite_common path]
- sqflite_common 2.5.3 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- super_clipboard 0.8.10 [flutter collection meta super_native_extensions]
- super_native_extensions 0.8.10 [flutter flutter_web_plugins meta ffi collection path uuid irondash_engine_context irondash_messag
e_channel device_info_plus pixel_snap web]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.2 [path]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- video_player 2.8.3 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.4.12 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.6 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.2.0 [flutter flutter_web_plugins video_player_platform_interface]
- vm_service 13.0.0
- wakelock_plus 1.1.4 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus js]
- wakelock_plus_platform_interface 1.1.0 [flutter plugin_platform_interface meta]
- web 0.5.1
- webview_flutter 4.7.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 3.15.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.12.0 [flutter path webview_flutter_platform_interface]
- win32 5.3.0 [ffi]
- win32_registry 1.1.2 [ffi win32]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]


```

</details>

### Additional context and comments

settings.gradle
```
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }
    settings.ext.flutterSdkPath = flutterSdkPath()

    includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.9.22" apply false
    id "com.google.gms.google-services" version "4.4.1" apply false
    id("com.google.firebase.crashlytics") version "2.9.9" apply false
}

include ":app"
```

build.gradle
```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

app/build.gradle
```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id "com.google.gms.google-services"
    id "com.google.firebase.crashlytics"
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "..."
    compileSdkVersion 34
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "..."
        minSdkVersion 23
        targetSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {

        release {
            multiDexKeepProguard file('multidex-config.pro')
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation(platform("com.google.firebase:firebase-bom:33.0.0"))
    implementation("com.onesignal:OneSignal:5.1.10")
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation("com.google.firebase:firebase-crashlytics")
    implementation("com.google.firebase:firebase-analytics")
    implementation("com.google.firebase:firebase-appcheck-playintegrity")
}
```
