### ISSUE TITLE
[FIIREBASE_AUTH] Unable to establish connection on channel.

### ISSUE THREAD

**Issue by Anderzzon** [firebase/flutterfire#12791]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android

### Description

I'm trying to sign in to Firebase Auth with an ID token like this:
```
final credentials = OAuthProvider(providerID).credential(idToken: idToken);
await FirebaseAuth.instance.signInWithCredential(credentials);
```
It works fine on iOS but on Android I get this error:
I/flutter (28425): [error] Error signing in with Firebase: [firebase_auth/channel-error] Unable to establish connection on channel.

I'm on 4.19.5 of the firebase_auth flutter version and Android version 11

### Reproducing the issue

final credentials = OAuthProvider("aProvider").credential(idToken: "idToken");
call await FirebaseAuth.instance.signInWithCredential(credentials);

The error occurs for both correct and incorrect provider and token Strings.

### Firebase Core version

2.31.0

### Flutter Version

3.19.6

### Relevant Log Output

```shell
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCredFailed to handle message
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCredjava.lang.NullPointerException
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at java.util.Objects.requireNonNull(Objects.java:220)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at io.flutter.plugins.firebase.auth.PigeonParser.getCredential(PigeonParser.java:221)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.signInWithCredential(FlutterFirebaseAuthPlugin.java:322)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthHostApi.lambda$setup$8(GeneratedAndroidFirebaseAuth.java:2820)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthHostApi.$r8$lambda$FsK5pIsoIQHj4oRphyytLYfCByU(GeneratedAndroidFirebaseAuth.java:0)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthHostApi$$ExternalSyntheticLambda20.onMessage(R8$$SyntheticClass:0)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$2j2MERcK825A5j1fv5sZ7xB2Iuo(DartMessenger.java:0)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at android.os.Handler.handleCallback(Handler.java:938)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at android.os.Handler.dispatchMessage(Handler.java:99)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at android.os.Looper.loop(Looper.java:246)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at android.app.ActivityThread.main(ActivityThread.java:8625)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at java.lang.reflect.Method.invoke(Native Method)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/BasicMessageChannel#dev.flutter.pigeon.firebase_auth_platform_interface.FirebaseAuthHostApi.signInWithCred at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
I/flutter (28425): [error] Error signing in with Firebase: [firebase_auth/channel-error] Unable to establish connection on channel.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

dependencies:
- agora_rtm 1.5.9 [flutter json_annotation]
- android_intent_plus 5.0.2 [flutter platform meta]
- another_flushbar 1.12.30 [flutter]
- app_links 4.0.1 [flutter plugin_platform_interface web flutter_web_plugins gtk]
- app_settings 5.1.1 [flutter plugin_platform_interface]
- arrow_path 3.1.0 [flutter]
- audio_service 0.18.13 [audio_service_platform_interface audio_service_web audio_session rxdart flutter_cache_manager clock js flutter flutter_web_plugins]
- audioplayers 6.0.0 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- auto_orientation 2.3.1 [flutter]
- badges 3.1.2 [flutter]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- confetti 0.7.0 [flutter vector_math]
- connecteo 2.2.1 [connectivity_plus flutter http rxdart]
- connectivity_plus 6.0.3 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- country_codes 2.2.0 [flutter]
- cupertino_icons 1.0.8
- cupertino_will_pop_scope 1.2.1 [flutter]
- customer_io 1.4.0 [flutter plugin_platform_interface]
- datadog_flutter_plugin 2.5.0 [flutter flutter_web_plugins js plugin_platform_interface json_annotation uuid meta]
- device_calendar 4.3.2 [flutter collection sprintf timezone]
- device_info_plus 9.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- dots_indicator 3.0.0 [flutter]
- ensure_visible_when_focused 1.2.0 [flutter]
- expand_tap_area 1.1.1 [flutter]
- external_app_launcher 3.1.0 [flutter]
- firebase_analytics 10.10.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.19.5 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.31.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.5.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.5.5 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 14.9.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- fl_chart 0.68.0 [equatable flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_animate 4.5.0 [flutter flutter_shaders]
- flutter_app_badger 1.5.0 [flutter]
- flutter_cache_manager 3.3.2 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_html 3.0.0-beta.2 [html csslib collection list_counter flutter]
- flutter_inappwebview 6.0.0 [flutter flutter_inappwebview_platform_interface flutter_inappwebview_android flutter_inappwebview_ios flutter_inappwebview_macos flutter_inappwebview_web]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_local_notifications 16.3.3 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_markdown 0.7.1 [flutter markdown meta path]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_secure_storage 9.2.1 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_segment 3.13.1 [flutter flutter_web_plugins meta]
- flutter_svg 2.0.9 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_switch 0.3.2 [flutter]
- flutter_widget_from_html 0.15.0 [flutter flutter_widget_from_html_core fwfh_cached_network_image fwfh_chewie fwfh_just_audio fwfh_svg fwfh_url_launcher fwfh_webview html]
- get 4.6.6 [flutter]
- get_ip_address 0.0.7 [http]
- get_storage 2.1.1 [flutter get path_provider]
- html_character_entities 1.0.0+1
- http 1.2.1 [async http_parser meta web]
- image_size_getter 2.1.3 [collection hashcodes]
- intercom_flutter 9.0.4 [flutter flutter_web_plugins intercom_flutter_platform_interface intercom_flutter_web]
- interval_time_picker 2.0.0+5 [flutter]
- intl 0.18.1 [clock meta path]
- just_audio 0.9.37 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- launch_review 3.0.1 [flutter]
- lottie 3.1.1 [archive flutter http path vector_math]
- mailto 2.0.0
- markdown_editable_textinput 2.1.0 [flutter effective_dart expandable]
- material_symbols_icons 4.2741.0 [flutter]
- modal_bottom_sheet 3.0.0 [flutter]
- numberpicker 2.1.2 [flutter infinite_listview]
- package_info_plus 4.2.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- percent_indicator 4.2.3 [flutter]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- qr_flutter 4.1.0 [flutter qr]
- quill_html_editor 2.2.8 [flutter flutter_web_plugins file_picker http path pointer_interceptor uuid webview_flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- retry 3.1.2
- sanitize_html 2.1.0 [html meta]
- shared_preferences 2.2.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 3.0.0 [flutter]
- sleek_circular_slider 2.0.1 [flutter]
- step_progress_indicator 1.0.2 [flutter]
- syncfusion_flutter_charts 24.2.9 [flutter intl vector_math syncfusion_flutter_core]
- universal_io 2.2.2 [collection meta typed_data]
- upgrader 8.4.0 [flutter device_info_plus html http os_detect package_info_plus shared_preferences url_launcher version xml]
- url_launcher 6.2.6 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- vibration 1.8.4 [flutter device_info_plus]
- video_player 2.8.6 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- wakelock_plus 1.2.1 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus web]
- webview_flutter 4.4.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- mockito 5.4.4 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- path_provider 2.1.3 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.33 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.5.1 [crypto path]
- args 2.5.0
- async 2.11.0 [collection meta]
- audio_service_platform_interface 0.1.1 [flutter plugin_platform_interface meta]
- audio_service_web 0.1.2 [audio_service_platform_interface rxdart js flutter flutter_web_plugins]
- audio_session 0.1.19 [flutter flutter_web_plugins rxdart meta]
- audioplayers_android 5.0.0 [audioplayers_platform_interface flutter]
- audioplayers_darwin 6.0.0 [audioplayers_platform_interface flutter]
- audioplayers_linux 4.0.0 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 7.0.0 [collection flutter meta plugin_platform_interface]
- audioplayers_web 5.0.0 [audioplayers_platform_interface flutter flutter_web_plugins web]
- audioplayers_windows 4.0.0 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.2.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- chewie 1.8.0 [cupertino_icons flutter provider video_player wakelock_plus]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- connectivity_plus_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- csslib 0.17.3 [source_span]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- effective_dart 1.3.2
- equatable 2.0.5 [collection meta]
- expandable 5.0.1 [flutter]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- file_picker 6.2.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_analytics_platform_interface 3.10.6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.7+5 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_auth_platform_interface 7.2.6 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.11.5 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.33 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+33 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.35 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.8.5 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- fixnum 1.1.0
- flutter_inappwebview_android 1.0.13 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_internal_annotations 1.1.1
- flutter_inappwebview_ios 1.0.13 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_macos 1.0.11 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_platform_interface 1.0.10 [flutter flutter_inappwebview_internal_annotations plugin_platform_interface]
- flutter_inappwebview_web 1.0.8 [flutter flutter_web_plugins js flutter_inappwebview_platform_interface]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.1.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.19 [flutter]
- flutter_secure_storage_linux 1.2.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.1.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.1.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.2.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.1.2 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_shaders 0.1.2 [flutter vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- flutter_widget_from_html_core 0.14.12 [csslib flutter html logging]
- fwfh_cached_network_image 0.14.2 [cached_network_image flutter flutter_cache_manager flutter_widget_from_html_core]
- fwfh_chewie 0.14.7 [chewie flutter flutter_widget_from_html_core video_player]
- fwfh_just_audio 0.14.3 [flutter flutter_widget_from_html_core just_audio]
- fwfh_svg 0.8.1 [flutter flutter_svg flutter_widget_from_html_core]
- fwfh_url_launcher 0.9.0+4 [flutter flutter_widget_from_html_core url_launcher]
- fwfh_webview 0.15.0 [flutter flutter_widget_from_html_core logging web webview_flutter webview_flutter_android webview_flutter_wkwebview]
- glob 2.1.2 [async collection file path string_scanner]
- gtk 2.1.0 [ffi flutter meta]
- hashcodes 2.0.0
- html 0.15.4 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- infinite_listview 1.1.0 [flutter]
- intercom_flutter_platform_interface 2.0.0 [flutter plugin_platform_interface]
- intercom_flutter_web 1.1.1 [flutter flutter_web_plugins intercom_flutter_platform_interface uuid web]
- js 0.6.7 [meta]
- json_annotation 4.9.0 [meta]
- just_audio_platform_interface 4.2.2 [flutter plugin_platform_interface]
- just_audio_web 0.4.9 [just_audio_platform_interface flutter flutter_web_plugins]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- list_counter 1.0.2
- logging 1.2.0
- markdown 7.2.2 [args meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.0.0 [flutter]
- os_detect 2.0.1
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.4 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 12.0.6 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.4 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.2.1 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointer_interceptor 0.10.1+1 [flutter flutter_web_plugins pointer_interceptor_ios pointer_interceptor_platform_interface pointer_interceptor_web]
- pointer_interceptor_ios 0.10.0+2 [flutter plugin_platform_interface pointer_interceptor_platform_interface]
- pointer_interceptor_platform_interface 0.10.0+1 [flutter plugin_platform_interface]
- pointer_interceptor_web 0.10.2 [flutter flutter_web_plugins plugin_platform_interface pointer_interceptor_platform_interface web]
- provider 6.1.2 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- qr 3.0.1 [meta]
- rxdart 0.27.7
- shared_preferences_android 2.2.2 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.4.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.3.0 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.3+1 [flutter sqflite_common path]
- sqflite_common 2.5.4 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- syncfusion_flutter_core 24.2.9 [vector_math flutter]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.3 [path]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.4.0 [crypto sprintf meta fixnum]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- version 3.0.2
- video_player_android 2.4.14 [flutter video_player_platform_interface]
- video_player_avfoundation 2.6.1 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.3.0 [flutter flutter_web_plugins video_player_platform_interface web]
- vm_service 13.0.0
- wakelock_plus_platform_interface 1.2.1 [flutter plugin_platform_interface meta]
- watcher 1.1.0 [async path]
- web 0.5.1
- webview_flutter_android 3.16.1 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.13.1 [flutter path webview_flutter_platform_interface]
- win32 5.5.0 [ffi]
- win32_registry 1.1.3 [ffi win32]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>
