### ISSUE TITLE
[cloud_firestore]: MissingPluginException in any method of firebase_firestore

### ISSUE THREAD

**Issue by geovaniprodata** [firebase/flutterfire#12835]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

cloud_firestore/Database

### Which platforms are affected?

Windows

### Description

For any kind of action using Firestore Instance, trigger this error, what stops me from doing anything. Even test with emulator.

`await controller.f.collection('AppsGenerated').get()`

`controller` => `GetxController`
`f` => `FirebaseFirestore.instance`

Using `get or snapshots()` neither one works.

Just keeping trigger 

### Reproducing the issue

Using `get() ` or any kind of async action with FirebaseFirestore.instance

### Firebase Core version

2.17.0

### Flutter Version

3.22.1

### Relevant Log Output

```shell
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method Query#get on channel plugins.flutter.io/firebase_firestore))
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.4.1
Flutter SDK 3.22.1
app_generator 0.1.0

dependencies:
- awesome_dialog 3.2.1 [flutter rive]
- basic_utils 5.7.0 [http logging json_annotation pointycastle]
- cloud_firestore 4.9.3 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_firestore_odm 1.0.0-dev.69 [cloud_firestore flutter json_annotation meta]       
- contextmenu 3.0.0 [flutter animations after_layout]
- filepicker_windows 2.1.3 [ffi win32]
- firebase_core 2.17.0 [firebase_core_platform_interface firebase_core_web flutter meta]- firebase_core_desktop 1.0.2 [firebase_core_dart firebase_core_platform_interface flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.5 [bloc flutter provider]
- flutter_dotenv 5.1.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_mobx 2.2.1+1 [flutter mobx provider]
- flutter_screenutil 5.9.1 [flutter]
- flutter_smart_dialog 4.9.7+6 [flutter]
- font_awesome_flutter 10.7.0 [flutter]
- gap 3.0.1 [flutter]
- get 4.6.6 [flutter]
- get_it 7.7.0 [async collection meta]
- go_router 14.1.3 [collection flutter flutter_web_plugins logging meta]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- hive 2.2.3 [meta crypto]
- json_annotation 4.9.0 [meta]
- mobx 2.3.3+2 [meta collection]
- number_selection 1.0.0 [flutter]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32] 
- readmore 3.0.0 [flutter]
- rive 0.13.5 [collection flutter flutter_web_plugins http meta plugin_platform_interface rive_common]
- roundcheckbox 2.0.5 [flutter]
- rxdart 0.27.7
- sembast 3.7.1 [meta path synchronized]
- shimmer 3.0.0 [flutter]
- sidebarx 0.17.1 [flutter]
- text_mask 1.0.4 [flutter]
- uuid 4.4.0 [crypto sprintf meta fixnum]
- window_manager 0.3.9 [flutter path screen_retriever]

dev dependencies:
- build_runner 2.4.10 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver 
pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- cloud_firestore_odm_generator 1.0.0-dev.69 [analyzer build build_config cloud_firestore_odm collection freezed_annotation graphs json_annotation meta recase source_gen]      
- flutter_lints 4.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- go_router_builder 2.7.0 [analyzer async build build_config collection meta path source_gen source_helper]
- json_serializable 6.8.0 [analyzer async build build_config collection json_annotation 
meta path pub_semver pubspec_parse source_gen source_helper]
- mobx_codegen 2.6.1 [analyzer build build_resolvers meta mobx path source_gen]

transitive dependencies:
- _fe_analyzer_shared 61.0.0 [meta]
- _flutterfire_internals 1.3.7 [collection firebase_core firebase_core_platform_interface flutter meta]
- after_layout 1.2.0 [flutter]
- analyzer 5.13.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- animations 2.0.11 [flutter]
- args 2.5.0
- async 2.11.0 [collection meta]
- bloc 8.1.4 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]     
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.2 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 5.16.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.7.2 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- dart_style 2.3.2 [analyzer args path pub_semver source_span]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- firebase_core_dart 1.0.1 [collection meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.0 [firebase_core_platform_interface flutter flutter_web_plugins 
js meta]
- fixnum 1.1.0
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- graphs 2.2.0 [collection]
- http 1.2.1 [async http_parser meta web]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.19.0 [clock meta path]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- leak_tracker 10.0.4 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.3 [flutter leak_tracker leak_tracker_testing matcher 
meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.12.0
- mime 1.0.5
- nested 1.0.0 [flutter]
- package_config 2.1.0 [path]
- path 1.9.0
- path_provider 2.1.3 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.4 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]   
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.9.1 [collection convert js]
- pool 1.5.1 [async stack_trace]
- provider 6.1.2 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- recase 4.1.0
- rive_common 0.4.9 [collection ffi flutter flutter_web_plugins graphs http meta plugin_platform_interface web]
- screen_retriever 0.1.9 [flutter]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 2.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.7.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- vm_service 14.2.1
- watcher 1.1.0 [async path]
- web 0.5.1
- web_socket 0.1.4 [web]
- web_socket_channel 3.0.0 [async crypto stream_channel web web_socket]
- win32 5.5.1 [ffi]
- xdg_directories 1.0.4 [meta path]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

### Tried 

- flutter clean
- flutter pub get
- flutter pub cache repair
- flutter pub cache clean
- change the versions of dependencies
- downgrade
