### ISSUE TITLE
[firebase_cpp_sdk_windows]: CMake Deprecation Warning

### ISSUE THREAD

**Issue by stephane-archer** [firebase/flutterfire#12849]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

Windows

### Description

build an app on windows
```
CMake Deprecation Warning at C:/Users/steph/Programs/lut_viewer/build/windows/x64/extracted/firebase_cpp_sdk_windows/CMakeLists.txt:17 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

### Reproducing the issue

up

### Firebase Core version

2.27.0

### Flutter Version

3.19.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by stephane-archer** [comment]
@Lyokone thanks for mentioning the right place for this issue

**Comment by bennajah** [comment]
same issue here using

`Flutter 3.27.2`

and firebase packages

```yaml
cloud_firestore: ^5.6.1
firebase_analytics: ^11.4.0
firebase_auth: ^5.4.0
firebase_core: ^3.10.0
firebase_crashlytics: ^4.3.0
firebase_performance: ^0.10.1
firebase_storage: ^12.4.0
```


![Image](https://github.com/user-attachments/assets/67b65b71-443d-4f9e-9e79-6b3106b27e72)
