### ISSUE TITLE
[firebase_crashlytics]: iOS Crashlytics failing with "Crashlytics skipped rotating the Install ID during urgent mode because it is run on the main thread, which can't succeed"

### ISSUE THREAD

**Issue by roblframpton** [firebase/flutterfire#12864]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

iOS

### Description

~Crashlytics is failing to report errors on my iOS app~.  There is an error message in the console when it tries:

```
Crashlytics skipped rotating the Install ID during urgent mode because it is run on the main thread, which can't succeed. This can happen if the app crashed the last run and Crashlytics is uploading urgently.
```

Also, when the app starts, I have this error which may or may not be related (although I have reason to believe this is a separate issue):

```
[Firebase/Core][I-COR000005] No app has been configured yet.
```

Crashlytics DOES work on Android.

### Reproducing the issue

This occurred in my existing project, so I tried creating a fresh project and following the steps to install Crashlytics, getting the same result.  Here's what I did:

```
# First, create project
mkdir fresh_project
flutter create fresh_project
cd fresh_project

# Now add Firebase
flutterfire configure
flutter pub add firebase_core
# I then updated main.dart to initialise firebase, shown below
# Also I opened the project in XCode to set my Development Team correctly
flutter run # Quick test - app starts fine

# Now add Crashlytics
flutter pub add firebase_crashlytics
flutter pub add firebase_analytics
flutterfire configure
# Updated main.dart again  to initialize crashlytics- see final result below
# Also updated main.dart to trigger text exception on button blick
flutter run

# Press the button, a crash occurs, the message appears in debug log, no error in Crashlytics.
```

And here is what my `main.dart` looked like.  This is just the default Flutter example, except it initializes Crashlytics, and it triggers an exception on button press.

<details>
  <summary>main.dart</summary>

```dart

import 'dart:ui';


import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'firebase_options.dart';


Future<void> main() async {
 WidgetsFlutterBinding.ensureInitialized();
 await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
 );
 FlutterError.onError = (errorDetails) {
   FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
 };
 // Pass all uncaught asynchronous errors that aren't handled by the Flutter framework to Crashlytics
 PlatformDispatcher.instance.onError = (error, stack) {
   FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
   return true;
 };
 runApp(const MyApp());
}


class MyApp extends StatelessWidget {
 const MyApp({super.key});


 // This widget is the root of your application.
 @override
 Widget build(BuildContext context) {
   return MaterialApp(
     title: 'Flutter Demo',
     theme: ThemeData(
       // This is the theme of your application.
       //
       // TRY THIS: Try running your application with "flutter run". You'll see
       // the application has a purple toolbar. Then, without quitting the app,
       // try changing the seedColor in the colorScheme below to Colors.green
       // and then invoke "hot reload" (save your changes or press the "hot
       // reload" button in a Flutter-supported IDE, or press "r" if you used
       // the command line to start the app).
       //
       // Notice that the counter didn't reset back to zero; the application
       // state is not lost during the reload. To reset the state, use hot
       // restart instead.
       //
       // This works for code too, not just values: Most code changes can be
       // tested with just a hot reload.
       colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
       useMaterial3: true,
     ),
     home: const MyHomePage(title: 'Flutter Demo Home Page'),
   );
 }
}


class MyHomePage extends StatefulWidget {
 const MyHomePage({super.key, required this.title});


 // This widget is the home page of your application. It is stateful, meaning
 // that it has a State object (defined below) that contains fields that affect
 // how it looks.


 // This class is the configuration for the state. It holds the values (in this
 // case the title) provided by the parent (in this case the App widget) and
 // used by the build method of the State. Fields in a Widget subclass are
 // always marked "final".


 final String title;


 @override
 State<MyHomePage> createState() => _MyHomePageState();
}


class _MyHomePageState extends State<MyHomePage> {
 int _counter = 0;


 void _incrementCounter() {
   setState(() {
     // This call to setState tells the Flutter framework that something has
     // changed in this State, which causes it to rerun the build method below
     // so that the display can reflect the updated values. If we changed
     // _counter without calling setState(), then the build method would not be
     // called again, and so nothing would appear to happen.
     _counter++;
   });
 }


 @override
 Widget build(BuildContext context) {
   // This method is rerun every time setState is called, for instance as done
   // by the _incrementCounter method above.
   //
   // The Flutter framework has been optimized to make rerunning build methods
   // fast, so that you can just rebuild anything that needs updating rather
   // than having to individually change instances of widgets.
   return Scaffold(
     appBar: AppBar(
       // TRY THIS: Try changing the color here to a specific color (to
       // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
       // change color while the other colors stay the same.
       backgroundColor: Theme.of(context).colorScheme.inversePrimary,
       // Here we take the value from the MyHomePage object that was created by
       // the App.build method, and use it to set our appbar title.
       title: Text(widget.title),
     ),
     body: Center(
       // Center is a layout widget. It takes a single child and positions it
       // in the middle of the parent.
       child: Column(
         // Column is also a layout widget. It takes a list of children and
         // arranges them vertically. By default, it sizes itself to fit its
         // children horizontally, and tries to be as tall as its parent.
         //
         // Column has various properties to control how it sizes itself and
         // how it positions its children. Here we use mainAxisAlignment to
         // center the children vertically; the main axis here is the vertical
         // axis because Columns are vertical (the cross axis would be
         // horizontal).
         //
         // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
         // action in the IDE, or press "p" in the console), to see the
         // wireframe for each widget.
         mainAxisAlignment: MainAxisAlignment.center,
         children: <Widget>[
           const Text(
             'You have pushed the button this many times:',
           ),
           Text(
             '$_counter',
             style: Theme.of(context).textTheme.headlineMedium,
           ),
         ],
       ),
     ),
     floatingActionButton: FloatingActionButton(
       onPressed: () {
         throw Exception("Crashlytics test");
       },
       tooltip: 'Increment',
       child: const Icon(Icons.add),
     ), // This trailing comma makes auto-formatting nicer for build methods.
   );
 }
}
```

</details>

### Firebase Core version

2.32.0

### Flutter Version

3.22.1

### Relevant Log Output

```shell
(lldb) 2024-05-31 15:47:40.517057+0100 Runner[3776:171311] 10.25.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
[Firebase/Crashlytics] Version 10.25.0
10.25.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.10.25.0 started
10.25.0 - [FirebaseAnalytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
10.25.0 - [FirebaseAnalytics][I-ACS044002] The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
10.25.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
Installing and launching...                                        30.4s
10.25.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
10.25.0 - [FirebaseAnalytics][I-ACS023220] Analytics screen reporting is enabled. Call Analytics.logEvent(AnalyticsEventScreenView, parameters: [...]) to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
Syncing files to device X's iPhone...                       404ms


Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).


A Dart VM Service on X’s iPhone is available at: http://127.0.0.1:52251/ZJC5Qhf9Dv8=/
The Flutter DevTools debugger and profiler on X’s iPhone is available at:
http://127.0.0.1:9102?uri=http://127.0.0.1:52251/ZJC5Qhf9Dv8=/


══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following _Exception was thrown while handling a gesture:
Exception: Crashlytics test


When the exception was thrown, this was the stack:
#0      _MyHomePageState.build.<anonymous closure> (package:fresh_project/main.dart:137:11)
#1      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171:21)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#5      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279:7)
#6      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
#7      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:499:20)
#8      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#9      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
#10     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#11     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#14     _invoke1 (dart:ui/hooks.dart:328:13)
#15     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#16     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)


Handler: "onTap"
Recognizer:
  TapGestureRecognizer#9e32d
════════════════════════════════════════════════════════════════════════════════════════════════════


10.25.0 - [FirebaseCrashlytics][I-CLS000000] Crashlytics skipped rotating the Install ID during urgent mode because it is run on the main thread, which can't succeed. This can happen if the app crashed the last run and Crashlytics is uploading urgently.
Application finished.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.4.1
Flutter SDK 3.22.1
fresh_project 1.0.0+1


dependencies:
- cupertino_icons 1.0.8
- firebase_analytics 10.10.7 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.32.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.5.7 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]


dev dependencies:
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]


transitive dependencies:
- _flutterfire_internals 1.3.35 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_analytics_platform_interface 3.10.8 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.7+7 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.35 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.4 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.3 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.12.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.2.1
- web 0.5.1


```

</details>

### Additional context and comments

I tried my physical iPhone SE (2017) and the iPhone 15 simulator, both with the same result.
