### ISSUE TITLE
[firebase_crashlytics]: Fatal Exception: FlutterError (null)._startMicrotaskLoop (dart:async)

### ISSUE THREAD

**Issue by rairongf** [firebase/flutterfire#12906]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

iOS

### Description

The expectation was that no errors would occur, but there have been 3,885 failure events since the release of the version.

### Reproducing the issue

It was not possible to obtain an example to replicate the problem.

### Firebase Core version

^2.30.1

### Flutter Version

3.19.6

### Relevant Log Output

```shell
Fatal Exception: FlutterError
0  ???                            0x0 (null)._startMicrotaskLoop (dart:async)

Crashed: com.apple.main-thread
0  FirebaseCrashlytics            0x21c10 FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x21ff0 FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x18e74 FIRCLSHandler + 48
3  FirebaseCrashlytics            0x131b0 FIRCLSExceptionRecordOnDemand + 1332
4  FirebaseCrashlytics            0x12bec FIRCLSExceptionRecordOnDemandModel + 228
5  FirebaseCrashlytics            0x213dc -[FIRCLSOnDemandModel recordOnDemandExceptionWithModel:] + 68
6  FirebaseCrashlytics            0x20e3c -[FIRCLSOnDemandModel recordOnDemandExceptionIfQuota:withDataCollectionEnabled:usingExistingReportManager:] + 164
7  FirebaseCrashlytics            0x2f608 -[FIRCrashlytics recordOnDemandExceptionModel:] + 140
8  Runner                         0x5d2524 -[FLTFirebaseCrashlyticsPlugin recordError:withMethodCallResult:] + 177 (FLTFirebaseCrashlyticsPlugin.m:177)
9  Runner                         0x5d1de0 -[FLTFirebaseCrashlyticsPlugin handleMethodCall:result:] + 101 (FLTFirebaseCrashlyticsPlugin.m:101)
10 Flutter                        0x5c05f0 InternalFlutterGpu_Texture_AsImage + 6316
11 Flutter                        0x43d0c (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
12 libdispatch.dylib              0x63094 <redacted> + 24
13 libdispatch.dylib              0x64094 <redacted> + 16
14 libdispatch.dylib              0x10d44 <redacted> + 928
15 libdispatch.dylib              0x10994 <redacted> + 36
16 CoreFoundation                 0x4e014 <redacted> + 12
17 CoreFoundation                 0xb4f8 <redacted> + 2544
18 CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
19 GraphicsServices               0x1988 GSEventRunModal + 160
20 UIKitCore                      0x4e5a88 <redacted> + 1080
21 UIKitCore                      0x27ef78 UIApplicationMain + 336
22 Runner                         0x8750 main + 7 (AppDelegate.swift:7)
23 ???                            0x1032d84d0 (Ausente)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6c88 <redacted> + 368
3  CoreFoundation                 0xaf90 <redacted> + 1160
4  CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
5  Foundation                     0x17eac <redacted> + 232
6  Foundation                     0x56fd0 <redacted> + 88
7  UIKitCore                      0x464ef4 <redacted> + 512
8  Foundation                     0x64bdc <redacted> + 792
9  libsystem_pthread.dylib        0x3338 _pthread_start + 116
10 libsystem_pthread.dylib        0x1938 thread_start + 8

io.flutter.1.ui
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6c88 <redacted> + 368
3  CoreFoundation                 0xaf90 <redacted> + 1160
4  CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
5  Flutter                        0x2ec7a8 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
6  Flutter                        0x2ebe20 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
7  libsystem_pthread.dylib        0x3338 _pthread_start + 116
8  libsystem_pthread.dylib        0x1938 thread_start + 8

io.flutter.1.raster
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6c88 <redacted> + 368
3  CoreFoundation                 0xaf90 <redacted> + 1160
4  CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
5  Flutter                        0x2ec7a8 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
6  Flutter                        0x2ebe20 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
7  libsystem_pthread.dylib        0x3338 _pthread_start + 116
8  libsystem_pthread.dylib        0x1938 thread_start + 8

io.flutter.1.io
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6c88 <redacted> + 368
3  CoreFoundation                 0xaf90 <redacted> + 1160
4  CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
5  Flutter                        0x2ec7a8 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
6  Flutter                        0x2ebe20 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
7  libsystem_pthread.dylib        0x3338 _pthread_start + 116
8  libsystem_pthread.dylib        0x1938 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bc4 <redacted> + 1240
2  Flutter                        0x58ca4 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
3  Flutter                        0x2e60e4 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
4  libsystem_pthread.dylib        0x3338 _pthread_start + 116
5  libsystem_pthread.dylib        0x1938 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bc4 <redacted> + 1240
2  Flutter                        0x58ca4 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
3  Flutter                        0x2e60e4 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
4  libsystem_pthread.dylib        0x3338 _pthread_start + 116
5  libsystem_pthread.dylib        0x1938 thread_start + 8

dart:io EventHandler
0  libsystem_kernel.dylib         0x2294 kevent + 8
1  Flutter                        0x57a3e8 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
2  Flutter                        0x5a7f48 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
3  libsystem_pthread.dylib        0x3338 _pthread_start + 116
4  libsystem_pthread.dylib        0x1938 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bc4 <redacted> + 1240
2  Flutter                        0x58ca4 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
3  Flutter                        0x2e60e4 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
4  libsystem_pthread.dylib        0x3338 _pthread_start + 116
5  libsystem_pthread.dylib        0x1938 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bc4 <redacted> + 1240
2  Flutter                        0x58ca4 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
3  Flutter                        0x2e60e4 (Ausente UUID 4c4c44bd55553144a1714204dc08bdb2)
4  libsystem_pthread.dylib        0x3338 _pthread_start + 116
5  libsystem_pthread.dylib        0x1938 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  FirebaseCrashlytics            0x1b5bc FIRCLSMachExceptionServer + 104
3  libsystem_pthread.dylib        0x3338 _pthread_start + 116
4  libsystem_pthread.dylib        0x1938 thread_start + 8

com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6c88 <redacted> + 368
3  CoreFoundation                 0xaf90 <redacted> + 1160
4  CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
5  CoreFoundation                 0x99320 CFRunLoopRun + 60
6  CoreMotion                     0x12ab0 CLMotionActivity::isTypeInVehicle(CLMotionActivity::Type) + 21528
7  libsystem_pthread.dylib        0x3338 _pthread_start + 116
8  libsystem_pthread.dylib        0x1938 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6c88 <redacted> + 368
3  CoreFoundation                 0xaf90 <redacted> + 1160
4  CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
5  CFNetwork                      0x246b9c _CFURLStorageSessionDisableCache + 50420
6  Foundation                     0x64bdc <redacted> + 792
7  libsystem_pthread.dylib        0x3338 _pthread_start + 116
8  libsystem_pthread.dylib        0x1938 thread_start + 8

AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6c88 <redacted> + 368
3  CoreFoundation                 0xaf90 <redacted> + 1160
4  CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
5  AudioSession                   0x6478 <redacted> + 156
6  AudioSession                   0xf7c8 <redacted> + 88
7  libsystem_pthread.dylib        0x3338 _pthread_start + 116
8  libsystem_pthread.dylib        0x1938 thread_start + 8

com.google.Maps.LabelingBehavior
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6c88 <redacted> + 368
3  CoreFoundation                 0xaf90 <redacted> + 1160
4  CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
5  Foundation                     0x17eac <redacted> + 232
6  Runner                         0x46b75c -[GMSx_GTMSimpleWorkerThread main] + 44620
7  Foundation                     0x64bdc <redacted> + 792
8  libsystem_pthread.dylib        0x3338 _pthread_start + 116
9  libsystem_pthread.dylib        0x1938 thread_start + 8

com.google.firebase.crashlytics.startup
0  CoreFoundation                 0x24830 __CFStringHash + 120
1  CoreFoundation                 0x5ffc0 <redacted> + 96
2  FirebaseCrashlytics            0x299c8 __47-[FIRCLSSymbolResolver loadedBinaryImageForPC:]_block_invoke + 44
3  CoreFoundation                 0x4fdc8 <redacted> + 16
4  CoreFoundation                 0xac380 <redacted> + 444
5  FirebaseCrashlytics            0x29964 -[FIRCLSSymbolResolver loadedBinaryImageForPC:] + 80
6  FirebaseCrashlytics            0x29b30 -[FIRCLSSymbolResolver updateStackFrame:] + 80
7  FirebaseCrashlytics            0x294d0 __36-[FIRCLSSymbolicationOperation main]_block_invoke + 56
8  FirebaseCrashlytics            0x29de4 -[FIRCLSThreadArrayOperation enumerateFramesWithBlock:] + 264
9  FirebaseCrashlytics            0x2948c -[FIRCLSSymbolicationOperation main] + 68
10 Foundation                     0x39a8c <redacted> + 20
11 Foundation                     0x49fcc <redacted> + 764
12 FirebaseCrashlytics            0x22f00 -[FIRCLSProcessReportOperation symbolicateFile:withResolver:] + 236
13 FirebaseCrashlytics            0x23070 __36-[FIRCLSProcessReportOperation main]_block_invoke + 68
14 FirebaseCrashlytics            0x1a5cc -[FIRCLSInternalReport enumerateSymbolicatableFilesInContent:] + 200
15 FirebaseCrashlytics            0x23010 -[FIRCLSProcessReportOperation main] + 172
16 Foundation                     0x39a8c <redacted> + 20
17 Foundation                     0x49fcc <redacted> + 764
18 FirebaseCrashlytics            0x261a0 __91-[FIRCLSReportUploader prepareAndSubmitReport:dataCollectionToken:asUrgent:withProcessing:]_block_invoke + 460
19 FirebaseCrashlytics            0x9228 FIRCLSApplicationActivity + 72
20 FirebaseCrashlytics            0x25f8c -[FIRCLSReportUploader prepareAndSubmitReport:dataCollectionToken:asUrgent:withProcessing:] + 172
21 FirebaseCrashlytics            0x14cdc -[FIRCLSExistingReportManager processExistingActiveReportPath:dataCollectionToken:asUrgent:] + 152
22 libdispatch.dylib              0x63094 <redacted> + 24
23 libdispatch.dylib              0x64094 <redacted> + 16
24 libdispatch.dylib              0xa73c <redacted> + 644
25 libdispatch.dylib              0xb1f4 <redacted> + 408
26 libdispatch.dylib              0x14ec8 <redacted> + 632
27 libsystem_pthread.dylib        0x1e00 _pthread_wqthread + 284
28 libsystem_pthread.dylib        0x192c start_wqthread + 8

com.google.firebase.crashlytics.on.demand
0  libsystem_kernel.dylib         0xfd0 __semwait_signal + 8
1  libsystem_c.dylib              0x4a40 nanosleep + 216
2  libsystem_c.dylib              0x18710 sleep + 48
3  FirebaseCrashlytics            0x210d4 __107-[FIRCLSOnDemandModel recordOnDemandExceptionIfQuota:withDataCollectionEnabled:usingExistingReportManager:]_block_invoke + 340
4  Foundation                     0x4e39c <redacted> + 16
5  Foundation                     0x5fa70 <redacted> + 100
6  Foundation                     0x39a8c <redacted> + 20
7  Foundation                     0x49fcc <redacted> + 764
8  Foundation                     0x4d498 <redacted> + 20
9  Foundation                     0x5accc <redacted> + 180
10 libdispatch.dylib              0x11544 <redacted> + 104
11 libdispatch.dylib              0x64094 <redacted> + 16
12 libdispatch.dylib              0xa73c <redacted> + 644
13 libdispatch.dylib              0xb1f4 <redacted> + 408
14 libdispatch.dylib              0x14ec8 <redacted> + 632
15 libsystem_pthread.dylib        0x1e00 _pthread_wqthread + 284
16 libsystem_pthread.dylib        0x192c start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x1924 <redacted> + 270

Thread
0  libsystem_pthread.dylib        0x1924 <redacted> + 270

DartWorker
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bf0 <redacted> + 1284
2  Flutter                        0x6765ec InternalFlutterGpu_Texture_AsImage + 751784
3  Flutter                        0x6b1404 InternalFlutterGpu_Texture_AsImage + 992960
4  Flutter                        0x675fb8 InternalFlutterGpu_Texture_AsImage + 750196
5  libsystem_pthread.dylib        0x3338 _pthread_start + 116
6  libsystem_pthread.dylib        0x1938 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bf0 <redacted> + 1284
2  Flutter                        0x6765ec InternalFlutterGpu_Texture_AsImage + 751784
3  Flutter                        0x6b1404 InternalFlutterGpu_Texture_AsImage + 992960
4  Flutter                        0x675fb8 InternalFlutterGpu_Texture_AsImage + 750196
5  libsystem_pthread.dylib        0x3338 _pthread_start + 116
6  libsystem_pthread.dylib        0x1938 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bf0 <redacted> + 1284
2  Flutter                        0x6765ec InternalFlutterGpu_Texture_AsImage + 751784
3  Flutter                        0x6b1404 InternalFlutterGpu_Texture_AsImage + 992960
4  Flutter                        0x675fb8 InternalFlutterGpu_Texture_AsImage + 750196
5  libsystem_pthread.dylib        0x3338 _pthread_start + 116
6  libsystem_pthread.dylib        0x1938 thread_start + 8
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.3.4
Flutter SDK 3.19.6

dependencies:
- app_links 5.0.0 [flutter plugin_platform_interface web flutter_web_plugins gtk]
- asuka 2.2.1 [flutter]
- battery_plus 6.0.1 [flutter flutter_web_plugins battery_plus_platform_interface meta upower web]
- carousel_slider 4.2.1 [flutter]
- collection 1.18.0
- connectivity_plus 6.0.3 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- curved_navigation_bar 1.0.3 [flutter meta]
- dio 5.4.3+1 [async http_parser meta path]
- disable_battery_optimization 1.1.1 [flutter]
- dropdown_search 5.0.6 [flutter]
- equatable 2.0.5 [collection meta]
- firebase_analytics 10.10.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]   
- firebase_core 2.30.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.5.4 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.5.4 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_remote_config 4.4.4 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_background_geolocation 4.15.2 [flutter collection background_fetch]
- flutter_inappwebview 6.0.0 [flutter flutter_inappwebview_platform_interface flutter_inappwebview_android flutter_inappwebview_ios flutter_inappwebview_macos flutter_inappwebview_web]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_mobx 2.2.1+1 [flutter mobx provider]
- flutter_modular 6.3.3 [modular_core meta result_dart flutter]
- flutter_slidable 3.1.0 [flutter]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- font_awesome_flutter 10.7.0 [flutter]
- get 4.6.6 [flutter]
- google_maps_flutter 2.6.1 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- google_maps_flutter_android 2.8.0 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.6.0 [collection flutter plugin_platform_interface stream_transform]
- google_polyline_algorithm 3.1.0
- hive_flutter 1.1.0 [flutter hive path_provider path]
- image_cropper 5.0.1 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 1.1.1 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.18.1 [clock meta path]
- intl_phone_number_input 0.7.4 [flutter libphonenumber_plugin equatable collection]
- mobx 2.3.3+2 [meta collection]
- onesignal_flutter 5.1.6 [flutter]
- package_info_plus 8.0.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- pub_semver 2.1.4 [collection meta]
- screenshot 2.3.0 [flutter]
- sensors_plus 5.0.1 [flutter flutter_web_plugins sensors_plus_platform_interface]
- shimmer 3.0.0 [flutter]
- update_available 3.1.0+1 [flutter update_available_android update_available_ios update_available_platform_interface]
- url_launcher 6.2.6 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.4.0 [crypto sprintf meta fixnum]

dev dependencies:
- build_runner 2.4.9 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- change_app_package_name 1.1.0
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]   
- mobx_codegen 2.6.1 [analyzer build build_resolvers meta mobx path source_gen]
- mockito 5.4.4 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.32 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.5.0 [crypto path]
- args 2.5.0
- async 2.11.0 [collection meta]
- auto_injector 2.0.4 [meta uuid]
- background_fetch 1.3.4 [flutter]
- battery_plus_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]    
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+1 [meta web]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.10.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.7+4 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.16.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.32 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+32 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_platform_interface 1.4.32 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.6.4 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- fixnum 1.1.0
- flutter_inappwebview_android 1.0.13 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_internal_annotations 1.1.1
- flutter_inappwebview_ios 1.0.13 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_macos 1.0.11 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_platform_interface 1.0.10 [flutter flutter_inappwebview_internal_annotations plugin_platform_interface]
- flutter_inappwebview_web 1.0.8 [flutter flutter_web_plugins js flutter_inappwebview_platform_interface]
- flutter_plugin_android_lifecycle 2.0.19 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- google_maps 7.1.0 [js js_wrapping meta web]
- google_maps_flutter_ios 2.6.0 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_web 0.5.7 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform web]
- graphs 2.3.1 [collection]
- gtk 2.1.0 [ffi flutter meta]
- hive 2.2.3 [meta crypto]
- html 0.15.4 [csslib source_span]
- http 1.2.1 [async http_parser meta web]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.7 [archive meta xml]
- image_cropper_for_web 3.0.0 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 5.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.11 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.4 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.10+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- libphonenumber_platform_interface 0.4.2 [flutter plugin_platform_interface]
- libphonenumber_plugin 0.3.3 [flutter flutter_web_plugins libphonenumber_platform_interface libphonenumber_web]
- libphonenumber_web 0.3.2 [flutter flutter_web_plugins js libphonenumber_platform_interface]
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- modular_core 3.3.2 [auto_injector characters meta]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 3.0.0 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.3 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.4 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 12.0.6 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.4 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.2.1 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- provider 6.1.2 [collection flutter nested]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- result_dart 1.1.1 [meta]
- sanitize_html 2.1.0 [html meta]
- sensors_plus_platform_interface 1.2.0 [flutter logging meta plugin_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- update_available_android 3.1.0 [flutter update_available_platform_interface]
- update_available_ios 3.0.2 [flutter meta package_info_plus pub_semver update_available_platform_interface]
- update_available_platform_interface 4.0.1 [meta plugin_platform_interface]
- upower 0.7.0 [dbus]
- url_launcher_android 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 13.0.0
- watcher 1.1.0 [async path]
- web 0.5.1
- web_socket_channel 2.4.5 [async crypto stream_channel web]
- win32 5.5.0 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

### Additional context and comments

- Reports appeared after migration from Flutter 3.3.0 to 3.19.6;
- Only iOS is affected;
- 3,885 failure events since version release;
- 73% of the events occurred on iOS 16, 14% occurred on iOS 17 and 13% occurred on iOS 15;
- 92% of the events occurred while the application was running in the background;

The data above was collected from the Firebase Crashlytics console.
