### ISSUE TITLE
[firebase_app_check]: Flutter iOS module is not building when using firebase_app_check package

### ISSUE THREAD

**Issue by AriasBros** [firebase/flutterfire#12923]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

App Check

### Which platforms are affected?

iOS

### Description

I originally posted this issue in the Flutter project: https://github.com/flutter/flutter/issues/149833
Where I was invited to put here the issue.

The problem is that when you try to build or run a  Flutter module for iOS that includes the `firebase_app_check` package, the build is failing with the next error:

```
Lexical or Preprocessor Issue (Xcode): 'FLTAppCheckProviderFactory.h' file not found with include; use "quotes" instead
/some/path/.pub-cache/hosted/pub.dev/firebase_app_check-0.3.0/ios/Classes/FLTFirebaseAppCheckPlugin.h:10:8

Parse Issue (Xcode): Could not build module 'firebase_app_check'
/some/path/angled_error/.ios/Flutter/FlutterPluginRegistrant/Classes/GeneratedPluginRegistrant.m:9:8
```

Tested in Flutter 3.19.1 and 3.22.1. Failing in both.
Tested with Firebase App Check 0.2.2+7 and 0.3.0. Failing in both.

The error only happens in a Flutter module project. In a Flutter app project it works as expected.

### Reproducing the issue

Just follow these steps:

1. Create a new Flutter module: `flutter create --template module angled_error`
2. Install the package firebase_app_check: `flutter pub add firebase_app_check`
3. If installing the latest version of firebase_app_check (0.3.0), change the iOS deployment target to version 13.
4. Run or build the module for iOS: `flutter run` or `flutter build ios-framework`

### Firebase Core version

Tested in Firebase Core 2.32.0 and 3.0.0

### Flutter Version

Tested in Flutter 3.19.1 and 3.22.1

### Relevant Log Output

```shell
Lexical or Preprocessor Issue (Xcode): 'FLTAppCheckProviderFactory.h' file not found with include; use "quotes" instead
/some/path/.pub-cache/hosted/pub.dev/firebase_app_check-0.3.0/ios/Classes/FLTFirebaseAppCheckPlugin.h:10:8

Parse Issue (Xcode): Could not build module 'firebase_app_check'
/some/path/angled_error/.ios/Flutter/FlutterPluginRegistrant/Classes/GeneratedPluginRegistrant.m:9:8
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
Dart SDK 3.4.3
Flutter SDK 3.22.2
angled_error 1.0.0+1

dependencies:
- cupertino_icons 1.0.8
- firebase_app_check 0.3.0 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.36 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_app_check_platform_interface 0.1.0+30 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.1.2+8 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
- firebase_core 3.0.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.4 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.3 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.12.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.2.1
- web 0.5.1
```

</details>
