### ISSUE TITLE
[Core]: "No app has been configured yet" message on iOS

### ISSUE THREAD

**Issue by qwadrox** [firebase/flutterfire#12921]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

iOS

### Description

Following the installing process with FlutterFire cli based on the docs, we will have a configuration that wouldn't work, because of the build phase scripts. This is another issue, that is not the point of my report. 
No problem, we can manually place GoogleService-Info where it needs to be, and add it to the Runner.

Install pods and run for iOS with flutter. 
Than try to run on iOS from Xcode.
You will see this error on the console: 

10.27.0 - [FirebaseCore][I-COR000005] No app has been configured yet.

**Workaround:**
Based on the iOS documentation modify: 
```diff
import Flutter
import UIKit
+import FirebaseCore

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
+  FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

**Expected:** 

Firebase Core should be initialised by calling:

```dart
 await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

```

The error should not appear on the console after calling this.  The documentation might missing a step or information regarded, because I had to use the iOS documentation. 

### Reproducing the issue

See this branch with the commits: 
https://github.com/qwadrox/my_catalog_app/tree/bug/firebase-core-not-being-initialized

### Firebase Core version

3.0.0

### Flutter Version

3.22.1

### Relevant Log Output

```shell
10.27.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
flutter: The Dart VM service is listening on http://127.0.0.1:56184/mU2VYm7zYfE=/
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.4.1
Flutter SDK 3.22.1
my_catalog_app 1.0.0+1

dependencies:
- cupertino_icons 1.0.8
- firebase_core 3.0.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 15.0.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.36 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_messaging_platform_interface 4.5.38 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.8.8 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.4 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.3 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.12.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.2.1
- web 0.5.1

```

</details>
