### ISSUE TITLE
cloud_firestore: unsupported option '-G' for target 'x86_64-apple-ios10.0-simulator'

### ISSUE THREAD

**Issue by curtiscovington** [firebase/flutterfire#12960]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Database, Other

### Which platforms are affected?

iOS

### Description

Using the Xcode 16 beta, I ran into this issue trying to build my projects. It only happens when I include the cloud_firestore plugin.

`unsupported option '-G' for target 'x86_64-apple-ios10.0-simulator'`

### Reproducing the issue

Use Xcode 16 beta on macOS Sequoia beta. Create a new flutter project, add cloud_firestore as a dependency. 

### Firebase Core version

3.1.0

### Flutter Version

3.23.0-13.0.pre.239

### Relevant Log Output

```shell
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.23.0-13.0.pre.239, on macOS 15.0 24A5264n
    darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.90.0)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!


------


flutter run
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running pod install...                                             17.4s
Running Xcode build...                                                  
Xcode build done.                                           21.7s
Failed to build iOS app
Error (Xcode): unsupported option '-G' for target
'x86_64-apple-ios10.0-simulator'


Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.0-254.0.dev
Flutter SDK 3.23.0-13.0.pre.239
foo 0.1.0

dependencies:
- cloud_firestore 5.0.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 4.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.37 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.2.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.0.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 5.1.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.2 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.2.4
- web 0.5.1

```

</details>
