### ISSUE TITLE
[cloud-functions]: HttpsCallableResult.data nested lists can't be used with JsonSerializable

### ISSUE THREAD

**Issue by BuyMyBeard** [firebase/flutterfire#13038]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Cloud Functions

### Which platforms are affected?

Android

### Description

For some reason, instead of directly using normal Dart ListIterator\<dynamic\>, nested lists returned in a HttpsCallableResult have an iterator _ArrayIterator\<Object?\>. Trying to cast that list to List\<dynamic\> doesn't affect the iterator.

In JsonSerializable, This is how a nested list of object is cast: 

```dart
      sections: (json['Sections'] as List<dynamic>)
          .map((e) => Section.fromJson(e as Map<String, dynamic>))
          .toList(),
```
But the Map\<String, dynamic\> explicit cast fails if the iterator is an _ArrayIterator\<Object?\> with exception ```type '_Map<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>' in type cast```

### Reproducing the issue

```dart
test() async {
  final result = await FirebaseFunctions.instance.httpsCallable('test').call();

  final names = (result.data['list'] as List<dynamic>)
    .map((e) => (e as Map<String, dynamic>)['name'])
    .toList();

  print(names);
}
```

```typescript

import { onCall } from "firebase-functions/v2/https";

export const test = onCall(
  (_) => {  
    return {
      list: [
        {
          name: "obj1",
        },
        {
          name: "obj2",
        },
      ],
    }
  },
);
```

### Firebase Core version

3.1.1

### Flutter Version

3.22.2

### Relevant Log Output

```shell
I/flutter (18122): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (18122): type '_Map<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>' in type cast
I/flutter (18122): #0      test.<anonymous closure> (package:cxpress/main.dart:77:20)
I/flutter (18122): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
I/flutter (18122): #2      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
I/flutter (18122): #3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
I/flutter (18122): #4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
I/flutter (18122): #5      new List.of (dart:core-patch/array_patch.dart:39:18)
I/flutter (18122): #6      ListIterable.toList (dart:_internal/iterable.dart:224:7)
I/flutter (18122): #7      test (package:cxpress/main.dart:78:6)
I/flutter (18122): <asynchronous suspension>
I/flutter (18122): ----------------------------------------------------
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  flutter_riverpod: ^2.4.10
  google_fonts: ^6.1.0
  pin_code_fields: ^8.0.1
  logger: ^2.0.2+1
  accordion: ^2.6.0
  flutter_lorem: ^2.0.0
  intl_phone_number_input: ^0.7.4
  email_validator: ^3.0.0
  fancy_password_field: ^2.0.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  mocktail: ^1.0.4
  google_sign_in: ^6.2.1
  fake_cloud_firestore: ^3.0.0
  im_stepper: ^1.0.1+1
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  google_maps_flutter_android: ^2.10.0
  google_maps_flutter_platform_interface: ^2.8.0
  throttling: ^2.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fluster: ^1.2.0
  super_context_menu: ^0.8.17
  hold_to_confirm_button: ^0.0.2
  collection: ^1.18.0
  firebase_storage: ^12.0.1
  image_picker: ^1.1.2
  uuid: ^4.4.0
  firebase_performance: ^0.10.0
  path_provider: ^2.1.3
  firebase_analytics: ^11.0.1
  rxdart: ^0.27.7
  firebase_app_check: ^0.3.0
  get_thumbnail_video:
    git:
      url: https://github.com/kdhfred/video_thumbnail
  lazy_load_indexed_stack: ^1.1.0
  firebase_crashlytics: ^4.0.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  cloud_functions: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.9
  integration_test:
    sdk: flutter
  freezed: ^2.4.7
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  cxpress_lint:
    git:
      url: https://github.com/DevXpressInc/cxpress_lint
      ref: ea9ee3556518a4f3765f14901d7d53be72075410
      path: packages/pyramid_lint
  mocktail_image_network: ^1.2.0

```

</details>
