### ISSUE TITLE
[firebase_crashlytics]: flutter macOS does not terminate the app after stop debuging

### ISSUE THREAD

**Issue by letrungdo** [firebase/flutterfire#13052]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

macOS

### Description

In Flutter MacOS app, After install firebase_crashlytics, when I stop a debug session => does not terminate the app.

### Reproducing the issue

Start Debuging app from VSCode and then Stop debuging
repo: https://github.com/letrungdo/flutter_desktop_crash_report

### Firebase Core version

3.1.1

### Flutter Version

3.19.6

### Relevant Log Output

```shell
[ +298 ms] DevFS: Deleting filesystem on the device (file:///var/folders/9b/yhmc7hzs5wv9pxt5k4044w5h0000gn/T/my_app4tT9Jq/sbi_fx_pc/)
[   +4 ms] DevFS: Deleted filesystem on the device (file:///var/folders/9b/yhmc7hzs5wv9pxt5k4044w5h0000gn/T/my_app4tT9Jq/sbi_fx_pc/)
[  +59 ms] Application finished.
[   +7 ms] "flutter run" took 160,386ms.
[  +35 ms] Service protocol connection closed.
[ +135 ms] ensureAnalyticsSent: 141ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[  +13 ms] exiting with code 0
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
Dart SDK 3.3.4
Flutter SDK 3.19.6
flutter_desktop_crash_report 1.0.0

dependencies:
- firebase_core 3.1.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.0.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.38 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 5.1.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.2 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.38 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 2.1.1
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.5.1

```

</details>
