### ISSUE TITLE
[firebase_auth]: Google login to localhost works but hosting release not working

### ISSUE THREAD

**Issue by longtn-imt** [firebase/flutterfire#13109]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

firebase_auth

### Which platforms are affected?

Web

### Description

Google sign in localhost working but build release hosting not work.
When click button sign google not do action or exception. (Console Log Browser)
 
[Example Web](https://example-477b8.firebaseapp.com/#/login?from=/setting)

### Reproducing the issue

[firebase_authentication.dart](https://github.com/longtn-imt/example/blob/main/lib/firebase/firebase_authentication.dart)
```dart
// Create a new provider
GoogleAuthProvider googleProvider = GoogleAuthProvider();

googleProvider.addScope(
  'https://www.googleapis.com/auth/contacts.readonly',
);
googleProvider.setCustomParameters({
  'login_hint': 'user@example.com',
});

// Once signed in, return the UserCredential
return await FirebaseAuth.instance.signInWithPopup(googleProvider);
```

### Firebase Core version

3.2.0

### Flutter Version

3.22.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
dependencies:
- cloud_firestore 5.1.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.8
- device_info_plus 10.1.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- dio 5.5.0+1 [async http_parser meta path dio_web_adapter]
- encrypt 5.0.3 [args asn1lib clock collection crypto pointycastle]
- firebase_app_check 0.3.0+3 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.1.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.2.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 12.1.1 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fluent_ui 4.9.0 [flutter flutter_localizations intl scroll_pos recase math_expressions]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- go_router 14.2.1 [collection flutter flutter_web_plugins logging meta]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- json_annotation 4.9.0 [meta]
- logger 2.4.0
- retrofit 4.1.0 [dio meta]
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- build_runner 2.4.11 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 4.0.0 [lints]
- freezed 2.5.2 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- go_router_builder 2.7.0 [analyzer async build build_config collection meta path source_gen source_helper]
- json_serializable 6.8.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- retrofit_generator 8.1.2 [analyzer build built_collection code_builder dart_style dio retrofit source_gen tuple protobuf]
```

</details>
