### ISSUE TITLE
10.29.0 - [FirebaseFirestore][I-FST000001] (null)

### ISSUE THREAD

**Issue by victorcode1** [firebase/flutterfire#13125]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Description

10.29.0 - [FirebaseFirestore][I-FST000001] (null)

### Reproducing the issue

10.29.0 - [FirebaseFirestore][I-FST000001] (null)

### Firebase Core version

3.3.0

### Flutter Version

3.22

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

name: invukds
description: Kitchen Display Systems.
publish_to: 'none'
version: 1.3.8+60

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  fluttertoast: 8.2.6
  firebase_core: 3.3.0
  firebase_auth: 5.1.3
  http: 1.0.0
  lottie: 3.1.2
  cloud_firestore: 5.2.0
  cloud_firestore_web: 4.1.0
  just_audio: 0.9.39
  intl: 0.19.0
  firebase_ui_auth: 1.15.0
  http_multi_server: 3.2.1
  shelf: 1.4.1
  rxdart: 0.27.7
  shared_preferences: 2.2.3
  collection: 1.18.0
  device_info_plus: 10.1.1
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  json_annotation: 4.9.0
  go_router: 14.2.1
  flutter_hooks: 0.20.5

  flutter_staggered_grid_view: 0.7.0


dev_dependencies:
  
  flutter_lints: 4.0.0
  riverpod_generator: 2.4.0
  build_runner: 2.4.11
  custom_lint: 0.6.4  # Versión compatible
  json_serializable: 6.8.0
  riverpod_lint: 2.3.10



override:
  http: 1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/loading/
    - assets/btn_view/vertical_color_view.gif
    - assets/btn_view/horizontal_color_view.gif





```

</details>

### Additional context and comments

No response
