### ISSUE TITLE
[CLOUD_FIRESTORE]:  Invalid Query Error: Conflict Between array_contains_any and not_in Filters

### ISSUE THREAD

**Issue by rrakesh28** [firebase/flutterfire#13156]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

cloud firestore

### Description

I am experiencing an issue with Firestore queries in Flutter where using array_contains_any filters in combination with not_in filters results in an IllegalArgumentException. The error message indicates that these filters cannot be used together.

### Reproducing the issue

Create a Firestore query using array_contains_any filter.
Add a not_in filter to the same query.
Attempt to execute the query.
Observe the IllegalArgumentException error in the logs.

### Firebase Core version

3.0.0

### Flutter Version

3.22.3

### Relevant Log Output

```shell
E/FLTFirestoreMsgCodec(30812): java.lang.IllegalArgumentException: Invalid Query. You cannot use 'array_contains_any' filters with 'not_in' filters.
E/FLTFirestoreMsgCodec(30812): 	at com.google.firebase.firestore.Query.validateNewFieldFilter(Query.java:584)
E/FLTFirestoreMsgCodec(30812): 	at com.google.firebase.firestore.Query.validateNewFilter(Query.java:594)
E/FLTFirestoreMsgCodec(30812): 	at com.google.firebase.firestore.Query.where(Query.java:406)
E/FLTFirestoreMsgCodec(30812): 	at com.google.firebase.firestore.Query.whereArrayContainsAny(Query.java:315)
E/FLTFirestoreMsgCodec(30812): 	at io.flutter.plugins.firebase.firestore.utils.PigeonParser.parseQuery(PigeonParser.java:209)
E/FLTFirestoreMsgCodec(30812): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin.lambda$queryGet$17(FlutterFirebaseFirestorePlugin.java:745)
E/FLTFirestoreMsgCodec(30812): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin$$ExternalSyntheticLambda13.run(Unknown Source:12)
E/FLTFirestoreMsgCodec(30812): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/FLTFirestoreMsgCodec(30812): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/FLTFirestoreMsgCodec(30812): 	at java.lang.Thread.run(Thread.java:1012)
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  firebase_database: ^11.0.0
  firebase_dart: ^1.0.0-dev.27
  firebase_messaging: ^15.0.3
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  envied_generator: ^0.5.4+1

```

</details>
