### ISSUE TITLE
[firebase_hosting] Wasm is not used in Flutter Web App

### ISSUE THREAD

**Issue by Kuhlemann** [firebase/flutterfire#13171]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

Web

### Problem

Wasm is not used when deploying to Firebase Hosting and I do not understand why.

### Analysis

Deploying the same flutter code locally works with Wasm-active.
I checked all requirements which I found at: https://docs.flutter.dev/platform-integration/web/wasm

What am I missing? 
Wrong CORS configuration for example?

### Reproducing the issue

- I use Flutter stable channel on version 3.24.0
- I use the simplest possible code to reproduce (see sample below)
- To make sure there is no problem inside the index.html I deleted the "web"-folder and recreated it with: flutter create . --platforms=web
- `flutter build web --wasm` compiles successfully: "✓ Built build/web"
- Directly after that I start a local server in my "build/web"-folder with dhttp for testing purpose: `dhttpd '--headers=Cross-Origin-Embedder-Policy=credentialless;Cross-Origin-Opener-Policy=same-origin'`
- I use Chrome version 126 to open localhost:8080 and kIsWasm is **true**.
- After that I deploy with firebase deploy and kIsWasm is now **false** in the online version of my app.

### Minimal reproducible example (main.dart):
```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('WebAssembly-Status: $kIsWasm!'),
        ),
        body: const Center(
          child: Text('Welcome to Flutter WebAssembly!'),
        ),
      ),
    ),
  );
}

```

### My firebase.json in my project folder looks like this:
```
{
  "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "frameworksBackend": {
      "region": "europe-west1"
    },
    "rewrites": [ {
      "source": "**",
      "destination": "/index.html"
    } ],
    "headers": [
        {
           "source": "**/*",
            "headers": [
                {
                    "key": "Cross-Origin-Embedder-Policy",
                    "value": "require-corp"
                },
                {
                    "key": "Cross-Origin-Opener-Policy",
                    "value": "same-origin"
                }
            ]
        }
    ]    
  }
}
```

### Firebase Core version

None in my minimal reproducible example

### Flutter Version

3.24.0 (Stable)

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.0
Flutter SDK 3.24.0
test_app 1.0.0+1

dependencies:
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 4.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- path 1.9.0
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.2.4
 
```

</details>

### Additional context and comments

I hope this "flutterfire"-repository is the right place for this topic.
