### ISSUE TITLE
[firebase_remote_config]: Remote config condition not working for Android devices

### ISSUE THREAD

**Issue by fabio-tanda** [firebase/flutterfire#13194]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Remote Config

### Which platforms are affected?

Android

### Description

Summary:
When adding a Remote Config condition in the Firebase console that considers a Custom User Property from Firebase Analytics, I expected consistent behavior across both iOS and Android platforms. However, the condition works as expected only on iOS, while Android devices are returning the default value instead of the value from the condition.

Steps to Reproduce:

Set up a Custom Definition in Firebase Analytics (deviceBuildNumber, User Scope)
Created a Condition in Firebase Remote Config that uses this Custom User Property (deviceBuildNumber = 1)
Sample app shows the User Property being set from main.dart.
Sample app fetches the Remote Config values in both an iOS and an Android app using the FlutterFire SDK.

Expected Behavior:
Both iOS and Android devices should apply the condition based on the Custom User Property, resulting in the same logic and value being returned on both platforms.

Actual Behavior:
iOS: The condition is correctly applied, and the expected value is returned.
Android: The condition is not applied, and the default value is returned instead.
Additional Information:

Firebase Analytics version: 11.2.1
Firebase Core version: 3.3.0
Firebase Remote Config version: 5.0.4

### Reproducing the issue

The sample code below shows the firebase_remote_config integration and displays a simple json string on the screen showing the fetched value either from the condition or the default value.

https://github.com/fhirata/firebase_remote_config_test

The same flutter code runs on both iOS and Android devices but, 

on iOS the response is:
{"enabled": true, "message": "Remote Condition"}

on Android the response is:
{"enabled": true, "message": "Remote Default"}

Remote config condition:
<img width="846" alt="Screenshot 2024-08-16 at 9 48 37 PM" src="https://github.com/user-attachments/assets/f5e7230e-cdc2-4ed0-92f6-005f4b28c3ee">

Remote config parameter:
<img width="1246" alt="Screenshot 2024-08-16 at 9 49 01 PM" src="https://github.com/user-attachments/assets/3c3991a3-e1ca-4774-a530-824297ef35be">

### Firebase Core version

3.3.0

### Flutter Version

3.24.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.0
Flutter SDK 3.24.0
firebase_remote_config_test 1.0.0+1

dependencies:
- cupertino_icons 1.0.8
- firebase_analytics 11.2.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_remote_config 5.0.4 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.40 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_analytics_platform_interface 4.2.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.9+1 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.2.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.4 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_remote_config_platform_interface 1.4.40 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.6.12 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.2.4
- web 0.5.1

```

</details>

### Additional context and comments

Happy to give access to the Firebase console as needed.  Thanks!
