### ISSUE TITLE
[firebase_app_installations]: GetId loads forever on iOS

### ISSUE THREAD

**Issue by Colman** [firebase/flutterfire#13240]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

App Installations

### Which platforms are affected?

iOS

### Description

When calling the `FirebaseInstallations.instance.getId()` function in series it works. However, when calling it in parallel, it hangs forever.

### Reproducing the issue

This never completes:
```dart
await Firebase.initializeApp();

final tasks = <Future<String>>[];
for (var i = 0; i < 30; i++) {
   tasks.add(FirebaseInstallations.instance.getId());
}

await Future.wait(tasks); //Never completes
```

However, this does complete:
```dart
await Firebase.initializeApp();

for (var i = 0; i < 30; i++) {
   await FirebaseInstallations.instance.getId();
}
```

### Firebase Core version

3.4.0

### Flutter Version

3.22.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
  firebase_app_installations: 0.3.1
  firebase_analytics: 11.3.0
  firebase_core: 3.4.0
  firebase_crashlytics: 4.1.0
  firebase_remote_config: 5.1.0
```

</details>
