### ISSUE TITLE
firebase_messaging: foreground notifications showing despite setting alert to false in ios

### ISSUE THREAD

**Issue by Jonny1987** [firebase/flutterfire#13254]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

In-App Messaging

### Which platforms are affected?

iOS

### Description

I have turned off foreground alerts by doing the following, but they still appear:
```
      await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
        alert: false,
        badge: false,
        sound: false,
      );
```

### Reproducing the issue

1) add the code above to turn off foreground messages
2) send fcm message containing a notification to an ios device

### Firebase Core version

3.3.0

### Flutter Version

3.22.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.4.0
Flutter SDK 3.22.0
workwith 2.0.0+47

dependencies:
- amplitude_flutter 3.16.2 [flutter flutter_web_plugins js]
- app_settings 5.1.1 [flutter plugin_platform_interface]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cron 0.6.1 [clock]
- crypto 3.0.3 [typed_data]
- cupertino_icons 1.0.8
- dotenv 4.2.0 [args meta]
- envied 0.5.4+1
- eraser 2.0.2 [flutter]
- fake_async 1.3.1 [clock collection]
- firebase_core 3.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 15.0.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.6 [bloc flutter provider]
- flutter_cache_manager 3.3.3 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_localized_locales 2.0.5 [flutter intl]
- flutter_radar 3.9.1 [flutter]
- flutter_riverpod 2.5.1 [collection flutter meta riverpod state_notifier]
- flutter_secure_storage 9.2.2 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_slidable 3.1.1 [flutter]
- flutter_udid 3.0.0 [flutter crypto]
- flutter_uxcam 2.5.4 [flutter stack_trace visibility_detector]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- geolocator 10.1.1 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- go_router 13.2.5 [collection flutter flutter_web_plugins logging meta]
- google_maps_flutter 2.7.0 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- http 1.2.2 [async http_parser meta web]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.19.0 [clock meta path]
- json_serializable 6.8.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- logger 2.4.0
- mocktail 1.0.4 [collection matcher test_api]
- network_image_mock 2.1.1 [flutter mockito]
- onesignal_flutter 5.2.2 [flutter]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- platform 3.1.5
- provider 6.1.2 [collection flutter nested]
- sensors_plus 5.0.1 [flutter flutter_web_plugins sensors_plus_platform_interface]
- sentry_dart_plugin 1.7.1 [yaml injector ansicolor system_info2 file http crypto convert process properties]
- sentry_flutter 8.1.0 [flutter flutter_web_plugins sentry package_info_plus meta ffi]
- shared_preferences 2.2.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 6.1.1 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- stream_chat_flutter 7.3.0 [cached_network_image chewie collection contextmenu desktop_drop diacritic dio ezanimation file_picker file_selector flutter flutter_markdown flutter_portal flutter_svg http_parser image_gallery_saver image_picker image_size_getter jiffy just_audio lottie media_kit media_kit_video meta path_provider photo_manager photo_view rxdart share_plus shimmer stream_chat_flutter_core synchronized thumblr url_launcher video_player video_thumbnail]
- supabase 2.2.5 [functions_client gotrue http postgrest realtime_client storage_client rxdart yet_another_json_isolate]
- supabase_flutter 2.5.9 [app_links async crypto flutter http meta supabase url_launcher path_provider shared_preferences]
- time_range_picker 2.3.0 [flutter]
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- wiredash 2.2.1 [async clock collection device_info_plus file flutter flutter_localizations http http_parser intl material_color_utilities nanoid2 package_info_plus path_provider platform shared_preferences]

dev dependencies:
- build_runner 2.4.11 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- envied_generator 0.5.4+1 [envied build code_builder dart_style source_gen analyzer recase equatable]
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.40 [collection firebase_core firebase_core_platform_interface flutter meta]
- after_layout 1.2.0 [flutter]
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- animations 2.0.11 [flutter]
- ansicolor 2.0.2
- app_links 6.1.4 [flutter app_links_linux app_links_platform_interface app_links_web]
- app_links_linux 1.0.3 [flutter app_links_platform_interface gtk]
- app_links_platform_interface 2.0.2 [flutter plugin_platform_interface]
- app_links_web 1.0.3 [flutter flutter_web_plugins app_links_platform_interface web]
- archive 3.6.1 [crypto path]
- args 2.5.0
- asn1lib 1.5.3
- async 2.11.0 [collection meta]
- audio_session 0.1.21 [flutter flutter_web_plugins rxdart meta]
- bloc 8.1.4 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.2 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.1 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.2.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- chewie 1.8.1 [cupertino_icons flutter provider video_player wakelock_plus]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- connectivity_plus 5.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- contextmenu 3.0.0 [flutter animations after_layout]
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+1 [meta web]
- crypto_keys 0.3.0+1 [pointycastle meta collection quiver]
- csslib 1.0.0 [source_span]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- desktop_drop 0.4.4 [flutter flutter_web_plugins cross_file]
- device_info_plus 10.1.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- diacritic 0.1.5
- dio 5.5.0+1 [async http_parser meta path dio_web_adapter]
- dio_web_adapter 1.0.1 [dio http_parser meta]
- equatable 2.0.5 [collection meta]
- ezanimation 0.6.0 [flutter]
- ffi 2.1.2
- file 7.0.0 [meta path]
- file_picker 8.0.6 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file web]
- file_selector 1.0.3 [file_selector_android file_selector_ios file_selector_linux file_selector_macos file_selector_platform_interface file_selector_web file_selector_windows flutter]
- file_selector_android 0.5.1+3 [file_selector_platform_interface flutter plugin_platform_interface]
- file_selector_ios 0.5.3 [file_selector_platform_interface flutter]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_web 0.9.4+1 [file_selector_platform_interface flutter flutter_web_plugins web]
- file_selector_windows 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- firebase_core_platform_interface 5.2.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.4 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_messaging_platform_interface 4.5.42 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.8.12 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- fixnum 1.1.0
- flutter_markdown 0.7.3 [flutter markdown meta path]
- flutter_plugin_android_lifecycle 2.0.20 [flutter]
- flutter_portal 1.1.4 [collection flutter vector_math]
- flutter_secure_storage_linux 1.2.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.1.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.2.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.1.2 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- frontend_server_client 4.0.0 [async path]
- functions_client 2.2.0 [http yet_another_json_isolate]
- geolocator_android 4.6.0 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.4 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.2.1 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.2.3 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- globbing 1.0.0 [path]
- google_identity_services_web 0.3.1+1 [meta web]
- google_maps 7.1.0 [js js_wrapping meta web]
- google_maps_flutter_android 2.12.0 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.10.0 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.8.0 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.8 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform web]
- google_sign_in_android 6.1.27 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.6 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4+1 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- gotrue 2.8.3 [collection crypto http jwt_decode retry rxdart meta]
- graphs 2.3.2 [collection]
- gtk 2.1.0 [ffi flutter meta]
- hashcodes 2.0.0
- html 0.15.4 [csslib source_span]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.2.0 [archive meta xml]
- image_gallery_saver 2.0.3 [flutter]
- image_picker_android 0.8.12+7 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.4 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- image_size_getter 2.1.3 [collection hashcodes]
- injector 3.0.0
- io 1.0.4 [meta path string_scanner]
- jiffy 6.3.1 [intl]
- jose 0.3.4 [crypto_keys meta typed_data x509 http http_parser asn1lib collection]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- json_annotation 4.9.0 [meta]
- just_audio 0.9.39 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- just_audio_platform_interface 4.3.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.11 [just_audio_platform_interface flutter flutter_web_plugins web]
- jwt_decode 0.3.1
- leak_tracker 10.0.4 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.3 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- logging 1.2.0
- lottie 3.1.2 [archive flutter http path vector_math]
- markdown 7.2.2 [args meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- media_kit 1.1.10+1 [meta path image uri_parser collection synchronized uuid http safe_local_storage universal_platform js]
- media_kit_video 1.2.4 [flutter media_kit synchronized wakelock_plus screen_brightness volume_controller universal_platform plugin_platform_interface]
- meta 1.12.0
- mime 1.0.5
- mockito 5.4.4 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- nanoid2 2.0.1
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.0.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus 8.0.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- package_info_plus_platform_interface 3.0.0 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.3 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.7 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- permission_handler_android 12.0.7 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.5 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.2.1 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- photo_manager 3.2.2 [flutter]
- photo_view 0.15.0 [flutter]
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.9.1 [collection convert js]
- pool 1.5.1 [async stack_trace]
- postgrest 2.1.2 [http yet_another_json_isolate meta]
- process 5.0.2 [file path platform]
- properties 2.1.1 [meta]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.3.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.1 [matcher]
- rate_limiter 1.0.0
- realtime_client 2.2.0 [collection http meta web_socket_channel]
- recase 4.1.0
- retry 3.1.2
- riverpod 2.5.1 [collection meta stack_trace state_notifier]
- rxdart 0.27.7
- safe_local_storage 1.0.2 [path synchronized]
- sanitize_html 2.1.0 [html meta]
- screen_brightness 0.2.2+1 [flutter screen_brightness_platform_interface screen_brightness_android screen_brightness_ios screen_brightness_macos screen_brightness_windows]
- screen_brightness_android 0.1.0+2 [flutter screen_brightness_platform_interface]
- screen_brightness_ios 0.1.0 [flutter screen_brightness_platform_interface]
- screen_brightness_macos 0.1.0+1 [flutter screen_brightness_platform_interface]
- screen_brightness_platform_interface 0.1.0 [flutter plugin_platform_interface]
- screen_brightness_windows 0.1.3 [flutter screen_brightness_platform_interface]
- sensors_plus_platform_interface 1.2.0 [flutter logging meta plugin_platform_interface]
- sentry 8.1.0 [http meta stack_trace uuid]
- share_plus 9.0.0 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- share_plus_platform_interface 4.0.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.2.3 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.4.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.3.0 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 2.0.0 [shelf stream_channel web_socket_channel]
- shimmer 3.0.0 [flutter]
- sign_in_with_apple_platform_interface 1.1.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 2.1.0 [flutter flutter_web_plugins sign_in_with_apple_platform_interface]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.3+1 [flutter sqflite_common path]
- sqflite_common 2.5.4 [synchronized path meta]
- stack_trace 1.11.1 [path]
- state_notifier 1.0.0 [meta]
- storage_client 2.0.2 [http http_parser mime retry meta]
- stream_channel 2.1.2 [async]
- stream_chat 7.3.0 [async collection dio equatable freezed_annotation http_parser jose json_annotation logging meta mime rate_limiter rxdart synchronized uuid web_socket_channel]
- stream_chat_flutter_core 7.3.0 [collection connectivity_plus flutter freezed_annotation meta rxdart stream_chat]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- system_info2 4.0.0 [globbing path]
- term_glyph 1.2.1
- test_api 0.7.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- thumblr 0.0.4 [flutter thumblr_platform_interface thumblr_macos thumblr_windows]
- thumblr_macos 0.4.0 [flutter thumblr_platform_interface]
- thumblr_platform_interface 0.3.1+1 [flutter plugin_platform_interface]
- thumblr_windows 0.0.3+1 [flutter thumblr_platform_interface path_provider]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- universal_platform 1.1.0
- uri_parser 2.0.2 [path safe_local_storage]
- url_launcher_android 6.3.5 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.2 [flutter url_launcher_platform_interface]
- uuid 4.4.2 [crypto sprintf meta fixnum]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- video_player 2.9.1 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.5.2 [flutter video_player_platform_interface]
- video_player_avfoundation 2.6.1 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.3.1 [flutter flutter_web_plugins video_player_platform_interface web]
- video_thumbnail 0.5.3 [flutter]
- visibility_detector 0.4.0+2 [flutter]
- vm_service 14.2.1
- volume_controller 2.0.7 [flutter]
- wakelock_plus 1.2.5 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus web]
- wakelock_plus_platform_interface 1.2.1 [flutter plugin_platform_interface meta]
- watcher 1.1.0 [async path]
- web 0.5.1
- web_socket_channel 2.4.5 [async crypto stream_channel web]
- win32 5.5.1 [ffi]
- win32_registry 1.1.3 [ffi win32]
- x509 0.2.4+2 [asn1lib quiver crypto_keys]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
- yet_another_json_isolate 2.0.0 [async]


```

</details>
