### ISSUE TITLE
[bug]: firebase.json not found

### ISSUE THREAD

**Issue by Habibieproject** [firebase/flutterfire#13261]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core, Crashlytics

### Which platforms are affected?

iOS

### Description

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/fr/lq4ft8x10l5b7bj4jd0ny90w0000gn/T/flutter_tools.zks4P1/flutter_ios_build_temp_dirskmrJ0/temporary_xcresult_bundle

    ld: warning: ignoring duplicate libraries: '-lc++'
    Unhandled exception:
    PathNotFoundException: Cannot open file, path = '/Users/ashabibie/firebase.json' (OS Error: No such file or directory, errno = 2)
    #0      _checkForErrorResponse (dart:io/common.dart:55:9)
    #1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
    <asynchronous suspension>
    #2      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562:24)
    <asynchronous suspension>
    #3      _File.readAsString (dart:io/file_impl.dart:621:18)
    <asynchronous suspension>
    #4      appleConfigFromFirebaseJson (package:flutterfire_cli/src/common/utils.dart:286:7)
    <asynchronous suspension>
    #5      UploadCrashlyticsSymbols._getConfigurationFromFirebaseJsonFile (package:flutterfire_cli/src/commands/upload_symbols.dart:278:9)
    <asynchronous suspension>
    #6      UploadCrashlyticsSymbols.run (package:flutterfire_cli/src/commands/upload_symbols.dart:331:34)
    <asynchronous suspension>

### Reproducing the issue

Steps to Reproduce:

Set Up Firebase in a Flutter Project:

Create a new Flutter project or use an existing one.
Add the following Firebase dependencies to the pubspec.yaml file:
yaml
Copy code
dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  firebase_auth: any
  firebase_crashlytics: any
Configure Firebase with flutterfire_cli:

Run flutterfire configure to configure Firebase for the project.
Ensure that Crashlytics is enabled during the setup process.
Update iOS Deployment Target:

Update the iOS deployment target in Podfile to at least 13.0 as required by some Firebase dependencies.
Run pod install in the ios directory to install necessary pods.
Build the iOS Project:

Attempt to build the iOS project using either flutter build ios or by running the project in Xcode (Runner.xcworkspace).
Observe the Error:

During the build process, observe the following:
Warnings related to ignoring duplicate libraries -lc++.
A PathNotFoundException related to a missing firebase.json file, which was not required before the update.

Minimal Reproducible Example:

Start with a minimal Flutter project.
Add Firebase dependencies, including firebase_crashlytics.
Use flutterfire_cli to configure Firebase.
Ensure no firebase.json file is manually created or added to the root directory.

### Firebase Core version

2.23.0

### Flutter Version

3.24.0

### Relevant Log Output

```shell
Xcode build done.                                           37,0s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
2
    { platform:iOS Simulator, id:D5EEA5EF-16D1-422E-BCA4-4C49AD2CC7D6, OS:17.4, name:iPhone 15 Pro }
    ** BUILD FAILED **
2

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/fr/lq4ft8x10l5b7bj4jd0ny90w0000gn/T/flutter_tools.zks4P1/flutter_ios_build_temp_dirskmrJ0/temporary_xcresult_bundle

    ld: warning: ignoring duplicate libraries: '-lc++'
    Unhandled exception:
    PathNotFoundException: Cannot open file, path = '/Users/ashabibie/firebase.json' (OS Error: No such file or directory, errno = 2)
    #0      _checkForErrorResponse (dart:io/common.dart:55:9)
    #1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
    <asynchronous suspension>
    #2      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562:24)
    <asynchronous suspension>
    #3      _File.readAsString (dart:io/file_impl.dart:621:18)
    <asynchronous suspension>
    #4      appleConfigFromFirebaseJson (package:flutterfire_cli/src/common/utils.dart:286:7)
    <asynchronous suspension>
    #5      UploadCrashlyticsSymbols._getConfigurationFromFirebaseJsonFile (package:flutterfire_cli/src/commands/upload_symbols.dart:278:9)
    <asynchronous suspension>
    #6      UploadCrashlyticsSymbols.run (package:flutterfire_cli/src/commands/upload_symbols.dart:331:34)
    <asynchronous suspension>
    #7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
    <asynchronous suspension>
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.1
Flutter SDK 3.24.1
mosfeed 5.2.0+10130

dependencies:
- adhan 2.0.0+1
- animate_do 3.3.4 [flutter]
- animated_bottom_navigation_bar 1.3.3 [flutter]
- app_settings 5.1.1 [flutter plugin_platform_interface]
- audio_video_progress_bar 2.0.3 [flutter]
- audioplayers 6.1.0 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- bloc 8.1.4 [meta]
- bloc_concurrency 0.2.5 [bloc stream_transform]
- cached_network_image 3.4.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- collection 1.18.0
- connectivity_plus 6.0.5 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- cupertino_icons 1.0.8
- delightful_toast 1.1.0 [flutter flutter_animate]
- device_info_plus 10.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- dio 5.6.0 [async http_parser meta path dio_web_adapter]
- easy_stepper 0.8.5+1 [flutter lottie]
- equatable 2.0.5 [collection meta]
- file_picker 8.0.7 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file web]
- firebase_auth 4.20.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.32.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.5.7 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 14.9.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- fl_chart 0.63.0 [equatable flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.6 [bloc flutter provider]
- flutter_bounceable 1.1.0 [flutter]
- flutter_dotenv 5.1.0 [flutter]
- flutter_downloader 1.11.8 [flutter]
- flutter_easyloading 3.0.5 [flutter flutter_spinkit]
- flutter_file_dialog 3.0.2 [flutter]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_local_notifications 17.2.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_pdfview 1.3.2 [flutter]
- flutter_qiblah 3.0.3 [flutter flutter_compass_v2 geolocator stream_transform vector_math]
- flutter_quill 9.6.0 [flutter flutter_localizations intl dart_quill_delta collection quiver equatable meta html flutter_colorpicker flutter_quill_delta_from_html markdown charcode url_launcher flutter_keyboard_visibility device_info_plus]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_screenutil 5.9.3 [flutter]
- flutter_spinkit 5.2.1 [flutter]
- flutter_staggered_animations 1.1.1 [flutter]
- flutter_staggered_grid_view 0.7.0 [flutter]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_swiper_view 1.1.8 [flutter]
- flutter_widget_from_html 0.14.11 [flutter flutter_widget_from_html_core fwfh_cached_network_image fwfh_chewie fwfh_just_audio fwfh_svg fwfh_url_launcher fwfh_webview html]
- fluttertoast 8.2.8 [flutter flutter_web_plugins web]
- geocoding 3.0.0 [flutter geocoding_platform_interface geocoding_android geocoding_ios]
- geolocator 11.1.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get 4.6.6 [flutter]
- get_it 7.7.0 [async collection meta]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- http 1.2.2 [async http_parser meta web]
- hydrated_bloc 9.1.5 [bloc hive meta synchronized]
- image_cropper 8.0.2 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_update 4.2.3 [flutter]
- intl 0.19.0 [clock meta path]
- intl_phone_field 3.2.0 [flutter]
- just_audio 0.9.40 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- just_audio_background 0.0.1-beta.13 [just_audio_platform_interface audio_service audio_session flutter flutter_web_plugins meta rxdart]
- just_audio_cache 0.1.2 [flutter just_audio shared_preferences path_provider http]
- keyboard_actions 4.2.0 [flutter]
- logger 2.4.0
- lottie 3.1.2 [archive flutter http path vector_math]
- material_dialogs 1.1.5 [flutter lottie]
- msh_checkbox 2.0.1 [flutter]
- package_info_plus 8.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- page_transition 2.1.0 [flutter]
- path 1.9.0
- path_provider 2.1.4 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- photo_view 0.14.0 [flutter]
- pip_view 0.9.7 [flutter]
- pretty_dio_logger 1.4.0 [dio]
- provider 6.1.2 [collection flutter nested]
- rxdart 0.27.7
- sensors_plus 4.0.2 [flutter flutter_web_plugins sensors_plus_platform_interface]
- share_plus 9.0.0 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- shared_preferences 2.3.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 3.0.0 [flutter]
- sign_in_with_apple 6.1.2 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sqflite 2.3.3+1 [flutter sqflite_common path]
- stream_transform 2.1.0
- syncfusion_flutter_calendar 24.2.9 [flutter timezone syncfusion_flutter_core syncfusion_flutter_datepicker intl]
- table_calendar 3.1.2 [flutter intl simple_gesture_detector]
- text_scroll 0.2.0 [flutter]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- vibration 2.0.0 [flutter vibration_platform_interface]
- vs_scrollbar 0.2.1 [flutter]
- vsc_quill_delta_to_html 1.0.5 [html_unescape collection meta]
- webview_flutter 4.9.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 3.16.7 [flutter webview_flutter_platform_interface]
- webview_flutter_wkwebview 3.15.0 [flutter path webview_flutter_platform_interface]
- youtube_player_flutter 8.1.2 [flutter flutter_inappwebview]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.35 [collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.6.1 [crypto path]
- args 2.5.0
- async 2.11.0 [collection meta]
- audio_service 0.18.15 [audio_service_platform_interface audio_service_web audio_session rxdart flutter_cache_manager clock js flutter flutter_web_plugins]
- audio_service_platform_interface 0.1.1 [flutter plugin_platform_interface meta]
- audio_service_web 0.1.3 [audio_service_platform_interface rxdart js flutter flutter_web_plugins]
- audio_session 0.1.21 [flutter flutter_web_plugins rxdart meta]
- audioplayers_android 5.0.0 [audioplayers_platform_interface flutter]
- audioplayers_darwin 6.0.0 [audioplayers_platform_interface flutter]
- audioplayers_linux 4.0.0 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 7.0.0 [collection flutter meta plugin_platform_interface]
- audioplayers_web 5.0.1 [audioplayers_platform_interface flutter flutter_web_plugins web]
- audioplayers_windows 4.0.0 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- charcode 1.3.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- chewie 1.8.3 [cupertino_icons flutter provider video_player wakelock_plus]
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.5 [typed_data]
- csslib 1.0.0 [source_span]
- dart_quill_delta 9.6.0 [collection diff_match_patch quiver]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.1 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- dio_web_adapter 2.0.0 [dio http_parser meta web]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- firebase_auth_platform_interface 7.3.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.12.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.2.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.5 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.35 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.37 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.8.7 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- fixnum 1.1.0
- flutter_animate 4.5.0 [flutter flutter_shaders]
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_colorpicker 1.1.0 [flutter]
- flutter_compass_v2 1.0.3 [flutter]
- flutter_inappwebview 5.8.0 [flutter]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 4.0.1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.2.0 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.22 [flutter]
- flutter_quill_delta_from_html 1.3.12 [dart_quill_delta html]
- flutter_shaders 0.1.2 [flutter vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- flutter_widget_from_html_core 0.14.12 [csslib flutter html logging]
- fwfh_cached_network_image 0.14.3 [cached_network_image flutter flutter_cache_manager flutter_widget_from_html_core]
- fwfh_chewie 0.14.8 [chewie flutter flutter_widget_from_html_core video_player]
- fwfh_just_audio 0.14.3 [flutter flutter_widget_from_html_core just_audio]
- fwfh_svg 0.8.3 [flutter flutter_svg flutter_widget_from_html_core]
- fwfh_url_launcher 0.9.1 [flutter flutter_widget_from_html_core url_launcher]
- fwfh_webview 0.14.8 [flutter flutter_widget_from_html_core logging webview_flutter webview_flutter_android webview_flutter_wkwebview]
- geocoding_android 3.3.1 [flutter geocoding_platform_interface]
- geocoding_ios 3.0.1 [flutter geocoding_platform_interface]
- geocoding_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- geolocator_android 4.6.1 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.4 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 3.0.0 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.2.3 [flutter geolocator_platform_interface]
- google_identity_services_web 0.3.1+4 [meta web]
- google_sign_in_android 6.1.28 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.7 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4+2 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- hive 2.2.3 [meta crypto]
- html 0.15.4 [csslib source_span]
- html_unescape 2.0.0
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.2.0 [archive meta xml]
- image_cropper_for_web 6.0.2 [flutter flutter_web_plugins image_cropper_platform_interface web]
- image_cropper_platform_interface 7.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.12+13 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.5 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- js 0.7.1
- json_annotation 4.9.0 [meta]
- just_audio_platform_interface 4.3.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.12 [just_audio_platform_interface flutter flutter_web_plugins web]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 2.1.1
- logging 1.2.0
- markdown 7.2.2 [args meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 1.0.6
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.1.0 [flutter]
- package_info_plus_platform_interface 3.0.1 [flutter meta plugin_platform_interface]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.10 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- permission_handler_android 12.0.12 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.5 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+2 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.2.2 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.5
- plugin_platform_interface 2.1.8 [meta]
- quiver 3.2.2 [matcher]
- sensors_plus_platform_interface 1.2.0 [flutter logging meta plugin_platform_interface]
- share_plus_platform_interface 4.0.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.3.2 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sign_in_with_apple_platform_interface 1.1.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 2.1.0 [flutter flutter_web_plugins sign_in_with_apple_platform_interface]
- simple_gesture_detector 0.2.1 [flutter]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite_common 2.5.4+2 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- syncfusion_flutter_core 24.2.9 [vector_math flutter]
- syncfusion_flutter_datepicker 24.2.9 [flutter intl syncfusion_flutter_core]
- synchronized 3.2.0
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.2 [path]
- typed_data 1.3.2 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- url_launcher_android 6.3.10 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.2 [flutter url_launcher_platform_interface]
- uuid 4.5.0 [crypto sprintf meta fixnum]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vibration_platform_interface 0.0.1 [flutter plugin_platform_interface device_info_plus]
- video_player 2.9.1 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.7.2 [flutter video_player_platform_interface]
- video_player_avfoundation 2.6.1 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.3.2 [flutter flutter_web_plugins video_player_platform_interface web]
- vm_service 14.2.5
- wakelock_plus 1.2.8 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus web]
- wakelock_plus_platform_interface 1.2.1 [flutter plugin_platform_interface meta]
- web 0.5.1
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- win32 5.5.4 [ffi]
- win32_registry 1.1.4 [ffi win32]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

### Additional context and comments

Xcode version: 15.3
macOS version: 14.4.1
Flutter version: 3.24.0 (stable)
The issue began occurring immediately after integrating Crashlytics and updating Firebase configurations using flutterfire_cli.
