### ISSUE TITLE
Crash when accessing FirebaseFirestore.instance on Windows Desktop with Firebase initialization

### ISSUE THREAD

**Issue by rajaonahtoky** [firebase/flutterfire#13319]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Cloud Functions

### Which platforms are affected?

Windows

### Description

When initializing Firebase using `await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform)` in a Flutter Windows desktop application, and later calling `FirebaseFirestore.instance`, the application crashes with the message "Lost connection to device. Exited."

### Reproducing the issue

1. Initialize Firebase with `await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform)`.
2. Call `FirebaseFirestore.instance`.
3. Observe the crash with the message "Lost connection to device. Exited."

### Firebase Core version

3.4.1

### Flutter Version

3.24.1

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
Dart SDK 3.5.1
Flutter SDK 3.24.1

dependencies:
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cloud_firestore 5.4.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- connectivity_plus 5.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- cupertino_icons 1.0.8
- dropdown_button2 2.3.9 [flutter meta]
- envied 0.5.4+1
- extended_nested_scroll_view 6.2.1 [flutter visibility_detector]
- file_picker 8.1.2 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file web]
- file_saver 0.2.14 [collection dio flutter flutter_web_plugins path_provider path_provider_linux path_provider_windows web]
- firebase_auth 5.2.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.4.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_staggered_grid_view 0.7.0 [flutter]
- get 4.6.6 [flutter]
- get_storage 2.1.1 [flutter get path_provider]
- group_tablelist 0.0.4 [flutter]
- json_annotation 4.9.0 [meta]
- json_serializable 6.8.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mask_text_input_formatter 2.9.0 [flutter]
- midi_file_player 0.0.1 [flutter path_provider plugin_platform_interface]
- overlay_support 2.1.0 [flutter async]
- package_info_plus 8.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- page_view_dot_indicator 2.3.0 [flutter]
- path 1.9.0
- progress_dialog_null_safe 3.0.0 [flutter]
- responsive_framework 1.5.1 [flutter collection]
- shared_preferences 2.3.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 3.0.0 [flutter]
- sidebarx 0.17.1 [flutter]
- spritewidget 2.0.1 [flutter vector_math]
- sqlcipher_library_windows 1.0.2 [flutter path]
- sqlite3 1.11.2 [collection ffi js meta path]
- system_info2 4.0.0 [globbing path]
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.0 [crypto sprintf meta fixnum]
- wechat_assets_picker 9.2.1 [flutter wechat_picker_library extended_image photo_manager photo_manager_image_provider provider video_player]
- window_manager 0.3.9 [flutter path screen_retriever]

dev_dependencies:
- build_runner 2.4.12 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- envied_generator 0.5.4+1 [envied build code_builder dart_style source_gen analyzer recase equatable]
- flutter_lints 4.0.0 [lints]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive_dependencies:
- _fe_analyzer_shared 72.0.0 [meta]
- _flutterfire_internals 1.3.42 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.2
- analyzer 6.7.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- args 2.5.0
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.2 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_web 4.3.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.5 [typed_data]
- csslib 1.0.0 [source_span]
- dart_style 2.3.7 [analyzer args collection package_config path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- dio 5.7.0 [async http_parser meta path dio_web_adapter]
- dio_web_adapter 2.0.0 [dio http_parser meta web]
- equatable 2.0.5 [collection meta]
- extended_image 8.2.3 [extended_image_library flutter meta]
- extended_image_library 4.0.5 [crypto flutter http_client_helper js path path_provider web]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.0 [meta path]
- firebase_auth_platform_interface 7.4.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.2.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- fixnum 1.1.0
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.22 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- globbing 1.0.0 [path]
- graphs 2.3.2 [collection]
- html 0.15.4 [csslib source_span]
- http 1.2.2 [async http_parser meta web]
- http_client_helper 3.0.0 [http]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.19.0 [clock meta path]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- logging 1.2.0
- macros 0.1.2-main.4 [_macros]
- matcher 0.12.0
- meta 1.8.0
- mime 1.1.0
- node_preamble 2.0.1
- path 1.9.0
- path_provider 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.0 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.1 [flutter]
- path_provider_windows 2.1.0 [flutter path_provider_platform_interface win32]
- path_provider_macos 2.1.0 [flutter path_provider_platform_interface]
- plugin_platform_interface 2.2.1 [flutter]
- pubspec_parse 1.8.0 [yaml]
- provider 6.1.3 [collection flutter]
- rxdart 0.27.7
- shelf 1.4.0 [async shelf_web_socket]
- shelf_web_socket 1.2.0 [async shelf]
- source_gen 1.3.0 [analyzer build build_config code_builder collection glob meta package_config path]
- source_helper 2.0.0
- sqflite 2.2.7+1 [file path_provider sqlite3]
- stack_trace 1.11.0
- stream_transform 2.2.1
- string_scanner 1.1.1
- testing 0.5.0
- term_glyph 1.2.0
- typed_data 1.1.1
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_linux 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 6.3.0 [flutter]
- url_launcher_web 6.3.0 [flutter url_launcher_platform_interface web]
- url_launcher_windows 6.3.0 [flutter url_launcher_platform_interface win32]
- uuid 3.0.4 [crypto]
- video_player 2.7.1 [flutter ffmpeg_kit flutter_plugin_android_lifecycle]
- visibility_detector 0.3.0 [flutter]
- watcher 1.2.1 [async io]
- win32 6.2.0 [ffi]
- xml 6.0.1 [collection]
- yaml 3.2.1 [collection source_span string_scanner]
```
