### ISSUE TITLE
[Firebase Core]: Android Build failing with latest Flutter SDK 3.24.3  and latest packages 3.4.1

### ISSUE THREAD

**Issue by dgurudot** [firebase/flutterfire#13334]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

Android

### Description

During compile, I get the following errors and this is happening only after upgrade to latest SDK and latest flutter.
I did "flutter clean", "invalidated caches from Android Studio", looked at possible solutions but not able to resolve it.
====================

/Users/vk/.pub-cache/hosted/pub.dev/cloud_firestore-5.4.1/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreRegistrar.java:19: error: cannot find symbol
        LibraryVersionComponent.create(BuildConfig.LIBRARY_NAME, BuildConfig.LIBRARY_VERSION));
                                       ^
  symbol:   variable BuildConfig
  location: class FlutterFirebaseFirestoreRegistrar
/Users/vk/.pub-cache/hosted/pub.dev/cloud_firestore-5.4.1/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreRegistrar.java:19: error: cannot find symbol
        LibraryVersionComponent.create(BuildConfig.LIBRARY_NAME, BuildConfig.LIBRARY_VERSION));
                                                                 ^
  symbol:   variable BuildConfig
  location: class FlutterFirebaseFirestoreRegistrar
2 errors

FAILURE: Build failed with an exception.

==========

Sharing Flutter info:

flutter --version
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (3 days ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

### Reproducing the issue

It's a compile of the simple app with the latest flutter SDK and Firebase libs.

Kindly respond if the error shared is not enough and I will try to create a minimal app and share it here.

### Firebase Core version

^3.4.1

### Flutter Version

3.24.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  firebase_analytics: ^11.3.1
  firebase_auth: ^5.2.1
  firebase_auth_web: ^5.13.0
  firebase_core: ^3.4.1
  firebase_crashlytics: ^4.1.1
  firebase_messaging: ^15.1.1
  firebase_storage: ^12.3.0
  flutter_archive: ^6.0.3
  flutter_credit_card: ^4.0.1
  flutter_device_type: ^0.4.0
  flutter_inappwebview: ^6.0.0
  flutter_expandable_table: ^2.1.0
  flutter_jailbreak_detection: ^1.10.0
  flutter_local_notifications: ^17.2.2
  flutter_mailer: ^2.1.2
  flutter_markdown: ^0.7.3+1
  flutter_pw_validator: ^1.6.0
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.1
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_webview_plugin:
```

</details>

### Additional context and comments

No Additional context
