### ISSUE TITLE
[firebase_core]: Empty APP_CURRENT_USER

### ISSUE THREAD

**Issue by brian-superlist** [firebase/flutterfire#13354]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Auth

### Which platforms are affected?

macOS

### Description

Upgrading firebase plugins results in the user needing to log in again. 

Before the upgrade, we get an `APP_CURRENT_USER` when initializing the core. After update, `APP_CURRENT_USER` is null, which is then forwarded through the stack to our call to `idTokenChanges` which reports a `null` user.

I'm completely open to this being a fault on our side, but I went as far as the call into the ios firebase SDK and I couldn't see what might have changed between these two versions. I also looked at the changelog for the ios firebase sdk and didn't see any mentions of this kind of change. Finally, this does not happen on our iOS app, only macOS. 

Appreciate any help.

### Reproducing the issue

1. Launch app
2. Log in
3. Restart App
4. Inspect `pluginConstants` variable 
5. See data for appConstants.APP_CURRENT_USER
1. Upgrade `firebase_core` from `3.3.0` to `3.4.1`
6. Upgrade `firebase_auth` from `5.1.4` to `5.2.1`
7. Delete `macos/Podfile.lock`
8. Run app to regenerate Podfile
9. Podfile updated with new version of Firebase packages
10. Run app
11. Inspect `pluginConstants` variable
12. NO data for appConstants.APP_CURRENT_USER
13. Firebase does not report initial user
14. User must log in again

### Firebase Core version

3.4.1

### Flutter Version

3.26.0-1.0.pre.36

### Relevant Log Output

```shell
No logs or errors are thrown. The user is simply empty.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.6.0-218.0.dev
Flutter SDK 3.26.0-1.0.pre.36
superlist_workspace 0.0.0

dev dependencies:
- lint 2.3.0

dependency overrides:
- attributed_text 0.3.3 [characters collection logging meta test]
- super_editor 0.3.0-dev.4 [flutter attributed_text characters collection follow_the_leader http linkify logging super_text_layout url_launcher uuid overlord flutter_test flutter_test_robots clock super_sliver_list]
- super_editor_markdown 0.1.6 [flutter super_editor logging markdown]
- super_text_layout 0.1.12 [flutter attributed_text collection logging flutter_test]

super_design 0.0.1

dependencies:
- animations 2.0.11 [flutter]
- collection 1.19.0
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- gap 3.0.1 [flutter]
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- shimmer 3.0.0 [flutter]
- super_editor 0.3.0-dev.4 [flutter attributed_text characters collection follow_the_leader http linkify logging super_text_layout url_launcher uuid overlord flutter_test flutter_test_robots clock super_sliver_list]
- super_text_layout 0.1.12 [flutter attributed_text collection logging flutter_test]
- super_utils 0.0.1 [clock collection flutter rive super_editor universal_platform headless_widgets]

dev dependencies:
- alchemist 0.7.0 [equatable flutter flutter_test meta]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- lint 2.3.0

example 1.0.0+1

dependencies:
- cupertino_icons 1.0.8
- dashbook 0.1.12 [device_frame flutter flutter_colorpicker flutter_markdown shared_preferences url_launcher]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- gap 3.0.1 [flutter]
- super_design 0.0.1 [animations collection flutter flutter_svg gap path_drawing shimmer super_editor super_text_layout super_utils]
- super_utils 0.0.1 [clock collection flutter rive super_editor universal_platform headless_widgets]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- lint 2.3.0

dependency overrides:
- flutter_colorpicker 1.0.3 [flutter]

super_logger 0.0.1

dependencies:
- logging 1.2.0
- super_utils 0.0.1 [clock collection flutter rive super_editor universal_platform headless_widgets]

dev dependencies:
- lint 2.3.0

super_utils 0.0.1

dependencies:
- clock 1.1.1
- collection 1.19.0
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- headless_widgets 0.0.5 [flutter]
- rive 0.13.9 [collection flutter flutter_web_plugins http meta plugin_platform_interface rive_common]
- super_editor 0.3.0-dev.4 [flutter attributed_text characters collection follow_the_leader http linkify logging super_text_layout url_launcher uuid overlord flutter_test flutter_test_robots clock super_sliver_list]
- universal_platform 1.1.0

dev dependencies:
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- lint 2.3.0
- test 1.25.8 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]

superlist 1.15.1+1

dependencies:
- android_content_provider 0.4.2 [flutter async uuid]
- animate_do 3.3.4 [flutter]
- animated_text_kit 4.2.2 [flutter characters]
- animations 2.0.11 [flutter]
- any_link_preview 3.0.2 [flutter flutter_svg html http shared_preferences string_validator url_launcher xml]
- app_links 6.3.2 [flutter app_links_linux app_links_platform_interface app_links_web]
- app_settings 5.1.1 [flutter plugin_platform_interface]
- async 2.11.0 [collection meta]
- audioplayers 6.1.0 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- characters 1.3.0
- chopper 8.0.2 [equatable http logging meta qs_dart]
- clock 1.1.1
- collection 1.19.0
- confetti 0.7.0 [flutter vector_math]
- cronet_http 1.3.2 [flutter http http_profile jni]
- cupertino_http 1.5.1-wip [async ffi flutter http http_profile web_socket]
- device_info_plus 10.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- diffutil_dart 3.0.0
- diffutil_sliverlist 0.5.1 [flutter diffutil_dart]
- dio 5.7.0 [async http_parser meta path dio_web_adapter]
- drift 2.20.2 [async convert collection meta stream_channel sqlite3 path stack_trace web]
- drift_dev 2.20.3 [charcode collection recase meta path json_annotation stream_transform args logging cli_util yaml io drift sqlite3 sqlparser analyzer analyzer_plugin source_span package_config pub_semver build build_resolvers build_config dart_style source_gen string_scanner]
- email_validator 3.0.0
- emoji_picker_flutter 3.0.0 [flutter flutter_web_plugins plugin_platform_interface shared_preferences web]
- equatable 2.0.5 [collection meta]
- fetch_client 1.1.2 [fetch_api http]
- file_selector 1.0.3 [file_selector_android file_selector_ios file_selector_linux file_selector_macos file_selector_platform_interface file_selector_web file_selector_windows flutter]
- firebase_analytics 11.3.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.2.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.4.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 15.1.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 5.1.1 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- fixnum 1.1.0
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_downloader 1.11.8 [flutter]
- flutter_local_notifications 17.2.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_sharing_intent 1.1.1 [flutter plugin_platform_interface]
- flutter_staggered_grid_view 0.7.0 [flutter]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_timezone 3.0.1 [flutter flutter_web_plugins]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- follow_the_leader 0.0.4+8 [flutter logging vector_math]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- gap 3.0.1 [flutter]
- get_it 7.7.0 [async collection meta]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_dartio 0.2.1 [flutter google_sign_in shared_preferences url_launcher meta crypto http html_unescape]
- google_sign_in_web 0.12.4+2 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- home_widget 0.7.0 [flutter path_provider path_provider_foundation]
- html 0.15.4 [csslib source_span]
- http 1.2.2 [async http_parser meta web]
- http_image_provider 0.0.3 [http flutter]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- image_picker_android 0.8.12+12 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- in_app_review 2.0.9 [flutter in_app_review_platform_interface]
- intercom_flutter 8.1.1 [flutter flutter_web_plugins intercom_flutter_platform_interface intercom_flutter_web]
- intl 0.19.0 [clock meta path]
- intl_utils 2.8.7 [analyzer archive args dart_style http intl path petitparser yaml]
- json_annotation 4.9.0 [meta]
- localizely_sdk 2.5.7 [flutter build build_config glob intl http logger path package_info_plus path_provider petitparser shared_preferences uuid web_socket_channel yaml]
- logging 1.2.0
- meta 1.15.0
- mime 1.0.6
- native_dio_adapter 1.3.0 [flutter dio cupertino_http cronet_http http]
- nativeshell 0.1.16 [flutter pedantic]
- nlp 0.0.1 [flutter collection diacritic intl js logging quiver super_native_regex]
- package_info_plus 8.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- path 1.9.0
- path_provider 2.1.4 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- phoenix_socket 0.7.4 [logging rxdart web_socket_channel]
- protobuf 2.1.0 [fixnum collection meta]
- provider 6.1.2 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- purchases_flutter 8.1.1 [flutter freezed_annotation json_annotation]
- quill_delta 3.0.0-nullsafety.2 [collection quiver diff_match_patch]
- quiver 3.2.2 [matcher]
- record 5.1.2 [flutter uuid record_platform_interface record_web record_windows record_linux record_android record_darwin]
- retry 3.1.2
- rive 0.13.9 [collection flutter flutter_web_plugins http meta plugin_platform_interface rive_common]
- routemaster 0.10.0-dev5 [flutter flutter_web_plugins path collection]
- rxdart 0.27.7
- sentry_flutter 8.9.0 [flutter flutter_web_plugins sentry package_info_plus meta ffi file]
- shared_preferences 2.3.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 6.1.2 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sliver_tools 0.2.12 [flutter]
- sqlite3_flutter_libs 0.5.24 [flutter]
- stash 5.2.0 [meta clock async equatable uuid]
- stash_memory 5.2.0 [stash]
- streaming_shared_preferences 2.0.0 [flutter meta shared_preferences]
- super_audio 0.1.0 [flutter super_audio_android super_audio_ios super_audio_macos super_audio_windows super_audio_platform_interface]
- super_clipboard 0.8.22 [flutter collection meta super_native_extensions]
- super_context_menu 0.8.22 [flutter super_native_extensions collection device_info_plus pixel_snap]
- super_design 0.0.1 [animations collection flutter flutter_svg gap path_drawing shimmer super_editor super_text_layout super_utils]
- super_drag_and_drop 0.8.22 [flutter collection super_native_extensions super_clipboard]
- super_editor 0.3.0-dev.4 [flutter attributed_text characters collection follow_the_leader http linkify logging super_text_layout url_launcher uuid overlord flutter_test flutter_test_robots clock super_sliver_list]
- super_editor_markdown 0.1.6 [flutter super_editor logging markdown]
- super_hot_key 0.8.22 [flutter super_native_extensions super_keyboard_layout]
- super_logger 0.0.1 [logging super_utils]
- super_proto_dart 0.0.1 [protobuf]
- super_sliver_list 0.4.1 [flutter collection logging]
- super_text_layout 0.1.12 [flutter attributed_text collection logging flutter_test]
- super_utils 0.0.1 [clock collection flutter rive super_editor universal_platform headless_widgets]
- syncfusion_flutter_core 26.2.14 [vector_math flutter]
- syncfusion_flutter_datepicker 26.2.14 [flutter intl syncfusion_flutter_core]
- timeago 3.7.0 [intl]
- timezone 0.9.4 [path]
- transparent_image 2.0.1
- tuple 2.0.2
- ulid4d 2.0.0 [fixnum meta]
- universal_platform 1.1.0
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.0 [crypto sprintf meta fixnum]
- vector_math 2.1.4
- visibility_detector 0.4.0+2 [flutter]
- web_socket_channel 3.0.1 [async crypto stream_channel web web_socket]

dev dependencies:
- build_runner 2.4.12 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- chopper_generator 8.0.2 [analyzer build built_collection chopper code_builder dart_style logging meta source_gen yaml collection]
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 7.4.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- flutter_test_robots 0.0.24 [flutter flutter_test]
- freezed 2.5.7 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation dart_style]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math webdriver]
- json_serializable 6.8.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- lint 2.3.0
- mockito 5.4.4 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- plugin_platform_interface 2.1.8 [meta]
- sentry_dart_plugin 2.1.0 [yaml injector ansicolor system_info2 file http crypto convert process properties]
- swagger_dart_code_generator 3.0.0 [build path markdown recase json_annotation universal_io collection dart_style code_builder http yaml]
- test 1.25.8 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]

dependency overrides:
- cupertino_http 1.5.1-wip [async ffi flutter http http_profile web_socket]
- flutter_local_notifications_linux 4.0.1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.2.0 [flutter plugin_platform_interface]
- http 1.2.2 [async http_parser meta web]
- uuid 4.5.0 [crypto sprintf meta fixnum]
- web 1.0.0
- web_socket_channel 3.0.1 [async crypto stream_channel web web_socket]

transitive dependencies:
- _fe_analyzer_shared 74.0.0 [meta]
- _flutterfire_internals 1.3.42 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.3
- analyzer 6.9.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.11.3 [analyzer collection dart_style pub_semver yaml]
- ansicolor 2.0.3
- app_links_linux 1.0.3 [flutter app_links_platform_interface gtk]
- app_links_platform_interface 2.0.2 [flutter plugin_platform_interface]
- app_links_web 1.0.4 [flutter flutter_web_plugins app_links_platform_interface web]
- archive 3.6.1 [crypto path]
- args 2.5.0
- audioplayers_android 5.0.0 [audioplayers_platform_interface flutter]
- audioplayers_darwin 6.0.0 [audioplayers_platform_interface flutter]
- audioplayers_linux 4.0.0 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 7.0.0 [collection flutter meta plugin_platform_interface]
- audioplayers_web 5.0.1 [audioplayers_platform_interface flutter flutter_web_plugins web]
- audioplayers_windows 4.0.0 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.2 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- charcode 1.3.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_config 0.2.0 [args yaml]
- cli_util 0.4.1 [meta path]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- convert 3.1.1 [typed_data]
- coverage 1.9.2 [args glob logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.5 [typed_data]
- csslib 1.0.0 [source_span]
- dart_style 2.3.7 [analyzer args collection package_config path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- device_frame 1.2.0 [freezed_annotation flutter]
- device_info_plus_platform_interface 7.0.1 [flutter meta plugin_platform_interface]
- diacritic 0.1.5
- diff_match_patch 0.4.1
- dio_web_adapter 2.0.0 [dio http_parser meta web]
- fetch_api 2.2.0 [web]
- ffi 2.1.3
- file 7.0.0 [meta path]
- file_selector_android 0.5.1+6 [file_selector_platform_interface flutter plugin_platform_interface]
- file_selector_ios 0.5.3 [file_selector_platform_interface flutter]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_web 0.9.4+2 [file_selector_platform_interface flutter flutter_web_plugins web]
- file_selector_windows 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 4.2.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_auth_web 5.13.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.2.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_messaging_platform_interface 4.5.44 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.9.0 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_remote_config_platform_interface 1.4.42 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.7.0 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math]
- flutter_markdown 0.6.10+6 [flutter markdown meta path]
- flutter_plugin_android_lifecycle 2.0.22 [flutter]
- frontend_server_client 4.0.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.1.2 [async collection file path string_scanner]
- globbing 1.0.0 [path]
- google_identity_services_web 0.3.1+4 [meta web]
- google_sign_in_android 6.1.30 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.7 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- graphs 2.3.2 [collection]
- gtk 2.1.0 [ffi flutter meta]
- html_unescape 2.0.0
- http_multi_server 3.2.1 [async]
- http_parser 4.1.0 [collection source_span string_scanner typed_data]
- http_profile 0.1.0
- image_picker_for_web 3.0.5 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_review_platform_interface 2.0.5 [flutter url_launcher plugin_platform_interface platform]
- injector 3.0.0
- intercom_flutter_platform_interface 2.0.0 [flutter plugin_platform_interface]
- intercom_flutter_web 1.1.1 [flutter flutter_web_plugins intercom_flutter_platform_interface uuid web]
- io 1.0.4 [meta path string_scanner]
- irondash_engine_context 0.5.4 [flutter plugin_platform_interface]
- irondash_message_channel 0.7.0 [flutter ffi]
- jni 0.10.1 [args collection ffi package_config path plugin_platform_interface]
- js 0.6.7 [meta]
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- linkify 5.0.0
- logger 2.4.0
- macros 0.1.3-main.0 [_macros]
- markdown 5.0.0 [args charcode meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- native_assets_cli 0.5.4 [cli_config collection crypto logging pub_semver yaml]
- native_regex_js 0.0.1 [flutter logging]
- native_regex_pcre2 0.0.1 [flutter cli_config logging native_assets_cli native_toolchain_c ffi]
- native_toolchain_c 0.4.1 [glob logging meta native_assets_cli pub_semver]
- nested 1.0.0 [flutter]
- node_preamble 2.0.2
- octo_image 2.1.0 [flutter]
- overlord 0.0.3+5 [flutter collection follow_the_leader logging]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 3.0.1 [flutter meta plugin_platform_interface]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.10 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- pedantic 1.11.1
- petitparser 6.0.2 [meta]
- pixel_snap 0.1.5 [flutter]
- platform 3.1.5
- pool 1.5.1 [async stack_trace]
- process 5.0.2 [file path platform]
- properties 2.1.1 [meta]
- pubspec_parse 1.3.0 [checked_yaml collection json_annotation pub_semver yaml]
- qs_dart 1.2.3 [collection equatable meta recursive_regex weak_map]
- recase 4.1.0
- record_android 1.2.6 [flutter record_platform_interface]
- record_darwin 1.1.2 [flutter record_platform_interface]
- record_linux 0.7.2 [flutter record_platform_interface]
- record_platform_interface 1.1.0 [flutter plugin_platform_interface]
- record_web 1.1.3 [flutter flutter_web_plugins web record_platform_interface]
- record_windows 1.0.3 [flutter record_platform_interface]
- recursive_regex 1.0.0 [meta]
- rive_common 0.4.9 [collection ffi flutter flutter_web_plugins graphs http meta plugin_platform_interface web]
- sentry 8.9.0 [http meta stack_trace uuid]
- shared_preferences_android 2.3.2 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.3 [convert http_parser mime path shelf]
- shelf_web_socket 2.0.0 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.1.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 2.1.0 [flutter flutter_web_plugins sign_in_with_apple_platform_interface]
- sky_engine 0.0.0
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_map_stack_trace 2.1.2 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.3+1 [flutter sqflite_common path]
- sqflite_common 2.5.4+3 [synchronized path meta]
- sqlite3 2.4.6 [collection ffi meta path web]
- sqlparser 0.38.1 [meta collection source_span charcode]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.3.0 [source_span]
- string_validator 1.1.0
- super_audio_android 0.1.0 [flutter super_audio_platform_interface]
- super_audio_ios 0.1.0 [flutter super_audio_platform_interface]
- super_audio_macos 0.1.0 [flutter super_audio_platform_interface]
- super_audio_platform_interface 0.1.0 [flutter plugin_platform_interface]
- super_audio_windows 0.0.1 [flutter super_audio_platform_interface]
- super_keyboard_layout 0.8.22 [flutter super_native_extensions]
- super_native_extensions 0.8.22 [flutter flutter_web_plugins meta ffi collection path uuid irondash_engine_context irondash_message_channel device_info_plus pixel_snap web]
- super_native_regex 0.0.1 [flutter logging native_regex_js native_regex_pcre2]
- sync_http 0.3.1
- synchronized 3.3.0+2
- system_info2 4.0.0 [globbing path]
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.6.5 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.3.9 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.2 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vm_service 14.2.5
- watcher 1.1.0 [async path]
- weak_map 3.0.1
- web_socket 0.1.6 [web]
- webdriver 3.0.3 [matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.2.1 [logging]
- win32 5.5.4 [ffi]
- win32_registry 1.1.5 [ffi win32]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>
