### ISSUE TITLE
[firebase_ crashlytics]: iOS build failing on PrecompileModule

### ISSUE THREAD

**Issue by SincerelyFaust** [firebase/flutterfire#13374]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

iOS

### Description

This started happening once I upgraded my macOS, iOS and XCode to latest when iOS 18 dropped, before it was building for iOS just fine.

### Reproducing the issue

Run Flutter build command for iOS
Get the error

### Firebase Core version

2.27.0

### Flutter Version

3.16.9

### Relevant Log Output

```shell
** BUILD FAILED **


                     The following build commands failed:
                        PrecompileModule
                        /Users/faust/Library/Developer/Xcode/DerivedData/Runner-dzovwzbdkyofmecrohgwwimefcjd/Build/Intermediates.noindex/ExplicitPrecompiledModules/firebase_
                        crashlytics-9M6FB9SB7H49MJ3DBJ7KP0KHC.scan
                        Building workspace Runner with scheme product and configuration Release-product
                     (2 failures)
[+7601 ms]  └─Compiling, linking and signing... (completed in 20,6s)
[   +1 ms] Xcode build done.                                           149,9s
[   +6 ms] executing: /usr/bin/arch -arm64e xcrun xcresulttool get --path
/var/folders/g4/zrzdtr191xb3dj1byxn22hz40000gn/T/flutter_tools.0bj8kd/flutter_ios_build_temp_dirW3s8Ku/temporary_xcresult_bundle --format json
[  +53 ms] Error: This command is deprecated and will be removed in a future release, --legacy flag is required to use it.
           Usage: xcresulttool get object [--legacy] --path <path> [--id <id>] [--version <version>] [--format <format>]
             See 'xcresulttool get object --help' for more information.
[   +3 ms] Failed to build iOS app
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.2.6
Flutter SDK 3.16.9
ivault 2.3.3

dependencies:
- adaptive_dialog 2.1.0 [animations collection dynamic_color flutter intersperse macos_ui meta]
- animated_size_and_fade 3.0.1 [flutter]
- animations 2.0.11 [flutter]
- auto_size_text 3.0.0 [flutter]
- bip39_mnemonic 3.0.6 [pointycastle unorm_dart]
- blur 3.1.0 [flutter]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- camera 0.10.6 [camera_android camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle]
- camera_avfoundation 0.9.17+3 [camera_platform_interface flutter stream_transform]
- chewie 1.7.5 [cupertino_icons flutter provider video_player wakelock_plus]
- collection 1.18.0
- confetti 0.7.0 [flutter vector_math]
- country_code_picker 3.0.0 [flutter collection]
- country_picker 2.0.26 [collection universal_io flutter]
- crypto 3.0.3 [typed_data]
- cryptography 2.7.0 [collection crypto ffi js meta typed_data]
- cryptography_flutter 2.3.2 [cryptography flutter]
- delightful_toast 1.1.0 [flutter flutter_animate]
- dio 5.7.0 [async http_parser meta path dio_web_adapter]
- dio_cache_interceptor 3.5.0 [dio uuid string_scanner]
- dotted_border 2.1.0 [flutter path_drawing]
- dropdown_button2 2.3.9 [flutter meta]
- easy_localization 3.0.7 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- easy_localization_loader 2.0.2 [connectivity_plus csv easy_localization flutter http path_provider xml yaml]
- equatable 2.0.5 [collection meta]
- expandable_page_view 1.0.17 [flutter]
- firebase_core 2.27.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.18 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 14.7.19 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flex_list 1.0.0 [flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_dotenv 5.1.0 [flutter]
- flutter_expandable_fab 2.3.0 [flutter]
- flutter_fgbg 0.4.0 [flutter]
- flutter_html 3.0.0-beta.2 [html csslib collection list_counter flutter]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_local_notifications 14.1.5 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_map 6.1.0 [async collection flutter http latlong2 logger meta polylabel proj4dart vector_math]
- flutter_map_cancellable_tile_provider 2.0.0 [dio flutter flutter_map meta]
- flutter_portal 1.1.4 [collection flutter vector_math]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_screen_lock 9.0.1 [flutter]
- flutter_secure_storage 9.2.2 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_spinkit 5.2.1 [flutter]
- flutter_staggered_animations 1.1.1 [flutter]
- flutter_stripe 11.1.0 [flutter meta stripe_android stripe_ios stripe_platform_interface]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_timer_countdown 1.0.7 [flutter]
- flutter_timezone 1.0.8 [flutter_web_plugins flutter js]
- fuzzywuzzy 1.2.0 [collection]
- fvm 3.1.7 [args date_format git interact io mason_logger meta path pub_semver pub_updater scope yaml dart_console tint stack_trace pubspec jsonc dart_mappable cli_completion]
- geocoding 2.1.1 [flutter geocoding_platform_interface geocoding_android geocoding_ios]
- geolocator 10.1.1 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get 4.6.6 [flutter]
- glowy_borders 1.0.2 [flutter]
- go_router 12.1.3 [collection flutter flutter_web_plugins logging meta]
- gradient_borders 1.0.1 [flutter]
- image 4.2.0 [archive meta xml]
- image_picker 1.0.8 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- insta_image_viewer 1.0.4 [flutter cached_network_image]
- instabug_flutter 12.7.0 [flutter meta stack_trace]
- intl 0.18.1 [clock meta path]
- latlong2 0.9.1 [intl]
- like_button 2.0.5 [flutter]
- local_auth 2.3.0 [flutter local_auth_android local_auth_darwin local_auth_platform_interface local_auth_windows]
- logger 2.4.0
- lottie 2.7.0 [archive flutter path vector_math]
- mixpanel_flutter 2.3.2 [flutter flutter_web_plugins js]
- mobile_scanner 4.0.1 [flutter flutter_web_plugins js]
- modal_bottom_sheet 3.0.0-pre [flutter]
- moment_dart 2.2.1+beta.0
- open_settings_plus 0.3.3 [flutter plugin_platform_interface]
- overlay_kit 1.0.8 [flutter back_button_interceptor]
- package_info_plus 4.2.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- percent_indicator 4.2.3 [flutter]
- pretty_qr_code 3.3.0 [flutter qr meta]
- rating_summary 1.0.3+1 [flutter flutter_rating_bar]
- rxdart 0.27.7
- sensors_plus 4.0.2 [flutter flutter_web_plugins sensors_plus_platform_interface]
- share_plus 7.2.2 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- shared_preferences 2.2.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 3.0.0 [flutter]
- shuftipro_onsite_sdk 1.0.5 [flutter]
- simple_animations 5.0.2 [flutter collection]
- skeletonizer 1.4.2 [collection flutter]
- smooth_page_indicator 1.2.0+3 [flutter]
- speech_balloon 0.0.4 [flutter]
- store_checker 1.6.0 [flutter]
- syncfusion_flutter_charts 24.2.9 [flutter intl vector_math syncfusion_flutter_core]
- syncfusion_flutter_core 24.2.9 [vector_math flutter]
- timeago 3.7.0 [intl]
- tuple 2.0.2
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.9.1 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- web3dart 2.7.2 [pointycastle sec http uuid json_rpc_2 stream_transform stream_channel eip55 eip1559 typed_data convert async wallet]
- web_socket_channel 2.4.0 [async crypto stream_channel]
- widget_and_text_animator 1.1.5 [flutter]
- zoom_tap_animation 1.1.0 [flutter]

dependency overrides:
- js 0.7.1
- stream_channel 2.1.2 [async]

transitive dependencies:
- _flutterfire_internals 1.3.25 [collection firebase_core firebase_core_platform_interface flutter meta]
- appkit_ui_element_colors 1.0.0 [equatable flutter plugin_platform_interface]
- archive 3.6.1 [crypto path]
- args 2.5.0
- async 2.11.0 [collection meta]
- back_button_interceptor 6.0.2 [collection flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.2.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- camera_android 0.10.9+2 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]
- camera_platform_interface 2.8.0 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.4 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_completion 0.5.0 [args equatable mason_logger meta path]
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- connectivity_plus 6.0.3 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+8 [meta web]
- csslib 0.17.3 [source_span]
- csv 6.0.0
- cupertino_icons 1.0.8
- dart_console 1.2.0 [ffi win32 intl characters]
- dart_mappable 4.2.2 [collection meta type_plus]
- date_format 2.0.9
- dbus 0.7.10 [args ffi meta xml]
- dio_web_adapter 1.0.1 [dio http_parser meta]
- dynamic_color 1.7.0 [flutter flutter_test material_color_utilities]
- easy_logger 0.0.2 [flutter]
- eip1559 0.6.2 [http]
- eip55 1.0.2 [pointycastle]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_crashlytics_platform_interface 3.6.25 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.27 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.6.8 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta web]
- fixnum 1.1.0
- flutter_animate 4.5.0 [flutter flutter_shaders]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_local_notifications_linux 4.0.1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.2.0 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_plugin_android_lifecycle 2.0.19 [flutter]
- flutter_secure_storage_linux 1.2.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.1.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.2.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.1.2 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_shaders 0.1.2 [flutter vector_math]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- geocoding_android 2.1.2 [flutter geocoding_platform_interface]
- geocoding_ios 2.1.1 [flutter geocoding_platform_interface]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- geolocator_android 4.6.1 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.4 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.2.1 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.2.3 [flutter geolocator_platform_interface]
- git 2.2.1 [path]
- html 0.15.4 [csslib source_span]
- http 1.2.0 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.9+6 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.2 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.3 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- interact 2.2.0 [dart_console meta tint]
- intersperse 2.0.0
- io 1.0.4 [meta path string_scanner]
- json_annotation 4.9.0 [meta]
- json_rpc_2 3.0.2 [stack_trace stream_channel]
- jsonc 0.0.3
- list_counter 1.0.2
- lists 1.0.1 [meta]
- local_auth_android 1.0.38 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_darwin 1.4.0 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.10 [flutter plugin_platform_interface]
- local_auth_windows 1.0.11 [flutter local_auth_platform_interface]
- logging 1.2.0
- macos_ui 2.0.9 [flutter macos_window_utils gradient_borders appkit_ui_element_colors equatable]
- macos_window_utils 1.5.0 [flutter]
- mason_logger 0.2.14 [ffi io win32]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- mgrs_dart 2.0.0 [unicode]
- mime 1.0.6
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.1.0 [flutter]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.4 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.4 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.5
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.9.1 [collection convert js]
- polylabel 1.0.1 [collection]
- process 5.0.2 [file path platform]
- proj4dart 2.1.0 [mgrs_dart wkt_parser meta]
- provider 6.1.2 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pub_updater 0.4.0 [http json_annotation process pub_semver]
- pubspec 2.3.0 [path pub_semver yaml uri]
- qr 3.0.1 [meta]
- quiver 3.2.2 [matcher]
- scope 4.1.1 [meta]
- sec 1.1.0 [pointycastle]
- sensors_plus_platform_interface 1.2.0 [flutter logging meta plugin_platform_interface]
- share_plus_platform_interface 3.4.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.2.2 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.2 [flutter sqflite_common path]
- sqflite_common 2.5.3 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- stripe_android 11.1.0 [flutter]
- stripe_ios 11.1.0 [flutter]
- stripe_platform_interface 11.1.1 [flutter freezed_annotation json_annotation meta plugin_platform_interface]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.4 [path]
- tint 2.0.1
- type_plus 2.1.1
- typed_data 1.3.2 [collection]
- unicode 0.3.1 [lists]
- universal_io 2.2.2 [collection meta typed_data]
- unorm_dart 0.2.0
- uri 1.0.0 [matcher quiver]
- url_launcher_android 6.3.2 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.2.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.2 [flutter url_launcher_platform_interface]
- uuid 4.5.0 [crypto sprintf meta fixnum]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- video_player_android 2.4.14 [flutter video_player_platform_interface]
- video_player_avfoundation 2.6.1 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.1.3 [flutter flutter_web_plugins video_player_platform_interface]
- wakelock_plus 1.1.6 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus js]
- wakelock_plus_platform_interface 1.1.0 [flutter plugin_platform_interface meta]
- wallet 0.0.13 [convert eip55 pointycastle sec]
- web 0.3.0
- win32 5.2.0 [ffi]
- wkt_parser 2.0.0
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>
