### ISSUE TITLE
firebase_auth: The method 'getMappedHost' isn't defined for the class 'FirebaseAuth'

### ISSUE THREAD

**Issue by daviddavis83** [firebase/flutterfire#13419]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Description

This week I upgraded my Macbook to Sequoia 15.0 which updated my xcode version to 16.0. After that I was unable to build my existing flutter app. I ran `flutter pub upgrade` to pull in any new packages and then I started getting the following error

```
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/firebase_auth-5.3.1/lib/src/firebase_auth.dart:86:48: Error: The method 'getMappedHost' isn't defined for the class 'FirebaseAuth'.
```

### Steps I tried

1. `flutter clean && flutter pub get`
2. `cd ios && rm -rf Pods && rm Podfile.lock && pod repo update && pod install`
3. `flutter pub cache repair`
4. Closing and reopening xcode
5. I also tried upgrading my cocoapods version

### Reproducing the issue

To reproduce update firebase_auth to 5.3.1 and firebase_core to 3.6.0. Also update xcode to version 16 and try to run the app in debug. 

### Firebase Core version

3.6.0

### Flutter Version

3.24.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.3
Flutter SDK 3.24.3

dependencies:
- app_tracking_transparency 2.0.6 [flutter]
- awesome_notifications 0.9.3+1 [flutter flutter_web_plugins plugin_platform_interface intl]
- awesome_notifications_fcm 0.9.3+1 [flutter firebase_core firebase_crashlytics awesome_notifications]
- badges 3.1.2 [flutter]
- cloud_firestore 4.17.5 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- collection 1.18.0
- cupertino_icons 1.0.8
- data_table_2 2.5.15 [flutter async]
- dropdown_button2 2.3.9 [flutter meta]
- firebase_auth 5.3.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.32.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.5.7 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_storage 11.7.7 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_config 2.0.2 [flutter]
- flutter_datetime_picker 1.5.1 [flutter]
- flutter_inappwebview 6.1.1 [flutter flutter_inappwebview_platform_interface flutter_inappwebview_android flutter_inappwebview_ios flutter_inappwebview_macos flutter_inappwebview_web flutter_inappwebview_windows]
- flutter_secure_storage 9.2.2 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_slidable 3.1.1 [flutter]
- flutter_timezone 3.0.1 [flutter flutter_web_plugins]
- font_awesome_flutter 10.7.0 [flutter]
- fraction 5.0.3
- get_it 7.7.0 [async collection meta]
- get_it_mixin 4.2.2 [flutter functional_listener get_it]
- google_mobile_ads 5.1.0 [meta flutter webview_flutter_android webview_flutter_wkwebview webview_flutter]
- http 1.2.2 [async http_parser meta web]
- in_app_purchase 3.2.0 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- in_app_purchase_storekit 0.3.18+1 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_review 2.0.9 [flutter in_app_review_platform_interface]
- intl 0.19.0 [clock meta path]
- intl_phone_field 3.1.0 [flutter]
- json_annotation 4.9.0 [meta]
- json_diff 0.2.1 [collection diff_match_patch]
- loading_animation_widget 1.2.1 [flutter]
- modal_bottom_sheet 3.0.0 [flutter]
- path 1.9.0
- path_provider 2.1.4 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- pdf 3.11.1 [archive barcode bidi crypto image meta path_parsing vector_math xml]
- printing 5.13.3 [ffi flutter flutter_web_plugins http image meta pdf pdf_widget_wrapper plugin_platform_interface web]
- provider 6.1.2 [collection flutter nested]
- regexed_validator 2.0.0+1
- remove_emoji 0.0.10
- rrule 0.2.16 [collection intl meta time]
- syncfusion_flutter_pdfviewer 27.1.50 [flutter vector_math async http uuid device_info_plus intl syncfusion_pdfviewer_platform_interface syncfusion_pdfviewer_web syncfusion_pdfviewer_macos syncfusion_pdfviewer_windows syncfusion_flutter_core syncfusion_flutter_pdf syncfusion_flutter_signaturepad url_launcher]
- textfield_tags 3.0.1 [flutter]
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.1 [crypto sprintf meta fixnum]

dev dependencies:
- build_runner 2.4.12 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- firebase_auth_mocks 0.14.1 [flutter firebase_auth firebase_core meta equatable dart_jsonwebtoken uuid firebase_auth_platform_interface mock_exceptions]
- flutter_launcher_icons 0.14.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math webdriver]
- json_serializable 6.8.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mocktail 1.0.4 [collection matcher test_api]
- rename 3.0.2 [args logger path]

dependency overrides:
- firebase_core 2.32.0 [firebase_core_platform_interface firebase_core_web flutter meta]

transitive dependencies:
- _fe_analyzer_shared 72.0.0 [meta]
- _flutterfire_internals 1.3.44 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.2
- adaptive_number 1.0.0 [fixnum]
- analyzer 6.7.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- archive 3.6.1 [crypto path]
- args 2.5.0
- async 2.11.0 [collection meta]
- barcode 2.2.8 [meta qr]
- bidi 2.0.12
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.2 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.4.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.12.5 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- convert 3.1.1 [typed_data]
- crypto 3.0.5 [typed_data]
- dart_jsonwebtoken 2.14.0 [crypto pointycastle convert collection ed25519_edwards clock]
- dart_style 2.3.7 [analyzer args collection package_config path pub_semver source_span]
- device_info_plus 10.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- device_info_plus_platform_interface 7.0.1 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- ed25519_edwards 0.3.1 [collection crypto convert adaptive_number]
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.0 [meta path]
- firebase_auth_platform_interface 7.4.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.44 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_platform_interface 5.1.31 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.10.2 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http meta web]
- fixnum 1.1.0
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math]
- flutter_inappwebview_android 1.1.0+3 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_internal_annotations 1.1.1
- flutter_inappwebview_ios 1.1.0+2 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_macos 1.1.0+2 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_platform_interface 1.1.0+1 [flutter flutter_inappwebview_internal_annotations plugin_platform_interface]
- flutter_inappwebview_web 1.1.0+1 [flutter flutter_web_plugins web flutter_inappwebview_platform_interface]
- flutter_inappwebview_windows 0.2.0 [flutter flutter_inappwebview_platform_interface]
- flutter_secure_storage_linux 1.2.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.1.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.2.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.1.2 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- functional_listener 2.3.1 [flutter]
- glob 2.1.2 [async collection file path string_scanner]
- graphs 2.3.2 [collection]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.2.0 [archive meta xml]
- in_app_purchase_android 0.3.6+8 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.4.0 [flutter plugin_platform_interface]
- in_app_review_platform_interface 2.0.5 [flutter url_launcher plugin_platform_interface platform]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.0.0
- logger 2.4.0
- logging 1.2.0
- macros 0.1.2-main.4 [_macros]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 1.0.6
- mock_exceptions 0.8.2 [matcher]
- nested 1.0.0 [flutter]
- package_config 2.1.0 [path]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.10 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- pdf_widget_wrapper 1.0.4 [flutter pdf]
- petitparser 6.0.2 [meta]
- platform 3.1.5
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.9.1 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 5.0.2 [file path platform]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.3.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.2 [meta]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 2.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- sync_http 0.3.1
- syncfusion_flutter_core 27.1.50 [vector_math flutter]
- syncfusion_flutter_pdf 27.1.50 [flutter intl xml syncfusion_flutter_core crypto convert http]
- syncfusion_flutter_signaturepad 27.1.50 [flutter syncfusion_flutter_core]
- syncfusion_pdfviewer_macos 27.1.50 [flutter syncfusion_pdfviewer_platform_interface]
- syncfusion_pdfviewer_platform_interface 27.1.50 [flutter plugin_platform_interface]
- syncfusion_pdfviewer_web 27.1.50 [flutter flutter_web_plugins js meta syncfusion_pdfviewer_platform_interface]
- syncfusion_pdfviewer_windows 27.1.50 [flutter]
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- time 2.1.4 [clock]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.3.10 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.2 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- vm_service 14.2.5
- watcher 1.1.0 [async path]
- web 1.1.0
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.1 [async crypto stream_channel web web_socket]
- webdriver 3.0.3 [matcher path stack_trace sync_http]
- webview_flutter 4.9.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 3.16.7 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.15.0 [flutter path webview_flutter_platform_interface]
- win32 5.5.4 [ffi]
- win32_registry 1.1.5 [ffi win32]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

<details>
<summary>Expand <code>pubspec.yaml</code> snippet</summary>
<br>

```yaml
environment:
  sdk: ">=3.0.0 <3.10.0"

dependencies:
  app_tracking_transparency: ^2.0.4
  awesome_notifications: ^0.9.3+1
  awesome_notifications_fcm: ^0.9.3+1
  badges: ^3.1.2
  collection: ^1.17.1
  cupertino_icons: ^1.0.6
  data_table_2: ^2.5.8
  dropdown_button2: ^2.3.9
  # Firebase
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^3.3.5
  firebase_storage: ^11.2.6
  # End Firebase
  flutter:
    sdk: flutter
  flutter_datetime_picker: 
    git: 
      url: https://github.com/ryojiro/flutter_datetime_picker.git 
      ref: 32ea47240c10469ad31db0084f5d9b7a12d16e01
  flutter_inappwebview: ^6.0.0
  flutter_secure_storage: ^9.1.1
  flutter_config: ^2.0.2
  flutter_slidable: ^3.0.0
  flutter_timezone: ^3.0.1
  font_awesome_flutter: ^10.5.0
  fraction: ^5.0.2
  get_it: ^7.6.4
  get_it_mixin: ^4.2.2
  google_mobile_ads: ^5.1.0
  http: ^1.2.1
  in_app_purchase: ^3.1.10
  in_app_purchase_storekit: ^0.3.6+7
  in_app_review: ^2.0.6
  intl: ^0.19.0
  intl_phone_field:
    git:
      url: https://github.com/Anan-Saadi/intl_phone_field.git
      ref: master
  json_annotation: ^4.8.1
  json_diff: ^0.2.1
  loading_animation_widget: ^1.2.0+4
  modal_bottom_sheet: ^3.0.0-pre
  path: ^1.8.3
  path_provider: ^2.1.1
  cloud_firestore: ^4.9.1
  provider: ^6.0.5
  pdf: ^3.10.4
  printing: ^5.11.0
  remove_emoji: ^0.0.10
  regexed_validator: ^2.0.0+1
  textfield_tags: ^3.0.1
  rrule: ^0.2.16
  syncfusion_flutter_pdfviewer: ^27.1.50
  url_launcher: ^6.1.14
  uuid: ^4.4.0

dependency_overrides: 
  firebase_core: ^2.27.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  rename: ^3.0.1
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  mocktail: ^1.0.0
  firebase_auth_mocks: ^0.14.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
          weight: 900

```

</details>
