### ISSUE TITLE
[firebase_auth]: Using Google Sign in on iOS 18 Simulator returns blank screen

### ISSUE THREAD

**Issue by hls-app** [firebase/flutterfire#13420]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

The Sign in with Google works perfectly on iOS 17 but looks like there is an issue with iOS 18 simulator. Actual device running iOS 18 is fine though.

### Reproducing the issue

To reproduce, simply tap on the Sign in with Google button on an iOS 18 simulator and you can see the native sheet goes beyond the normal setting and shows a blank screen. Interestingly, there were no errors or exceptions thrown in the Flutter Console. However, I did find there was an error message "Unknown client: appname" when running using Xcode.

### Firebase Core version

3.6.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
Unknown client: appname
```

### Flutter dependencies

```yaml
  firebase_auth: ^5.3.1
  firebase_auth_platform_interface: ^7.4.7
  firebase_core: ^3.6.0
  firebase_core_platform_interface: ^5.3.0
  google_sign_in: ^6.2.1
```

### Additional context and comments

![Simulator Screenshot - iPhone 16 - 2024-09-27 at 12 03 42](https://github.com/user-attachments/assets/26ede9f3-611c-41f4-ab2b-312d8d1eb41f)

As you can see after the alert box, instead of opening the native sheet normally, it goes all the way up and shows blank.
