### ISSUE TITLE
[firebase_core]: <Cannot enable Swift Package Manager>

### ISSUE THREAD

**Issue by WTPieh** [firebase/flutterfire#13469]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

iOS

### Description

During work on one of my projects, I stopped the project, and then restarted it. I was immediately met with the message
```
Plugin firebase_core is only Swift Package Manager compatible. Try
enabling Swift Package Manager by running "flutter config
--enable-swift-package-manager" or remove the plugin as a dependency.
```
I thought, okay, I'll just type in `flutter config --enable-swift-package-manager` and i'll be fine and dandy. It printed out 
```
Setting "enable-swift-package-manager" value to "true".

You may need to restart any open editors for them to read new settings.
```

I figured I was fine, so I closed Xcode and iTerm2 running my dart instance. I restarted, and was met with the same response. I tried removing the package from dependencies, and adding them back. Always met with the same message. I tried pod deintegrate and pod install, and still no bacon. I went online and found some old article about adding firebase sdk as a dependency into the Xcode package manager, installed it all, and still nothing was working. I tried opening up a brand new project, adding firebase_core sdk to it, and still met with the same issue, and yet I still attempted to do the `flutter config --enable-swift-package-manager`. Nothing. I have been trying to fix for hours now and I finally give up. Hoping anyone can help me with this.

### Reproducing the issue

1. flutter create test
2. cd test
3. flutter pub add firebase_core
4. flutter run
5. Wait for console output

### Firebase Core version

3.6.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (4 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3


Plugin firebase_core is only Swift Package Manager compatible. Try
enabling Swift Package Manager by running "flutter config
--enable-swift-package-manager" or remove the plugin as a dependency.

flutter config --enable-swift-package-manager
Setting "enable-swift-package-manager" value to "true".

You may need to restart any open editors for them to read new settings.
```

### Flutter dependencies

<details>
<summary>Expand <code>Original Flutter dependencies</code> snippet</summary>
<br>

```yaml
  flutter_platform_widgets: ^7.0.1
  http: ^1.2.2
  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.4.2
  provider: ^6.1.1
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.2
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  package_info_plus: ^8.0.2
  barcode: ^2.2.8
  flutter_svg: ^2.0.10+1
  barcode_widget: ^2.0.4
  path_provider: ^2.1.3
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.3
  restart_app: ^1.2.1
  url_launcher: ^6.1.8
  screen_brightness: ^1.0.1
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  cloud_functions: ^5.1.3
  google_nav_bar: ^5.0.6

```

</details>
<details>
<summary>Expand <code>Test Flutter dependencies</code> snippet</summary>
<br>

```yaml
  cupertino_icons: ^1.0.2
  firebase_core: ^3.6.0
```

</details>
