### ISSUE TITLE
[firebase_messaging]: When I upgraded FCM to v1, the number of arrivals was dropped a lot

### ISSUE THREAD

**Issue by zeqinjie** [firebase/flutterfire#13550]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

In-App Messaging

### Which platforms are affected?

iOS

### Description

When I upgraded FCM to v1, the number of arrivals was dropped a lot[link](https://firebase.google.com/docs/cloud-messaging/migrate-v1?hl=zh-cn)

### Reproducing the issue

```
@interface NotificationService ()<NSURLSessionDelegate>

@property (nonatomic, strong) void (^contentHandler)(UNNotificationContent *contentToDeliver);
@property (nonatomic, strong) UNMutableNotificationContent *bestAttemptContent;

@end

@implementation NotificationService


- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {
    
    self.contentHandler = contentHandler;
    self.bestAttemptContent = [request.content mutableCopy];
    
    ...

    NSDictionary *userInfo = request.content.userInfo;
    
    // Interface for reporting arrival statistics
    [NotifyStatTool sendFcmPushStatAction: userInfo];
    self.contentHandler(self.bestAttemptContent);
}

- (void)serviceExtensionTimeWillExpire {
    self.contentHandler(self.bestAttemptContent);
}
@end


```

### Firebase Core version

2.29.0

### Flutter Version

3.19.6

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  firebase_core: 2.29.0 # ^2.24.2
  firebase_messaging: ^14.7.8 
  firebase_performance: ^0.9.3+8 
  firebase_crashlytics: ^3.4.9 
  firebase_dynamic_links: ^5.5.1
  firebase_messaging: ^14.7.8
```

</details>
