### ISSUE TITLE
[Firebase/Performance]: firebase_performance 0.10.0-8 does not play nice with firebase_core

### ISSUE THREAD

**Issue by oneForCode** [firebase/flutterfire#13556]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Performance

### Which platforms are affected?

iOS

### Description

I was building in Codemagic:

    [!] CocoaPods could not find compatible versions for pod "FirebaseCore":
      In Podfile:
        firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 3.6.0, which depends on
          Firebase/CoreOnly (= 11.2.0) was resolved to 11.2.0, which depends on
            FirebaseCore (= 11.2.0)

        firebase_performance (from `.symlinks/plugins/firebase_performance/ios`) was resolved to 0.10.0-8, which depends on
          Firebase/Performance (= 11.2.0) was resolved to 11.2.0, which depends on
            FirebasePerformance (~> 11.2.0) was resolved to 11.2.0, which depends on
              FirebaseCore (~> 11.0)

### Reproducing the issue

building for iOS in Codemagic

### Firebase Core version

3.6.0

### Flutter Version

 3.24.2

### Relevant Log Output

```shell
[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
      In Podfile:
        firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 3.6.0, which depends on
          Firebase/CoreOnly (= 11.2.0) was resolved to 11.2.0, which depends on
            FirebaseCore (= 11.2.0)

        firebase_performance (from `.symlinks/plugins/firebase_performance/ios`) was resolved to 0.10.0-8, which depends on
          Firebase/Performance (= 11.2.0) was resolved to 11.2.0, which depends on
            FirebasePerformance (~> 11.2.0) was resolved to 11.2.0, which depends on
              FirebaseCore (~> 11.0)
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ai_barcode_scanner: ^5.2.2
  audio_session: 0.1.21
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  cloud_firestore: 5.4.4
  cloud_firestore_platform_interface: 6.4.3
  cloud_firestore_web: 4.3.2
  cloud_functions: 5.1.3
  cloud_functions_platform_interface: 5.5.37
  cloud_functions_web: 4.10.2
  collection: 1.18.0
  csslib: 0.17.3
  easy_debounce: 2.0.1
  file_picker: 8.1.2
  firebase_auth: 5.3.1
  firebase_auth_platform_interface: 7.4.7
  firebase_auth_web: 5.13.2
  firebase_core: 3.6.0
  firebase_core_platform_interface: 5.3.0
  firebase_core_web: 2.18.1
  firebase_crashlytics: 4.1.3
  firebase_crashlytics_platform_interface: 3.6.44
  firebase_performance: 0.10.0+8
  firebase_performance_platform_interface: 0.1.4+44
  firebase_performance_web: 0.1.7+2
  firebase_remote_config: 5.1.3
  firebase_remote_config_platform_interface: 1.4.44
  firebase_remote_config_web: 1.7.2
  firebase_storage: 12.3.2
  firebase_storage_platform_interface: 5.1.31
  firebase_storage_web: 3.10.2
  flutter_animate: 4.5.0
  flutter_barcode_scanner: 
    git:
      url: https://github.com/FlutterFlow/flutter_barcode_scanner
      ref: v2.0.0
  flutter_cache_manager: 3.4.1
  flutter_keyboard_visibility: 6.0.0
  flutter_keyboard_visibility_linux: 1.0.0
  flutter_keyboard_visibility_macos: 1.0.0
  flutter_keyboard_visibility_platform_interface: 2.0.0
  flutter_keyboard_visibility_web: 2.0.0
  flutter_keyboard_visibility_windows: 1.0.0
  flutter_plugin_android_lifecycle: 2.0.20
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  google_sign_in: 6.2.1
  google_sign_in_android: 6.1.30
  google_sign_in_ios: 5.7.7
  google_sign_in_platform_interface: 2.4.5
  google_sign_in_web: 0.12.4+2
  html: 0.15.4
  image_picker: 1.1.2
  image_picker_android: 0.8.12+13
  image_picker_for_web: 3.0.5
  image_picker_ios: 0.8.12
  image_picker_linux: 0.2.1+1
  image_picker_macos: 0.2.1+1
  image_picker_platform_interface: 2.10.0
  image_picker_windows: 0.2.1+1
  internet_connection_checker_plus: ^2.5.2
  intl: 0.19.0
  json_path: 0.7.2
  just_audio: 0.9.40
  just_audio_platform_interface: 4.3.0
  just_audio_web: 0.4.12
  mime_type: 1.0.0
  package_info_plus: ^8.0.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.2.1
  plugin_platform_interface: 2.1.8
  pointer_interceptor: ^0.10.1+2
  pointer_interceptor_ios: 0.10.1
  pointer_interceptor_platform_interface: 0.10.0+1
  pointer_interceptor_web: 0.10.2+1
  provider: 6.1.2
  rxdart: 0.27.7
  share_plus: 10.0.2
  share_plus_platform_interface: 5.0.0
  shared_preferences: 2.3.2
  shared_preferences_android: 2.3.2
  shared_preferences_foundation: 2.5.2
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.2
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: 6.1.2
  sign_in_with_apple_platform_interface: 1.1.0
  sign_in_with_apple_web: 2.1.0
  smooth_page_indicator: 1.1.0
  sqflite: 2.3.3+1
  sqflite_common: 2.5.4+3
  stepper_counter_swipe: ^1.0.2
  stream_transform: 2.1.0
  timeago: 3.6.1
  url_launcher: 6.3.0
  url_launcher_android: 6.3.10
  url_launcher_ios: 6.3.1
  url_launcher_linux: 3.2.0
  url_launcher_macos: 3.2.1
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.3.3
  url_launcher_windows: 3.1.2
  uuid: ^4.0.0
  video_player: 2.9.2
  video_player_android: 2.7.13
  video_player_avfoundation: 2.6.2
  video_player_platform_interface: 6.2.3
  video_player_web: 2.3.2
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.2.8
  webview_flutter: 4.9.0
  webview_flutter_android: 3.16.7
  webview_flutter_platform_interface: 2.10.0
  webview_flutter_wkwebview: 3.15.0
  webviewx_plus: 0.5.0

```

</details>
