### ISSUE TITLE
FlutterFire: Can't run or build Flutter App for iOS 18.1

### ISSUE THREAD

**Issue by taufiq-husain** [firebase/flutterfire#13563]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

iOS

### Description

I just tried running `flutter run` or `flutter build ipa --release` and it fails with the errors mentioned in the "logs" section. Note that I created a new Flutter project for my own sanity check and tested it without ANY external dependencies and it built successfully for the new iOS. Since `grpc-core` is part of Firebase/FlutterFire, I'm assuming it's an issue with Firebase.

_**Note that it doesn't fail on Android or Web.**_

```
flutter doctor -v 
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-arm64, locale en-US)
    • Flutter version 3.24.4 on channel stable at /Users/taufiqhusain/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (5 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/taufiqhusain/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.95.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (6 available)
    • Taufiq’s iPhone (mobile)        • 00008110-000174EE0AE1801E                • ios            • iOS 18.1 22B83
    • Aliya’s iPad (mobile)           • 2473f2ea59643e01170ff9d69af3897f97b65837 • ios            • iOS 17.7.1 21H216
    • Aliya’s iPhone (mobile)         • 00008130-000A03D226E0001C                • ios            • iOS 18.1 22B83
    • Taufiq’s iPad (mobile)          • 807bffd1cb8c32e863b48f182ed91185a97a8fbc • ios            • iOS 18.1 22B83
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                    • darwin         • macOS 15.1 24B83
      darwin-arm64
    • Chrome (web)                    • chrome                                   • web-javascript • Google Chrome
      130.0.6723.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Reproducing the issue

I have a feeling this has to do something with iOS 18.1 or the newly updated macOS. I can't say definitively but I was able to build all my apps for iOS as of yesterday but today I can't run or build on iOS.

### Firebase Core version

3.6.0

### Flutter Version

3.24.4

### Relevant Log Output

```shell
gRPC-Core
Undefined symbol: absl::lts_20240116::CHexEscape(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::FormatTime(absl::lts_20240116::string_view, absl::lts_20240116::Time, absl::lts_20240116::TimeZone)

Undefined symbol: absl::lts_20240116::SimpleAtof(absl::lts_20240116::string_view, float*)

Undefined symbol: absl::lts_20240116::Base64Escape(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::UnknownError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::log_internal::LogMessage::AtLocation(absl::lts_20240116::string_view, int)

Undefined symbol: void absl::lts_20240116::log_internal::LogMessage::CopyToEncodedBuffer<(absl::lts_20240116::log_internal::LogMessage::StringType)0>(absl::lts_20240116::string_view)

Undefined symbol: void absl::lts_20240116::log_internal::LogMessage::CopyToEncodedBuffer<(absl::lts_20240116::log_internal::LogMessage::StringType)1>(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::log_internal::LogMessage::operator<<(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::log_internal::PrependVModule(absl::lts_20240116::string_view, int)

Undefined symbol: absl::lts_20240116::log_internal::LogMessageFatal::LogMessageFatal(char const*, int, absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::InternalError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::NotFoundError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::StrReplaceAll(absl::lts_20240116::string_view, std::initializer_list<std::__1::pair<absl::lts_20240116::string_view, absl::lts_20240116::string_view>>)

Undefined symbol: absl::lts_20240116::Base64Unescape(absl::lts_20240116::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)

Undefined symbol: absl::lts_20240116::CancelledError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::flags_internal::AbslParseFlag(absl::lts_20240116::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)

Undefined symbol: absl::lts_20240116::flags_internal::AbslParseFlag(absl::lts_20240116::string_view, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)

Undefined symbol: absl::lts_20240116::flags_internal::AbslParseFlag(absl::lts_20240116::string_view, bool*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)

Undefined symbol: absl::lts_20240116::flags_internal::AbslParseFlag(absl::lts_20240116::string_view, int*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)

Undefined symbol: absl::lts_20240116::flags_internal::AbslUnparseFlag(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::status_internal::StatusRep::SetPayload(absl::lts_20240116::string_view, absl::lts_20240116::Cord)

Undefined symbol: absl::lts_20240116::BytesToHexString(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::EqualsIgnoreCase(absl::lts_20240116::string_view, absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::UnavailableError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::numbers_internal::safe_strto32_base(absl::lts_20240116::string_view, int*, int)

Undefined symbol: absl::lts_20240116::numbers_internal::safe_strto64_base(absl::lts_20240116::string_view, long long*, int)

Undefined symbol: absl::lts_20240116::numbers_internal::safe_strtou32_base(absl::lts_20240116::string_view, unsigned int*, int)

Undefined symbol: absl::lts_20240116::numbers_internal::safe_strtou64_base(absl::lts_20240116::string_view, unsigned long long*, int)

Undefined symbol: absl::lts_20240116::strings_internal::AppendPieces(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::initializer_list<absl::lts_20240116::string_view>)

Undefined symbol: absl::lts_20240116::strings_internal::StringifySink::Append(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::strings_internal::CatPieces(std::initializer_list<absl::lts_20240116::string_view>)

Undefined symbol: absl::lts_20240116::variant_internal::ThrowBadVariantAccess()

Undefined symbol: absl::lts_20240116::optional_internal::throw_bad_optional_access()

Undefined symbol: absl::lts_20240116::EndsWithIgnoreCase(absl::lts_20240116::string_view, absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::UnimplementedError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::WebSafeBase64Escape(absl::lts_20240116::string_view)

Undefined symbol: bool absl::lts_20240116::str_format_internal::FormatArgImpl::Dispatch<absl::lts_20240116::string_view>(absl::lts_20240116::str_format_internal::FormatArgImpl::Data, absl::lts_20240116::str_format_internal::FormatConversionSpecImpl, void*)

Undefined symbol: absl::lts_20240116::InvalidArgumentError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::StartsWithIgnoreCase(absl::lts_20240116::string_view, absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::UnauthenticatedError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::DeadlineExceededError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::PermissionDeniedError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::WebSafeBase64Unescape(absl::lts_20240116::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)

Undefined symbol: absl::lts_20240116::ResourceExhaustedError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::FailedPreconditionError(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::Cord::GetFlatAux(absl::lts_20240116::cord_internal::CordRep*, absl::lts_20240116::string_view*)

Undefined symbol: absl::lts_20240116::Cord::InlineRep::AppendArray(absl::lts_20240116::string_view, absl::lts_20240116::cord_internal::CordzUpdateTracker::MethodIdentifier)

Undefined symbol: absl::lts_20240116::Cord::Cord(absl::lts_20240116::string_view, absl::lts_20240116::cord_internal::CordzUpdateTracker::MethodIdentifier)

Undefined symbol: absl::lts_20240116::Status::Status(absl::lts_20240116::StatusCode, absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::CEscape(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::ByString::ByString(absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::CUnescape(absl::lts_20240116::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)

Undefined symbol: absl::lts_20240116::ParseTime(absl::lts_20240116::string_view, absl::lts_20240116::string_view, absl::lts_20240116::Time*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)

Undefined symbol: absl::lts_20240116::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, absl::lts_20240116::string_view)

Undefined symbol: absl::lts_20240116::string_view::find_first_of(absl::lts_20240116::string_view, unsigned long) const

Undefined symbol: absl::lts_20240116::string_view::find(absl::lts_20240116::string_view, unsigned long) const

Undefined symbol: absl::lts_20240116::string_view::find(char, unsigned long) const

Undefined symbol: absl::lts_20240116::string_view::rfind(char, unsigned long) const

Undefined symbol: absl::lts_20240116::status_internal::StatusRep::GetPayload(absl::lts_20240116::string_view) const

Undefined symbol: absl::lts_20240116::status_internal::StatusRep::ForEachPayload(absl::lts_20240116::FunctionRef<void (absl::lts_20240116::string_view, absl::lts_20240116::Cord const&)>) const

Undefined symbol: absl::lts_20240116::ByChar::Find(absl::lts_20240116::string_view, unsigned long) const

Undefined symbol: absl::lts_20240116::ByString::Find(absl::lts_20240116::string_view, unsigned long) const
```

### Flutter dependencies

```
dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  csv: ^6.0.0
  easy_image_viewer: ^1.5.1
  file_picker: ^8.1.3
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.4.2
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  in_app_review: ^2.0.9
  intl: ^0.19.0
  js: ^0.7.1
  just_audio: ^0.9.41
  loading_animation_widget: ^1.3.0
  mutex: ^3.1.0
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.3.2
  simple_ripple_animation: ^0.0.9
  toastification: ^2.3.0
  universal_html: ^2.2.4
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  wakelock_plus: ^1.2.8

dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
#  dependency_validator: ^4.1.0
#  flutter_app_name: ^0.1.0
#  flutter_app_name: ^0.1.0
#  flutter_test:
#    sdk: flutter
```

```yaml

Dart SDK 3.5.4
Flutter SDK 3.24.4
HelperHat 0.1.7+7

dependencies:
- auto_size_text 3.0.0 [flutter]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cloud_firestore 5.4.4 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 5.1.3 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- csv 6.0.0
- easy_image_viewer 1.5.1 [flutter]
- file_picker 8.1.3 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file web]
- firebase_analytics 11.3.3 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.3.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.6.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.1.3 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 15.1.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 12.3.4 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fl_chart 0.69.0 [equatable flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_animate 4.5.0 [flutter flutter_shaders]
- flutter_easyloading 3.0.5 [flutter flutter_spinkit]
- flutter_native_splash 2.4.2 [args flutter flutter_web_plugins html image meta path universal_io xml yaml ansicolor]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- get 4.6.6 [flutter]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- image_cropper 8.0.2 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_review 2.0.9 [flutter in_app_review_platform_interface]
- intl 0.19.0 [clock meta path]
- js 0.7.1
- just_audio 0.9.41 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- loading_animation_widget 1.3.0 [flutter]
- mutex 3.1.0
- percent_indicator 4.2.3 [flutter]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- salomon_bottom_bar 3.3.2 [flutter]
- shared_preferences 2.3.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- simple_ripple_animation 0.0.9 [flutter hyper_lint]
- toastification 2.3.0 [flutter equatable uuid pausable_timer collection iconsax_flutter]
- universal_html 2.2.4 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- wakelock_plus 1.2.8 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus web]

dev dependencies:
- flutter_launcher_icons 0.14.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 5.0.0 [lints]

dependency overrides:
- web 1.1.0

transitive dependencies:
- _flutterfire_internals 1.3.44 [collection firebase_core firebase_core_platform_interface flutter meta]
- ansicolor 2.0.3
- archive 3.6.1 [crypto path]
- args 2.6.0
- async 2.11.0 [collection meta]
- audio_session 0.1.21 [flutter flutter_web_plugins rxdart meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- characters 1.3.0
- charcode 1.3.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.2 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.4.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.3.2 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- cloud_functions_platform_interface 5.5.37 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.10.2 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- collection 1.18.0
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.6 [typed_data]
- csslib 1.0.2 [source_span]
- dbus 0.7.10 [args ffi meta xml]
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.1 [meta path]
- file_selector_linux 0.9.3 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 4.2.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+2 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_auth_platform_interface 7.4.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.44 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.46 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.9.2 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_storage_platform_interface 5.1.31 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.10.3 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http meta web]
- fixnum 1.1.1
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.23 [flutter]
- flutter_shaders 0.1.3 [flutter vector_math]
- flutter_spinkit 5.2.1 [flutter]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- html 0.15.5 [csslib source_span]
- http 1.2.2 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- hyper_lint 0.0.2 [flutter]
- iconsax_flutter 1.0.0 [flutter]
- image 4.3.0 [archive meta xml]
- image_cropper_for_web 6.0.2 [flutter flutter_web_plugins image_cropper_platform_interface web]
- image_cropper_platform_interface 7.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.12+17 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.6 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_review_platform_interface 2.0.5 [flutter url_launcher plugin_platform_interface platform]
- json_annotation 4.9.0 [meta]
- just_audio_platform_interface 4.3.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.13 [just_audio_platform_interface flutter flutter_web_plugins web]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 2.0.0
- octo_image 2.1.0 [flutter]
- package_info_plus 8.1.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- package_info_plus_platform_interface 3.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_provider 2.1.4 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.12 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- pausable_timer 3.1.0+3 [clock]
- permission_handler_android 12.0.13 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.5 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+2 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.2.3 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- rxdart 0.28.0
- shared_preferences_android 2.3.3 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.3 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.0 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.0 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.4+5 [synchronized path meta]
- sqflite_darwin 2.4.1-1 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- synchronized 3.3.0+3
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.4.0 [collection]
- url_launcher_android 6.3.13 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.3 [flutter url_launcher_platform_interface]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- vector_math 2.1.4
- vm_service 14.2.5
- wakelock_plus_platform_interface 1.2.1 [flutter plugin_platform_interface meta]
- win32 5.7.2 [ffi]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>
