### ISSUE TITLE
firebase_messaging: An unknown error has occurred.

### ISSUE THREAD

**Issue by shijinthottiyil** [firebase/flutterfire#13566]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

iOS

### Description

I'm encountering a problem while running flutter app on iOS devices. The app was working fine since yesterday (29/10/2024). While running the app on iOS simulator I'm getting this error [firebase_messaging/unknown] An unknown error has occurred. The app is working fine on android emulator.

I reconfigured firebase project but that doesn't seems to work.

### Reproducing the issue

CODE:

main.dart

//Adding Firebase to the Project for implementing push notifications.
import 'package:bluelin/features/auth/views/init_view.dart';
import 'package:bluelin/utils/logic/networking/networking.dart';
import 'package:bluelin/utils/logic/push_notification/push_notification_manager.dart';
import 'package:bluelin/utils/ui/constants/constants.dart';
import 'package:bluelin/utils/ui/widgets/v2/app_error_widget.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';

import 'firebase_options.dart';

void main() async {
try {
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp(
options: DefaultFirebaseOptions.currentPlatform);
await GetStorage.init();
await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
await PushNotificationManager().initAndReceiveNotifications();
runApp(const MyApp());
} catch (error) {
logger.i(error.toString());
runApp(
ErrorApp(
error: error,
),
);
}
}

class MyApp extends StatelessWidget {
const MyApp({super.key});

@OverRide
Widget build(BuildContext context) {
return GetMaterialApp(
debugShowCheckedModeBanner: false,
scrollBehavior: const ScrollBehavior()
.copyWith(physics: const BouncingScrollPhysics()),
defaultTransition: Transition.fadeIn,
darkTheme: AppTheme.darkTheme,
themeMode: ThemeMode.dark,
home: const InitView(),
// initialBinding: DI(),
// home: TokenManager.contanisAccess()
// ? const BottomView()
// : const OnboardingScreen(),
);
}
}

// ErrorApp
class ErrorApp extends StatelessWidget {
const ErrorApp({super.key, this.error});
final dynamic error;
@OverRide
Widget build(BuildContext context) {
return MaterialApp(
home: Scaffold(
backgroundColor: AppColors.kBlack,
body: AppErrorWidget(
message:
"We’re experiencing some issues on our end.\nMake sure you're connect to internet and try again.",
buttonName: 'Restart',
onButtonPress: () {
SystemNavigator.pop();
},
error: error,
),
),
);
}
}

push_notification_manager.dart

import 'dart:io';

import 'package:bluelin/utils/logic/push_notification/flutter_local_notifications_manager.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';

///Top-Level Function for handling background Notifications.<--App is Terminated--->
///
Future handleBackgroundMessage(RemoteMessage message) async {
if (kDebugMode) {
print('Title = ${message.notification?.title}');
print('Body = ${message.notification?.body}');
print('Payload = ${message.data}');
}
await FlutterLocalNotificationsManager.showNotification(message);
}

///Class For Handling Firebase Notification Logic.
///
class PushNotificationManager {
final _firebaseMessaging = FirebaseMessaging.instance;

// variable to store fcm token.
static late final String? _fcmToken;

// getter to read fcmToken
static String? get fcmToken => _fcmToken;

Future initAndReceiveNotifications() async {
await _firebaseMessaging.requestPermission();

_fcmToken = await _firebaseMessaging.getToken();

await FlutterLocalNotificationsManager
    .initializeFlutterLocalNotificationsPlugin();

if (kDebugMode) {
  print('FCM TOKEN = $_fcmToken');
  print('Device Type = ${Platform.isAndroid ? 'android' : 'ios'}');
}

// to handle foreground notifications.
FirebaseMessaging.onMessage.listen((RemoteMessage message) {
  if (kDebugMode) {
    print('Handling a foreground message: ${message.messageId}');
    print('Message data: ${message.data}');
    print('Message notification: ${message.notification?.title}');
    print('Message notification: ${message.notification?.body}');
  }

  FlutterLocalNotificationsManager.showNotification(message);
});

///To receive notifications in the background.
///
FirebaseMessaging.onBackgroundMessage(handleBackgroundMessage);
}
}

### Firebase Core version

3.5.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
[firebase_messaging/unknown] An unknown error has occurred.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

dependencies:
  action_slider: ^0.7.0
  animate_do: ^3.3.4
  audioplayers: ^6.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  flutter_rating_stars: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_widget_from_html: ^0.15.1
  get: ^4.6.6
  get_storage: ^2.1.1
  glowy_borders: ^1.0.2
  google_fonts: ^6.2.0
  intl: ^0.19.0
  location: ^6.0.2
  logger: ^2.0.2+1
  lottie: ^3.1.0
  phosphor_flutter: ^2.1.0
  pinput: ^5.0.0
  pod_player: ^0.2.2
  razorpay_flutter: ^1.3.5
  share_plus: ^10.0.2
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

```

</details>
