### ISSUE TITLE
FlutterFire: IOS simulator not building

### ISSUE THREAD

**Issue by StaffordInnovations** [firebase/flutterfire#13599]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Analytics, Auth, Cloud Functions, In-App Messaging, Messaging

### Which platforms are affected?

iOS

### Description

This is similar but not quite to issue #13563 however I've tried the solutions and they're not working for me plus the error reports aren't quite the same.

I expected to add FlutterFire/Firebase_core to my new Flutter app and be able to build on the IOS simulator.

I've already tried a million things.
I took out 
`use_frameworks!
  use_modular_headers!
`
from the target 'Runner' do in my podfile and tried the manual `pod 'Firebase', :modular_headers => true` for each package

I've done the delete podfile.lock, clean cache, clean flutter etc over and over any time I've tried a new solution

doing the following didn't help:
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'abseil'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++14'
      end
    end
  end
end`

I tried adding the packages to Runner in Xcode but then got conflict there.  I took out url_launcher in case that was causing an issue.   I'm really at a loss as to how to fix this.

### Reproducing the issue

I created a new flutter app in order to refactor an existing app.  The app built on both the IOS simulator  Iphone 15 (18.0) and android emulator prior to adding flutter core.  I used the Flutter config instructions from the Firebase console in order to install Firebase but then I got crash reports.  It took me a long time to find it's an issue with the packages.

### Firebase Core version

3.6.0

### Flutter Version

3.24.4

### Relevant Log Output

```shell
Package Loading (Xcode): Missing package product 'FirebaseDatabase'
/ios/Runner.xcodeproj

Package Loading (Xcode): Missing package product 'FirebaseAnalytics'
/ios/Runner.xcodeproj

Package Loading (Xcode): Missing package product 'FirebaseMessaging'
/ios/Runner.xcodeproj

Package Loading (Xcode): Missing package product 'FirebaseCore'
/ios/Runner.xcodeproj

Package Loading (Xcode): Missing package product 'FirebaseFunctions'
/ios/Runner.xcodeproj

Package Loading (Xcode): Missing package product 'FirebaseAppCheck'
/ios/Runner.xcodeproj

Package Loading (Xcode): Missing package product 'FirebaseFirestore'
/ios/Runner.xcodeproj

Package Loading (Xcode): Missing package product 'FirebaseStorage'
/ios/Runner.xcodeproj

Package Loading (Xcode): Missing package product 'FirebaseDynamicLinks'
/ios/Runner.xcodeproj

Package Loading (Xcode): Missing package product 'FirebaseAuth'
/ios/Runner.xcodeproj

Could not build the application for the simulator.
Error launching application on iPhone 15.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.2.1
  path_provider: ^2.1.1
  firebase_core: ^3.6.0

  #state management plugins
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0

  go_router: ^14.3.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter_launcher_icons: ^0.14.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_portal: ^1.1.4
  syncfusion_flutter_datepicker: ^27.1.57
  webview_flutter: ^4.10.0

  flutter_stripe: ^11.2.0
  flutter_stripe_web: ^6.2.0
  pay: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/NGT_simple.png"
  image_path_android: "assets/images/NGT_simple.png"
  adaptive_icon_background: "assets/images/NGT_background.png"
  adaptive_icon_foreground: "assets/images/NGT_foreground.png"
  windows:
    generate: true
    image_path: "assets/images/NGT_simple.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/NGT_simple.png"

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  generate: true

```

</details>

### Additional context and comments

I'm wondering if maybe there might be related to the swift package manager or maybe I should migrate to that? I'm currently on Flutter Channel Stable

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-x64, locale en-IE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.95.0)
[✓] Connected device (4 available)
[✓] Network resources
`
