### ISSUE TITLE
[Firebase Auth]: Sign in with Apple on Android Device Galaxy S21 freezes.

### ISSUE THREAD

**Issue by michaeljajou** [firebase/flutterfire#14900]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android

### Description

When a user triggers the sign in with apple flow, the apple browser is presented but after successfully authenticating, the browser redirects back to the app in which the app is frozen. This happens on a successful apple authentication or a cancelled authentication. 

It is fair to note that the issue is different across devices:
1. The issue happens on a Samsung Galaxy S21
2. The issue DOES NOT happen on a Pixel 6 Pro

```
try {
  final appleProvider = AppleAuthProvider();
  appleProvider.addScope('email');
  appleProvider.addScope('name');
  final cred =
      await FirebaseAuth.instance.signInWithProvider(appleProvider);

  /// THIS LINE IS NEVER REACHED
} catch (e) {
  /// ERROR IS NEVER THROWN
  log(e.toString(), name: 'ApiAuth');
}
```

### Reproducing the issue

1. Start a new flutter app
2. Install the Firebase Auth package
3. Integrate sign in with apple
4. Launch on Galaxy S21 
5. Tap sign in with apple, trigger the flow, and you will see that the device is frozen after returning. 

### Firebase Core version

3.7.0

### Flutter Version

3.24.4

### Relevant Log Output

```shell
I/MediaCodec(23286): setCodecState state(1), called in 6
I/[CIO]   (23286): Found 0 messages for user
I/Surface (23286): Surface::setFrameRate is deprecated, setFrameRate hint is dropped as destination is not SurfaceFlinger
I/ViewRootImpl@d37f302[GenericIdpActivity](23286): stopped(true) old = false
D/ViewRootImpl@d37f302[GenericIdpActivity](23286): WindowStopped on com.letsgetoffline.lgomobile.staging/com.google.firebase.auth.internal.GenericIdpActivity set to true
W/WindowOnBackDispatcher(23286): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda19@6b63d4e
I/ViewRootImpl@d37f302[GenericIdpActivity](23286): dispatchDetachedFromWindow
D/InputTransport(23286): Input channel destroyed: '12903e2', fd=407
W/System  (23286): Ignoring header X-Firebase-Locale because its value was null.
D/FirebaseAuth(23286): Notifying id token listeners about user ( ).
D/FirebaseAuth(23286): Notifying auth state listeners about user ( ).
D/TrafficStats(23286): tagSocket(164) with statsTag=0xf9f3, statsUid=-1
I/MediaCodec(23286): setCodecState state(0), called in 6
D/BufferPoolAccessor2.0(23286): bufferpool2 0xb400007c0f627278 : 5(6922240 size) total buffers - 4(5537792 size) used buffers - 185/190 (recycle/alloc) - 5/190 (fetch/transfer)
D/BufferPoolAccessor2.0(23286): evictor expired: 4, evicted: 0
D/BufferPoolAccessor2.0(23286): bufferpool2 0xb400007c0f65ecc8 : 5(6922240 size) total buffers - 4(5537792 size) used buffers - 22/27 (recycle/alloc) - 5/28 (fetch/transfer)
D/BufferPoolAccessor2.0(23286): evictor expired: 1, evicted: 1
D/BufferPoolAccessor2.0(23286): bufferpool2 0xb400007c0f627278 : 5(6922240 size) total buffers - 5(6922240 size) used buffers - 343/348 (recycle/alloc) - 5/348 (fetch/transfer)
I/ViewRootImpl@82e2778[MainActivity](23286): onDisplayChanged oldDisplayState=2 newDisplayState=2
D/BufferPoolAccessor2.0(23286): bufferpool2 0xb400007c0f627278 : 5(6922240 size) total buffers - 5(6922240 size) used buffers - 502/507 (recycle/alloc) - 5/507 (fetch/transfer)
D/BufferPoolAccessor2.0(23286): bufferpool2 0xb400007c0f627278 : 5(6922240 size) total buffers - 5(6922240 size) used buffers - 664/669 (recycle/alloc) - 5/669 (fetch/transfer)
```

### Flutter dependencies

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  pin_code_fields: ^8.0.1
  app_settings: ^5.1.1
  collection: ^1.18.0
  dio: ^5.4.2+1
  dotted_border: ^2.1.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  freezed_annotation: ^2.4.1
  visibility_detector: ^0.4.0+2
  go_router: ^13.2.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  email_validator: ^2.1.17
  qr_flutter: ^4.1.0
  webview_flutter: ^4.7.0
  phone_number: ^2.1.0
  flutter_contacts: ^1.1.7+1
  intercom_flutter: ^8.1.3
  sticky_headers: ^0.3.0+2
  flutter_keyboard_visibility: ^6.0.0
  permission_handler: ^11.3.1
  simple_gradient_text: ^1.3.0
  intl: ^0.19.0
  flutter_uxcam: ^2.5.2
  flutter_switch: ^0.3.2
  geolocator: ^11.0.0
  expandable_page_view: ^1.0.17
  animated_text_kit: ^4.2.2
  flutter_markdown: ^0.6.22+1
  add_2_calendar: ^3.0.1
  json_annotation: ^4.8.1
  screenshot: ^2.3.0
  posthog_flutter: ^4.4.1
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.2
  lottie: ^3.1.0
  video_player: ^2.8.6
  in_app_review: ^2.0.9
  table_calendar: ^3.1.1
  mixpanel_flutter: ^2.2.0
  tuple: ^2.0.2
  flutter_staggered_grid_view: ^0.7.0
  skeletonizer: ^1.4.2
  event_bus: ^2.0.0
  flutter_animate: ^4.5.0
  google_maps_flutter: ^2.9.0
  uuid: ^4.5.0
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^3.0.1
  customer_io: ^1.5.2
  app_links: ^6.3.2
  flutter_stripe: ^11.1.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  firebase_crashlytics: ^4.1.4
  firebase_analytics: ^11.3.4
  package_info_plus: ^8.1.1
  share_plus: ^10.1.2
```
