### ISSUE TITLE
[firebase_crashlytics]: Unable to get readable Android crashes

### ISSUE THREAD

**Issue by aadrianpislaru** [firebase/flutterfire#16374]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

Android

### Description

I've been using this command to build the app:

`flutter build apk --flavor dev -t lib/main_uat.dart --obfuscate --split-debug-info=build/app/outputs/symbols --release --verbose`

then this to upload the symbols:

`firebase crashlytics:symbols:upload --app=1:576672652820:android:blablabla build/app/outputs/symbols`

And my stack trace looks like this:

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: hello. Error thrown .
#00 pc 0x7be82ddbf7 com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#01 pc 0x7be856b03f com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#02 pc 0x7be84b1afb com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#03 pc 0x7be835bad7 com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#04 pc 0x7be835ba13 com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#05 pc 0x7be8111643 com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#06 pc 0x7be81114cb com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#07 pc 0x7be85404db com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#08 pc 0x7be7f7212f com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#09 pc 0x7be7f7206f com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#10 pc 0x7be7f71b1b com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#11 pc 0x7be85400ef com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#12 pc 0x7be7f71a7f com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#13 pc 0x7be7f491cb com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#14 pc 0x7be7f4a857 com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#15 pc 0x7be7f4a7db com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)
#16 pc 0x7be7f4b41b com.redacted.debug (assert type is List<dynamic>) (BuildId: 63956a45b9840a2210d24405a9a5e2e2)

```

If i dont submit the symbols...

it looks like this (which is normal i think):

```
  Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: hello. Error thrown .
BuildId: 63956a453cfdf87b10d24405781e1fd0
#00 abs 00000072b2eb6ba3 virt 00000000006b0ba3 _kDartIsolateSnapshotInstructions+0x3ba063
#01 abs 00000072b3143c53 virt 000000000093dc53 _kDartIsolateSnapshotInstructions+0x647113
#02 abs 00000072b308aaa3 virt 0000000000884aa3 _kDartIsolateSnapshotInstructions+0x58df63
#03 abs 00000072b2f34a83 virt 000000000072ea83 _kDartIsolateSnapshotInstructions+0x437f43
#04 abs 00000072b2f349bf virt 000000000072e9bf _kDartIsolateSnapshotInstructions+0x437e7f
#05 abs 00000072b2cea5ef virt 00000000004e45ef _kDartIsolateSnapshotInstructions+0x1edaaf
#06 abs 00000072b2cea477 virt 00000000004e4477 _kDartIsolateSnapshotInstructions+0x1ed937
#07 abs 00000072b3119483 virt 0000000000913483 _kDartIsolateSnapshotInstructions+0x61c943
#08 abs 00000072b2b4b12f virt 000000000034512f _kDartIsolateSnapshotInstructions+0x4e5ef
#09 abs 00000072b2b4b06f virt 000000000034506f _kDartIsolateSnapshotInstructions+0x4e52f
#10 abs 00000072b2b4ab1b virt 0000000000344b1b _kDartIsolateSnapshotInstructions+0x4dfdb
#11 abs 00000072b3119097 virt 0000000000913097 _kDartIsolateSnapshotInstructions+0x61c557
#12 abs 00000072b2b4aa7f virt 0000000000344a7f _kDartIsolateSnapshotInstructions+0x4df3f
#13 abs 00000072b2b221cb virt 000000000031c1cb _kDartIsolateSnapshotInstructions+0x2568b
#14 abs 00000072b2b23857 virt 000000000031d857 _kDartIsolateSnapshotInstructions+0x26d17
#15 abs 00000072b2b237db virt 000000000031d7db _kDartIsolateSnapshotInstructions+0x26c9b
#16 abs 00000072b2b2441b virt 000000000031e41b _kDartIsolateSnapshotInstructions+0x278db
```

But if i take the trace above and try to deobfuscate it using 

`flutter symbolize -i obfuscated.txt -d app.android-arm64.symbols`

it magically works.

What am i missing?

For crashing flutter im using:

```
return Padding(
    padding: EdgeInsets.only(top: AppSize.spaceSmall.w),
    child: GestureDetector(
      onTap: () {
        throw 'hello';
      },
      child: _buildWelcomeMessage(context),
    ),
  );
```

This is my build.gradle

```
buildscript {
    repositories {
        google()
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

```

```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader("UTF-8") { reader ->
        localProperties.load(reader)
    }
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def flutterVersionCode = localProperties.getProperty("flutter.versionCode")
if (flutterVersionCode == null) {
    flutterVersionCode = "1"
}

def flutterVersionName = localProperties.getProperty("flutter.versionName")
if (flutterVersionName == null) {
    flutterVersionName = "1.0"
}

android {
    namespace = "com.redacted.replatform"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.redacted"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdk = 26
        targetSdk = 34
        versionCode = flutterVersionCode.toInteger()
        versionName = flutterVersionName
        multiDexEnabled true
    }

    signingConfigs {
        debug {
            storeFile file("v2.keystore")
        }
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
            v1SigningEnabled false
            v2SigningEnabled true
        }
    }

    flavorDimensions "default"

    buildTypes {
        debug {
            minifyEnabled true
            firebaseCrashlytics {
                mappingFileUploadEnabled true
            }
        }
        release {
            minifyEnabled true
            shrinkResources true
            firebaseCrashlytics {
                mappingFileUploadEnabled true
            }
        }
    }

    productFlavors {
        prod {
            dimension "default"
            resValue "string", "app_name", "AppName"
            manifestPlaceholders = [appName: "AppName", mapApiKeyValue: GOOGLE_MAPS_KEY]
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        dev {
            dimension "default"
            applicationIdSuffix ".debug"
            resValue "string", "app_name", "AppName Debug"
            manifestPlaceholders = [appName: "AppName Debug", mapApiKeyValue: GOOGLE_MAPS_KEY]
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.security:security-crypto:1.1.0-alpha03'
    implementation 'com.google.firebase:firebase-messaging:24.0.0'
    implementation 'com.onetrust.cmp:native-sdk:202410.1.0.0'
    implementation 'androidx.security:security-crypto:1.1.0-alpha03'
    implementation 'com.exponea.sdk:sdk:3.16.0'
}

flutter {
    source = "../.."
}

```

### Reproducing the issue

- build app using obfuscate
- upload symbols
- look at the obfuscated traces

### Firebase Core version

3.4.0

### Flutter Version

3.24.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.3
Flutter SDK 3.24.3
replatform 10.0.70+9144

dependencies:
- android_intent_plus 5.1.0 [flutter platform meta]
- app_links 6.3.2 [flutter app_links_linux app_links_platform_interface app_links_web]
- app_set_id 1.2.1 [flutter flutter_web_plugins plugin_platform_interface]
- appcheck 1.5.2 [flutter]
- background_downloader 8.5.5 [flutter logging http path_provider path async mime collection]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- certificatetransparency 0.0.2 [dio flutter plugin_platform_interface]
- chewie 1.8.5 [cupertino_icons flutter provider video_player wakelock_plus]
- collection 1.18.0
- connectivity_plus 6.0.5 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- crypto 3.0.5 [typed_data]
- cupertino_icons 1.0.8
- device_info_plus 10.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- dio 5.7.0 [async http_parser meta path dio_web_adapter]
- either_dart 1.0.0
- equatable 2.0.5 [collection meta]
- exponea 1.7.0 [flutter flutter_web_plugins meta plugin_platform_interface file webview_flutter]
- firebase_analytics 11.3.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.1.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 15.1.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 5.1.0 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.6 [bloc flutter provider]
- flutter_dotenv 5.1.0 [flutter]
- flutter_file_downloader 2.0.0 [flutter]
- flutter_google_places_sdk 0.3.9 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_ios flutter_google_places_sdk_web flutter_google_places_sdk_android flutter_google_places_sdk_windows flutter_google_places_sdk_linux flutter_google_places_sdk_macos]
- flutter_html 3.0.0-beta.2 [html csslib collection list_counter flutter]
- flutter_local_notifications 17.2.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_markdown 0.7.3+1 [flutter markdown meta path]
- flutter_native_splash 2.4.0 [args flutter flutter_web_plugins html image meta path universal_io xml yaml ansicolor]
- flutter_polyline_points 2.1.0 [flutter http]
- flutter_screenutil 5.9.3 [flutter]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_typeahead 5.2.0 [flutter flutter_keyboard_visibility pointer_interceptor]
- formz 0.7.0 [meta]
- geocoding 3.0.0 [flutter geocoding_platform_interface geocoding_android geocoding_ios]
- geolocator 12.0.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get_it 7.7.0 [async collection meta]
- go_router 14.2.7 [collection flutter flutter_web_plugins logging meta]
- google_directions_api 0.10.0 [google_polyline_algorithm http flinq]
- google_maps_cluster_manager_2 3.2.0 [flutter google_maps_flutter_platform_interface]
- google_maps_directions 0.0.4 [equatable http]
- google_maps_flutter 2.7.1 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- gtm 0.1.6 [flutter gtm_platform_interface gtm_android gtm_ios]
- html2md 1.3.2 [html collection]
- hydrated_bloc 9.1.5 [bloc hive meta synchronized]
- injectable 2.4.4 [get_it meta]
- intl 0.19.0 [clock meta path]
- json_annotation 4.9.0 [meta]
- json_serializable 6.8.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- jwt_decoder 2.0.1
- local_auth 2.3.0 [flutter local_auth_android local_auth_darwin local_auth_platform_interface local_auth_windows]
- lottie 3.1.2 [archive flutter http path vector_math]
- map_launcher 3.5.0 [flutter]
- oauth2 2.0.3 [collection crypto http http_parser]
- onetrust_publishers_native_cmp 202410.1.0 [flutter]
- package_info_plus 8.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- path_provider 2.1.4 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- pkce 1.1.0+1 [crypto]
- pretty_qr_code 3.3.0 [flutter qr meta]
- quantum_metric 1.4.2 [flutter path_provider http dio flutter_svg cached_network_image vector_math]
- retrofit 4.4.1 [dio meta]
- root_jailbreak_sniffer 1.0.9 [flutter plugin_platform_interface]
- rxdart 0.27.7
- screen_brightness 2.0.0+2 [flutter screen_brightness_platform_interface screen_brightness_android screen_brightness_ios screen_brightness_macos screen_brightness_windows]
- shared_preferences 2.3.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 3.0.0 [flutter]
- smooth_page_indicator 1.2.0+3 [flutter]
- sprintf 7.0.0
- table_calendar 3.1.2 [flutter intl simple_gesture_detector]
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.0 [crypto sprintf meta fixnum]
- video_player 2.9.2 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- webview_flutter 4.8.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 3.16.7 [flutter webview_flutter_platform_interface]
- webview_flutter_wkwebview 3.14.0 [flutter path webview_flutter_platform_interface]

dev dependencies:
- build_runner 2.4.11 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 4.0.0 [lints]
- flutter_oss_licenses 3.0.2 [path meta yaml dart_pubspec_licenses args]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- injectable_generator 2.6.2 [build source_gen path glob analyzer code_builder dart_style injectable collection recase meta]
- quantum_metric_generator 1.0.1 [build_runner analyzer]
- retrofit_generator 8.1.0 [analyzer build built_collection code_builder dart_style dio retrofit source_gen tuple protobuf]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.41 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- ansicolor 2.0.3
- app_links_linux 1.0.3 [flutter app_links_platform_interface gtk]
- app_links_platform_interface 2.0.2 [flutter plugin_platform_interface]
- app_links_web 1.0.4 [flutter flutter_web_plugins app_links_platform_interface web]
- archive 3.6.1 [crypto path]
- args 2.5.0
- async 2.11.0 [collection meta]
- bloc 8.1.4 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.2 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.1 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.2.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- csslib 0.17.3 [source_span]
- dart_pubspec_licenses 3.0.1 [yaml path json_annotation]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.1 [flutter meta plugin_platform_interface]
- dio_web_adapter 2.0.0 [dio http_parser meta web]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 4.2.2 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.9+2 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.5 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.41 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.43 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.8.13 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_remote_config_platform_interface 1.4.41 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.6.13 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- fixnum 1.1.0
- flinq 2.0.2 [collection]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_google_places_sdk_android 0.1.9 [flutter flutter_google_places_sdk_platform_interface]
- flutter_google_places_sdk_http 0.1.4 [flutter http latlong2 flutter_google_places_sdk_platform_interface freezed_annotation json_annotation]
- flutter_google_places_sdk_ios 0.1.5 [flutter flutter_google_places_sdk_platform_interface]
- flutter_google_places_sdk_linux 0.1.4 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_http]
- flutter_google_places_sdk_macos 0.1.4 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_http]
- flutter_google_places_sdk_platform_interface 0.2.7 [flutter freezed_annotation json_annotation plugin_platform_interface]
- flutter_google_places_sdk_web 0.1.7 [flutter flutter_web_plugins flutter_google_places_sdk_platform_interface js google_maps collection]
- flutter_google_places_sdk_windows 0.1.4 [flutter flutter_google_places_sdk_platform_interface flutter_google_places_sdk_http]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 4.0.1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.2.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.22 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- frontend_server_client 4.0.0 [async path]
- geocoding_android 3.3.1 [flutter geocoding_platform_interface]
- geocoding_ios 3.0.1 [flutter geocoding_platform_interface]
- geocoding_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- geolocator_android 4.6.1 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.4 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 4.0.0 [flutter flutter_web_plugins geolocator_platform_interface web]
- geolocator_windows 0.2.3 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- google_maps 7.1.0 [js js_wrapping meta web]
- google_maps_flutter_android 2.14.6 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.13.0 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.9.2 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.8 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform web]
- google_polyline_algorithm 3.1.0
- graphs 2.3.2 [collection]
- gtk 2.1.0 [ffi flutter meta]
- gtm_android 0.1.2 [flutter gtm_platform_interface]
- gtm_ios 0.1.1 [flutter gtm_platform_interface]
- gtm_platform_interface 0.1.0 [flutter plugin_platform_interface]
- hive 2.2.3 [meta crypto]
- html 0.15.4 [csslib source_span]
- http 1.2.2 [async http_parser meta web]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.2.0 [archive meta xml]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- latlong2 0.9.1 [intl]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- list_counter 1.0.2
- local_auth_android 1.0.43 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_darwin 1.4.1 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.10 [flutter plugin_platform_interface]
- local_auth_windows 1.0.11 [flutter local_auth_platform_interface]
- logging 1.2.0
- markdown 7.2.2 [args meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 1.0.6
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.1.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 3.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.10 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- permission_handler_android 12.0.12 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.5 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+2 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.2.3 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.5
- plugin_platform_interface 2.1.8 [meta]
- pointer_interceptor 0.10.1+2 [flutter flutter_web_plugins pointer_interceptor_ios pointer_interceptor_platform_interface pointer_interceptor_web]
- pointer_interceptor_ios 0.10.1 [flutter plugin_platform_interface pointer_interceptor_platform_interface]
- pointer_interceptor_platform_interface 0.10.0+1 [flutter plugin_platform_interface]
- pointer_interceptor_web 0.10.2+1 [flutter flutter_web_plugins plugin_platform_interface pointer_interceptor_platform_interface web]
- pool 1.5.1 [async stack_trace]
- protobuf 3.1.0 [collection fixnum meta]
- provider 6.1.2 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.2 [meta]
- recase 4.1.0
- sanitize_html 2.1.0 [html meta]
- screen_brightness_android 2.0.0 [flutter screen_brightness_platform_interface]
- screen_brightness_ios 2.0.0 [flutter screen_brightness_platform_interface]
- screen_brightness_macos 2.0.0 [flutter screen_brightness_platform_interface]
- screen_brightness_platform_interface 2.0.0 [flutter plugin_platform_interface]
- screen_brightness_windows 2.0.0 [flutter screen_brightness_platform_interface]
- shared_preferences_android 2.3.2 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.3 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 2.0.0 [shelf stream_channel web_socket_channel]
- simple_gesture_detector 0.2.1 [flutter]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sqflite 2.3.3+1 [flutter sqflite_common path]
- sqflite_common 2.5.4 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.4 [path]
- timing 1.0.1 [json_annotation]
- tuple 2.0.2
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.3.9 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.2 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- video_player_android 2.7.1 [flutter video_player_platform_interface]
- video_player_avfoundation 2.6.1 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.3.2 [flutter flutter_web_plugins video_player_platform_interface web]
- vm_service 14.2.5
- wakelock_plus 1.2.8 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus web]
- wakelock_plus_platform_interface 1.2.1 [flutter plugin_platform_interface meta]
- watcher 1.1.0 [async path]
- web 0.5.1
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.1 [async crypto stream_channel web web_socket]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- win32 5.5.4 [ffi]
- win32_registry 1.1.5 [ffi win32]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

### Additional context and comments

<details>
<summary>Expand <code>proguard file</code> snippet</summary>
<br>

```yaml
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/google/home/samstern/android-sdk-linux/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html
# Add any project specific keep options here:
# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}
# Uncomment this to preserve the line number information for
# debugging stack traces.
-keepattributes SourceFile,LineNumberTable
# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile
# Keep custom model classes
-keep class com.google.firebase.** { *; }

# To ignore minifyEnabled: true error
# https://github.com/flutter/flutter/issues/19250
#https://github.com/flutter/flutter/issues/37441
-ignorewarnings
-keep class * {
    public private *;
}

```

</details>
