### ISSUE TITLE
[firebase_core/messaging]: Flutter build apk crashed immediately when opening the app (java.lang.RuntimeException: Missing type parameter)

### ISSUE THREAD

**Issue by agilst** [firebase/flutterfire#16597]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Description

Debug and Profile mode are working good. When I tried to build an apk, the app is installed but crashed when I open it.

### Reproducing the issue

1. Use these packages:
```
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
```
2. Perform `flutter build apk`
3. Install the app
4. See logcat and find "your.app.domain" or "firebase"

### Firebase Core version

3.8.0

### Flutter Version

3.24.1

### Relevant Log Output

```shell
FATAL EXCEPTION: Firebase Blocking Thread #0
Process: org.my.app, PID: 17638
java.lang.ExceptionInInitializerError
    at m7.n.h(Unknown Source:11)
    at m7.n.e(Unknown Source:4)
    at l7.b.\u003cinit\u003e(SourceFile:4)
    at l7.b.\u003cinit\u003e(SourceFile:7)
    at l7.b.\u003cclinit\u003e(Unknown Source:4)
    at l7.b.n(Unknown Source:0)
    at l7.c.\u003cinit\u003e(Unknown Source:6)
    at l7.c$c.\u003cinit\u003e(Unknown Source:0)
    at l7.c.b(Unknown Source:2)
    at l7.a.i(Unknown Source:5)
    at p7.k.i(Unknown Source:10)
    at p7.e.\u003cinit\u003e(Unknown Source:23)
    at p7.l.a(Unknown Source:8)
    at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.openHttpURLConnection(Unknown Source:8)
    at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(Unknown Source:34)
    at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(Unknown Source:48)
    at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(Unknown Source:36)
    at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$3(Unknown Source:0)
    at com.google.firebase.installations.FirebaseInstallations.c(Unknown Source:0)
    at com.google.firebase.installations.a.run(Unknown Source:4)
    at com.google.firebase.concurrent.SequentialExecutor$1.run(Unknown Source:2)
    at com.google.firebase.concurrent.SequentialExecutor$QueueWorker.workOnQueue(Unknown Source:88)
    at com.google.firebase.concurrent.SequentialExecutor$QueueWorker.run(Unknown Source:0)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(Unknown Source:12)
    at com.google.firebase.concurrent.CustomThreadFactory.a(Unknown Source:0)
    at com.google.firebase.concurrent.a.run(Unknown Source:4)
    at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.RuntimeException: Missing type parameter.
    at m8.a.d(Unknown Source:26)
    at m8.a.\u003cinit\u003e(SourceFile:2)
    at o7.a$a.\u003cinit\u003e(Unknown Source:0)
    at o7.a.\u003cclinit\u003e(Unknown Source:2)
    at m7.n.h(Unknown Source:11) 
    at m7.n.e(Unknown Source:4) 
    at l7.b.\u003cinit\u003e(SourceFile:4) 
    at l7.b.\u003cinit\u003e(SourceFile:7) 
    at l7.b.\u003cclinit\u003e(Unknown Source:4) 
    at l7.b.n(Unknown Source:0) 
    at l7.c.\u003cinit\u003e(Unknown Source:6) 
    at l7.c$c.\u003cinit\u003e(Unknown Source:0) 
    at l7.c.b(Unknown Source:2) 
    at l7.a.i(Unknown Source:5) 
    at p7.k.i(Unknown Source:10) 
    at p7.e.\u003cinit\u003e(Unknown Source:23) 
    at p7.l.a(Unknown Source:8) 
    at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.openHttpURLConnection(Unknown Source:8) 
    at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(Unknown Source:34) 
    at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(Unknown Source:48) 
    at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(Unknown Source:36) 
    at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$3(Unknown Source:0) 
    at com.google.firebase.installations.FirebaseInstallations.c(Unknown Source:0) 
    at com.google.firebase.installations.a.run(Unknown Source:4) 
    at com.google.firebase.concurrent.SequentialExecutor$1.run(Unknown Source:2) 
    at com.google.firebase.concurrent.SequentialExecutor$QueueWorker.workOnQueue(Unknown Source:88) 
    at com.google.firebase.concurrent.SequentialExecutor$QueueWorker.run(Unknown Source:0) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
    at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(Unknown Source:12) 
    at com.google.firebase.concurrent.CustomThreadFactory.a(Unknown Source:0) 
    at com.google.firebase.concurrent.a.run(Unknown Source:4) 
    at java.lang.Thread.run(Thread.java:920) 
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.1
Flutter SDK 3.24.1
future_steps 1.0.2+4

dependencies:
- base 1.0.0+1 [flutter flavor cached_network_image calendar_date_picker2 carousel_slider community_charts_flutter connectivity_plus cupertino_icons dotted_border firebase_core firebase_messaging flutter_background flutter_image_compress flutter_local_notifications flutter_plugin_android_lifecycle flutter_polyline_points flutter_svg fluttertoast font_awesome_flutter gap geolocator get_it google_fonts google_maps_flutter google_maps_utils google_sign_in health http image_cropper image_editor image_picker intl introduction_screen json_annotation json_serializable location logger maps_toolkit newrelic_mobile package_info_plus path path_provider percent_indicator permission_handler provider pushy_flutter qr_flutter retry rxdart screenshot share_plus shared_preferences social_share sqflite url_launcher uuid wakelock_plus webview_flutter webview_flutter_android webview_flutter_wkwebview]

dev dependencies:
- flutter_lints 4.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

dependency overrides:
- flavor 1.0.1+6 [flutter base]

transitive dependencies:
- _fe_analyzer_shared 59.0.0 [meta]
- _flutterfire_internals 1.3.46 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.11.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.4.0
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.3.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- calendar_date_picker2 1.1.7 [flutter intl]
- carousel_slider 5.0.0 [flutter]
- carp_serializable 2.0.0 [flutter meta json_annotation]
- characters 1.3.0
- charcode 1.3.1
- checked_yaml 2.0.2 [json_annotation source_span yaml]
- clock 1.1.1
- collection 1.18.0
- community_charts_common 1.0.4 [intl collection meta vector_math]
- community_charts_flutter 1.0.4 [collection meta community_charts_common flutter]
- connectivity_plus 6.1.0 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.2 [typed_data]
- csslib 0.17.3 [source_span]
- cupertino_icons 1.0.5
- dart_style 2.3.0 [analyzer args path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus 10.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- device_info_plus_platform_interface 7.0.1 [flutter meta plugin_platform_interface]
- dots_indicator 2.1.2 [flutter]
- dotted_border 2.1.0 [flutter path_drawing]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.1 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- firebase_core 3.8.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_messaging 15.1.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_messaging_platform_interface 4.5.48 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.9.4 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- fixnum 1.1.0
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_background 1.3.0+1 [flutter plugin_platform_interface]
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_image_compress 2.3.0 [flutter flutter_image_compress_platform_interface flutter_image_compress_common flutter_image_compress_web flutter_image_compress_macos flutter_image_compress_ohos]
- flutter_image_compress_common 1.0.5 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_macos 1.0.2 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_ohos 0.0.3 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_platform_interface 1.0.5 [flutter plugin_platform_interface cross_file]
- flutter_image_compress_web 0.1.4+1 [flutter flutter_web_plugins flutter_image_compress_platform_interface js]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications 17.2.4 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_local_notifications_linux 4.0.1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.2.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.23 [flutter]
- flutter_polyline_points 2.1.0 [flutter http]
- flutter_svg 2.0.13 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- fluttertoast 8.2.8 [flutter flutter_web_plugins web]
- font_awesome_flutter 10.8.0 [flutter]
- gap 3.0.1 [flutter]
- geolocator 13.0.1 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- geolocator_android 4.6.1 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.4 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 4.1.1 [flutter flutter_web_plugins geolocator_platform_interface web]
- geolocator_windows 0.2.3 [flutter geolocator_platform_interface]
- get_it 7.7.0 [async collection meta]
- glob 2.1.2 [async collection file path string_scanner]
- go_router 12.1.1 [collection flutter flutter_web_plugins logging meta]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- google_identity_services_web 0.3.1+4 [meta web]
- google_maps 8.0.0 [meta web]
- google_maps_flutter 2.9.0 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- google_maps_flutter_android 2.14.3 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.13.0 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.9.0 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.10 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform web]
- google_maps_utils 2.0.0+1
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_android 6.1.28 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.6 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4+2 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- health 11.1.0 [flutter intl device_info_plus json_annotation carp_serializable]
- html 0.15.4 [csslib source_span]
- http 1.2.2 [async http_parser meta web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_cropper 8.0.2 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_cropper_for_web 6.0.2 [flutter flutter_web_plugins image_cropper_platform_interface web]
- image_cropper_platform_interface 7.0.0 [flutter plugin_platform_interface http]
- image_editor 1.5.1 [flutter image_editor_platform_interface image_editor_common image_editor_ohos]
- image_editor_common 1.1.2 [flutter image_editor_platform_interface]
- image_editor_ohos 0.0.9 [flutter image_editor_platform_interface]
- image_editor_platform_interface 1.1.0 [flutter platform plugin_platform_interface]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- image_picker_android 0.8.12+13 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.5 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- intl 0.19.0 [clock meta path]
- introduction_screen 3.1.14 [flutter collection dots_indicator flutter_keyboard_visibility]
- js 0.7.1
- json_annotation 4.8.0 [meta]
- json_serializable 6.6.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- location 6.0.2 [flutter location_platform_interface location_web]
- location_platform_interface 4.0.0 [flutter plugin_platform_interface]
- location_web 5.0.0 [flutter flutter_web_plugins http_parser js location_platform_interface]
- logger 2.4.0
- logging 1.1.1
- maps_toolkit 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 1.0.4
- nested 1.0.0 [flutter]
- newrelic_mobile 1.1.5 [flutter stack_trace go_router]
- nm 0.5.0 [dbus]
- octo_image 2.1.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus 8.1.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- package_info_plus_platform_interface 3.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.12 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- percent_indicator 4.2.3 [flutter]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- permission_handler_android 12.0.12 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.5 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+2 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.2.2 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.8 [meta]
- provider 6.1.2 [collection flutter nested]
- pub_semver 2.1.3 [collection meta]
- pubspec_parse 1.2.2 [checked_yaml collection json_annotation pub_semver yaml]
- pushy_flutter 2.0.28 [js universal_html flutter]
- qr 3.0.1 [meta]
- qr_flutter 4.1.0 [flutter qr]
- retry 3.1.1
- rxdart 0.27.7
- sanitize_html 2.1.0 [html meta]
- screenshot 3.0.0 [flutter]
- share_plus 10.1.1 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- share_plus_platform_interface 5.0.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences 2.3.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.3.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- social_share 2.3.1 [flutter path_provider]
- source_gen 1.2.7 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.3 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.3+1 [flutter sqflite_common path]
- sqflite_common 2.5.4+2 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.4 [path]
- typed_data 1.3.1 [collection]
- universal_html 2.2.2 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.3.14 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.3 [flutter url_launcher_platform_interface]
- uuid 4.4.2 [crypto sprintf meta fixnum]
- vector_graphics 1.1.14 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.12
- vector_graphics_compiler 1.1.14 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 14.2.5
- wakelock_plus 1.2.8 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus web]
- wakelock_plus_platform_interface 1.2.1 [flutter plugin_platform_interface meta]
- watcher 1.0.2 [async path]
- web 1.1.0
- webview_flutter 4.10.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 4.0.1 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.16.1 [flutter path webview_flutter_platform_interface]
- win32 5.5.4 [ffi]
- win32_registry 1.1.5 [ffi win32]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]

```

</details>
