### ISSUE TITLE
CocoaPods could not find compatible versions for pod "FirebaseCore"

### ISSUE THREAD

**Issue by sswedan** [firebase/flutterfire#16718]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core, Analytics, Messaging

### Which platforms are affected?

iOS

### Description

I have a flutter app that was working correctly without any issue. yesterday I have to update to the latest Flutter version (3.24.5).

I started to get the following error on

`_fcmToken = await _messaging.getToken();`

"flutter error while checking the internet connection firebase_messaging/unknown an unknown error occurred"

I had to upgrade to the latest firebase packages as shown:

```
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  firebase_messaging: ^15.1.5
```

ios version in Podfile:
`platform :ios, '13.0'`

now when I run "pod install" I get the below error:

```

[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 3.8.0, which depends on
      Firebase/CoreOnly (= 11.4.0) was resolved to 11.4.0, which depends on
        FirebaseCore (= 11.4.0)

    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.5, which depends on
      Firebase/Messaging (= 11.4.0) was resolved to 11.4.0, which depends on
        FirebaseMessaging (~> 11.4.0) was resolved to 11.4.0, which depends on
          FirebaseCore (~> 11.0)


CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.5, which depends on
      Firebase/Messaging (= 11.4.0) was resolved to 11.4.0, which depends on
        FirebaseMessaging (~> 11.4.0) was resolved to 11.4.0, which depends on
          GoogleDataTransport (~> 10.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.5.6, which depends on
      GoogleMLKit/BarcodeScanning (~> 4.0.0) was resolved to 4.0.0, which depends on
        GoogleMLKit/MLKitCore (= 4.0.0) was resolved to 4.0.0, which depends on
          MLKitCommon (~> 9.0.0) was resolved to 9.0.0, which depends on
            GoogleDataTransport (~> 9.0)`

```
I tried a lot of things and nothing helped. Can anyone please help me with this issue?

### Reproducing the issue

 firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  firebase_messaging: ^15.1.5

platform :ios, '13.0'

### Firebase Core version

3.8.0

### Flutter Version

3.24.5

### Relevant Log Output

```shell
!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 3.8.0, which depends on
      Firebase/CoreOnly (= 11.4.0) was resolved to 11.4.0, which depends on
        FirebaseCore (= 11.4.0)

    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.5, which depends on
      Firebase/Messaging (= 11.4.0) was resolved to 11.4.0, which depends on
        FirebaseMessaging (~> 11.4.0) was resolved to 11.4.0, which depends on
          FirebaseCore (~> 11.0)


CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.5, which depends on
      Firebase/Messaging (= 11.4.0) was resolved to 11.4.0, which depends on
        FirebaseMessaging (~> 11.4.0) was resolved to 11.4.0, which depends on
          GoogleDataTransport (~> 10.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.5.6, which depends on
      GoogleMLKit/BarcodeScanning (~> 4.0.0) was resolved to 4.0.0, which depends on
        GoogleMLKit/MLKitCore (= 4.0.0) was resolved to 4.0.0, which depends on
          MLKitCommon (~> 9.0.0) was resolved to 9.0.0, which depends on
            GoogleDataTransport (~> 9.0)`
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.4
Flutter SDK 3.24.5
just_students 2.0.24+46

dependencies:
- android_id 0.3.3 [flutter]
- app_settings 4.2.0 [flutter]
- assets_audio_player 3.0.6 [flutter rxdart uuid http path_provider assets_audio_player_web]
- auto_size_text 3.0.0 [flutter]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- connectivity_plus 4.0.1 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- cupertino_icons 1.0.5
- device_info_plus 11.1.1 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- double_back_to_close_app 2.1.0 [flutter]
- enum_to_string 2.0.1
- firebase_analytics 11.3.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.8.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 15.1.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_hms_gms_availability 3.7.0 [flutter]
- flutter_html 3.0.0-beta.2 [html csslib collection list_counter flutter]
- flutter_lints 2.0.1 [lints]
- flutter_local_notifications 12.0.4 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_riverpod 2.3.6 [collection flutter meta riverpod state_notifier]
- flutter_spinkit 5.2.0 [flutter]
- font_awesome_flutter 10.4.0 [flutter]
- http 0.13.6 [async http_parser meta]
- huawei_push 6.10.0+300 [flutter]
- intl 0.17.0 [clock path]
- map_launcher 3.1.0 [flutter]
- mobile_scanner 3.5.6 [flutter flutter_web_plugins js]
- overlay_support 2.1.0 [flutter async]
- package_info_plus 4.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- path_provider 2.0.15 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 10.3.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- provider 6.0.5 [collection flutter nested]
- shared_preferences 2.1.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- url_launcher 6.1.11 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- win32 5.8.0 [ffi]

dev dependencies:
- flutter_launcher_icons 0.11.0 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

dependency overrides:
- intl 0.17.0 [clock path]

transitive dependencies:
- _flutterfire_internals 1.3.46 [collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.2
- assets_audio_player_web 3.0.6 [flutter flutter_web_plugins]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.2.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.1
- collection 1.18.0
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- csslib 0.17.3 [source_span]
- dbus 0.7.8 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 4.2.7 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+4 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_messaging_platform_interface 4.5.48 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.9.4 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- flutter_local_notifications_linux 1.0.0 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 6.0.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- html 0.15.4 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 3.3.0 [archive meta xml]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 2.0.1
- list_counter 1.0.2
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.1.0 [flutter]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_provider_android 2.0.27 [flutter path_provider_platform_interface]
- path_provider_foundation 2.2.3 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.11 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.7 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.2.3 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.0 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.10.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.2 [flutter permission_handler_platform_interface]
- petitparser 5.1.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.4 [meta]
- pointycastle 3.7.3 [collection convert js]
- process 4.2.4 [file path platform]
- riverpod 2.3.6 [meta stack_trace state_notifier]
- rxdart 0.27.7
- shared_preferences_android 2.1.4 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.2.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.2.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.2.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.1.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.2.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sqflite 2.2.8+4 [flutter sqflite_common path]
- sqflite_common 2.4.5+1 [synchronized path meta]
- stack_trace 1.11.1 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.2 [path]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.0.35 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.17 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.6 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_math 2.1.4
- vm_service 14.2.5
- web 1.1.0
- win32_registry 1.1.5 [ffi win32]
- xdg_directories 0.2.0+3 [meta path process]
- xml 6.2.2 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>
