### ISSUE TITLE
[Flutterfire]: FlutterFire CLI: Unable to locate build.gradle file

### ISSUE THREAD

**Issue by zaid-kamil** [firebase/flutterfire#16792]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

Android

## FlutterFire CLI: Unable to locate `build.gradle` file during Firebase configuration

I encountered an issue while trying to configure Firebase in my Flutter project using the `flutterfire` CLI. When I executed the `flutterfire configure` command, it failed with the following error message:  

```
PathNotFoundException: Cannot open file, path = '\flutter_auth_demo\android\build.gradle' (OS Error: The system cannot find the file specified.
, errno = 2).
```
![image](https://github.com/user-attachments/assets/15b4918e-baa9-428d-bc69-ed90ef08d056)

The CLI could not locate the `android/build.gradle` file even though the project was generated using the Flutter tool, and the `android` directory exists in the project structure.  

**Additional Context**:  
- The project structure includes the `android` directory and `build.gradle.kts` files. (and it's looking for build.gradle)  

- My Flutter and Dart version information is as follows:  
  ```bash
  flutter doctor -v
  ```  
![image](https://github.com/user-attachments/assets/a2364de9-efd0-42b2-8e5d-c4181bbaa3af)

---

### Reproducing the issue

**Steps to Reproduce**:  
1. Create a new Flutter project.  
2. Add the required dependencies:  
   ```bash
   flutter pub add firebase_core firebase_auth flutter_bloc
   ```  
3. Activate the FlutterFire CLI:  
   ```bash
   flutter pub global activate flutterfire_cli
   ```  
4. Run the `flutterfire configure` command:  
   ```bash
   flutterfire configure --project=<your_firebase_project>
   ```  
5. Select `android`

**Expected Behavior**:  
The command should successfully configure Firebase and update the project files.

**Actual Behavior**:  
The command fails with the error message:  
```
OS Error: The system cannot find the file specified.
```

### Firebase Core version

3.8.0

### Flutter Version

 3.27.0-1.0.pre.655

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.7.0-188.0.dev
Flutter SDK 3.27.0-1.0.pre.655
flutter_auth_demo 1.0.0+1

dependencies:
- cupertino_icons 1.0.8
- firebase_auth 5.3.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.8.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.6 [bloc flutter provider]

dev dependencies:
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.46 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.12.0 [collection meta]
- bloc 8.1.4 [meta]
- boolean_selector 2.1.2 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.2
- collection 1.19.0
- fake_async 1.3.2 [clock collection]
- firebase_auth_platform_interface 7.4.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- http_parser 4.1.1 [collection source_span string_scanner typed_data]
- leak_tracker 10.0.8 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- nested 1.0.0 [flutter]
- path 1.9.1
- plugin_platform_interface 2.1.8 [meta]
- provider 6.1.2 [collection flutter nested]
- sky_engine 0.0.0
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.12.0 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.4.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.4.0 [collection]
- vector_math 2.1.4
- vm_service 14.3.1
- web 1.1.0

```

</details>

### Additional context and comments

i think the plugin looks for build.gradle but the folder contains build.gradle.kts
