### ISSUE TITLE
[CLOUD_FIRESTORE]: Critically slow performance (45 seconds) when reading from cache 

### ISSUE THREAD

**Issue by cedvdb** [firebase/flutterfire#16867]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Cloud Firestore

### Which platforms are affected?

Web

### Description

When reading a decently sized dataset from cache (thousand items) a simple query takes 45 seconds to perform to completion when there is a `CircularProgressIndicator` on the screen. When the `CircularProgressIndicator` is removed, the query performs normally. I could not isolate the issue further between those two things

With circular progress indicator 53 seconds here:

![image](https://github.com/user-attachments/assets/155c7df1-2b3a-4533-8996-a151247bbf78)

Without:

![image](https://github.com/user-attachments/assets/d59e520a-a14d-46e8-9541-1c4d5f52856d)

### Reproducing the issue

Steps to reproduce:

  - create a new flutter project
  - `flutter pub add  cloud_firestore`
  - `flutter pub add firebase_core`
  - copy past the below code in main.dart
  - either use your own firebase project or ask me privately for a firebase project containing a collection `all_products_test` with 1000 documents.
  - we are first going to load the cache by launching the application below , use a static web port, `--web-port=5040`
  - you should now see "1000 products loaded in 7 seconds" this currently loads the data from network
  - while the app is running change `.get(GetOptions(source: Source.serverAndCache))` to `.get(GetOptions(source: Source.cache))`
  - reload the app 
  - the query now takes somewhere between 30 seconds to 2 minutes to load data from cache.
  - Now replace the `CircularProgressIndicator` with a `Container`, it should take 1 second.
  
```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:test_flut/firebase_options.dart';

void main() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FirebaseFirestore.instance.settings = Settings(
    persistenceEnabled: true,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(title: 'Flutter firestore test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final Future<QuerySnapshot> data;
  final watch = Stopwatch();

  @override
  void initState() {
    watch.start();
    super.initState();
    data = FirebaseFirestore.instance
        .collection('all_products_test')
        .get(GetOptions(source: Source.serverAndCache));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: FutureBuilder(
          future: data,
          builder: (ctx, snap) {
            if (!snap.hasData) {
              return CircularProgressIndicator();
            }
            return Text(
                'found ${snap.requireData.docs.length} products, ${watch.elapsed}');
          }),
    );
  }
}

```

### Firebase Core version

3.8.1

### Flutter Version

3.27.0

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.6.0
Flutter SDK 3.27.0
test_flut 1.0.0+1

dependencies:
- cloud_firestore 5.5.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.8.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.47 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.5.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.3.5 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- collection 1.19.0
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 5.3.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.2 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.0
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.12.0 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.3.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.3.0
- web 1.1.0
```

</details>
