### ISSUE TITLE
[cloud_firestore]: EXC_BAD_ACCESS __63-[FLTTransactionStreamHandler onListenWithArguments:eventSink:]_block_invoke

### ISSUE THREAD

**Issue by daniloapr** [firebase/flutterfire#16899]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

iOS

### Description

This crash is happening for a subset of iOS users. From the issue reports, looks like it's caused by writing transactions. 

flutter: 3.24.4
firebase_core: ^3.4.0 -> "3.7.0" on pubspec.lock
cloud_firestore: ^5.4.0 -> "5.4.0" on pubspec.lock

<details>
<summary>Logs from TestFlight feedback:</summary>

```txt
Thread 41 name:
Thread 41 Crashed:
0   CoreFoundation                	0x00000001957a03d4 -[__NSDictionaryM setObject:forKeyedSubscript:] + 452 (NSDictionaryM.m:202)
1   Runner                        	0x0000000102841ca8 __63-[FLTTransactionStreamHandler onListenWithArguments:eventSink:]_block_invoke + 108 (FLTTransactionStreamHandler.m:51)
2   Runner                        	0x0000000102730778 invocation function for block in -[FIRFirestore runTransactionWithOptions:block:dispatchQueue:completion:]::TransactionResult::RunUpdateBlock(std::__1::shared_ptr<firebase::firestore::core::Transac... + 180
3   libdispatch.dylib             	0x000000019d4f4370 _dispatch_call_block_and_release + 32 (init.c:1549)
4   libdispatch.dylib             	0x000000019d4f60d0 _dispatch_client_callout + 20 (object.m:576)
5   libdispatch.dylib             	0x000000019d4f9580 _dispatch_continuation_pop + 596 (queue.c:325)
6   libdispatch.dylib             	0x000000019d4f8c44 _dispatch_async_redirect_invoke + 728 (queue.c:849)
7   libdispatch.dylib             	0x000000019d507d8c _dispatch_root_queue_drain + 392 (queue.c:7331)
8   libdispatch.dylib             	0x000000019d508590 _dispatch_worker_thread2 + 156 (queue.c:7399)
9   libsystem_pthread.dylib       	0x000000021dd27c40 _pthread_wqthread + 228 (pthread.c:2709)
10  libsystem_pthread.dylib       	0x000000021dd24488 start_wqthread + 8

```

Full log:
[crashlog.txt](https://github.com/user-attachments/files/18210444/crashlog.txt)

</details>
<details>

<summary>Logs from Sentry:</summary>

```txt
EXC_BAD_ACCESS
hash >
Attempted to dereference null pointer.

mechanism: mach
handled: false
mach exception: EXC_BAD_ACCESS
signal: SIGSEGV (SEGV_NOOP)

CoreFoundation
+0x0023d4
-[__NSDictionaryM setObject:forKeyedSubscript:]

Runner
+0x195ca4
__63-[FLTTransactionStreamHandler onListenWithArguments:eventSink:]_block_invoke (FLTTransactionStreamHandler.m:51)

Runner
+0x084774
___ZZ73-[FIRFirestore runTransactionWithOptions:block:dispatchQueue:completion:]EN17TransactionResult14RunUpdateBlockENSt3__110shared_ptrIN8firebase9firestore4core11TransactionEEENS0_8functionIFvNS3_4util6StatusEEEE_block_invoke

Called from
libdispatch
+0x00236c
_dispatch_call_block_and_release

```
</details>

### Reproducing the issue

We group each 500 documents in a custom `TransactionBatch` and call the transactions in parallel as below:

```dart
class TransactionBatch {
  final List<TransactionDocument> documents = [];

  TransactionBatch();

  void set(DocumentReference ref, Map<String, dynamic> changeset) {
    documents.add(TransactionDocument(ref: ref, changeset: changeset));
  }
}

// "batches" declaration in the class
final List<TransactionBatch> _batches;

// Commit the _batches when user syncs data
final result =  await Future.wait(_batches.map((batch) => _commitBatch(batch)));

Future<TransactionResult> _commitBatch(TransactionBatch batch) async {
  final successIds = <String>[];
  final failureIds = <String>[];
  try {
    await db.runTransaction((transaction) async {
      for (final document in batch.documents) {
        transaction.set(document.ref, document.changeset);
      }
    });
    successIds.addAll(batch.documents.map((e) => e.ref.id));
  } catch (e, stackTrace) {
    Sentry.captureException(e, stackTrace: stackTrace);
    failureIds.addAll(batch.documents.map((e) => e.ref.id));
  }
  return TransactionResult(successIds: successIds, failureIds: failureIds);
}
```

### Firebase Core version

3.7.0

### Flutter Version

3.24.4

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.4
Flutter SDK 3.24.4
spectora_mobile 10.0.1+446

dependencies:
- animations 2.0.11 [flutter]
- archive 3.6.1 [crypto path]
- auto_route 7.9.2 [flutter path collection meta]
- auto_size_text 3.0.0 [flutter]
- build_runner 2.4.13 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- cached_network_image 3.4.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- camerawesome 1.4.0 [carousel_slider collection colorfilter_generator flutter image rxdart]
- clock 1.1.1
- cloud_firestore 5.4.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 5.1.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- datetime_picker_formfield 2.0.1 [flutter intl]
- device_info_plus 10.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- enum_to_string 2.0.1
- equatable 2.0.5 [collection meta]
- exif 3.3.0 [args collection convert json_annotation sprintf]
- file_picker 8.1.3 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file web]
- firebase_auth 5.2.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.7.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_remote_config 5.1.0 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_badged 2.0.3 [flutter]
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_data 1.6.0 [analyzer async build build_resolvers collection crypto equatable glob hive http inflection3 json_annotation meta path pool pubspec_parse recase retry riverpod source_gen source_helper state_notifier uuid]
- flutter_data_json_api_adapter 0.9.0 [collection flutter_data json_api]
- flutter_draggable_gridview 0.0.12 [flutter]
- flutter_easyrefresh 2.2.2 [flutter]
- flutter_foreground_task 6.1.2 [flutter plugin_platform_interface shared_preferences]
- flutter_hooks 0.20.5 [flutter]
- flutter_html 3.0.0-beta.2 [html csslib collection list_counter flutter]
- flutter_image_compress 2.3.0 [flutter flutter_image_compress_platform_interface flutter_image_compress_common flutter_image_compress_web flutter_image_compress_macos flutter_image_compress_ohos]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_native_splash 2.4.1 [args flutter flutter_web_plugins html image meta path universal_io xml yaml ansicolor]
- flutter_phoenix 1.1.1 [flutter]
- flutter_secure_storage 9.2.2 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_slidable 3.1.1 [flutter]
- flutter_sticky_header 0.6.5 [flutter value_layout_builder]
- flutter_stripe 10.1.1 [flutter meta stripe_android stripe_ios stripe_platform_interface]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_vibrate 1.3.0 [flutter]
- font_awesome_flutter 10.6.0 [flutter]
- fuzzy 0.5.1 [stringr]
- gal 2.3.0 [flutter]
- glob 2.1.2 [async collection file path string_scanner]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- heap_flutter_bridge 0.1.3 [flutter plugin_platform_interface]
- hooks_riverpod 2.5.4 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- html_unescape 2.0.0
- http 1.2.2 [async http_parser meta web]
- image 4.2.0 [archive meta xml]
- image_cropper 8.0.2 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intercom_flutter 9.0.9 [flutter flutter_web_plugins intercom_flutter_platform_interface intercom_flutter_web]
- intl 0.18.1 [clock meta path]
- isar 3.1.0+1 [ffi js meta]
- isar_flutter_libs 3.1.0+1 [flutter isar]
- jiffy 5.0.1 [intl]
- json_annotation 4.9.0 [meta]
- local_auth 2.3.0 [flutter local_auth_android local_auth_darwin local_auth_platform_interface local_auth_windows]
- map_launcher 3.5.0 [flutter]
- messagepack 0.2.1
- mime 1.0.6
- modal_bottom_sheet 2.1.2+1 [flutter]
- native_device_orientation 2.0.3 [flutter plugin_platform_interface]
- objectbox 4.0.3 [collection flat_buffers ffi meta path]
- objectbox_flutter_libs 4.0.3 [flutter objectbox path_provider]
- package_info_plus 8.0.3 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- path_provider 2.1.4 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- perfect_volume_control 1.0.5 [flutter]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- photo_view 0.15.0 [flutter]
- pool 1.5.1 [async stack_trace]
- recase 4.1.0
- reorderables 0.6.0 [flutter]
- responsive_builder 0.7.0 [flutter provider]
- sentry_flutter 8.9.0 [flutter flutter_web_plugins sentry package_info_plus meta ffi file]
- shared_preferences 2.3.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer_animation 2.2.1 [flutter]
- sliding_up_panel 2.0.0+1 [flutter]
- sliver_tools 0.2.12 [flutter]
- smooth_page_indicator 1.2.0+3 [flutter]
- syncfusion_flutter_datepicker 26.2.14 [flutter intl syncfusion_flutter_core]
- syncfusion_flutter_signaturepad 26.2.14 [flutter syncfusion_flutter_core]
- synchronized 3.3.0+3
- timelines 0.1.0 [flutter]
- timer_builder 2.0.0 [flutter]
- torch_controller 2.0.1 [flutter]
- tuple 2.0.2
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- validators 3.0.0
- video_compress 3.1.3 [flutter]
- video_thumbnail 0.5.3 [flutter]
- visibility_detector 0.4.0+2 [flutter]
- wc_form_validators 1.0.1 [flutter]
- webview_flutter 4.10.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- auto_route_generator 7.3.2 [build source_gen analyzer path build_runner code_builder dart_style xml args glob auto_route]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- fake_async 1.3.1 [clock collection]
- fake_cloud_firestore 3.0.3 [flutter cloud_firestore cloud_firestore_platform_interface collection plugin_platform_interface quiver rxdart mock_exceptions fake_firebase_security_rules rx equatable clock]
- faker 2.2.0 [crypto]
- firebase_storage_mocks 0.7.0 [flutter firebase_storage]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- freezed 2.5.7 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation dart_style]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math webdriver]
- isar_generator 3.1.0+1 [analyzer build dart_style dartx glob isar path source_gen xxh3]
- json_serializable 6.8.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mockito 5.4.4 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- mocktail 1.0.4 [collection matcher test_api]
- objectbox_generator 4.0.3 [objectbox analyzer build collection dart_style glob path source_gen pubspec_parse yaml http pointycastle]
- path 1.9.0
- pedantic 1.11.1
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- test 1.25.7 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]

dependency overrides:
- analyzer 6.8.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- collection 1.19.0
- flutter_plugin_android_lifecycle 2.0.23 [flutter]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- font_awesome_flutter 10.6.0 [flutter]
- image 4.2.0 [archive meta xml]
- intl 0.18.1 [clock meta path]
- meta 1.16.0
- rxdart 0.28.0
- watcher 1.1.0 [async path]

transitive dependencies:
- _fe_analyzer_shared 73.0.0 [meta]
- _flutterfire_internals 1.3.45 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.2
- ansicolor 2.0.3
- antlr4 4.13.2 [logging collection]
- args 2.5.0
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.2 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- carousel_slider 5.0.0 [flutter]
- cel 0.5.3 [antlr4 collection equatable]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.1 [meta path]
- cloud_firestore_platform_interface 6.4.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.2.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- cloud_functions_platform_interface 5.5.34 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.9.12 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- colorfilter_generator 0.0.8 [flutter matrix2d]
- convert 3.1.1 [typed_data]
- coverage 1.9.2 [args glob logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.5 [typed_data]
- csslib 0.17.3 [source_span]
- dartx 1.2.0 [characters collection crypto meta path time]
- device_info_plus_platform_interface 7.0.1 [flutter meta plugin_platform_interface]
- fake_firebase_security_rules 0.5.3 [antlr4 cel equatable logger tuple]
- ffi 2.1.3
- file 7.0.0 [meta path]
- file_selector_linux 0.9.3 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- firebase_auth_platform_interface 7.4.8 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_remote_config_platform_interface 1.4.41 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.6.13 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- firebase_storage 12.2.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- firebase_storage_platform_interface 5.1.32 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.10.4 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http meta web]
- fixnum 1.1.0
- flat_buffers 23.5.26
- flutter_image_compress_common 1.0.5 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_macos 1.0.2 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_ohos 0.0.3 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_platform_interface 1.0.5 [flutter plugin_platform_interface cross_file]
- flutter_image_compress_web 0.1.4+1 [flutter flutter_web_plugins flutter_image_compress_platform_interface js]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_riverpod 2.5.3 [collection flutter meta riverpod state_notifier]
- flutter_secure_storage_linux 1.2.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.1.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.2.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.1.2 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- frontend_server_client 4.0.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- graphs 2.3.2 [collection]
- hive 2.2.3 [meta crypto]
- html 0.15.4 [csslib source_span]
- http_interop 1.0.1 [http_parser]
- http_multi_server 3.2.1 [async]
- http_parser 4.1.0 [collection source_span string_scanner typed_data]
- image_cropper_for_web 6.0.2 [flutter flutter_web_plugins image_cropper_platform_interface web]
- image_cropper_platform_interface 7.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.12+15 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.5 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- inflection3 0.5.3+2
- intercom_flutter_platform_interface 2.0.1 [flutter plugin_platform_interface]
- intercom_flutter_web 1.1.3 [flutter flutter_web_plugins intercom_flutter_platform_interface uuid web]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json_api 7.0.1 [http_parser http_interop]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- list_counter 1.0.2
- local_auth_android 1.0.46 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_darwin 1.4.1 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.10 [flutter plugin_platform_interface]
- local_auth_windows 1.0.11 [flutter local_auth_platform_interface]
- logger 2.4.0
- logging 1.2.0
- macros 0.1.2-main.4 [_macros]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- matrix2d 1.0.4
- mock_exceptions 0.8.2 [matcher]
- more 4.3.0 [characters clock collection meta]
- nested 1.0.0 [flutter]
- node_preamble 2.0.2
- octo_image 2.1.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 3.0.1 [flutter meta plugin_platform_interface]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.12 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- permission_handler_android 12.0.12 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.5 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+2 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.2.3 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.5
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.9.1 [collection convert js]
- process 5.0.2 [file path platform]
- provider 6.1.2 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.3.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.2 [matcher]
- retry 3.1.2
- riverpod 2.5.3 [collection meta stack_trace state_notifier]
- rx 0.4.0 [collection matcher meta more]
- sentry 8.9.0 [http meta stack_trace uuid]
- shared_preferences_android 2.3.3 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.3 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.3 [convert http_parser mime path shelf]
- shelf_web_socket 2.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_helper 1.3.4 [analyzer collection source_gen]
- source_map_stack_trace 2.1.2 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.0 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.0 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.4+5 [synchronized path meta]
- sqflite_darwin 2.4.1-1 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.11.1 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- stringr 1.0.0 [characters]
- stripe_android 10.2.1 [flutter]
- stripe_ios 10.2.0 [flutter]
- stripe_platform_interface 10.2.0 [flutter freezed_annotation json_annotation meta plugin_platform_interface]
- sync_http 0.3.1
- syncfusion_flutter_core 26.2.14 [vector_math flutter]
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.6.4 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- time 2.1.4 [clock]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.3.12 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.2 [flutter url_launcher_platform_interface]
- value_layout_builder 0.3.1 [flutter]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 14.2.5
- web 1.1.0
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.1 [async crypto stream_channel web web_socket]
- webdriver 3.0.3 [matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.2.1 [logging]
- webview_flutter_android 4.0.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.16.0 [flutter path webview_flutter_platform_interface]
- win32 5.6.0 [ffi]
- win32_registry 1.1.5 [ffi win32]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- xxh3 1.1.0
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>
