### ISSUE TITLE
[cloud_firestore]: Semantic Issue (Xcode): Use of undeclared identifier 'FIRVectorValue'

### ISSUE THREAD

**Issue by ben-milanko** [firebase/flutterfire#16906]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

iOS

### Description

The Flutter app fails to build with the below error.

### Reproducing the issue

I tried to create a fresh flutter project with only `firebase_core: 3.9.0` and `cloud_firestore: ^5.6.0` but the app builds without issue.

### Firebase Core version

3.9.0

### Flutter Version

3.27.1

### Relevant Log Output

```shell
Launching lib/main.dart on Ben’s iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: N5K9GK8B27
Xcode build done.                                           12.0s
Failed to build iOS app
Could not build the precompiled application for the device.
Semantic Issue (Xcode): Use of undeclared identifier 'FIRVectorValue'
/Users/ben/.pub-cache/hosted/pub.dev/cloud_firestore-5.6.0/ios/cloud_firestore/Sources/cloud_firestore/FLTFirebaseFirestoreReader.m:40:15
2

Error launching application on Ben’s iPad.

Exited (1).
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.6.0
Flutter SDK 3.27.1
trax 1.5.10+231

dependencies:
- app_links 6.3.3 [flutter app_links_linux app_links_platform_interface app_links_web]
- archive 3.6.1 [crypto path]
- boxy 2.2.1 [flutter vector_math]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- chewie 1.8.5 [cupertino_icons flutter provider video_player wakelock_plus]
- cloud_firestore 5.6.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 5.2.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.19.0
- connectivity_plus 6.1.1 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- context_menus 2.0.0+1 [flutter url_launcher]
- cryptography 2.7.0 [collection crypto ffi js meta typed_data]
- device_info_plus 10.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- excel 4.0.6 [archive xml collection equatable]
- exif 3.3.0 [args collection convert json_annotation sprintf]
- file 7.0.0 [meta path]
- file_picker 8.1.6 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file web]
- firebase_analytics 11.3.6 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.3.1+7 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.3.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.9.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.2.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 6.0.11 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 15.1.6 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 12.3.7 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fl_chart 0.70.0 [equatable flutter vector_math]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_animate 4.5.2 [flutter flutter_shaders]
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_map 7.0.2 [async collection dart_earcut flutter http latlong2 logger meta polylabel proj4dart vector_math]
- flutter_map_animations 0.8.0 [flutter flutter_map latlong2]
- flutter_map_cancellable_tile_provider 3.0.2 [dio flutter flutter_map meta]
- flutter_map_dragmarker 7.0.0 [flutter flutter_map latlong2]
- flutter_map_location_marker 9.1.2 [flutter dchs_flutter_compass flutter_map geolocator latlong2]
- flutter_map_marker_cluster 1.3.6 [flutter flutter_map flutter_map_marker_popup latlong2]
- flutter_map_tile_caching 10.0.0-dev.6 [async collection dart_earcut flat_buffers flutter flutter_map http latlong2 meta objectbox objectbox_flutter_libs path path_provider]
- flutter_markdown 0.7.4+3 [flutter markdown meta path]
- flutter_mobx 2.3.0 [flutter mobx provider]
- flutter_pdfview 1.3.4 [flutter]
- flutter_progress_hud 2.0.2 [flutter]
- flutter_timezone 4.0.0 [flutter flutter_web_plugins]
- flutter_typeahead 5.2.0 [flutter flutter_keyboard_visibility pointer_interceptor]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- formatted_text 4.0.1 [equatable flutter]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- geolocator 13.0.2 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get_it 8.0.3 [async collection meta]
- go_router 14.6.2 [collection flutter flutter_web_plugins logging meta]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- http 1.2.2 [async http_parser meta web]
- image 4.3.0 [archive meta xml]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- image_size_getter 2.2.0 [collection hashcodes]
- intl 0.19.0 [clock meta path]
- intl_phone_field 3.2.0 [flutter]
- jiffy 6.3.2 [intl]
- just_the_tooltip 0.0.12 [flutter]
- latlong2 0.9.1 [intl]
- logger 2.5.0
- material_floating_search_bar 0.4.1 [flutter meta]
- mobile_scanner 7.0.0-beta.3 [flutter flutter_web_plugins plugin_platform_interface web]
- mobx 2.5.0 [meta collection]
- native_exif 0.6.0 [flutter intl]
- open_file_plus 3.4.1+1 [flutter ffi]
- overlay_support 2.1.0 [flutter async]
- package_info_plus 8.1.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- path 1.9.0
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- pdf 3.11.1 [archive barcode bidi crypto image meta path_parsing vector_math xml]
- pdfx 2.8.0 [flutter flutter_web_plugins plugin_platform_interface device_info_plus uuid meta extension synchronized universal_platform photo_view vector_math web]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- pinput 5.0.0 [flutter universal_platform]
- pluto_grid 8.0.0 [flutter intl rxdart collection]
- proj4dart 2.1.0 [mgrs_dart wkt_parser meta]
- provider 6.1.2 [collection flutter nested]
- qr_flutter 4.1.0 [flutter qr]
- retry 3.1.2
- scrollable_positioned_list 0.3.8 [flutter collection]
- scrollview_observer 1.24.0 [flutter]
- sembast 3.8.0+1 [meta path synchronized]
- sembast_web 2.4.0+4 [web sembast idb_shim synchronized]
- share_plus 10.1.3 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- shared_preferences 2.3.4 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- signature 5.5.0 [flutter flutter_svg image]
- sliver_tools 0.2.12 [flutter]
- smooth_page_indicator 1.2.0+3 [flutter]
- spreadsheet_decoder 2.3.0 [archive xml]
- super_clipboard 0.8.24 [flutter collection meta super_native_extensions]
- super_drag_and_drop 0.8.24 [flutter collection super_native_extensions super_clipboard]
- tuple 2.0.2
- two_dimensional_scrollables 0.3.3 [flutter]
- universal_html 2.2.4 [async csslib charcode collection html meta source_span typed_data universal_io]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- video_player 2.9.2 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_thumbnail 0.5.4 [flutter]
- zxcvbn 1.0.0

dev dependencies:
- build_runner 2.4.14 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- dart_code_metrics_presets 2.19.0
- dartdoc 8.3.1 [analyzer args collection crypto glob html logging markdown meta package_config path pub_semver source_span yaml]
- fake_cloud_firestore 3.0.2 [flutter cloud_firestore cloud_firestore_platform_interface collection plugin_platform_interface quiver rxdart mock_exceptions fake_firebase_security_rules rx equatable clock]
- firebase_auth_mocks 0.14.1 [flutter firebase_auth firebase_core meta equatable dart_jsonwebtoken uuid firebase_auth_platform_interface mock_exceptions]
- firebase_storage_mocks 0.7.0 [flutter firebase_storage]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- freezed 2.5.7 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation dart_style]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math webdriver]
- lint 2.3.0
- mobx_codegen 2.7.0 [analyzer build build_resolvers meta mobx path source_gen]
- mock_exceptions 0.8.2 [matcher]
- mocktail 1.0.4 [collection matcher test_api]
- mocktail_image_network 1.2.0 [mocktail]
- network_image_mock 2.1.1 [flutter mockito]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- plugin_platform_interface 2.1.8 [meta]

dependency overrides:
- flutter_keyboard_visibility_web 2.0.1 [flutter_keyboard_visibility_platform_interface web flutter_web_plugins flutter]

transitive dependencies:
- _fe_analyzer_shared 76.0.0 [meta]
- _flutterfire_internals 1.3.48 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.3
- adaptive_number 1.0.0 [fixnum]
- analyzer 6.11.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- animated_stack_widget 0.0.4 [flutter]
- antlr4 4.13.2 [logging collection]
- app_links_linux 1.0.3 [flutter app_links_platform_interface gtk]
- app_links_platform_interface 2.0.2 [flutter plugin_platform_interface]
- app_links_web 1.0.4 [flutter flutter_web_plugins app_links_platform_interface web]
- args 2.6.0
- async 2.11.0 [collection meta]
- barcode 2.2.8 [meta qr]
- bidi 2.0.12
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.3 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.3 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.3 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- cel 0.5.3 [antlr4 collection equatable]
- characters 1.3.0
- charcode 1.4.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 6.6.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.4.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- cloud_functions_platform_interface 5.5.40 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.10.5 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.1.2 [typed_data]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.6 [typed_data]
- csslib 1.0.2 [source_span]
- cupertino_icons 1.0.8
- dart_earcut 1.1.0
- dart_jsonwebtoken 2.14.2 [crypto pointycastle convert collection ed25519_edwards clock]
- dart_style 2.3.7 [analyzer args collection package_config path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- dchs_flutter_compass 1.0.0 [flutter plugin_platform_interface]
- device_info_plus_platform_interface 7.0.2 [flutter meta plugin_platform_interface]
- dio 5.7.0 [async http_parser meta path dio_web_adapter]
- dio_web_adapter 2.0.0 [dio http_parser meta web]
- ed25519_edwards 0.3.1 [collection crypto convert adaptive_number]
- equatable 2.0.7 [collection meta]
- extension 0.6.0 [meta]
- fake_async 1.3.1 [clock collection]
- fake_firebase_security_rules 0.5.3 [antlr4 cel equatable logger tuple]
- ffi 2.1.3
- file_selector_linux 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 4.2.8 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+5 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_app_check_platform_interface 0.1.0+41 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.2.0+3 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
- firebase_auth_platform_interface 7.4.10 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.5 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.19.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.7.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+47 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.49 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.9.5 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_storage_platform_interface 5.1.34 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.10.6 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http meta web]
- fixnum 1.1.1
- flat_buffers 23.5.26
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_map_marker_popup 7.0.0 [flutter animated_stack_widget flutter_map latlong2 provider]
- flutter_plugin_android_lifecycle 2.0.24 [flutter]
- flutter_shaders 0.1.3 [flutter vector_math]
- flutter_svg 2.0.16 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- frontend_server_client 4.0.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- geolocator_android 4.6.1 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.8+1 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.4 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 4.1.1 [flutter flutter_web_plugins geolocator_platform_interface web]
- geolocator_windows 0.2.3 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- graphs 2.3.2 [collection]
- gtk 2.1.0 [ffi flutter meta]
- hashcodes 2.0.0
- html 0.15.5 [csslib source_span]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.1 [collection source_span string_scanner typed_data]
- idb_shim 2.6.1+7 [sembast collection path meta web]
- image_picker_android 0.8.12+18 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.6 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- io 1.0.5 [meta path string_scanner]
- irondash_engine_context 0.5.4 [flutter plugin_platform_interface]
- irondash_message_channel 0.7.0 [flutter ffi]
- js 0.6.7 [meta]
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lists 1.0.1 [meta]
- logging 1.3.0
- macros 0.1.3-main.0 [_macros]
- markdown 7.2.2 [args meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mgrs_dart 2.0.0 [unicode]
- mime 2.0.0
- mockito 5.4.5 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- more 4.4.0 [characters clock collection meta]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- objectbox 4.0.3 [collection flat_buffers ffi meta path]
- objectbox_flutter_libs 4.0.3 [flutter objectbox path_provider]
- octo_image 2.1.0 [flutter]
- package_config 2.1.1 [path]
- package_info_plus_platform_interface 3.0.2 [flutter meta plugin_platform_interface]
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.15 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- permission_handler_android 12.0.13 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.5 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+5 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.2.3 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- photo_view 0.15.0 [flutter]
- pixel_snap 0.1.5 [flutter]
- platform 3.1.5
- pointer_interceptor 0.10.1+2 [flutter flutter_web_plugins pointer_interceptor_ios pointer_interceptor_platform_interface pointer_interceptor_web]
- pointer_interceptor_ios 0.10.1 [flutter plugin_platform_interface pointer_interceptor_platform_interface]
- pointer_interceptor_platform_interface 0.10.0+1 [flutter plugin_platform_interface]
- pointer_interceptor_web 0.10.2+1 [flutter flutter_web_plugins plugin_platform_interface pointer_interceptor_platform_interface web]
- pointycastle 3.9.1 [collection convert js]
- polylabel 1.0.1 [collection]
- pool 1.5.1 [async stack_trace]
- process 5.0.2 [file path platform]
- pub_semver 2.1.5 [collection meta]
- pubspec_parse 1.4.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.2 [meta]
- quiver 3.2.2 [matcher]
- rx 0.4.0 [collection matcher meta more]
- rxdart 0.27.7
- share_plus_platform_interface 5.0.2 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.4.0 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 2.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.1 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.0 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.4+6 [synchronized path meta]
- sqflite_darwin 2.4.1 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.12.0 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.1
- string_scanner 1.3.0 [source_span]
- super_native_extensions 0.8.24 [flutter flutter_web_plugins meta ffi collection path uuid irondash_engine_context irondash_message_channel device_info_plus pixel_snap web]
- sync_http 0.3.1
- synchronized 3.3.0+3
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.2 [json_annotation]
- typed_data 1.4.0 [collection]
- unicode 0.3.1 [lists]
- universal_io 2.2.2 [collection meta typed_data]
- universal_platform 1.1.0
- url_launcher_android 6.3.14 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.2 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.3 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.15 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.12
- vector_graphics_compiler 1.1.16 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- video_player_android 2.7.16 [flutter video_player_platform_interface]
- video_player_avfoundation 2.6.5 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.3 [flutter plugin_platform_interface]
- video_player_web 2.3.3 [flutter flutter_web_plugins video_player_platform_interface web]
- vm_service 14.3.0
- wakelock_plus 1.2.10 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus web]
- wakelock_plus_platform_interface 1.2.2 [flutter plugin_platform_interface meta]
- watcher 1.1.1 [async path]
- web 1.1.0
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.1 [async crypto stream_channel web web_socket]
- webdriver 3.0.4 [matcher path stack_trace sync_http]
- win32 5.9.0 [ffi]
- win32_registry 1.1.5 [ffi win32]
- wkt_parser 2.0.0
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

```

</details>
