### ISSUE TITLE
[firebase_auth]: Microsoft Federated identity sign-in not working with Firebase MFA enabled authentication credentials/user in iOS platform

### ISSUE THREAD

**Issue by chetansharmapsi** [firebase/flutterfire#16929]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

I am trying to integrate Microsoft Federated identity login in flutter with Firebase. Able to integrate it successfully for Web and Android platforms, but getting issues for few cases in iOS platform. When trying to sign-in using Microsoft Federated identity for the credential/user who have MFA enabled, iOS app getting crashed just after validating Microsoft credentials, before initiating MFA flow. Same case and flow working fine in Android and Web platform. In iOS too only getting issues with MFA enabled credential/user, when trying to sign-in using Microsoft Federated identity without MFA, it is working fine in iOS too. So issue is with Microsoft Federated identity sign-in with MFA enabled credential. 

Using below code for sing in using Microsoft : 

 ```
Future<SignInResult> signInWithMicrosoft() async {
    UserCredential? userCredential;
    final microsoftProvider = MicrosoftAuthProvider();

    try {
      if (isWebPlatform()) {
        userCredential =
            await FirebaseAuth.instance.signInWithPopup(microsoftProvider);
      } else {
        userCredential =
            await FirebaseAuth.instance.signInWithProvider(microsoftProvider);
      }

      if (userCredential.user == null) {
        // handling user null
      }
    } on FirebaseAuthMultiFactorException catch (e) {
      // handling FirebaseAuthMultiFactorException 
    } on FirebaseAuthException catch (e) {
       // handling FirebaseAuthException 
    } on Exception {
       // handling Exception 
    }

    .
    .
    .
}
```

When running above code in iOS platform and trying to sing in with Microsoft credentials which have MFA enabled, iOS app getting crashed before showing MFA flow. It is working fine for the Microsoft credentials which do not have MFA attached and enabled, but getting crash for credentials which have MFA attached and enabled.

### Reproducing the issue

- Enable and add Microsoft as sign-in methods in Firebase project
- Enable MFA in Firebase project
- Integrate MFA flow and Microsoft Federated identity flow in flutter with Firebase authentication(for sign-up, sing-in, re-authentication, anonymous user upgrade) using Firebase dependencies (`firebase_auth`, `firebase_core` and other required dependencies)
- Run Flutter app in iOS platform
- Create user, attach Microsoft credentials using Microsoft Federated identity flow, then attach MFA phone number (here can use test numbers too).
- Now logout user and try to login with same Microsoft credentials
- Just after Microsoft credentials verification, before starting MFA flow, iOS app will crash.

### Firebase Core version

2.17.0

### Flutter Version

3.13.8 

### Relevant Log Output

```shell
FLTFirebaseDynamicLinks: An error occurred while calling method FirebaseDynamicLinks#getDynamicLink, errorOrNil => {
    NSLocalizedFailureReason = "Universal link URL could not be parsed by Dynamic Links.";
}
Unsupported value: <FIRMultiFactorResolver: 0x6000020e4ab0> of type FIRMultiFactorResolver
Lost connection to device.

Exited.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.1.4
Flutter SDK 3.13.8
project_v2 0.0.0

dependencies:
- after_layout 1.2.0 [flutter]
- android_id 0.1.3+1 [flutter]
- animated_size_and_fade 3.0.1 [flutter]
- animated_tree_view 2.1.0 [scroll_to_index diffutil_dart collection flutter]
- animations 2.0.8 [flutter]
- another_stepper 1.2.2 [flutter]
- app_links 3.4.1 [flutter app_links_platform_interface flutter_web_plugins]
- appinio_video_player 1.2.2 [video_player flutter]
- archive 3.4.6 [crypto path pointycastle]
- async 2.11.0 [collection meta]
- bubble 1.2.1 [flutter]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- carousel_slider 4.2.1 [flutter]
- chat_bubbles 1.5.0 [flutter intl]
- chatview 1.3.1 [flutter intl url_launcher image_picker timeago cached_network_image]
- chewie 1.7.5 [cupertino_icons flutter provider video_player wakelock_plus]
- clean_settings_nnbd 0.2.0 [flutter]
- cloud_firestore 4.9.3 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 4.4.2 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.17.2
- community_material_icon 5.9.55 [flutter]
- connectivity_plus 3.0.3 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- crypto 3.0.3 [typed_data]
- csslib 0.17.0 [source_span]
- cupertino_icons 1.0.6
- custom_sliding_segmented_control 1.8.3 [flutter]
- device_info_plus 9.1.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]        
- dotted_border 2.1.0 [flutter path_drawing]
- el_tooltip 2.2.1 [flutter]
- email_validator 3.0.0
- expandable 5.0.1 [flutter]
- fake_cloud_firestore 2.4.1+1 [flutter cloud_firestore cloud_firestore_platform_interface collection plugin_platform_interface quiver rxdart mock_exceptions fake_firebase_security_rules rx]
- faker 2.1.0 [crypto]
- file_picker 5.3.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- filesize 2.0.1
- filesystem_picker 2.0.1 [flutter path]
- firebase_analytics 10.5.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.10.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.17.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.3.7 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.3.7 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 14.6.9 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 11.2.8 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fixnum 1.1.0
- fl_chart 0.41.0 [flutter equatable]
- flex_color_picker 3.3.0 [flex_seed_scheme flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_adaptive_scaffold 0.1.7+1 [flutter]
- flutter_animate 4.3.0 [flutter]
- flutter_animated_loadingkit 0.0.7 [flutter]
- flutter_app_badger 1.5.0 [flutter]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_calendar_carousel 2.4.2 [intl flutter]
- flutter_chat_types 3.6.2 [equatable json_annotation meta]
- flutter_chat_ui 1.6.9 [diffutil_dart equatable flutter flutter_chat_types flutter_link_previewer flutter_parsed_text intl meta photo_view scroll_to_index url_launcher visibility_detector]
- flutter_colorpicker 1.0.3 [flutter]
- flutter_dropzone 3.0.6 [flutter flutter_dropzone_platform_interface flutter_dropzone_web]
- flutter_firebase_chat_core 1.6.7 [cloud_firestore firebase_auth firebase_core flutter flutter_chat_types meta]
- flutter_inappwebview 5.7.2+3 [flutter]
- flutter_jailbreak_detection 1.10.0 [flutter]
- flutter_linkify 6.0.0 [flutter linkify]
- flutter_local_notifications 9.9.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_markdown 0.6.18 [flutter markdown meta path]
- flutter_markdown_selectionarea 0.6.17+1 [flutter markdown meta path]
- flutter_quill 7.4.16 [flutter collection flutter_colorpicker flutter_keyboard_visibility quiver url_launcher pedantic characters diff_match_patch i18n_extension device_info_plus platform pasteboard flutter_test]
- flutter_quill_extensions 0.5.0 [flutter flutter_quill gal http image_picker math_keyboard photo_view universal_html url_launcher video_player youtube_player_flutter]
- flutter_radar_chart 0.2.1 [flutter]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_spinkit 5.2.0 [flutter]
- flutter_staggered_grid_view 0.6.2 [flutter]
- flutter_svg 2.0.7 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_switch 0.3.2 [flutter]
- flutter_typeahead 5.0.1 [flutter flutter_keyboard_visibility pointer_interceptor]
- flutter_widget_from_html_core 0.14.11 [csslib flutter html logging]
- font_awesome_flutter 9.2.0 [flutter]
- fuzzywuzzy 1.1.6 [collection]
- gaimon 1.2.0 [flutter]
- get 4.6.6 [flutter]
- get_storage 2.1.1 [flutter get path_provider]
- google_fonts 6.1.0 [flutter http path_provider crypto]
- google_sign_in 6.1.6 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]      
- googleapis_auth 1.4.1 [args crypto http http_parser js]
- grpc 3.2.4 [archive async crypto fixnum googleapis_auth meta http http2 protobuf clock]
- highlight 0.7.0 [collection]
- html 0.15.4 [csslib source_span]
- html2md 1.3.1 [html collection]
- http 1.1.0 [async http_parser meta]
- http2 2.2.0
- i18n_extension 9.0.2 [sprintf args equatable intl flutter]
- image_cropper 1.5.1 [flutter]
- image_picker 0.8.9 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- implicitly_animated_reorderable_list 0.4.2 [flutter async meta]
- infinite_carousel 1.0.3 [flutter]
- intl 0.18.1 [clock meta path]
- js 0.6.7 [meta]
- keyboard_actions 4.2.0 [flutter]
- launch_review 3.0.1 [flutter]
- logger 1.4.0
- markdown 7.2.1 [args meta]
- mesh_gradient 1.3.6 [flutter flutter_shaders]
- meta 1.9.1
- mockito 5.4.2 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- native_device_orientation 1.2.1 [flutter meta]
- notification_permissions 0.6.1 [flutter]
- open_mail_app 0.4.5 [platform url_launcher flutter]
- package_info 2.0.2 [flutter]
- package_info_plus 4.2.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- pdf 3.10.4 [archive barcode bidi crypto image meta path_parsing vector_math xml]
- pedantic 1.11.1
- percent_indicator 4.2.3 [flutter]
- permission_handler 7.2.0 [flutter meta permission_handler_platform_interface]
- pointer_interceptor 0.9.3+6 [flutter]
- printing 5.11.0 [ffi flutter flutter_web_plugins http image js meta pdf plugin_platform_interface]
- protoc_plugin 21.1.2 [fixnum path protobuf]
- provider 6.0.5 [collection flutter nested]
- public_suffix 3.0.0 [punycode]
- pubnub 4.3.4 [async cbor convert crypto encrypt form_data meta pedantic pool xml]
- quill_markdown 0.1.0 [flutter collection meta]
- random_color 1.0.6-nullsafety [flutter]
- readmore 2.2.0 [flutter]
- recase 4.1.0
- rxdart 0.27.7
- salomon_bottom_bar 3.3.2 [flutter]
- scroll_to_index 3.0.1 [flutter]
- scrollable_positioned_list 0.3.8 [flutter collection]
- share_plus 7.2.1 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- side_sheet 1.0.4 [flutter]
- simple_animations 5.0.2 [flutter collection]
- sortedmap 0.5.3 [quiver]
- store_redirect 2.0.1 [flutter]
- super_tooltip 2.0.8 [flutter]
- syncfusion_flutter_charts 23.1.41 [flutter intl vector_math syncfusion_flutter_core]
- syncfusion_flutter_core 23.1.41 [vector_math flutter]
- syncfusion_flutter_datagrid 23.1.41 [flutter syncfusion_flutter_core collection]
- syncfusion_flutter_datagrid_export 23.1.41 [flutter syncfusion_flutter_datagrid syncfusion_flutter_xlsio syncfusion_flutter_pdf collection]
- syncfusion_flutter_pdf 23.1.41 [flutter intl xml syncfusion_flutter_core crypto convert]
- syncfusion_flutter_pdfviewer 23.1.41 [flutter vector_math async http uuid device_info_plus intl syncfusion_pdfviewer_platform_interface syncfusion_pdfviewer_web syncfusion_pdfviewer_macos syncfusion_pdfviewer_windows syncfusion_flutter_core syncfusion_flutter_pdf 
syncfusion_flutter_signaturepad url_launcher]
- synchronized 3.1.0
- text_analysis 1.0.0+2 [collection porter_2_stemmer]
- textfield_tags 3.0.1 [flutter]
- timeago 3.5.0 [intl]
- timelines 0.1.0 [flutter]
- tuple 2.0.2
- universal_html 2.2.2 [async csslib charcode collection html meta source_span typed_data universal_io]
- url_launcher 6.1.14 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.1.0 [crypto sprintf]
- vector_math 2.1.4
- version 3.0.2
- video_player 2.8.3 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]  
- video_player_web_hls 1.1.0 [flutter flutter_web_plugins http js video_player_platform_interface]
- visibility_detector 0.4.0+2 [flutter]
- wakelock 0.6.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- websafe_svg 3.0.1+1 [convert flutter flutter_svg http logging meta]
- webview_flutter 3.0.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- youtube_player_flutter 8.1.2 [flutter flutter_inappwebview]

dev dependencies:
- dart_code_metrics_presets 2.13.0
- flutter_lints 3.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

dependency overrides:
- vector_graphics 1.1.7 [flutter vector_graphics_codec]
- win32 4.1.4 [ffi]

transitive dependencies:
- _fe_analyzer_shared 61.0.0 [meta]
- _flutterfire_internals 1.3.7 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.13.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]  
- antlr4 4.13.1 [logging collection]
- app_links_platform_interface 1.1.0 [flutter plugin_platform_interface]
- args 2.4.2
- asn1lib 1.5.3
- barcode 2.2.4 [meta qr]
- bidi 2.0.10
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- built_collection 5.1.1
- built_value 8.6.3 [built_collection collection fixnum meta]
- cbor 4.1.0 [typed_data convert meta]
- cel 0.5.3 [antlr4 collection equatable]
- characters 1.3.0
- charcode 1.3.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.16.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface] 
- cloud_firestore_web 3.7.2 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.5.2 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.6.2 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]      
- code_builder 4.7.0 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+6 [js meta]
- dart_style 2.3.2 [analyzer args path pub_semver source_span]
- dbus 0.7.8 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- diffutil_dart 3.0.0
- encrypt 5.0.3 [args asn1lib clock collection crypto pointycastle]
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- fake_firebase_security_rules 0.5.2 [antlr4 cel equatable logger tuple]
- ffi 2.1.0
- file 6.1.4 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.7.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+1 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.19.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]   
- firebase_auth_web 5.8.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+7 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]    
- firebase_messaging_platform_interface 4.5.8 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.8 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter 
flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.4.7 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.8 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flex_seed_scheme 1.4.0 [collection flutter meta]
- flutter_blurhash 0.7.0 [flutter]
- flutter_dropzone_platform_interface 2.0.6 [flutter plugin_platform_interface]
- flutter_dropzone_web 3.0.12 [flutter flutter_web_plugins flutter_dropzone_platform_interface js]
- flutter_keyboard_visibility 5.4.1 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_link_previewer 3.2.2 [flutter flutter_chat_types flutter_linkify html http linkify meta url_launcher]
- flutter_local_notifications_linux 0.5.1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_math_fork 0.7.1 [flutter flutter_svg provider meta collection tuple]
- flutter_parsed_text 2.2.1 [flutter]
- flutter_plugin_android_lifecycle 2.0.16 [flutter]
- flutter_shaders 0.1.2 [flutter vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- form_data 1.0.0-nullsafety.1
- gal 2.1.2 [flutter]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.2.2 [js meta]
- google_sign_in_android 6.1.22 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.6.5 [flutter google_sign_in_platform_interface pigeon]
- google_sign_in_platform_interface 2.4.4 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.2+1 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http js]   
- holding_gesture 1.2.0 [flutter]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.3 [archive meta xml]
- image_picker_android 0.8.8+1 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.1 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]      
- jiffy 6.2.1 [intl]
- json_annotation 4.8.1 [meta]
- linkify 5.0.0
- lints 3.0.0
- logging 1.2.0
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- math_expressions 2.4.0 [vector_math]
- math_keyboard 0.2.1 [flutter flutter_localizations flutter_math_fork holding_gesture intl math_expressions petitparser]
- mime 1.0.4
- mock_exceptions 0.8.2 [matcher]
- more 3.10.2 [characters clock collection meta]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- pasteboard 0.2.0 [flutter flutter_web_plugins js]
- path 1.8.3
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.0 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_platform_interface 3.12.0 [flutter meta plugin_platform_interface]
- petitparser 5.4.0 [meta]
- photo_view 0.14.0 [flutter]
- pigeon 11.0.1 [analyzer args collection meta path yaml]
- platform 3.1.3
- plugin_platform_interface 2.1.6 [meta]
- pointycastle 3.7.3 [collection convert js]
- pool 1.5.1 [async stack_trace]
- porter_2_stemmer 3.0.2
- process 4.2.4 [file path platform]
- protobuf 3.1.0 [collection fixnum meta]
- pub_semver 2.1.4 [collection meta]
- punycode 1.0.0
- qr 3.0.1 [meta]
- quiver 3.2.1 [matcher]
- rx 0.1.3 [collection matcher meta more]
- share_plus_platform_interface 3.3.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- sky_engine 0.0.99
- source_gen 1.4.0 [analyzer async build dart_style glob path source_span yaml]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.0 [flutter sqflite_common path]
- sqflite_common 2.5.0 [synchronized path meta]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- syncfusion_flutter_signaturepad 23.1.41 [flutter syncfusion_flutter_core]
- syncfusion_flutter_xlsio 23.1.41 [flutter xml archive image intl crypto jiffy syncfusion_officecore]
- syncfusion_officecore 23.1.41 [flutter syncfusion_flutter_core]
- syncfusion_pdfviewer_macos 23.1.41 [flutter syncfusion_pdfviewer_platform_interface]
- syncfusion_pdfviewer_platform_interface 23.1.41 [flutter plugin_platform_interface]
- syncfusion_pdfviewer_web 23.1.41 [flutter flutter_web_plugins js meta syncfusion_pdfviewer_platform_interface]
- syncfusion_pdfviewer_windows 23.1.41 [flutter]
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.8.0 [path]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.1.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.7 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.20 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.8 [flutter url_launcher_platform_interface]
- vector_graphics_codec 1.1.7
- vector_graphics_compiler 1.1.7 [args meta path_parsing xml vector_graphics_codec]
- video_player_android 2.4.10 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.0 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.1 [flutter plugin_platform_interface]
- video_player_web 2.1.1 [flutter flutter_web_plugins video_player_platform_interface]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_plus 1.1.4 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus js]
- wakelock_plus_platform_interface 1.1.0 [flutter plugin_platform_interface meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.1 [flutter wakelock_platform_interface win32]
- watcher 1.1.0 [async path]
- web 0.1.4-beta
- webview_flutter_android 2.10.4 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.5 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 2.9.5 [flutter path webview_flutter_platform_interface]
- win32_registry 1.1.0 [ffi win32]
- xdg_directories 0.2.0+3 [meta path process]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

### Additional context and comments

Sharing additional crash logs from **Crashlytics**

**OS version:** 
iOS 13.1.0

**Stack trace**
```
 Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x13d1de (Missing UUID c150bc9620523b1ba71de9607f82c939)
1  libobjc.A.dylib                0x5b20 objc_exception_throw
2  CoreFoundation                 0x13cf68 (Missing UUID c150bc9620523b1ba71de9607f82c939)
3  Foundation                     0x31eb2 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:]
4  Flutter                        0x679f5d (Missing UUID 4c4c443f55553144a1676684056327ec)
5  Flutter                        0x679ab3 (Missing UUID 4c4c443f55553144a1676684056327ec)
6  Runner                         0xd96ea -[FirebaseAuthHostApiCodecWriter writeValue:] + 901 (firebase_auth_messages.g.m:901)
7  CoreFoundation                 0x1a0d11 (Missing UUID c150bc9620523b1ba71de9607f82c939)
8  Flutter                        0x679d8d (Missing UUID 4c4c443f55553144a1676684056327ec)
9  Flutter                        0x679ea8 (Missing UUID 4c4c443f55553144a1676684056327ec)
10 Flutter                        0x679ab3 (Missing UUID 4c4c443f55553144a1676684056327ec)
11 Runner                         0xd96ea -[FirebaseAuthHostApiCodecWriter writeValue:] + 901 (firebase_auth_messages.g.m:901)
12 Flutter                        0x678626 (Missing UUID 4c4c443f55553144a1676684056327ec)
13 Flutter                        0x67430b (Missing UUID 4c4c443f55553144a1676684056327ec)
14 Runner                         0xdb9ed __FirebaseAuthHostApiSetup_block_invoke_12 + 1267 (firebase_auth_messages.g.m:1267)
15 Runner                         0xeabf8 __handleAppleAuthResult_block_invoke + 606 (FLTFirebaseAuthPlugin.m:606)
16 libdispatch.dylib              0x1810 (Missing UUID d7cc111c21283e569658ad66b2e1aa76)
17 libdispatch.dylib              0x2781 (Missing UUID d7cc111c21283e569658ad66b2e1aa76)
18 libdispatch.dylib              0xecaa (Missing UUID d7cc111c21283e569658ad66b2e1aa76)
19 CoreFoundation                 0x9fe49 (Missing UUID c150bc9620523b1ba71de9607f82c939)
20 CoreFoundation                 0x9aaa9 (Missing UUID c150bc9620523b1ba71de9607f82c939)
21 CoreFoundation                 0x99e66 (Missing UUID c150bc9620523b1ba71de9607f82c939)
22 GraphicsServices               0x3bb0 (Missing UUID 5b17c7d9d5cd3e81ba6e83ae10e27368)
23 UIKitCore                      0xaa3dd0 (Missing UUID bc4c8735c9b430d9ba807429e4eb5e1a)
24 Runner                         0x6f6f main + 6 (AppDelegate.swift:6)
25 ???                            0x11352852e (Missing)
```

**Keys**
```
flutter_error_exception | FormatException: Scheme not starting with alphabetic character (at character 1) <svg width="85" height="82" viewBox="0 0 85 82" fill="none" xmlns="http://w... ^ | communities_filledCommon
-- | -- | --
flutter_error_reason | thrown FormatException: Scheme not starting with alphabetic character (at character 1) <svg width="85" height="82" viewBox="0 0 85 82" fill="none" xmlns="http://w... ^. Error thrown image failed to precache.
```
