### ISSUE TITLE
[firebase_messaging]:`io.flutter.embedding.engine.FlutterJNI.nativeAttach` shows up in crashlytics once again

### ISSUE THREAD

**Issue by mhmzdev** [firebase/flutterfire#16925]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which platforms are affected?

Android

### Description

Related issue: https://github.com/firebase/flutterfire/issues/9345
This got closed but somehow, we are seeing this issue in our Crashlytics once again:

![Image](https://github.com/user-attachments/assets/56ae80f2-06a4-4602-85ea-37ea071b79a2)

### Reproducing the issue

We are using the following plugins:
```yaml
  firebase_core: 3.8.1
  firebase_messaging: 15.1.6
  firebase_analytics: 11.3.6
  firebase_performance: 0.10.0+11
  firebase_crashlytics: 4.2.0
  firebase_performance_dio: 0.7.1
  cloud_firestore: 5.5.1
```
Please note that this issue is there for a long time in our app we have just noticed this because it has started generated alert on Crashlytics for us.

### Assumptions
Our assumption is that whenever a notification is triggered in the background an ANR happens.

### Firebase Core version

3.8.1

### Flutter Version

3.24.7

### Relevant Log Output

```shell
main (native):tid=1 systid=30542 
#00 pc 0xc12bc linker64 (__dl_strcmp_default + 188)
#01 pc 0x326a8 linker64 (__dl__Z14find_librariesP19android_namespace_tP6soinfoPKPKcmPS2_PNSt3__16vectorIS2_NS8_9allocatorIS2_EEEEmiPK17android_dlextinfobbPNS9_IS0_NSA_IS0_EEEE + 816)
#02 pc 0x35a14 linker64 (__dl__Z9do_dlopenPKciPK17android_dlextinfoPKv + 1940)
#03 pc 0x310f0 linker64 (__dl__ZL10dlopen_extPKciPK17android_dlextinfoPKv + 80)
#04 pc 0x1024 libdl.so (dlopen + 12)
#05 pc 0x67e94 libMEOW_gift.so (oppoConfigFromService::oppoConfigFromService() + 172)
#06 pc 0x732b4 libMEOW_gift.so (ARCState::ReadConfig() + 68)
#07 pc 0x72dbc libMEOW_gift.so (ARCState::Init() + 60)
#08 pc 0x7225c libMEOW_gift.so (gli_init() + 52)
#09 pc 0x72318 libMEOW_gift.so (gli_initOnce() + 32)
#10 pc 0x688b4 libMEOW_gift.so (ARC_GLUE::processInit() + 84)
#11 pc 0x721e8 libMEOW_gift.so (MEOW_Registry::process_init() + 8)
#12 pc 0x9ede0 libGLES_meow.so (MEOW::Plugin::broadcastEvent(int) + 160)
#13 pc 0xdab38 libGLES_meow.so (TLS::callInitCallback() + 80)
#14 pc 0xa1d20 libGLES_meow.so (getTLS_init() + 240)
#15 pc 0xc7324 libGLES_meow.so (eglGetError + 44)
#16 pc 0x1f3d4 libEGL.so (android::eglGetErrorImpl() + 28)
#17 pc 0x1b918 libEGL.so (eglGetDisplay + 32)
#18 pc 0x45383c split_config.arm64_v8a.apk!libflutter.so + 17178624
#19 pc 0x7b2264 split_config.arm64_v8a.apk!libflutter.so + 17178624
#20 pc 0x7b16ac split_config.arm64_v8a.apk!libflutter.so + 17178624
#21 pc 0x45e080 split_config.arm64_v8a.apk!libflutter.so + 17178624
       at io.flutter.embedding.engine.FlutterJNI.nativeAttach(FlutterJNI.java)
       at io.flutter.embedding.engine.FlutterJNI.performNativeAttach(FlutterJNI.java)
       at io.flutter.embedding.engine.FlutterJNI.attachToNative(FlutterJNI.java)
       at io.flutter.embedding.engine.FlutterEngine.attachToJni(SourceFile)
       at io.flutter.embedding.engine.FlutterEngine.<init>(SourceFile)
       at io.flutter.embedding.engine.FlutterEngine.<init>(SourceFile)
       at io.flutter.embedding.engine.FlutterEngine.<init>(SourceFile)
       at io.flutter.embedding.engine.FlutterEngine.<init>(SourceFile)
       at io.flutter.embedding.engine.FlutterEngine.<init>(SourceFile)
       at io.flutter.embedding.engine.FlutterEngine.<init>(SourceFile)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.lambda$startBackgroundIsolate$0(FlutterFirebaseMessagingBackgroundExecutor.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:268)
       at android.app.ActivityThread.main(ActivityThread.java:8017)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.6.0
Flutter SDK 3.27.0
sastaticket 0.7.81+225

dependencies:
- antdesign_icons 0.0.3 [flutter]
- app_engine 1.0.0 [flutter dio intl recase uuid hive hive_flutter firebase_remote_config]
- appsflyer_sdk 6.15.2 [flutter]
- cached_network_image 3.3.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- carousel_slider 5.0.0 [flutter]
- cloud_firestore 5.5.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- collection 1.19.0
- country_code_picker 3.0.0 [flutter collection]
- country_pickers 3.0.1 [flutter]
- countup 0.1.4 [flutter]
- credit_card_validator 2.1.0 [credit_card_type_detector]
- crypto 3.0.6 [typed_data]
- dio 5.5.0+1 [async http_parser meta path dio_web_adapter]
- dotted_line 3.2.3 [flutter]
- dsm 0.0.1 [antdesign_icons flutter flutter_form_builder form_builder_validators shimmer just_the_tooltip intl cached_network_image flutter_keyboard_visibility hive hive_flutter transparent_pointer country_code_picker country_pickers provider app_engine]
- emojis 0.9.9 [collection]
- encrypt 5.0.3 [args asn1lib clock collection crypto pointycastle]
- enum_to_string 2.0.1
- equatable 2.0.7 [collection meta]
- expandable_page_view 1.0.17 [flutter]
- facebook_app_events 0.19.4 [flutter]
- firebase_analytics 11.3.6 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.8.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.2.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 15.1.6 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.10.0+11 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_performance_dio 0.7.1 [flutter dio firebase_performance]
- firebase_remote_config 5.0.1 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_advanced_switch 3.1.0 [flutter]
- flutter_bloc 8.1.6 [bloc flutter provider]
- flutter_countdown_timer 4.1.0 [flutter]
- flutter_datetime_picker 1.5.1 [flutter]
- flutter_form_builder 9.3.0 [flutter intl]
- flutter_icons_null_safety 1.1.0 [flutter]
- flutter_inappwebview 6.1.5 [flutter flutter_inappwebview_platform_interface flutter_inappwebview_android flutter_inappwebview_ios flutter_inappwebview_macos flutter_inappwebview_web flutter_inappwebview_windows]
- flutter_jailbreak_detection 1.10.0 [flutter]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_local_notifications 18.0.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_svg 2.0.16 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_timezone 4.0.0 [flutter flutter_web_plugins]
- form_builder_validators 10.0.1 [flutter flutter_localizations intl]
- freshchat_sdk 0.10.22 [flutter]
- growthbook_sdk_flutter 3.9.7 [dio equatable flutter json_annotation pointycastle shared_preferences tuple]
- hive 2.2.2 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- html 0.15.5 [csslib source_span]
- http 1.2.2 [async http_parser meta web]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_review 2.0.8 [flutter in_app_review_platform_interface]
- intl 0.19.0 [clock meta path]
- just_the_tooltip 0.0.12 [flutter]
- modal_bottom_sheet 3.0.0-pre [flutter]
- navigation_history_observer 1.1.1 [flutter built_collection]
- otp_autofill 4.1.0 [flutter]
- package_info_plus 8.1.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- page_transition 2.1.0 [flutter]
- paged_vertical_calendar 1.1.9 [flutter infinite_scroll_pagination]
- path 1.9.0
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- phone_numbers_parser 9.0.3 [meta]
- pin_code_fields 8.0.1 [flutter]
- platform_device_id 1.0.1 [flutter platform_device_id_platform_interface platform_device_id_macos platform_device_id_linux platform_device_id_web platform_device_id_windows device_info]
- provider 6.0.3 [collection flutter nested]
- pull_to_refresh 2.0.0 [flutter]
- recaptcha_enterprise_flutter 18.6.1 [flutter plugin_platform_interface]
- recase 4.0.0
- screenshot 3.0.0 [flutter]
- scrollable_positioned_list 0.3.8 [flutter collection]
- share 2.0.4 [meta mime flutter]
- shimmer 3.0.0 [flutter]
- simple_animations 5.1.0 [flutter]
- supercharged 2.1.1 [supercharged_dart flutter]
- system_clock 2.0.0 [flutter flutter_web_plugins ffi]
- talker_dio_logger 4.5.2 [dio talker]
- talker_flutter 4.5.2 [flutter talker group_button path_provider share_plus]
- timezone 0.10.0 [http path]
- top_modal_sheet 2.1.0 [flutter]
- touchable_opacity 1.2.0 [flutter]
- transparent_pointer 1.0.1 [flutter]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.4.0 [crypto sprintf meta fixnum]
- visibility_detector 0.4.0+2 [flutter]
- webengage_flutter 1.6.0 [flutter]
- youtube 1.0.1 [flutter http]

dev dependencies:
- bloc_test 9.1.7 [bloc diff_match_patch meta mocktail test]
- build_runner 2.4.14 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- glob 2.1.2 [async collection file path string_scanner]
- hive_generator 2.0.1 [build source_gen hive analyzer source_helper]
- hive_test 1.0.1 [flutter hive path]
- image 4.5.0 [archive meta xml]
- io 1.0.5 [meta path string_scanner]
- melos 6.2.0 [ansi_styles args async cli_launcher cli_util collection conventional_commit file glob graphs http intl meta mustache_template path platform pool prompts pub_semver pub_updater pubspec string_scanner yaml yaml_edit]
- mockito 5.4.4 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- mocktail 1.0.4 [collection matcher test_api]
- talker 4.5.2 [talker_logger]
- test 1.25.8 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

dependency overrides:
- modal_bottom_sheet 3.0.0-pre [flutter]

transitive dependencies:
- _fe_analyzer_shared 76.0.0 [meta]
- _flutterfire_internals 1.3.47 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.3
- analyzer 6.11.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- ansi_styles 0.3.2+1
- ansicolor 2.0.3
- archive 4.0.2 [crypto path posix]
- args 2.6.0
- asn1lib 1.5.8
- async 2.11.0 [collection meta]
- bloc 8.1.4 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 3.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- charcode 1.4.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_launcher 0.3.1 [path yaml]
- cli_util 0.4.2 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.5.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.3.5 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- conventional_commit 0.6.0+1
- convert 3.1.2 [typed_data]
- coverage 1.11.1 [args glob logging meta package_config path source_maps stack_trace vm_service]
- credit_card_type_detector 3.0.0
- cross_file 0.3.4+2 [meta web]
- csslib 1.0.2 [source_span]
- dart_style 2.3.7 [analyzer args collection package_config path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- device_info 2.0.3 [flutter device_info_platform_interface]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- dio_web_adapter 2.0.0 [dio http_parser meta web]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.1 [meta path]
- file_selector_linux 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 4.2.8 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+5 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.3.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.18.2 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.7.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.49 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.9.5 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_performance_platform_interface 0.1.4+47 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.7+5 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins]
- firebase_remote_config_platform_interface 1.4.44 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.7.2 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- fixnum 1.1.1
- flutter_cache_manager 3.4.0 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_inappwebview_android 1.1.3 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_internal_annotations 1.2.0
- flutter_inappwebview_ios 1.1.2 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_macos 1.1.2 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_platform_interface 1.3.0+1 [flutter flutter_inappwebview_internal_annotations plugin_platform_interface]
- flutter_inappwebview_web 1.1.2 [flutter flutter_web_plugins web flutter_inappwebview_platform_interface]
- flutter_inappwebview_windows 0.6.0 [flutter flutter_inappwebview_platform_interface]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 5.0.0 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 8.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.23 [flutter]
- flutter_staggered_grid_view 0.7.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- graphs 2.3.2 [collection]
- group_button 5.3.4 [flutter]
- http_multi_server 3.2.2 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.12+18 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.6 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_review_platform_interface 2.0.5 [flutter url_launcher plugin_platform_interface platform]
- infinite_scroll_pagination 4.1.0 [flutter flutter_staggered_grid_view sliver_tools]
- js 0.7.1
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.0.0
- logging 1.3.0
- macros 0.1.3-main.0 [_macros]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 1.0.6
- mustache_template 2.0.0
- nested 1.0.0 [flutter]
- node_preamble 2.0.2
- octo_image 2.1.0 [flutter]
- package_config 2.1.1 [path]
- package_info_plus_platform_interface 3.0.2 [flutter meta plugin_platform_interface]
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.15 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- permission_handler_android 12.0.13 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.5 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+5 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.2.3 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.6
- platform_device_id_linux 1.0.0 [flutter]
- platform_device_id_macos 1.0.0 [flutter]
- platform_device_id_platform_interface 1.0.0 [flutter plugin_platform_interface]
- platform_device_id_web 1.0.0 [flutter flutter_web_plugins platform_device_id_platform_interface]
- platform_device_id_windows 1.0.0 [flutter]
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.9.1 [collection convert js]
- pool 1.5.1 [async stack_trace]
- posix 6.0.1 [ffi meta path]
- process 5.0.3 [file path platform]
- prompts 2.0.0 [charcode io]
- pub_semver 2.1.5 [collection meta]
- pub_updater 0.4.0 [http json_annotation process pub_semver]
- pubspec 2.3.0 [path pub_semver yaml uri]
- pubspec_parse 1.3.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.2 [matcher]
- rxdart 0.28.0
- share_plus 10.1.3 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- share_plus_platform_interface 5.0.2 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences 2.3.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.4.0 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.3 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- sliver_tools 0.2.12 [flutter]
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.5 [analyzer collection source_gen]
- source_map_stack_trace 2.1.2 [path source_maps stack_trace]
- source_maps 0.10.13 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.1 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.0 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.4+6 [synchronized path meta]
- sqflite_darwin 2.4.1 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.12.0 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.1
- string_scanner 1.3.0 [source_span]
- supercharged_dart 2.1.1
- synchronized 3.3.0+3
- talker_logger 4.5.2 [ansicolor]
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.6.5 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- timing 1.0.2 [json_annotation]
- tuple 2.0.2
- typed_data 1.4.0 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- uri 1.0.0 [matcher quiver]
- url_launcher_android 6.3.14 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.2 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.3 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.15 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.12
- vector_graphics_compiler 1.1.16 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 14.3.0
- watcher 1.1.1 [async path]
- web 1.1.0
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.2.1 [logging]
- win32 5.9.0 [ffi]
- xdg_directories 1.1.0 [meta path]
- yaml_edit 2.2.1 [collection meta source_span yaml]


```

</details>
