### ISSUE TITLE
🐛[firebase_auth]:signInWithProvider returns " An internal error has occurred"

### ISSUE THREAD

**Issue by barahijawi** [firebase/flutterfire#16961]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android

### Description

Calling `signInWithProvider` with `AppleAuthProvider() ` or any 0Auth provider  throws PlatformException of "UNKOWN" with message | An internal error has occurred" .

### Reproducing the issue

```
    final firebase_auth.AppleAuthProvider appleProvider = firebase_auth.AppleAuthProvider();

      // Add required 'email' scope and optional 'name' scope.
    const List<String> scopes = ['email', 'name'];
    for (final String scope in scopes) {
      appleProvider.addScope(scope);
    }

    return await firebase_auth.FirebaseAuth.instance.signInWithProvider(appleProvider);
```

### Firebase Core version

3.10.0

### Flutter Version

3.27.1 

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.6.0
Flutter SDK 3.27.1
drops_app 0.1.0

dependencies:
- base_isolate_encapsulation 0.0.1 [flutter collection async]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- collection 1.19.0
- crypto 3.0.6 [typed_data]
- dio 5.7.0 [async http_parser meta path dio_web_adapter]
- dio_cache_interceptor 3.5.1 [dio uuid string_scanner]
- firebase_auth 5.4.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_ui_oauth 1.6.0 [desktop_webview_auth firebase_auth firebase_ui_auth firebase_ui_shared flutter_svg flutter]
- firebase_ui_oauth_apple 1.3.0 [firebase_auth firebase_ui_oauth flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_dotenv 5.2.1 [flutter]
- flutter_shaders 0.1.3 [flutter vector_math]
- flutter_svg 2.0.17 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- google_sign_in 6.2.2 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- json_annotation 4.9.0 [meta]
- logging 1.3.0
- native_dio_adapter 1.4.0 [flutter dio cupertino_http cronet_http http]
- path 1.9.0
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- roon_dev_utility 0.0.1 [flutter]
- roon_flutter_widgets 0.0.1 [flutter roon_dev_utility]
- short_background_op_manager 0.0.1 [flutter collection async base_isolate_encapsulation]
- sign_in_with_apple 6.1.4 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- uuid 4.5.1 [crypto sprintf meta fixnum]

dev dependencies:
- build_runner 2.4.14 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- freezed 2.5.7 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation dart_style]
- http_mock_adapter 0.6.1 [collection dio http_parser logger]
- json_serializable 6.9.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mockito 5.4.5 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- test 1.25.8 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]

transitive dependencies:
- _fe_analyzer_shared 76.0.0 [meta]
- _flutterfire_internals 1.3.49 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.3
- analyzer 6.11.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- args 2.6.0
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.3 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.3 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.3 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- convert 3.1.2 [typed_data]
- coverage 1.11.1 [args glob logging meta package_config path source_maps stack_trace vm_service]
- cronet_http 1.3.2 [flutter http http_profile jni]
- cupertino_http 2.0.1 [async ffi flutter http http_profile objective_c web_socket]
- dart_style 2.3.7 [analyzer args collection package_config path pub_semver source_span]
- desktop_webview_auth 0.0.15 [crypto flutter http flutter_web_plugins plugin_platform_interface]
- dio_web_adapter 2.0.0 [dio http_parser meta web]
- email_validator 2.1.17
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.1 [meta path]
- firebase_auth_platform_interface 7.5.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.6 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.19.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_dynamic_links 6.1.0 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.7 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_ui_auth 1.16.0 [email_validator firebase_auth firebase_core firebase_dynamic_links firebase_ui_localizations firebase_ui_oauth firebase_ui_shared flutter flutter_localizations meta]
- firebase_ui_localizations 1.13.0 [flutter flutter_localizations path]
- firebase_ui_shared 1.4.1 [flutter]
- fixnum 1.1.1
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.3.3 [meta web]
- google_sign_in_android 6.1.34 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.8 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4+3 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- graphs 2.3.2 [collection]
- http 1.2.2 [async http_parser meta web]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- http_profile 0.1.0
- intl 0.19.0 [clock meta path]
- io 1.0.5 [meta path string_scanner]
- jni 0.10.1 [args collection ffi package_config path plugin_platform_interface]
- js 0.7.1
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.1
- logger 2.5.0
- macros 0.1.3-main.0 [_macros]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 2.0.0
- node_preamble 2.0.2
- objective_c 3.0.0 [ffi flutter plugin_platform_interface yaml]
- octo_image 2.1.0 [flutter]
- package_config 2.1.1 [path]
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.15 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.5 [collection meta]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- rxdart 0.28.0
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.3 [convert http_parser mime path shelf]
- shelf_web_socket 2.0.1 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.1.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 2.1.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface]
- sky_engine 0.0.0
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.5 [analyzer collection source_gen]
- source_map_stack_trace 2.1.2 [path source_maps stack_trace]
- source_maps 0.10.13 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.1 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.0 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.4+6 [synchronized path meta]
- sqflite_darwin 2.4.1+1 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.12.0 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.1
- string_scanner 1.3.0 [source_span]
- synchronized 3.3.0+3
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.6.5 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- timing 1.0.2 [json_annotation]
- typed_data 1.4.0 [collection]
- vector_graphics 1.1.15 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.16 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 14.3.0
- watcher 1.1.1 [async path]
- web 1.1.0
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.1 [async crypto stream_channel web web_socket]
- webkit_inspection_protocol 1.2.1 [logging]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

![Image](https://github.com/user-attachments/assets/94b981a6-1933-431f-958d-5f5e8f98f7aa)

```

</details>
