### ISSUE TITLE
[Flutterfire, Xcode]: Flutter build ipa fails with FirebaseJsonException in project with multiple flavors.

### ISSUE THREAD

**Issue by Leedwon** [firebase/flutterfire#16964]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

iOS

### Description

When trying to produce an Xcode archive by running `flutter build ipa --flavor prod -t lib/main_prod.dart` it fails with:

> FirebaseJsonException: Please run "flutterfire configure" to update the `firebase.json` at the root of your Flutter project with correct values.

Re-running `flutterfire configure` doesn't solve the issue.

In my setup I have three flavors:
- local
- dev
- prod

For each flavor I have Scheme with the same name, and corresponding build configurations:
- Debug-local
- Debug-dev
- Debug-prod
- Release-local
- Release-dev
- Release-prod
- Profile-local
- Profile-dev
- Profile-prod

Each flavors has its own corresponding firebase project:
- myapp-local
- myapp-dev
- myapp (for prod)

I checked my schemes and configs as suggested in [this issue](https://github.com/firebase/flutterfire/issues/13306), but I can't spot any issues with my configuration. Moreover running `flutter run --flavor prod -t lib/main_prod.dart` works without any issues.

I'm using a custom script for configuring flutterfire which looks like this:

```
#!/bin/bash
# Script to generate Firebase configuration files for different environments/flavors

if [[ $# -eq 0 ]]; then
  echo "Error: No environment specified. Use 'local', 'dev', or 'prod'."
  exit 1
fi

case $1 in
  local)
    flutterfire config \
      --project=myproject-local \
      --out=lib/firebase_options_local.dart \
      --ios-bundle-id=myapp.local \
      --ios-out=ios/flavors/local/GoogleService-Info.plist \
      --android-package-name=myapp.local \
      --android-out=android/app/src/local/google-services.json
    ;;
  dev)
    flutterfire config \
      --project=myproject-dev \
      --out=lib/firebase_options_dev.dart \
      --ios-bundle-id=myapp.dev \
      --ios-out=ios/flavors/dev/GoogleService-Info.plist \
      --android-package-name=myapp.dev \
      --android-out=android/app/src/dev/google-services.json
    ;;
  prod)
    flutterfire config \
      --project=myapp \
      --out=lib/firebase_options_prod.dart \
      --ios-bundle-id=myapp \
      --ios-out=ios/flavors/prod/GoogleService-Info.plist \
      --android-package-name=myapp \
      --android-out=android/app/src/prod/google-services.json
    ;;
  *)
    echo "Error: Invalid environment specified. Use 'local', 'dev', or 'prod'."
    exit 1
    ;;
esac
```

Is there any way I could examine this `FirebaseJsonException` to see what exactly can't be parsed

### Reproducing the issue

I haven't tried creating a MRE, but I assume the steps would be:

- Create a sample flutter app
- Create three schemes: local,dev,prod
- Create build configs for each of them and remove default build configs
- Create firebase projects for each flavor
- Use custom script from description to configure each flavor firebase setup
- Run `flutter build ipa --flavor prod` to observe the issue

### Firebase Core version

3.4.0

### Flutter Version

3.24.5

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

- amplify_auth_cognito 2.4.1 [amplify_analytics_pinpoint amplify_analytics_pinpoint_dart amplify_auth_cognito_dart amplify_core amplify_flutter amplify_secure_storage async flutter meta path plugin_platform_interface]
- amplify_flutter 2.4.1 [amplify_core amplify_secure_storage aws_common collection flutter meta]
- collection 1.18.0
- cupertino_icons 1.0.8
- firebase_analytics 11.3.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.1.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- fl_chart 0.68.0 [equatable flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- flutter_svg 2.0.13 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- graphql_flutter 5.2.0-beta.6 [graphql gql_exec flutter meta path_provider path connectivity_plus hive plugin_platform_interface flutter_hooks]
- http 1.2.2 [async http_parser meta web]
- intl 0.19.0 [clock meta path]
- json_theme_plus 6.6.5 [flutter json_class json_schema json_theme_annotation logging meta]
- provider 6.1.2 [collection flutter nested]
- rxdart 0.28.0
- shared_preferences 2.3.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 3.0.0 [flutter]
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- test 1.25.7 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]

transitive dependencies:
- _fe_analyzer_shared 72.0.0 [meta]
- _flutterfire_internals 1.3.41 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.2
- amplify_analytics_pinpoint 2.4.1 [amplify_analytics_pinpoint_dart amplify_core amplify_db_common amplify_secure_storage aws_common device_info_plus flutter meta package_info_plus path_provider]
- amplify_analytics_pinpoint_dart 0.4.5 [amplify_core amplify_db_common_dart amplify_secure_storage_dart aws_common aws_signature_v4 built_collection built_value collection drift intl meta path smithy smithy_aws uuid]
- amplify_auth_cognito_dart 0.11.5 [amplify_analytics_pinpoint_dart amplify_core amplify_secure_storage_dart async aws_common aws_signature_v4 built_collection built_value clock collection convert crypto ffi fixnum http intl js json_annotation meta oauth2 path smithy smithy_aws stream_transform uuid win32 win32_registry worker_bee]
- amplify_core 2.4.1 [async aws_common aws_signature_v4 collection graphs intl json_annotation logging meta retry stack_trace uuid]
- amplify_db_common 0.4.5 [amplify_db_common_dart drift flutter path path_provider]
- amplify_db_common_dart 0.4.6 [amplify_core async aws_common drift meta path sqlite3]
- amplify_secure_storage 0.5.7 [amplify_secure_storage_dart async file flutter flutter_web_plugins meta path path_provider path_provider_windows]
- amplify_secure_storage_dart 0.5.3 [async aws_common built_collection built_value ffi file js meta path win32 worker_bee]
- analyzer 6.7.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- args 2.5.0
- async 2.11.0 [collection meta]
- aws_common 0.7.3 [async built_collection built_value collection http2 js json_annotation logging meta mime os_detect path stream_transform uuid]
- aws_signature_v4 0.6.3 [async aws_common collection convert crypto json_annotation meta path]
- boolean_selector 2.1.1 [source_span string_scanner]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- characters 1.3.0
- clock 1.1.1
- connectivity_plus 5.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- coverage 1.9.0 [args glob logging package_config path source_maps stack_trace vm_service]
- crclib 3.0.0 [meta tuple]
- crypto 3.0.5 [typed_data]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus 10.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- device_info_plus_platform_interface 7.0.1 [flutter meta plugin_platform_interface]
- drift 2.18.0 [async convert collection js meta stream_channel sqlite3 path stack_trace web]
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.0 [meta path]
- firebase_analytics_platform_interface 4.2.2 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.9+2 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.5 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.41 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- fixnum 1.1.0
- flutter_hooks 0.18.6 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- font_awesome_flutter 9.2.0 [flutter]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- gql 1.0.1-alpha+1717789143880 [collection meta source_span yaml]
- gql_dedupe_link 2.0.4-alpha+1715521079596 [async gql_exec gql_link meta]
- gql_error_link 1.0.0+1 [async gql_exec gql_link meta]
- gql_exec 1.1.1-alpha+1699813812660 [collection gql meta]
- gql_http_link 1.1.0 [gql gql_exec gql_link http http_parser meta]
- gql_link 1.0.1-alpha+1717789143896 [gql gql_exec meta]
- gql_transform_link 1.0.0 [gql_exec gql_link]
- graphql 5.2.0-beta.9 [meta path gql gql_exec gql_link gql_http_link gql_transform_link gql_error_link gql_dedupe_link hive normalize http collection web_socket_channel stream_channel rxdart uuid]
- graphs 2.3.2 [collection]
- hive 2.2.3 [meta crypto]
- http2 2.3.0
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.9.0 [meta]
- json_class 3.0.0+16 [intl logging meta]
- json_schema 5.2.0 [collection http logging rfc_6901 uri]
- json_theme_annotation 1.0.3+10
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- logging 1.3.0
- macros 0.1.2-main.4 [_macros]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 1.0.5
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- node_preamble 2.0.2
- normalize 0.8.2+1 [gql collection]
- oauth2 2.0.2 [collection crypto http http_parser]
- os_detect 2.0.1
- package_config 2.1.0 [path]
- package_info_plus 8.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- package_info_plus_platform_interface 3.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_parsing 1.1.0 [meta vector_math]
- path_provider 2.1.4 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.10 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.5
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.4 [collection meta]
- quiver 3.2.2 [matcher]
- retry 3.1.2
- rfc_6901 0.2.0
- shared_preferences_android 2.3.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.2 [convert http_parser mime path shelf]
- shelf_web_socket 2.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- smithy 0.7.3 [async aws_common built_collection built_value collection convert crypto fixnum http_parser intl json_annotation meta path retry shelf typed_data xml]
- smithy_aws 0.7.3 [aws_common aws_signature_v4 built_collection built_value collection convert crclib crypto intl json_annotation meta path smithy xml]
- source_map_stack_trace 2.1.2 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqlite3 2.4.2 [collection ffi js meta path]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.6.4 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- tuple 2.0.2
- typed_data 1.3.2 [collection]
- uri 1.0.0 [matcher quiver]
- url_launcher_android 6.3.10 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.2 [flutter url_launcher_platform_interface]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- vector_graphics 1.1.14 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.12
- vector_graphics_compiler 1.1.14 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 14.2.5
- watcher 1.1.0 [async path]
- web 0.5.1
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.2.1 [logging]
- win32 5.5.4 [ffi]
- win32_registry 1.1.4 [ffi win32]
- worker_bee 0.3.3 [async aws_common built_collection built_value collection js meta path stack_trace stream_channel stream_transform]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

### Additional context and comments

My current `firebase.json` looks like this:

```Json
{
    "flutter": {
        "platforms": {
            "android": {
                "buildConfigurations": {
                    "src/dev": {
                        "projectId": "myapp-dev-3892d",
                        "appId": "redacted",
                        "fileOutput": "android/app/src/dev/google-services.json"
                    },
                    "src/prod": {
                        "projectId": "myapp",
                        "appId": "redacted",
                        "fileOutput": "android/app/src/prod/google-services.json"
                    },
                    "src/local": {
                        "projectId": "myapp-local",
                        "appId": "redacted",
                        "fileOutput": "android/app/src/local/google-services.json"
                    }
                }
            },
            "ios": {
                "buildConfigurations": {
                    "Debug-dev": {
                        "projectId": "myapp-dev-3892d",
                        "appId": "redacted",
                        "uploadDebugSymbols": true,
                        "fileOutput": "ios/flavors/dev/GoogleService-Info.plist"
                    },
                    "Debug-prod": {
                        "projectId": "myapp",
                        "appId": "redacted",
                        "uploadDebugSymbols": true,
                        "fileOutput": "ios/flavors/prod/GoogleService-Info.plist"
                    },
                    "Debug-local": {
                        "projectId": "myapp-local",
                        "appId": "redacted",
                        "uploadDebugSymbols": true,
                        "fileOutput": "ios/flavors/local/GoogleService-Info.plist"
                    }
                }
            },
            "dart": {
                "lib/firebase_options_dev.dart": {
                    "projectId": "myapp-dev-3892d",
                    "configurations": {
                        "android": "redacted",
                        "ios": "redacted"
                    }
                },
                "lib/firebase_options_prod.dart": {
                    "projectId": "myapp",
                    "configurations": {
                        "android": "redacted",
                        "ios": "redacted"
                    }
                },
                "lib/firebase_options_local.dart": {
                    "projectId": "myapp-local",
                    "configurations": {
                        "android": "redacted",
                        "ios": "redacted"
                    }
                }
            }
        }
    }
}
```
