### ISSUE TITLE
[cloud_firestore]: Aggregate query (sum) returns wrong aggregates on fields when asking for many aggregates.

### ISSUE THREAD

**Issue by adifyr** [firebase/flutterfire#17003]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

Android, iOS, Web

### Description

When asking for many (10) aggregates in firestore, firestore returns some field aggregates (sums) with 0.

**When asking for 10 aggregates:**

```
{
  ViewerParam.viewers: 1596,
  ViewerParam.siteViews: 2247,
  ViewerParam.profileViews: 0, --- Not supposed to be 0.
  ViewerParam.instagramClicks: 92,
  ViewerParam.whatsappClicks: 93,
  ViewerParam.emailClicks: 1, --- Supposed to be 15.
  ViewerParam.websiteClicks: 32,
  ViewerParam.mapClicks: 0, --- Not supposed to be 0.
  ViewerParam.calendarClicks: 0, --- Not supposed to be 0.
  ViewerParam.telegramClicks: 2,
}
```

**The same query when asking for 7 aggregates:**

```
{
  ViewerParam.viewers: 1596,
  ViewerParam.siteViews: 2247,
  ViewerParam.profileViews: 1271, --- Notice it's not 0 anymore.
  ViewerParam.instagramClicks: 92,
  ViewerParam.whatsappClicks: 93,
  ViewerParam.emailClicks: 0, --- Why is this 0 now?
  ViewerParam.websiteClicks: 32,
}
```

In the Firestore Console's Query Builder:

**profile_views:**
![Correct Aggregate for Profile Views](https://github.com/user-attachments/assets/73113acd-cb4b-49d4-a5be-5a3166166249)

**email_clicks**

![Correct Aggregate for Email Clicks](https://github.com/user-attachments/assets/c563fbf8-b9f5-4732-adce-9cb3386053e5)

### Reproducing the issue

I created 2 firestore aggregate queries that requested aggregates of 5 fields each. So 10 fields total. Here is my code below:

```dart
try {
  final viewersRef = getProjectsRef(uid).doc(projectId).collection('viewers');
  debugPrint('Viewers Ref: ${viewersRef.path}');
  final snapshot = await viewersRef
      .aggregate(
        count(),
        sum(ViewerParam.siteViews.key),
        sum(ViewerParam.instagramClicks.key),
        sum(ViewerParam.whatsappClicks.key),
        sum(ViewerParam.websiteClicks.key),
      )
      .get();
  final snapshot2 = await viewersRef
      .aggregate(
        sum(ViewerParam.profileViews.key),
        sum(ViewerParam.calendarClicks.key),
        sum(ViewerParam.emailClicks.key),
        sum(ViewerParam.mapClicks.key),
        sum(ViewerParam.telegramClicks.key),
      )
      .get();
  debugPrint('${ViewerParam.profileViews.key}: ${snapshot2.getSum(ViewerParam.profileViews.key)}');
  final projectAnalytics = ProjectAnalytics(
    viewers: snapshot.count ?? 0,
    siteViews: snapshot.getSum(ViewerParam.siteViews.key)?.toInt() ?? 0,
    profileViews: snapshot2.getSum(ViewerParam.profileViews.key)?.toInt() ?? 0,
    calendarClicks: snapshot2.getSum(ViewerParam.calendarClicks.key)?.toInt() ?? 0,
    instagramClicks: snapshot.getSum(ViewerParam.instagramClicks.key)?.toInt() ?? 0,
    whatsAppClicks: snapshot.getSum(ViewerParam.whatsappClicks.key)?.toInt() ?? 0,
    websiteClicks: snapshot.getSum(ViewerParam.websiteClicks.key)?.toInt() ?? 0,
    telegramClicks: snapshot2.getSum(ViewerParam.telegramClicks.key)?.toInt() ?? 0,
    emailClicks: snapshot2.getSum(ViewerParam.emailClicks.key)?.toInt() ?? 0,
    mapClicks: snapshot2.getSum(ViewerParam.mapClicks.key)?.toInt() ?? 0,
  );
  debugPrint('Project Analytics: ${projectAnalytics.toJson()}');
  return projectAnalytics;
} on FirebaseException catch (fe) {
  debugPrintStack(label: 'Analytics Query Failed - ${fe.code}: ${fe.message}', stackTrace: fe.stackTrace);
  return null;
}
```

### Firebase Core version

3.10.1

### Flutter Version

3.27.2

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
Dart SDK 3.6.1
Flutter SDK 3.27.2
dashboard 1.8.3+55

dependencies:
- audio_video_progress_bar 2.0.3 [flutter]
- cloud_firestore 5.6.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 5.3.1 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.19.0
- country_code_picker 3.1.0 [flutter collection]
- file_picker 8.1.7 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file web]
- firebase_app_check 0.3.2+1 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.4.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.10.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 12.4.1 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- firebase_ui_firestore 1.7.1 [cloud_firestore firebase_ui_localizations firebase_ui_shared flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_animate 4.5.2 [flutter flutter_shaders]
- flutter_markdown 0.7.5 [flutter markdown meta path]
- flutter_riverpod 2.6.1 [collection flutter meta riverpod state_notifier]
- flutter_staggered_grid_view 0.7.0 [flutter]
- form_builder_validators 11.1.1 [flutter flutter_localizations intl]
- go_router 14.6.3 [collection flutter flutter_web_plugins logging meta]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- icons_launcher 3.0.0 [args image path universal_io yaml]
- image_cropper 8.1.0 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.19.0 [clock meta path]
- jovial_svg 1.1.24 [xml collection args vector_math jovial_misc http meta flutter]
- just_audio 0.9.43 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- material_symbols_icons 4.2801.1 [flutter]
- mobkit_dashed_border 0.0.7 [flutter]
- posthog_flutter 4.10.0 [flutter flutter_web_plugins plugin_platform_interface meta]
- qr_flutter 4.1.0 [flutter qr]
- reorderable_grid_view 2.2.8 [flutter]
- share_plus 10.1.4 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- side_sheet 1.0.4 [flutter]
- simple_icons 10.1.3 [flutter]
- stream_transform 2.1.1
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- youtube_player_iframe 5.2.1 [flutter meta webview_flutter webview_flutter_android webview_flutter_wkwebview url_launcher youtube_player_iframe_web]

dev dependencies:
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.50 [collection firebase_core firebase_core_platform_interface flutter meta]
- archive 4.0.2 [crypto path posix]
- args 2.6.0
- async 2.11.0 [collection meta]
- audio_session 0.1.23 [flutter flutter_web_plugins rxdart meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.6.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.4.2 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- cloud_functions_platform_interface 5.6.1 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.10.7 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- convert 3.1.2 [typed_data]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.6 [typed_data]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.1 [meta path]
- file_selector_linux 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- firebase_app_check_platform_interface 0.1.1+1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.2.0+5 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
- firebase_auth_platform_interface 7.5.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.7 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.19.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_storage_platform_interface 5.2.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.10.8 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http meta web]
- firebase_ui_localizations 1.13.1 [flutter flutter_localizations path]
- firebase_ui_shared 1.4.1 [flutter]
- fixnum 1.1.1
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.24 [flutter]
- flutter_shaders 0.1.3 [flutter vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- http 1.3.0 [async http_parser meta web]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- image 4.5.2 [archive meta xml]
- image_cropper_for_web 6.0.2 [flutter flutter_web_plugins image_cropper_platform_interface web]
- image_cropper_platform_interface 7.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.12+20 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.6 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.1 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- jovial_misc 0.9.0 [async collection convert meta]
- just_audio_platform_interface 4.3.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.13 [just_audio_platform_interface flutter flutter_web_plugins web]
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.1
- logging 1.3.0
- markdown 7.3.0 [args meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 2.0.0
- path 1.9.0
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.15 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- posix 6.0.1 [ffi meta path]
- qr 3.0.2 [meta]
- riverpod 2.6.1 [collection meta stack_trace state_notifier]
- rxdart 0.28.0
- share_plus_platform_interface 5.0.2 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- sky_engine 0.0.0
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.12.0 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- string_scanner 1.3.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.4.0 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.3.14 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.2 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.4.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.4 [flutter url_launcher_platform_interface]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- vector_math 2.1.4
- vm_service 14.3.0
- web 1.1.0
- webview_flutter 4.10.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 4.3.1 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.17.0 [flutter path webview_flutter_platform_interface]
- win32 5.10.0 [ffi]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]
- youtube_player_iframe_web 3.1.1 [flutter flutter_web_plugins web webview_flutter_platform_interface]
```

</details>
