### ISSUE TITLE
[firebase_auth]: Error popup-closed-by-user only for Facebook signin in chrome mobile

### ISSUE THREAD

**Issue by leferrad** [firebase/flutterfire#17020]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Web

### Description

I implemented a login module in my Flutter PWA (only web) using 2 social methods: Google and Facebook. I implemented the `signInWithPopup`approach which was simpler in my app than the `signInWithRedirect`.

 Here's a summary of my issue:
- Both methods work in Chrome desktop
- Both methods work in Safari mobile
- Only Google works in Chrome mobile. For Facebook I get this error: `[firebase_auth/popup-closed-by-user] The popup has been closed by the user before finalizing the operation` but the popop was not closed by the user (but by Facebook after a successful login).

### Reproducing the issue

Firebase initialization in `main.dart`

```dart
 // Initialize Firebase before any other service
 WidgetsFlutterBinding.ensureInitialized();
 await Firebase.initializeApp(options: await ConfigService.firebaseOptionsWeb);
 // Initialize FirebaseAuth with persistence to cache the user
 var auth = FirebaseAuth.instanceFor(
   app: Firebase.app(),
 );
 await auth.setPersistence(Persistence.INDEXED_DB);

// Store firebase auth in GetIt
getIt.registerSingleton<FirebaseAuth>(auth);
```

Authentication in Login Bloc
```dart
// Configure Facebook provider
FacebookAuthProvider facebookProvider = FacebookAuthProvider();
facebookProvider.addScope('public_profile');

// Sign in with popup
final firebaseAuth = getIt.get<FirebaseAuth>();
await firebaseAuth.signInWithPopup(facebookProvider);
// Popup shows successfully, login is also successful and popop is closed.
// Then it raises error: [firebase_auth/popup-closed-by-user] The popup has been closed by the user before finalizing the operation
```

### Firebase Core version

3.10.1

### Flutter Version

3.24.4

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.4
Flutter SDK 3.24.4
cappitan_ui 0.5.1+1

dependencies:
- badges 3.1.2 [flutter]
- bubble 1.2.1 [flutter]
- carousel_slider 5.0.0 [flutter]
- cloud_firestore 5.6.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- dart_geohash 2.1.0
- easy_infinite_pagination 0.0.6 [flutter]
- equatable 2.0.5 [collection meta]
- eva_icons_flutter 3.1.0 [flutter]
- fake_cloud_firestore 3.1.0 [flutter cloud_firestore cloud_firestore_platform_interface collection plugin_platform_interface quiver rxdart mock_exceptions fake_firebase_security_rules rx equatable clock]
- firebase_auth 5.4.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.10.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 11.3.1 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_messaging 15.2.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 12.4.1 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- firebase_storage_mocks 0.7.0 [flutter firebase_storage]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.6 [bloc flutter provider]
- flutter_chat_types 3.6.2 [equatable json_annotation meta]
- flutter_chat_ui 1.6.15 [diffutil_dart equatable flutter flutter_chat_types flutter_link_previewer flutter_parsed_text intl meta photo_view scroll_to_index url_launcher visibility_detector]
- flutter_datetime_picker 1.5.1 [flutter]
- flutter_dotenv 5.2.1 [flutter]
- flutter_email_sender 5.2.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_map 5.0.0 [async collection flutter http latlong2 meta polylabel proj4dart vector_math]
- flutter_map_marker_cluster 1.2.0 [flutter flutter_map flutter_map_marker_popup latlong2]
- flutter_markdown 0.6.23 [flutter markdown meta path]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- geolocator 9.0.2 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get_it 8.0.2 [async collection meta]
- go_router 14.3.0 [collection flutter flutter_web_plugins logging meta]
- google_fonts 5.1.0 [flutter http path_provider crypto]
- googleapis 11.4.0 [_discoveryapis_commons http]
- googleapis_auth 1.6.0 [args crypto google_identity_services_web http http_parser]
- http 1.2.2 [async http_parser meta web]
- image_cropper 8.0.2 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_network 2.5.4+1 [flutter http webviewimage]
- image_picker 0.8.9 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- intl 0.19.0 [clock meta path]
- introduction_screen 3.1.14 [flutter collection dots_indicator flutter_keyboard_visibility]
- latlong2 0.9.1 [intl]
- markdown 7.2.2 [args meta]
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- shimmer 3.0.0 [flutter]
- social_login_buttons 1.0.7 [flutter]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.7 [crypto]
- yaml 3.1.2 [collection source_span string_scanner]

dev dependencies:
- build_runner 2.4.13 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- import_sorter 4.6.0 [args tint yaml]
- mockito 5.4.4 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- mocktail_image_network 1.2.0 [mocktail]
- network_image_mock 2.1.1 [flutter mockito]
- test_cov_console 0.2.2

transitive dependencies:
- _discoveryapis_commons 1.0.7 [http http_parser meta]
- _fe_analyzer_shared 72.0.0 [meta]
- _flutterfire_internals 1.3.50 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.2
- analyzer 6.7.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- animated_stack_widget 0.0.4 [flutter]
- antlr4 4.13.2 [logging collection]
- args 2.6.0
- async 2.11.0 [collection meta]
- bloc 8.1.4 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.2 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- cel 0.5.3 [antlr4 collection equatable]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 6.6.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.4.2 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- collection 1.18.0
- convert 3.1.2 [typed_data]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.6 [typed_data]
- csslib 1.0.2 [source_span]
- dart_style 2.3.7 [analyzer args collection package_config path pub_semver source_span]
- diffutil_dart 4.0.1
- dots_indicator 2.1.2 [flutter]
- fake_async 1.3.1 [clock collection]
- fake_firebase_security_rules 0.5.3 [antlr4 cel equatable logger tuple]
- ffi 2.1.3
- file 7.0.1 [meta path]
- file_selector_linux 0.9.3 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- firebase_auth_platform_interface 7.5.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.7 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.19.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_database_platform_interface 0.2.6+1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.6+7 [collection firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins]
- firebase_messaging_platform_interface 4.6.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.10.1 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_storage_platform_interface 5.2.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.10.8 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http meta web]
- fixnum 1.1.1
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_link_previewer 3.2.2 [flutter flutter_chat_types flutter_linkify html http linkify meta url_launcher]
- flutter_linkify 6.0.0 [flutter linkify]
- flutter_map_marker_popup 5.2.0 [flutter animated_stack_widget flutter_map latlong2 provider]
- flutter_parsed_text 2.2.1 [flutter]
- flutter_plugin_android_lifecycle 2.0.23 [flutter]
- frontend_server_client 4.0.0 [async path]
- geolocator_android 4.3.1 [flutter geolocator_platform_interface uuid]
- geolocator_apple 2.3.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.4 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.2.1 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.3 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.3.1+4 [meta web]
- graphs 2.3.2 [collection]
- html 0.15.5 [csslib source_span]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_cropper_for_web 6.0.2 [flutter flutter_web_plugins image_cropper_platform_interface web]
- image_cropper_platform_interface 7.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.12+17 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_ios 0.8.12+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- linkify 5.0.0
- lints 2.1.1
- lists 1.0.1 [meta]
- logger 2.4.0
- logging 1.3.0
- macros 0.1.2-main.4 [_macros]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mgrs_dart 2.0.0 [unicode]
- mime 1.0.6
- mock_exceptions 0.8.2 [matcher]
- mocktail 1.0.4 [collection matcher test_api]
- more 4.4.0 [characters clock collection meta]
- nested 1.0.0 [flutter]
- package_config 2.1.0 [path]
- path 1.9.0
- path_provider_android 2.2.12 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- photo_view 0.15.0 [flutter]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pointer_interceptor 0.9.3+7 [flutter]
- polylabel 1.0.1 [collection]
- pool 1.5.1 [async stack_trace]
- proj4dart 2.1.0 [mgrs_dart wkt_parser meta]
- provider 6.1.2 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.3.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.2 [matcher]
- rx 0.4.0 [collection matcher meta more]
- rxdart 0.28.0
- scroll_to_index 3.0.1 [flutter]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 2.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- tint 2.0.1
- tuple 2.0.2
- typed_data 1.4.0 [collection]
- unicode 0.3.1 [lists]
- url_launcher_android 6.3.14 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.3 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- visibility_detector 0.4.0+2 [flutter]
- vm_service 14.2.5
- watcher 1.1.0 [async path]
- web 1.1.0
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.1 [async crypto stream_channel web web_socket]
- webview_flutter 4.10.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 4.0.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.16.0 [flutter path webview_flutter_platform_interface]
- webviewimage 0.0.4 [flutter http path pointer_interceptor uuid webview_flutter]
- wkt_parser 2.0.0
- xdg_directories 1.1.0 [meta path]

```

</details>

### Additional context and comments

When inspecting, I don't notice errors in the Facebook login - only the following warnings but seems to be unrelated:
  + Error with Permissions-Policy header: Unrecognized feature: 'compute-pressure'.
  + Error with Permissions-Policy header: Unrecognized feature: 'hid'.
  + Error with Permissions-Policy header: Unrecognized feature: 'local-fonts'.
  + Error with Permissions-Policy header: Unrecognized feature: 'serial'.

I noticed this was also reported in #12241 but I couldn't find the solution.
