### ISSUE TITLE
[Firebase Data Connect]: Error saying must not have a selection since type 'Table_KeyOutput' has no subfields" in Firebase Data Connect Mutation

### ISSUE THREAD

**Issue by harini18** [firebase/flutterfire#17044]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

Web

### Description

While using Firebase Data Connect with Flutter, I attempted to create a many-to-many relationship using a GraphQL mutation. The mutation is intended to insert a new circle and a related circleMember entry within a single transaction. However, an error occurs when executing the mutation.

**Schema**

```
type User
  @table(name: "Users", singular: "user", plural: "users", key: ["id"]) {
    id: UUID! @col(name: "user_id") @default(expr: "uuidV4()")
    auth: String! @col(name: "user_auth") @default(expr: "auth.uid")
    displayName: String! @col(dataType: "varchar(100)") @default(value: "Beautiful Human")
    picture: String!  
      @col(name: "picture") 
      @default(value: "https://thumbs.dreamstime.com/b/default-avatar-profile-icon-vector-social-media-user-image-182145777.jpg")
    createdAt: Timestamp! @default(expr: "request.time")
    updatedAt: Timestamp! @default(expr: "request.time")
  }

type Circle
  @table(name: "Circles", singular: "circle", plural: "circles", key: ["id"]) {
    id: UUID! @col(name: "circle_id") @default(expr: "uuidV4()")
    name: String! @col(dataType: "varchar(50)")
    description: String @col(dataType: "varchar(255)")
    createdBy: User! @ref
    createdAt: Timestamp! @default(expr: "request.time")
    updatedAt: Timestamp! @default(expr: "request.time")

}

type CircleMember 
  @table( name: "CircleMembers", singular: "circleMember", plural: "circleMembers",   key: ["circle", "user"]) {
    circle: Circle! @ref
    user: User! @ref
    role: String! @col(name: "role") @default(value: "member")# "admin" or "member"
}

```
**Mutation Code:**

```
mutation CreateCircleAndMembership($name: String!, $description: String, $userId: UUID!) 
@auth(level: USER) @transaction {
  circle: circle_insert(data: {name: $name, description: $description, createdBy: {id: $userId}}) {
    id
  }
  circleMember: circleMember_insert(data: {circleId_expr: "circle.id", userId: $userId, role: "member"})
}
```
**Error Message:**

Field "circle_insert" must not have a selection since type "Circle_KeyOutput" has no subfields

**Expected Behavior:**
The mutation should successfully insert a circle and a related circleMember within a transaction, linking the newly created circle.id to the circleMember.

**Observed Behavior:**
The error message suggests that circle_insert does not return an object with subfields, meaning the { id } selection is not valid.

**Possible Cause:**

- The circle_insert operation returns a Circle_KeyOutput type, which may not allow field selections like { id }.
- Firebase Data Connect might return only a key reference, and explicit selections might not be supported.
- The correct way to reference the inserted circle.id in circleMember_insert might differ.

### Reproducing the issue

- Use Firebase Data Connect with Flutter.
- Define a mutation to insert a circle and a circleMember in a single transaction.
- Execute the mutation.

### Firebase Core version

^3.10.1

### Flutter Version

 3.27.3

### Relevant Log Output

```shell
[Data Connect/DataConnectErrorCode.other] [{message: Cannot query field "id" on type "Circle_KeyOutput"., locations: [{line: 33, column: 4}], path: null, extensions: {file: connector/mutations.gql}}, {message: Field "circle_insert" must not have a selection since type "Circle_KeyOutput" has no subfields., locations: [{line: 28, column: 3}], path: null, extensions: {file: connector/mutations.gql}}]
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.6.1
Flutter SDK 3.27.3
circle 0.1.0

dependencies:
- cupertino_icons 1.0.8
- firebase_app_check 0.3.2+1 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.4.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.10.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_data_connect 0.1.2+7 [firebase_app_check firebase_auth firebase_core firebase_core_platform_interface flutter grpc http intl protobuf]
- firebase_dynamic_links 6.1.1 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_ui_auth 1.16.1 [email_validator firebase_auth firebase_core firebase_dynamic_links firebase_ui_localizations firebase_ui_oauth firebase_ui_shared flutter flutter_localizations meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_form_builder 9.7.0 [flutter intl]
- flutter_riverpod 2.6.1 [collection flutter meta riverpod state_notifier]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- form_builder_validators 11.1.1 [flutter flutter_localizations intl]
- go_router 14.7.2 [collection flutter flutter_web_plugins logging meta]
- riverpod 2.6.1 [collection meta stack_trace state_notifier]
- riverpod_annotation 2.6.1 [meta riverpod]

dev dependencies:
- build_runner 2.4.14 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- custom_lint 0.7.2 [analyzer analyzer_plugin args async ci cli_util collection custom_lint_core freezed_annotation json_annotation meta package_config path pub_semver pubspec_parse rxdart uuid yaml]
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- pubspec_dependency_sorter 1.0.5 [logger pubspec flutter yaml_writer]
- riverpod_generator 2.6.4 [analyzer build build_config collection crypto meta path riverpod_analyzer_utils riverpod_annotation source_gen]
- riverpod_lint 2.6.4 [analyzer analyzer_plugin collection custom_lint_builder meta path riverpod riverpod_analyzer_utils source_span yaml]

transitive dependencies:
- _fe_analyzer_shared 78.0.0 [meta]
- _flutterfire_internals 1.3.50 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.3
- analyzer 7.1.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.12.0 [analyzer collection dart_style meta pub_semver yaml path]
- archive 3.6.1 [crypto path]
- args 2.6.0
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.3 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.3 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.3 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- ci 0.1.0
- cli_util 0.4.2 [meta path]
- clock 1.1.1
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- collection 1.19.0
- convert 3.1.2 [typed_data]
- crypto 3.0.6 [typed_data]
- custom_lint_builder 0.7.2 [analyzer analyzer_plugin collection custom_lint custom_lint_core custom_lint_visitor glob hotreloader meta package_config path pubspec_parse rxdart]
- custom_lint_core 0.7.1 [analyzer analyzer_plugin collection custom_lint_visitor glob matcher meta package_config path pubspec_parse source_span uuid yaml]
- custom_lint_visitor 1.0.0+7.1.0 [analyzer]
- dart_style 3.0.1 [analyzer args collection package_config path pub_semver source_span yaml]
- desktop_webview_auth 0.0.15 [crypto flutter http flutter_web_plugins plugin_platform_interface]
- email_validator 2.1.17
- fake_async 1.3.1 [clock collection]
- file 7.0.1 [meta path]
- firebase_app_check_platform_interface 0.1.1+1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.2.0+5 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
- firebase_auth_platform_interface 7.5.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.7 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.19.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_dynamic_links_platform_interface 0.2.7+1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_ui_localizations 1.13.1 [flutter flutter_localizations path]
- firebase_ui_oauth 1.6.1 [desktop_webview_auth firebase_auth firebase_ui_auth firebase_ui_shared flutter_svg flutter]
- firebase_ui_shared 1.4.1 [flutter]
- fixnum 1.1.1
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_svg 2.0.17 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.3 [async collection file path string_scanner]
- google_identity_services_web 0.3.3 [meta web]
- googleapis_auth 1.6.0 [args crypto google_identity_services_web http http_parser]
- graphs 2.3.2 [collection]
- grpc 3.2.4 [archive async crypto fixnum googleapis_auth meta http http2 protobuf clock]
- hotreloader 4.3.0 [collection logging path stream_transform vm_service watcher]
- http 1.3.0 [async http_parser meta web]
- http2 2.3.1
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- intl 0.19.0 [clock meta path]
- io 1.0.5 [meta path string_scanner]
- js 0.7.1
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.1
- logger 2.5.0
- logging 1.3.0
- macros 0.1.3-main.0 [_macros]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 2.0.0
- package_config 2.1.1 [path]
- path 1.9.0
- path_parsing 1.1.0 [meta vector_math]
- petitparser 6.0.2 [meta]
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- protobuf 3.1.0 [collection fixnum meta]
- pub_semver 2.1.5 [collection meta]
- pubspec 2.3.0 [path pub_semver yaml uri]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.2 [matcher]
- riverpod_analyzer_utils 0.5.9 [analyzer collection crypto custom_lint_core freezed_annotation meta path source_span]
- rxdart 0.28.0
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 2.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- source_gen 2.0.0 [analyzer async build dart_style glob path pub_semver source_span yaml]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.12.0 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.1
- string_scanner 1.3.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.2 [json_annotation]
- typed_data 1.4.0 [collection]
- uri 1.0.0 [matcher quiver]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- vector_graphics 1.1.17 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.16 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 14.3.0
- watcher 1.1.1 [async path]
- web 1.1.0
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.2 [async crypto stream_channel web web_socket]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]
- yaml_writer 2.0.1

```

</details>
