### ISSUE TITLE
[firebase_app_check]: MacOS : The attestation provider AppAttestProvider is not supported on current platform and OS version

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#17057]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

App Check

### Which platforms are affected?

macOS

### Description

I would like to re-open #10934 because i have hundreds of crashlytics reports for my live app on the Mac App Store (MacOS).

I would like to draw your attention on 2 specific cases : 
1. The error : `The attestation provider AppAttestProvider is not supported on current platform and OS version` is thrown but my `FirebaseAppCheck` setup is the following : 

```
await FirebaseAppCheck.instance.activate(
      androidProvider: kDebugMode || kProfileMode
          ? AndroidProvider.debug
          : AndroidProvider.playIntegrity,
      appleProvider: kDebugMode || kProfileMode
          ? AppleProvider.debug
          : Platform.isMacOS
              ? AppleProvider.deviceCheck
              : AppleProvider.appAttestWithDeviceCheckFallback);
```

So the first problem is that this error is thrown while i specify only `AppleProvider.deviceCheck` on MacOS. 

2. This same error means that `AppAttest` is not supported on MacOS, but nothing prevents us from using it inside the app which leads to this kind of errors.

### Reproducing the issue

1. Setup a flutter app to support MacOS
2. Add the app check code with the multiple values `deviceCheck` - `appAttest` - `appAttestWithDeviceCheckFallback` to see the different cases: `await FirebaseAppCheck.instance.activate(appleProvider: AppleProvider.appAttestWithDeviceCheckFallback);`
3. See the errors 

### Firebase Core version

firebase_core: ^3.10.1

### Flutter Version

3.27.3

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.6.1
Flutter SDK 3.27.3
test_database 1.0.0+1

dependencies:
- firebase_app_check 0.3.2+1 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.10.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 4.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.50 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.19.0
- fake_async 1.3.1 [clock collection]
- firebase_app_check_platform_interface 0.1.1+1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.2.0+5 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.19.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.0
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.12.0 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.3.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.3.0
- web 1.1.0
```

</details>
