### ISSUE TITLE
firebase_auth: After updating the signing key on google app store sha-256 mismatch. phone verification not working.

### ISSUE THREAD

**Issue by vikasyadav2184** [firebase/flutterfire#17069]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which platforms are affected?

Android

### Description

Hi,

I am trying to sign in with phone authentication using my google app store App. But it does not allow to do it. Plz see the attachment. And do the changes required. As I tried every thing to sync with google play store and firebase. App available on google App Store “My rent Work”. This is happening only when we use google App Store app. In debug mode it working fine. This problem came when I updated my Signing key and Upload key.   I also created OAuth 2.0 Client IDs manually and updated the firebase and app with same details.   It is working. But when I use real user number it show me attached screen message.  Please help me it. Users start left the app. Existing user facing problem.

![Image](https://github.com/user-attachments/assets/6aa3d90f-65d6-4e54-b386-92121d8e02d2)

### Reproducing the issue

download the "[myrentwork ](https://play.google.com/store/apps/details?id=com.webfort.myrentwork&pcampaignid=web_share)App from google app store"  and on first screen app will ask for phone number enter the any indian phone number. and click on send otp button. then error comes.

### Firebase Core version

3.10.1

### Flutter Version

3.27.4

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  country_pickers: ^2.0.0
  intl: ^0.19.0
  pinput: ^2.2.31
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  image_picker: ^0.8.7+5
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  shared_preferences: ^2.0.5
  intl_phone_field: ^3.1.0
  material_dialogs: ^1.1.4
  permission_handler: ^11.3.1
  pdf: ^3.6.0
  printing: ^5.13.4
  path_provider: ^2.1.5
  open_file: ^3.5.10
  loader_overlay: ^2.3.2
  url_launcher: ^6.3.1
  firebase_ui_firestore: ^1.7.1
  flutter_launcher_icons: ^0.13.1
  upgrader: ^10.1.0
  flutter_file_dialog: ^3.0.2
  http: ^1.2.1
  number_inc_dec: ^0.8.0
  connectivity_plus: ^5.0.2
  get: ^4.6.6
  photo_view: ^0.14.0
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  flutter_native_contact_picker: ^0.0.10
  firebase_app_check: ^0.3.2+2
  firebase_crashlytics: ^4.3.1
  firebase_analytics: ^11.4.1
  package_info_plus: ^8.1.2

```

</details>
