### ISSUE TITLE
[firebase/auth]: ISPs blocking connection with gRPC on Windows

### ISSUE THREAD

**Issue by ciceromsjr** [firebase/flutterfire#17087]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Windows

### Description

I discovered that the Windows version uses the Firebase C++ SDK for authentication, and this SDK communicates via gRPC.

The problem is that the network is blocking this communication. Initially, this only happened on corporate networks, but now it is also occurring with some ISPs in my region.

All other libraries work fine.

I saw that the web was also having issues with this, and a change was made to support REST instead of gRPC.

Wouldn't it be possible to configure it in some way to prefer this method in the Firebase initialization settings?

It would be very interesting if, just like the Web platform support, the Windows version allowed authentication via REST, using the RestTransport instead of GRPCTransport (I saw this on FirebaseDataConnect class), which works correctly on any network.

**I created a brand new project to test only the auth lib and it happened as well.**

### Reproducing the issue

Unfortunately, the only way to reproduce this is in an environment where this network blocking issue occurs.

The only message we get when trying to use it is:

[firebase_auth/unknown-error] An internal error has occurred.

This happens when attempting to use any function from the authentication library.

I could arrange remote access if necessary to perform these checks.

Everything was working perfectly. I also use the cloud_store and storage libraries. The issues I found, I reported, and they were promptly fixed. Since then, I hadn't encountered any other problems. However, this one is really serious because it completely blocks the use of the framework on this platform.

One observation is that after successfully connecting using a VPN, for example, and then disconnecting, it continues to work. It seems like a token or something is stored and maintained after this successful connection.

### Firebase Core version

3.11.0

### Flutter Version

3.27.4

### Relevant Log Output

```shell
[firebase_auth/unknown-error] An internal error has occurred.

Nothing else.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml


Dart SDK 3.6.2
Flutter SDK 3.27.4
firebaseauth 1.0.0+1

dependencies:
- cupertino_icons 1.0.8
- firebase_auth 5.4.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.51 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.19.0
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 7.5.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.8 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core 3.11.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.20.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.1
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.0
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.12.0 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.3.0 [source_span]
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.4.0 [collection]
- vector_math 2.1.4
- vm_service 14.3.0
- web 1.1.0
Cícero Moura

```

</details>
