### ISSUE TITLE
[firebase_core]: [MacOS] unable to find firebase_sdk_version.rb during Adding Swift Package Manager integration

### ISSUE THREAD

**Issue by olostan** [firebase/flutterfire#17082]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

macOS

### Description

I am enabling SwiftPM to my project and for iOS it went well, but for MacOs it gives:

```
Adding Swift Package Manager integration...                      2,212ms
Error: An error occurred when adding Swift Package Manager integration:
  Error: Unable to get Xcode project information:
 2025-02-12 10:07:39.508 xcodebuild[90513:10450211] Writing error result bundle to /var/folders/s0/zyb5q1753fsggl0crslnvy600000gn/T/ResultBundle_2025-12-02_10-07-0039.xcresult
xcodebuild: error: Could not resolve package dependencies:
  <unknown>:0: warning: legacy driver is now deprecated; consider avoiding specifying '-disallow-use-new-driver'main/Package.swift:110: Fatal error: Failed to load configuration: fileNotFound("Error loading or parsing firebase_sdk_version.rb:
  Error Domain=NSCocoaErrorDomain Code=260 \"The file “firebase_sdk_version.rb” couldn’t be opened because there is no such file.\"
  UserInfo={NSFilePath=/Users/olostan/.pub-cache/hosted/pub.dev/cloud_firestore-5.6.3/macos/cloud_firestore/../../../../firebase_core/firebase_core/ios/firebase_sdk_version.rb,
  NSURL=file:///Users/olostan/.pub-cache/hosted/pub.dev/cloud_firestore-5.6.3/macos/cloud_firestore/../../../../firebase_core/firebase_core/ios/firebase_sdk_version.rb, NSUnderlyingError=0x600002198000 {Error Domain=NSPOSIXErrorDomain Code=2
  \"No such file or directory\"}}")
```

### Reproducing the issue

```
flutter clean
flutter config --enable-swift-package-manager
flutter run -d macos
```

### Firebase Core version

3.11.0

### Flutter Version

Flutter 3.27.4 • channel stable

### Relevant Log Output

```shell
flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
Adding Swift Package Manager integration...                      2,212ms
Error: An error occurred when adding Swift Package Manager integration:
  Error: Unable to get Xcode project information:
 2025-02-12 10:07:39.508 xcodebuild[90513:10450211] Writing error result bundle to /var/folders/s0/zyb5q1753fsggl0crslnvy600000gn/T/ResultBundle_2025-12-02_10-07-0039.xcresult
xcodebuild: error: Could not resolve package dependencies:
  <unknown>:0: warning: legacy driver is now deprecated; consider avoiding specifying '-disallow-use-new-driver'main/Package.swift:110: Fatal error: Failed to load configuration: fileNotFound("Error loading or parsing firebase_sdk_version.rb:
  Error Domain=NSCocoaErrorDomain Code=260 \"The file “firebase_sdk_version.rb” couldn’t be opened because there is no such file.\"
  UserInfo={NSFilePath=/Users/olostan/.pub-cache/hosted/pub.dev/cloud_firestore-5.6.3/macos/cloud_firestore/../../../../firebase_core/firebase_core/ios/firebase_sdk_version.rb,
  NSURL=file:///Users/olostan/.pub-cache/hosted/pub.dev/cloud_firestore-5.6.3/macos/cloud_firestore/../../../../firebase_core/firebase_core/ios/firebase_sdk_version.rb, NSUnderlyingError=0x600002198000 {Error Domain=NSPOSIXErrorDomain Code=2
  \"No such file or directory\"}}")



Swift Package Manager is currently an experimental feature, please file a bug at
  https://github.com/flutter/flutter/issues/new?template=1_activation.yml
Consider including a copy of the following files in your bug report:
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (or the scheme for the flavor used)

To avoid this failure, disable Flutter Swift Package Manager integration for the project
by adding the following in the project's pubspec.yaml under the "flutter" section:
  "disable-swift-package-manager: true"
Alternatively, disable Flutter Swift Package Manager integration globally with the
following command:
  "flutter config --no-enable-swift-package-manager"
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
Dart SDK 3.6.2
Flutter SDK 3.27.4
friendy 0.0.1+4

dependencies:
- audioplayers 6.1.2 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- carousel_slider 5.0.0 [flutter]
- cloud_firestore 5.6.3 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 5.3.2 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- connectivity_plus 6.1.3 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- cupertino_icons 1.0.8
- firebase_auth 5.4.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.11.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 12.4.2 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_animate 4.5.2 [flutter flutter_shaders]
- flutter_custom_carousel 0.1.0+1 [flutter flutter_animate]
- flutter_hooks 0.20.5 [flutter]
- flutter_launcher_icons 0.14.3 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_markdown 0.7.6+2 [flutter markdown meta path]
- flutter_offline 4.0.0 [flutter connectivity_plus network_info_plus]
- flutter_riverpod 2.6.1 [collection flutter meta riverpod state_notifier]
- flutter_tts 4.2.2 [flutter flutter_web_plugins]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- google_sign_in 6.2.2 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- googleapis 13.2.0 [_discoveryapis_commons http]
- googleapis_auth 1.6.0 [args crypto google_identity_services_web http http_parser]
- hooks_riverpod 2.6.1 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- infinite_carousel 1.1.1 [flutter]
- json_annotation 4.9.0 [meta]
- loading_animation_widget 1.3.0 [flutter]
- overlapped_carousel 1.0.2 [flutter]
- path 1.9.0
- quickalert 1.1.0 [flutter vector_math]
- retry 3.1.2
- riverpod 2.6.1 [collection meta stack_trace state_notifier]
- riverpod_annotation 2.6.1 [meta riverpod]
- rxdart 0.28.0
- shared_preferences 2.5.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- source_gen 2.0.0 [analyzer async build dart_style glob path pub_semver source_span yaml]
- speech_to_text 7.0.0 [flutter speech_to_text_platform_interface json_annotation clock pedantic flutter_web_plugins meta web]
- stream_transform 2.1.1
- subscription_tracker 1.0.1

dev dependencies:
- build_runner 2.4.15 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web web_socket_channel yaml]
- custom_lint 0.7.3 [analyzer analyzer_plugin args async ci cli_util collection custom_lint_core freezed_annotation json_annotation meta package_config path pub_semver pubspec_parse rxdart uuid yaml]
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- freezed 2.5.8 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation dart_style]
- json_serializable 6.9.4 [analyzer async build build_config collection dart_style json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- logger 2.5.0
- riverpod_generator 2.6.4 [analyzer build build_config collection crypto meta path riverpod_analyzer_utils riverpod_annotation source_gen]
- riverpod_lint 2.6.4 [analyzer analyzer_plugin collection custom_lint_builder meta path riverpod riverpod_analyzer_utils source_span yaml]
- yaml 3.1.3 [collection source_span string_scanner]

transitive dependencies:
- _discoveryapis_commons 1.0.7 [http http_parser meta]
- _fe_analyzer_shared 80.0.0 [meta]
- _flutterfire_internals 1.3.51 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 7.3.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.12.0 [analyzer collection dart_style meta pub_semver yaml path]
- archive 4.0.2 [crypto path posix]
- args 2.6.0
- async 2.11.0 [collection meta]
- audioplayers_android 5.0.2 [audioplayers_platform_interface flutter]
- audioplayers_darwin 6.0.0 [audioplayers_platform_interface flutter]
- audioplayers_linux 4.0.1 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 7.0.0 [collection flutter meta plugin_platform_interface]
- audioplayers_web 5.0.1 [audioplayers_platform_interface flutter flutter_web_plugins web]
- audioplayers_windows 4.0.0 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.4 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.4 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.3 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- ci 0.1.0
- cli_util 0.4.2 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.6.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.4.3 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- cloud_functions_platform_interface 5.6.2 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.10.8 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- collection 1.19.0
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.1.2 [typed_data]
- crypto 3.0.6 [typed_data]
- custom_lint_builder 0.7.3 [analyzer analyzer_plugin collection custom_lint custom_lint_core custom_lint_visitor glob hotreloader meta package_config path pubspec_parse rxdart]
- custom_lint_core 0.7.1 [analyzer analyzer_plugin collection custom_lint_visitor glob matcher meta package_config path pubspec_parse source_span uuid yaml]
- custom_lint_visitor 1.0.0+7.3.0 [analyzer]
- dart_style 3.0.1 [analyzer args collection package_config path pub_semver source_span yaml]
- dbus 0.7.11 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.1 [meta path]
- firebase_auth_platform_interface 7.5.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.13.8 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.20.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_storage_platform_interface 5.2.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.10.9 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http meta web]
- fixnum 1.1.1
- flutter_shaders 0.1.3 [flutter vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.3 [async collection file path string_scanner]
- google_identity_services_web 0.3.3 [meta web]
- google_sign_in_android 6.1.34 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.8 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4+3 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- graphs 2.3.2 [collection]
- hotreloader 4.3.0 [collection logging path stream_transform vm_service watcher]
- http 1.3.0 [async http_parser meta web]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- image 4.5.2 [archive meta xml]
- io 1.0.5 [meta path string_scanner]
- js 0.7.1
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.1
- logging 1.3.0
- markdown 7.3.0 [args meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 2.0.0
- network_info_plus 5.0.3 [collection nm flutter flutter_web_plugins meta network_info_plus_platform_interface win32 ffi]
- network_info_plus_platform_interface 2.0.2 [flutter meta plugin_platform_interface]
- nm 0.5.0 [dbus]
- package_config 2.1.1 [path]
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.15 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- pedantic 1.11.1
- petitparser 6.0.2 [meta]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- posix 6.0.1 [ffi meta path]
- pub_semver 2.1.5 [collection meta]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- riverpod_analyzer_utils 0.5.9 [analyzer collection crypto custom_lint_core freezed_annotation meta path source_span]
- shared_preferences_android 2.4.5 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 3.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- source_helper 1.3.5 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- speech_to_text_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- sprintf 7.0.0
- stack_trace 1.12.0 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- string_scanner 1.3.0 [source_span]
- synchronized 3.3.0+3
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.2 [json_annotation]
- typed_data 1.4.0 [collection]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- vector_math 2.1.4
- vm_service 14.3.0
- watcher 1.1.1 [async path]
- web 1.1.0
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.2 [async crypto stream_channel web web_socket]
- win32 5.10.1 [ffi]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
```

</details>
