### ISSUE TITLE
[firebase_analytics]: firebase debugview appear a lot of devices from release environment

### ISSUE THREAD

**Issue by windows7lake** [firebase/flutterfire#17117]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

Android, iOS

### Description

firebase debugview appear a lot of devices from release environment

### Reproducing the issue

login into firebase console, and open debugview.

### Firebase Core version

2.31.0

### Flutter Version

3.22.3

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  firebase_core: 2.31.0
  firebase_analytics: 10.10.5
  firebase_messaging: 14.9.2
  firebase_crashlytics: 3.5.5
  firebase_performance: 0.9.4+5

```

</details>
