### ISSUE TITLE
firebase_auth: Flutter 3.27+ and 3.29+ auto pops the previous screen when navigating to native on iOS

### ISSUE THREAD

**Issue by mnayef95** [firebase/flutterfire#17135]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Code sample

https://github.com/mnayef95/flutter-3.27-issue

When the user enters their phone number, a reCAPTCHA is triggered, opening a native screen. Once the reCAPTCHA is completed, it should return to the login screen and then navigate to the OTP screen, This behavior works as expected in version 3.24.5, In 3.27.4, both screens Recaptcha & Login screens close instead

Flutter repo issue: https://github.com/flutter/flutter/issues/163611

### Reproducing the issue

1. Install flutter 3.27+
2. Compile and run the attached code sample on iOS
3. Navigate to more
4. Click on login
5. Use `527612112` as a phone number
6. Press on login

### Firebase Core version

3.12.0

### Flutter Version

3.27+

### Relevant Log Output

```shell
None
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

flutter pub deps -- --style=compact                                                                                              mohammad.hamdan@mohammad
    Dart SDK 3.6.2
    Flutter SDK 3.27.4
    flutter_navigation_issue 1.0.0+1
  
  dependencies:
    - auto_route 9.3.0+1 [flutter path web collection meta]
    - bloc 9.0.0 [meta]
    - equatable 2.0.7 [collection meta]
    - firebase_app_check 0.3.2+3 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
    - firebase_auth 5.5.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
    - firebase_core 3.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
    - flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
    - flutter_bloc 9.0.0 [bloc flutter provider]
    - flutter_libphonenumber 2.5.1 [flutter flutter_libphonenumber_android flutter_libphonenumber_ios flutter_libphonenumber_platform_interface flutter_libphonenumber_web]
    - flutter_timezone 4.1.0 [flutter flutter_web_plugins]
    - get_it 8.0.3 [async collection meta]
    - google_fonts 6.2.1 [flutter http path_provider crypto]
    - injectable 2.5.0 [get_it meta]
    - pin_code_fields 8.0.1 [flutter]
  
  dev dependencies:
    - auto_route_generator 9.0.0 [build source_gen analyzer path build_runner code_builder dart_style xml args glob package_config auto_route]
    - build_runner 2.4.13 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
    - flutter_lints 5.0.0 [lints]
    - injectable_generator 2.6.2 [build source_gen path glob analyzer code_builder dart_style injectable collection recase meta]
    - lint 2.6.1
  
  transitive dependencies:
    - _fe_analyzer_shared 76.0.0 [meta]
    - _flutterfire_internals 1.3.52 [collection firebase_core firebase_core_platform_interface flutter meta]
    - _macros 0.3.3
    - analyzer 6.11.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
    - args 2.6.0
    - async 2.11.0 [collection meta]
    - boolean_selector 2.1.1 [source_span string_scanner]
    - build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
    - build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
    - build_daemon 4.0.2 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
    - build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
    - build_runner_core 7.3.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
    - built_collection 5.1.1
    - built_value 8.9.3 [built_collection collection fixnum meta]
    - characters 1.3.0
    - checked_yaml 2.0.3 [json_annotation source_span yaml]
    - clock 1.1.1
    - code_builder 4.10.1 [built_collection built_value collection matcher meta]
    - collection 1.19.0
    - convert 3.1.2 [typed_data]
    - crypto 3.0.6 [typed_data]
    - dart_style 2.3.7 [analyzer args collection package_config path pub_semver source_span]
    - fake_async 1.3.1 [clock collection]
    - ffi 2.1.3
    - file 7.0.1 [meta path]
    - firebase_app_check_platform_interface 0.1.1+3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
    - firebase_app_check_web 0.2.0+7 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
    - firebase_auth_platform_interface 7.6.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
    - firebase_auth_web 5.14.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
    - firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
    - firebase_core_web 2.21.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
    - fixnum 1.1.1
    - flutter_libphonenumber_android 1.4.1 [flutter flutter_libphonenumber_platform_interface]
    - flutter_libphonenumber_ios 1.4.0 [flutter flutter_libphonenumber_platform_interface]
    - flutter_libphonenumber_platform_interface 2.1.0 [flutter plugin_platform_interface]
    - flutter_libphonenumber_web 1.3.0 [flutter flutter_web_plugins flutter_libphonenumber_platform_interface web]
    - flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
    - flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
    - frontend_server_client 4.0.0 [async path]
    - glob 2.1.3 [async collection file path string_scanner]
    - graphs 2.3.2 [collection]
    - http 1.3.0 [async http_parser meta web]
    - http_multi_server 3.2.2 [async]
    - http_parser 4.0.2 [collection source_span string_scanner typed_data]
    - io 1.0.5 [meta path string_scanner]
    - js 0.7.1
    - json_annotation 4.9.0 [meta]
    - leak_tracker 10.0.7 [clock collection meta path vm_service]
    - leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
    - leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
    - lints 5.0.0
    - logging 1.3.0
    - macros 0.1.3-main.0 [_macros]
    - matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
    - material_color_utilities 0.11.1 [collection]
    - meta 1.15.0
    - mime 2.0.0
    - nested 1.0.0 [flutter]
    - package_config 2.1.1 [path]
    - path 1.9.0
    - path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
    - path_provider_android 2.2.15 [flutter path_provider_platform_interface]
    - path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
    - path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
    - path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
    - path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
    - petitparser 6.0.2 [meta]
    - platform 3.1.6
    - plugin_platform_interface 2.1.8 [meta]
    - pool 1.5.1 [async stack_trace]
    - provider 6.1.2 [collection flutter nested]
    - pub_semver 2.1.5 [collection meta]
    - pubspec_parse 1.4.0 [checked_yaml collection json_annotation pub_semver yaml]
    - recase 4.1.0
    - shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
    - shelf_web_socket 2.0.1 [shelf stream_channel web_socket_channel]
    - sky_engine 0.0.0
    - source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
    - source_span 1.10.0 [collection path term_glyph]
    - stack_trace 1.12.0 [path]
    - stream_channel 2.1.2 [async]
    - stream_transform 2.1.1
    - string_scanner 1.3.0 [source_span]
    - term_glyph 1.2.1
    - test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
    - timing 1.0.2 [json_annotation]
    - typed_data 1.4.0 [collection]
    - vector_math 2.1.4
    - vm_service 14.3.0
    - watcher 1.1.1 [async path]
    - web 1.1.0
    - web_socket 0.1.6 [web]
    - web_socket_channel 3.0.2 [async crypto stream_channel web web_socket]
    - xdg_directories 1.1.0 [meta path]
    - xml 6.5.0 [collection meta petitparser]
    - yaml 3.1.3 [collection source_span string_scanner]

```

</details>

### Screenshots or Video

# 3.24.5
https://github.com/user-attachments/assets/69c0268b-dc53-4730-8fcf-b52f20c760e5

# 3.27.4
https://github.com/user-attachments/assets/51287104-8379-4193-86df-128659dcb002
