### ISSUE TITLE
[firebase_auth]: Error: The pod "Firebase/CoreOnly" required by the plugin "firebase_auth" requires a higher minimum macOS deployment version than the plugin's reported minimum version.

### ISSUE THREAD

**Issue by mateusfccp** [firebase/flutterfire#17215]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

macOS

### Description

I am using `firebase_auth` in a project. When compiling for web, it works with no problem. However, when I try to compile to macOS, I get the following error:

```
➜  [redacted] git:(master) ✗ flutter run -d macos
Resolving dependencies in `/Users/mateusfccp/Projects/[redacted]`... 
Downloading packages... 
  async 2.12.0 (2.13.0 available)
  fake_async 1.3.2 (1.3.3 available)
  intl 0.19.0 (0.20.2 available)
  leak_tracker 10.0.8 (10.0.9 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  vm_service 14.3.1 (15.0.0 available)
Got dependencies in `/Users/mateusfccp/Projects/[redacted]`!
6 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                             459ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
      Using `ARCHS` setting to build architectures of target `Pods-RunnerTests`:
      (``)

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `firebase_auth` from
    `Flutter/ephemeral/.symlinks/plugins/firebase_auth/macos`
    firebase_auth: Using Firebase SDK version '11.8.0' defined in
    'firebase_core'
    -> Fetching podspec for `firebase_core` from
    `Flutter/ephemeral/.symlinks/plugins/firebase_core/macos`
    firebase_core: Using Firebase SDK version '11.8.0' defined in
    'firebase_core'

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/0/3/5/Firebase/11.8.0/Firebase.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/0/3/5/Firebase/11.8.0/Firebase.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/0/3/5/Firebase/11.8.0/Firebase.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path:
      Specs/0/3/5/Firebase/11.8.0/Firebase.podspec.json exists! Returning local
      because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod
    "Firebase/CoreOnly":
      In Podfile:
        firebase_auth (from
        `Flutter/ephemeral/.symlinks/plugins/firebase_auth/macos`) was resolved
        to 5.5.1, which depends on
          Firebase/CoreOnly (~> 11.8.0)

    Specs satisfying the `Firebase/CoreOnly (~> 11.8.0)` dependency were found,
    but they required a higher minimum deployment target.

    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:317:in
    'Molinillo::Resolver::Resolution#raise_error_unless_state'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:299:in 'block in
    Molinillo::Resolver::Resolution#unwind_for_conflict'
    <internal:kernel>:91:in 'Kernel#tap'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:297:in
    'Molinillo::Resolver::Resolution#unwind_for_conflict'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:682:in
    'Molinillo::Resolver::Resolution#attempt_to_activate'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:254:in
    'Molinillo::Resolver::Resolution#process_topmost_state'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:182:in 'Molinillo::Resolver::Resolution#resolve'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolver.rb:43:in 'Molinillo::Resolver#resolve'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/resolver.rb:94:in 'Pod::Resolver#resolve'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/installer/analyzer.rb:1082:in 'block in
    Pod::Installer::Analyzer#resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/user_interface.rb:64:in 'Pod::UserInterface.section'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/installer/analyzer.rb:1080:in
    'Pod::Installer::Analyzer#resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/installer/analyzer.rb:125:in 'Pod::Installer::Analyzer#analyze'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/installer.rb:422:in 'Pod::Installer#analyze'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/installer.rb:244:in 'block in Pod::Installer#resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/user_interface.rb:64:in 'Pod::UserInterface.section'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/installer.rb:243:in 'Pod::Installer#resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/installer.rb:162:in 'Pod::Installer#install!'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/command/install.rb:52:in 'Pod::Command::Install#run'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/claide-1.1.0/lib/claide
    /command.rb:334:in 'CLAide::Command.run'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/co
    coapods/command.rb:52:in 'Pod::Command.run'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/bin/po
    d:55:in '<top (required)>'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/bin/pod:25:in 'Kernel#load'
    /opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/bin/pod:25:in '<main>'

Error: The pod "Firebase/CoreOnly" required by the plugin "firebase_auth"
requires a higher minimum macOS deployment version than the plugin's reported
minimum version.
To build, remove the plugin "firebase_auth", or contact the plugin's developers
for assistance.
Error: Error running pod install
```

The suggested solution is to remove `firebase_auth`, which is not really a solution; or to contact the developers.

### Reproducing the issue

- Create a project using the mentioned Flutter vesion with only Flutter Auth.
- Try to compile it.

### Firebase Core version

3.12.1 (transitive)

### Flutter Version

3.29.2 • channel stable

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
➜ [redacted] git:(master) ✗ flutter pub deps -- --style=compact
Dart SDK 3.7.2
Flutter SDK 3.29.2
_ 0.0.0

dashboard 0.1.0

dependencies:
- firebase_auth 5.5.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.12.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- get_it 8.0.3 [async collection meta]
- go_router 14.8.1 [collection flutter flutter_web_plugins logging meta]
- meta 1.16.0
- pintasso 0.0.1 [flutter]
- rxdart 0.28.0

dev dependencies:
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

pintasso 0.0.1

dependencies:
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.53 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.12.0 [collection meta]
- boolean_selector 2.1.2 [source_span string_scanner]
- characters 1.4.0
- clock 1.1.2
- collection 1.19.1
- fake_async 1.3.2 [clock collection]
- firebase_auth_platform_interface 7.6.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.14.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.21.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- intl 0.19.0 [clock meta path]
- leak_tracker 10.0.8 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.1
- logging 1.3.0
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- path 1.9.1
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.0
- source_span 1.10.1 [collection path term_glyph]
- stack_trace 1.12.1 [path]
- stream_channel 2.1.4 [async]
- string_scanner 1.4.1 [source_span]
- term_glyph 1.2.2
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.4.0 [collection]
- vector_math 2.1.4
- vm_service 14.3.1
- web 1.1.1

```

</details>

### Additional context and comments

<details>
<summary>flutter doctor --verbose</summary>
```
➜ [redacted] git:(master) ✗ flutter doctor --verbose
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.3.2 24D81 darwin-arm64, locale
    en-AR) [341ms]
    • Flutter version 3.29.2 on channel stable at
      /Users/mateusfccp/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (7 days ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
    [435ms]
    • Android SDK at /Users/mateusfccp/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [1,960ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [15ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [14ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] Connected device (3 available) [6.1s]
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.3.2 24D81 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.3.2 24D81 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 134.0.6998.89

[✓] Network resources [413ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>
