### ISSUE TITLE
[cloud_functions]: v5.4.0 breaks flutter build ipa

### ISSUE THREAD

**Issue by shatanikmahanty** [firebase/flutterfire#17248]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

iOS

### Description

After upgrading cloud_functions to v5.4.0 building release mode ipa or archiving from xcode is no longer working with errors like:

undefined symbol: type metadata for swift.double

### Reproducing the issue

Include firebase deps.

Run flutter build ipa

### Firebase Core version

3.13.0

### Flutter Version

3.24.5

### Relevant Log Output

```shell
Failed to build iOS app
Error (Xcode): Undefined symbol: value witness table for Builtin.UnknownObject


Error (Xcode): Undefined symbol: Swift.String.hash(into: inout Swift.Hasher) -> ()


Error (Xcode): Undefined symbol: type metadata for Swift.String


Error (Xcode): Undefined symbol: protocol witness table for Swift.String : Swift.Hashable in Swift


Error (Xcode): Undefined symbol: type metadata for Swift.Bool


Error (Xcode): Undefined symbol: type metadata for Swift.Double


Error (Xcode): Undefined symbol: Swift._bridgeAnyObjectToAny(Swift.AnyObject?) -> Any


Error (Xcode): Undefined symbol: Swift.AnyHashable._rawHashValue(seed: Swift.Int) -> Swift.Int


Error (Xcode): Undefined symbol: static Swift.AnyHashable.== infix(Swift.AnyHashable, Swift.AnyHashable) -> Swift.Bool


Error (Xcode): Undefined symbol: nominal type descriptor for Swift.AnyHashable


Error (Xcode): Undefined symbol: type metadata for Swift.AnyHashable


Error (Xcode): Undefined symbol: protocol witness table for Swift.AnyHashable : Swift.Hashable in Swift


Error (Xcode): Undefined symbol: static Swift._DictionaryStorage.copy(original: Swift.__RawDictionaryStorage) -> Swift._DictionaryStorage<A, B>


Error (Xcode): Undefined symbol: static Swift._DictionaryStorage.resize(original: Swift.__RawDictionaryStorage, capacity: Swift.Int, move: Swift.Bool) -> Swift._DictionaryStorage<A,
B>


Error (Xcode): Undefined symbol: static Swift._DictionaryStorage.allocate(capacity: Swift.Int) -> Swift._DictionaryStorage<A, B>


Error (Xcode): Undefined symbol: nominal type descriptor for Swift._DictionaryStorage


Error (Xcode): Undefined symbol: Swift._bridgeAnythingToObjectiveC<A>(A) -> Swift.AnyObject


Error (Xcode): Undefined symbol: Swift._stringCompareWithSmolCheck(_: Swift._StringGuts, _: Swift._StringGuts, expecting: Swift._StringComparisonResult) -> Swift.Bool


Error (Xcode): Undefined symbol: Swift.KEY_TYPE_OF_DICTIONARY_VIOLATES_HASHABLE_REQUIREMENTS(Any.Type) -> Swift.Never


Error (Xcode): Undefined symbol: Swift.Hasher.init(_seed: Swift.Int) -> Swift.Hasher


Error (Xcode): Undefined symbol: Swift.Hasher._finalize() -> Swift.Int


Error (Xcode): Undefined symbol: type metadata for Any


Error (Xcode): Undefined symbol: __swiftEmptyArrayStorage


Error (Xcode): Undefined symbol: __swiftEmptyDictionarySingleton


Error (Xcode): Undefined symbol: _swift_allocObject


Error (Xcode): Undefined symbol: _swift_bridgeObjectRelease


Error (Xcode): Undefined symbol: _swift_bridgeObjectRelease_n


Error (Xcode): Undefined symbol: _swift_bridgeObjectRetain


Error (Xcode): Undefined symbol: _swift_deallocObject


Error (Xcode): Undefined symbol: _swift_deletedMethodError


Error (Xcode): Undefined symbol: _swift_dynamicCast


Error (Xcode): Undefined symbol: _swift_errorRelease


Error (Xcode): Undefined symbol: _swift_errorRetain


Error (Xcode): Undefined symbol: _swift_getObjCClassMetadata


Error (Xcode): Undefined symbol: _swift_getTypeByMangledNameInContext


Error (Xcode): Undefined symbol: _swift_isUniquelyReferenced_nonNull_native


Error (Xcode): Undefined symbol: _swift_isaMask


Error (Xcode): Undefined symbol: _swift_release


Error (Xcode): Undefined symbol: _swift_retain


Error (Xcode): Undefined symbol: _swift_unknownObjectRelease


Error (Xcode): Undefined symbol: _swift_unknownObjectRetain


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Encountered error while archiving for device.

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
- account_selector 1.0.1 [flutter]
- adaptive_dialog 2.3.0 [animations collection dynamic_color flutter intersperse macos_ui meta]
- async 2.12.0 [collection meta]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- carousel_slider 5.0.0 [flutter]
- cloud_firestore 5.6.5 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 5.3.4 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.19.1
- country_code_picker 3.2.0 [flutter collection diacritic]
- cr_calendar 1.3.0 [flutter intl jiffy scrollable_positioned_list]
- crypto 3.0.6 [typed_data]
- csv 6.0.0
- cupertino_icons 1.0.8
- device_info_plus 11.3.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- device_marketing_names 1.0.2 [flutter device_info_plus universal_platform]
- dio 5.8.0+1 [async collection http_parser meta path dio_web_adapter]
- dropdown_button2 2.3.9 [flutter meta]
- easy_refresh 3.4.0 [flutter path_drawing]
- equatable 2.0.7 [collection meta]
- esc_pos_utils_plus 2.0.4 [flutter image html]
- expandable_text 2.3.0 [flutter]
- file_saver 0.2.14 [collection dio flutter flutter_web_plugins path_provider path_provider_linux path_provider_windows web]
- filter_list 1.0.3 [flutter]
- firebase_auth 5.5.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.12.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.3.4 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_database 11.3.4 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_remote_config 5.4.2 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_ui_firestore 1.7.1 [cloud_firestore firebase_ui_localizations firebase_ui_shared flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_background_service 5.1.0 [flutter flutter_background_service_platform_interface flutter_background_service_android flutter_background_service_ios]
- flutter_bloc 9.1.0 [bloc flutter provider]
- flutter_dotenv 5.2.1 [flutter]
- flutter_email_sender 7.0.0 [flutter]
- flutter_local_notifications 18.0.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_material_color_picker 1.2.0 [flutter]
- flutter_overlay_window 0.5.0 [flutter]
- flutter_riverpod 2.6.1 [collection flutter meta riverpod state_notifier]
- flutter_slidable 3.1.2 [flutter]
- flutter_smart_dialog 4.9.8+7 [flutter]
- flutter_typeahead 5.2.0 [flutter flutter_keyboard_visibility pointer_interceptor]
- fluttertoast 8.2.12 [flutter flutter_web_plugins web]
- font_awesome_flutter 10.8.0 [flutter]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- get_it 8.0.3 [async collection meta]
- holding_gesture 1.2.0 [flutter]
- hydrated_bloc 10.0.0 [bloc hive_ce meta synchronized]
- image 4.5.4 [archive meta xml]
- info_popup 4.3.2 [flutter]
- installed_apps 3.0.0 [flutter]
- internet_connection_checker_plus 2.7.1 [connectivity_plus flutter http]
- intl 0.20.2 [clock meta path]
- json_annotation 4.9.0 [meta]
- loading_animations 2.2.0 [flutter]
- mailer 6.4.1 [async logging intl mime path meta]
- morphable_shape 2.0.0 [flutter flutter_class_parser dimension animated_box_decoration]
- multi_split_view 2.4.0 [flutter meta]
- package_info_plus 8.3.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- phone_state 2.1.1 [flutter collection]
- platform_device_id 2.0.0 [flutter platform_device_id_platform_interface platform_device_id_macos platform_device_id_linux platform_device_id_web platform_device_id_windows device_info_plus android_id]
- progress_builder 1.1.4 [flutter mounted_state]
- provider 6.1.2 [collection flutter nested]
- quickseat_payment_picker 0.1.1 [flutter cached_network_image freezed_annotation json_annotation]
- searchbar_animation 0.0.4 [flutter]
- sentry_flutter 8.14.1 [flutter flutter_web_plugins sentry package_info_plus meta ffi file collection]
- shared_preferences 2.5.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- slide_to_act 2.0.2 [flutter]
- syncfusion_flutter_calendar 28.1.33 [flutter timezone syncfusion_flutter_core syncfusion_flutter_datepicker intl]
- syncfusion_flutter_charts 28.1.33 [flutter intl vector_math syncfusion_flutter_core]
- table_calendar 3.2.0 [flutter intl simple_gesture_detector]
- timelines_plus 1.0.6 [flutter]
- timezone 0.10.0 [http path]
- typesense 0.5.1 [http crypto]
- universal_html 2.2.4 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- vector_math 2.1.4
- webview_flutter 4.10.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- whatsapp_unilink 2.1.0
- word_generator 0.4.6 [flutter]
- zoom_widget 2.0.1 [flutter vector_math]

dev dependencies:
- build_runner 2.4.11 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.14.3 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 4.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- freezed 2.5.7 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation dart_style]
- json_serializable 6.9.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]

dependency overrides:
- intl 0.20.2 [clock meta path]
- macos_ui 2.0.9 [flutter macos_window_utils gradient_borders appkit_ui_element_colors equatable]
- syncfusion_flutter_core 28.1.33 [vector_math flutter]
- timezone 0.10.0 [http path]

transitive dependencies:
- _fe_analyzer_shared 76.0.0 [meta]
- _flutterfire_internals 1.3.53 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.3
- analyzer 6.11.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- android_id 0.3.6 [flutter]
- animated_box_decoration 0.0.7 [flutter]
- animations 2.0.11 [flutter]
- appkit_ui_element_colors 1.0.0 [equatable flutter plugin_platform_interface]
- archive 4.0.5 [crypto path posix]
- args 2.7.0
- bloc 9.0.0 [meta]
- boolean_selector 2.1.2 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.2 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.1 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.5 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- characters 1.4.0
- charcode 1.4.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.2 [meta path]
- clock 1.1.2
- cloud_firestore_platform_interface 6.6.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.4.5 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- cloud_functions_platform_interface 5.6.4 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.10.10 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- connectivity_plus 6.1.3 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.1.2 [typed_data]
- csslib 1.0.2 [source_span]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- dbus 0.7.11 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.2 [flutter meta plugin_platform_interface]
- diacritic 0.1.6
- dimension 0.2.0 [flutter flutter_class_parser]
- dio_web_adapter 2.1.1 [dio http_parser meta web]
- dynamic_color 1.7.0 [flutter flutter_test material_color_utilities]
- fake_async 1.3.2 [clock collection]
- ffi 2.1.3
- file 7.0.1 [meta path]
- firebase_auth_platform_interface 7.6.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.14.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.22.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.8.4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_platform_interface 0.2.6+4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.6+10 [collection firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins]
- firebase_remote_config_platform_interface 1.5.2 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.8.2 [_flutterfire_internals firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- firebase_ui_localizations 1.13.1 [flutter flutter_localizations path]
- firebase_ui_shared 1.4.1 [flutter]
- fixnum 1.1.1
- flutter_background_service_android 6.3.0 [flutter flutter_background_service_platform_interface]
- flutter_background_service_ios 5.0.3 [flutter flutter_background_service_platform_interface]
- flutter_background_service_platform_interface 5.1.2 [flutter platform plugin_platform_interface]
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_class_parser 0.2.5 [flutter]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 5.0.0 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 8.0.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.3 [async collection file path string_scanner]
- gradient_borders 1.0.1 [flutter]
- graphs 2.3.2 [collection]
- hive_ce 2.10.1 [meta crypto web]
- html 0.15.5 [csslib source_span]
- http 1.3.0 [async http_parser meta web]
- http_multi_server 3.2.2 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intersperse 2.0.0
- io 1.0.5 [meta path string_scanner]
- jiffy 6.4.1 [intl quiver]
- js 0.7.1
- leak_tracker 10.0.8 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 4.0.0
- logging 1.3.0
- macos_window_utils 1.7.0 [flutter]
- macros 0.1.3-main.0 [_macros]
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- mime 1.0.6
- mounted_state 1.0.1 [flutter]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.1.0 [flutter]
- package_config 2.2.0 [path]
- package_info_plus_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- path 1.9.1
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.10 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- permission_handler_android 12.0.13 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.6 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+5 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.2.3 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.6
- platform_device_id_linux 1.0.0 [flutter]
- platform_device_id_macos 1.0.0 [flutter]
- platform_device_id_platform_interface 1.0.0 [flutter plugin_platform_interface]
- platform_device_id_web 1.0.0 [flutter flutter_web_plugins platform_device_id_platform_interface]
- platform_device_id_windows 1.0.0 [flutter]
- plugin_platform_interface 2.1.8 [meta]
- pointer_interceptor 0.10.1+2 [flutter flutter_web_plugins pointer_interceptor_ios pointer_interceptor_platform_interface pointer_interceptor_web]
- pointer_interceptor_ios 0.10.1 [flutter plugin_platform_interface pointer_interceptor_platform_interface]
- pointer_interceptor_platform_interface 0.10.0+1 [flutter plugin_platform_interface]
- pointer_interceptor_web 0.10.2+1 [flutter flutter_web_plugins plugin_platform_interface pointer_interceptor_platform_interface web]
- pool 1.5.1 [async stack_trace]
- posix 6.0.1 [ffi meta path]
- pub_semver 2.2.0 [collection]
- pubspec_parse 1.4.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.2 [matcher]
- riverpod 2.6.1 [collection meta stack_trace state_notifier]
- rxdart 0.28.0
- scrollable_positioned_list 0.3.8 [flutter collection]
- sentry 8.14.1 [http meta stack_trace uuid collection]
- shared_preferences_android 2.4.7 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.3 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 2.0.1 [shelf stream_channel web_socket_channel]
- simple_gesture_detector 0.2.1 [flutter]
- sky_engine 0.0.0
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.5 [analyzer collection source_gen]
- source_span 1.10.1 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.1 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.0 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.4+6 [synchronized path meta]
- sqflite_darwin 2.4.1+1 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.12.1 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.4 [async]
- stream_transform 2.1.1
- string_scanner 1.4.1 [source_span]
- syncfusion_flutter_datepicker 28.2.12 [flutter intl syncfusion_flutter_core]
- synchronized 3.1.0+1
- term_glyph 1.2.2
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.2 [json_annotation]
- typed_data 1.3.2 [collection]
- universal_platform 1.1.0
- url_launcher_android 6.3.9 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.2 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.4 [flutter url_launcher_platform_interface]
- vm_service 14.3.1
- watcher 1.1.1 [async path]
- web 1.1.1
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.2 [async crypto stream_channel web web_socket]
- webview_flutter_android 4.3.2 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.18.4 [flutter path webview_flutter_platform_interface]
- win32 5.5.4 [ffi]
- win32_registry 1.1.5 [ffi win32]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

```

</details>
