### ISSUE TITLE
[firebase_crashlytics]: When DART_OBFUSCATION is true,  Flutter Exceptions Not Deobfuscated in Crashlytics

### ISSUE THREAD

**Issue by canbi** [firebase/flutterfire#17258]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

iOS

### Test Case:
I tested the following code in TestFlight on a real device:

```dart
AppSettingRow(
    title: "TEST Exception", 
    leadingIcon: SvgPicture.asset(AppAssets.support), 
    onTap: () => throw Exception('TEST Exception')
),
```

### Crashlytics Output:
The crash report shows obfuscated stack traces without meaningful symbols:
```
          Fatal Exception: FlutterError
0  ???                            0x0 Dgb.RMc.<fn> + 78 (hPl:78)
1  ???                            0x0 _sT.hPe + 1185 (tql:1185)
2  ???                            0x0 wK.Cpe + 357 (Pol:357)
3  ???                            0x0 UK.Hoe + 653 (Sol:653)
4  ???                            0x0 TK._Uoe + 307 (Sol:307)
5  ???                            0x0 TK.Ikd + 277 (Sol:277)
6  ???                            0x0 MH.hbf + 173 (zol:173)
7  ???                            0x0 VH.gKd + 534 (Aol:534)
8  ???                            0x0 VH.EUd + 499 (Aol:499)
9  ???                            0x0 Sba.EUd + 460 (Csl:460)
10 ???                            0x0 VH._MUd + 437 (Aol:437)
11 ???                            0x0 VH.LUd + 394 (Aol:394)
12 ???                            0x0 VH._KUd + 341 (Aol:341)
13 ???                            0x0 VH._HUd + 308 (Aol:308)
14 ???                            0x0 (null)._hcd + 332 (Pil:332)
15 ???                            0x0 Vr._dispatchPointerDataPacket + 451 (Iil:451)
16 ???                            0x0 (null)._dispatchPointerDataPacket + 267 (Pil:267)
```

# Attempted Solutions:

### Scenario 1: Used the standard FlutterFire Crashlytics symbol upload script:

```bash
#!/bin/bash
PATH="${PATH}:$FLUTTER_ROOT/bin:$HOME/.pub-cache/bin"

if [ -z "$PODS_ROOT" ]; then
  # Cannot use "BUILD_DIR%/Build/*" as per Firebase documentation, it points to "flutter-project/build/ios/*" path which doesn't have run script
  DERIVED_DATA_PATH=$(echo "$BUILD_ROOT" | sed -E 's|(.*DerivedData/[^/]+).*|\1|')
  PATH_TO_CRASHLYTICS_UPLOAD_SCRIPT="${DERIVED_DATA_PATH}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
else
  PATH_TO_CRASHLYTICS_UPLOAD_SCRIPT="$PODS_ROOT/FirebaseCrashlytics/run"
fi

# Command to upload symbols script used to upload symbols to Firebase server
flutterfire upload-crashlytics-symbols --upload-symbols-script-path="$PATH_TO_CRASHLYTICS_UPLOAD_SCRIPT" --platform=ios --apple-project-path="${SRCROOT}" --env-platform-name="${PLATFORM_NAME}" --env-configuration="${CONFIGURATION}" --env-project-dir="${PROJECT_DIR}" --env-built-products-dir="${BUILT_PRODUCTS_DIR}" --env-dwarf-dsym-folder-path="${DWARF_DSYM_FOLDER_PATH}" --env-dwarf-dsym-file-name="${DWARF_DSYM_FILE_NAME}" --env-infoplist-path="${INFOPLIST_PATH}" --target=Runner
```

### Scenario 2: Custom Script (Firebase Documentation Approach)
Followed [Firebase's guide](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter#run-script-does-not-exist) to manually upload symbols:

```bash
$PODS_ROOT/FirebaseCrashlytics/upload-symbols --build-phase --validate -ai {MY_APP_ID} -- $DWARF_DSYM_FOLDER_PATH/App.framework.dSYM
$PODS_ROOT/FirebaseCrashlytics/upload-symbols --build-phase -ai  {MY_APP_ID} -- $DWARF_DSYM_FOLDER_PATH/App.framework.dSYM
```

# Outcome:
Both approaches fail to deobfuscate Flutter exception logs in Crashlytics. The stack traces remain unreadable.

### Step 1: Enable Dart Obfuscation in Xcode
- Open your project in Xcode.
- Select the Runner target.
- Go to Build Settings → User-Defined Settings.
- Add or update the following key:
      - Key: DART_OBFUSCATION
      - Value: TRUE

### Firebase Core version

3.13.0

### Flutter Version

3.29.2

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Resolving dependencies... 
Downloading packages... 
Got dependencies.
Dart SDK 3.7.2
Flutter SDK 3.29.2
flyme_mobile 1.1.0+60

dependencies:
- app_links 6.4.0 [flutter app_links_linux app_links_platform_interface app_links_web]
- app_set_id 1.2.1 [flutter flutter_web_plugins plugin_platform_interface]
- app_settings 5.2.0 [flutter plugin_platform_interface]
- auto_route 10.0.1 [flutter path web collection meta]
- auto_size_text 3.0.0 [flutter]
- better_player_plus 1.0.8 [flutter flutter_localizations collection wakelock_plus path_provider visibility_detector flutter_widget_from_html_core]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- collection 1.19.1
- connectivity_plus 6.1.3 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- device_info_plus 11.3.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- dio 5.8.0+1 [async collection http_parser meta path dio_web_adapter]
- dots_indicator 3.1.0 [flutter]
- easy_debounce 2.0.3
- firebase_core 3.13.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.3.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 15.2.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 9.1.0 [bloc flutter provider]
- flutter_html 3.0.0 [html csslib collection list_counter flutter]
- flutter_inappwebview 6.1.5 [flutter flutter_inappwebview_platform_interface flutter_inappwebview_android flutter_inappwebview_ios flutter_inappwebview_macos flutter_inappwebview_web flutter_inappwebview_windows]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_local_notifications 18.0.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_native_splash 2.4.4 [args flutter flutter_web_plugins html image meta path universal_io xml yaml ansicolor]
- flutter_pdfview 1.4.0 [flutter]
- flutter_secure_storage 9.2.4 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_svg 2.0.17 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- fpdart 1.1.1
- freezed_annotation 2.4.4 [collection json_annotation meta]
- get_time_ago 2.3.0 [intl]
- hydrated_bloc 10.0.0 [bloc hive_ce meta synchronized]
- icons_launcher 3.0.1 [args image path universal_io yaml]
- intl 0.19.0 [clock meta path]
- json_annotation 4.9.0 [meta]
- mobile_scanner 7.0.0-beta.8 [collection flutter flutter_web_plugins plugin_platform_interface web]
- open_filex 4.7.0 [flutter ffi]
- package_info_plus 8.3.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- reactive_date_range_picker 2.3.0 [flutter intl reactive_forms]
- reactive_flutter_rating_bar 2.0.1 [flutter reactive_forms flutter_rating_bar]
- reactive_forms 17.0.1 [flutter flutter_localizations intl]
- reactive_phone_form_field 5.0.1 [flutter reactive_forms phone_form_field]
- reactive_pinput 5.0.0 [flutter reactive_forms pinput smart_auth]
- rive 0.13.20 [collection flutter flutter_web_plugins http meta plugin_platform_interface rive_common]
- shared_preferences 2.5.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- story_view 0.16.5 [flutter flutter_cache_manager rxdart video_player collection]
- talker_dio_logger 4.7.1 [dio talker]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- very_good_infinite_list 0.9.0 [flutter]
- visibility_detector 0.4.0+2 [flutter]

dev dependencies:
- auto_route_generator 10.0.1 [build source_gen analyzer path build_runner code_builder dart_style xml args glob package_config auto_route]
- build_runner 2.4.15 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web web_socket_channel yaml]
- flutter_flavorizr 2.3.0 [flutter archive args checked_yaml collection image io json_annotation sprintf xml yaml]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- freezed 2.5.8 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation dart_style]
- json_serializable 6.9.4 [analyzer async build build_config collection dart_style json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- very_good_analysis 7.0.0

dependency overrides:
- provider 6.1.2 [collection flutter nested]

transitive dependencies:
- _fe_analyzer_shared 80.0.0 [meta]
- _flutterfire_internals 1.3.54 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 7.3.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- ansicolor 2.0.3
- app_links_linux 1.0.3 [flutter app_links_platform_interface gtk]
- app_links_platform_interface 2.0.2 [flutter plugin_platform_interface]
- app_links_web 1.0.4 [flutter flutter_web_plugins app_links_platform_interface web]
- archive 4.0.5 [crypto path posix]
- args 2.7.0
- async 2.12.0 [collection meta]
- bloc 9.0.0 [meta]
- boolean_selector 2.1.2 [source_span string_scanner]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.4 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.4 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.5 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- characters 1.4.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- circle_flags 5.0.0 [flutter flutter_svg]
- clock 1.1.2
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.1.2 [typed_data]
- crypto 3.0.6 [typed_data]
- csslib 1.0.2 [source_span]
- dart_style 3.0.1 [analyzer args collection package_config path pub_semver source_span yaml]
- dbus 0.7.11 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.2 [flutter meta plugin_platform_interface]
- diacritic 0.1.6
- dio_web_adapter 2.1.1 [dio http_parser meta web]
- fake_async 1.3.2 [clock collection]
- ffi 2.1.3
- file 7.0.1 [meta path]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.22.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.8.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.6.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.10.5 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- fixnum 1.1.1
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_country_selector 1.0.14 [flutter flutter_localizations intl diacritic circle_flags phone_numbers_parser]
- flutter_inappwebview_android 1.1.3 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_internal_annotations 1.2.0
- flutter_inappwebview_ios 1.1.2 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_macos 1.1.2 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_platform_interface 1.3.0+1 [flutter flutter_inappwebview_internal_annotations plugin_platform_interface]
- flutter_inappwebview_web 1.1.2 [flutter flutter_web_plugins web flutter_inappwebview_platform_interface]
- flutter_inappwebview_windows 0.6.0 [flutter flutter_inappwebview_platform_interface]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 5.0.0 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 8.0.0 [flutter plugin_platform_interface]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_secure_storage_linux 1.2.2 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.1.3 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.1.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.2.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.1.2 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- flutter_widget_from_html_core 0.15.2 [csslib flutter html logging]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.3 [async collection file path string_scanner]
- graphs 2.3.2 [collection]
- gtk 2.1.0 [ffi flutter meta]
- hive_ce 2.10.1 [meta crypto web]
- html 0.15.5 [csslib source_span]
- http 1.3.0 [async http_parser meta web]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- image 4.5.4 [archive meta xml]
- io 1.0.5 [meta path string_scanner]
- js 0.6.7 [meta]
- leak_tracker 10.0.8 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- list_counter 1.0.2
- logging 1.3.0
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- mime 2.0.0
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 2.1.0 [flutter]
- package_config 2.2.0 [path]
- package_info_plus_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- path 1.9.1
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.16 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.0.2 [meta]
- phone_form_field 10.0.6 [flutter flutter_localizations intl flutter_country_selector circle_flags phone_numbers_parser]
- phone_numbers_parser 9.0.3 [meta]
- pinput 5.0.1 [flutter universal_platform]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- posix 6.0.1 [ffi meta path]
- pub_semver 2.2.0 [collection]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- rive_common 0.4.15 [collection ffi flutter flutter_web_plugins graphs http meta plugin_platform_interface web]
- rxdart 0.27.7
- shared_preferences_android 2.4.8 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.3 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 3.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- smart_auth 3.2.0 [flutter]
- source_gen 2.0.0 [analyzer async build dart_style glob path pub_semver source_span yaml]
- source_helper 1.3.5 [analyzer collection source_gen]
- source_span 1.10.1 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.1 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.0 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.4+6 [synchronized path meta]
- sqflite_darwin 2.4.1+1 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.12.1 [path]
- stream_channel 2.1.4 [async]
- stream_transform 2.1.1
- string_scanner 1.4.1 [source_span]
- synchronized 3.3.0+3
- talker 4.7.1 [talker_logger]
- talker_logger 4.7.1 [ansicolor web]
- term_glyph 1.2.2
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.10.0 [http path]
- timing 1.0.2 [json_annotation]
- typed_data 1.4.0 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- universal_platform 1.1.0
- url_launcher_android 6.3.15 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.3 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.4.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.4 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.18 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.16 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- video_player 2.9.5 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.8.2 [flutter video_player_platform_interface]
- video_player_avfoundation 2.7.0 [flutter video_player_platform_interface]
- video_player_platform_interface 6.3.0 [flutter plugin_platform_interface]
- video_player_web 2.3.4 [flutter flutter_web_plugins video_player_platform_interface web]
- vm_service 14.3.1
- wakelock_plus 1.2.11 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus web]
- wakelock_plus_platform_interface 1.2.2 [flutter plugin_platform_interface meta]
- watcher 1.1.1 [async path]
- web 1.1.1
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.2 [async crypto stream_channel web web_socket]
- win32 5.10.1 [ffi]
- win32_registry 1.1.5 [ffi win32]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

```

</details>
