### ISSUE TITLE
[firebase_crashlytics]: ios build failed with upload-crashlytics-symbols in Runner.xcodeproj/project.pbxproj

### ISSUE THREAD

**Issue by wch930** [firebase/flutterfire#17257]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

iOS

### Description

After running the command `flutterfire reconfigure`, `FlutterFire: "flutterfire upload-crashlytics-symbols"` was added to `Runner.xcodeproj/project.pbxproj`. This caused an error when building the iOS side of the Flutter project.

Relevant error output:

```
  ERR : The current activation of `flutterfire_cli` cannot resolve to the same set of dependencies.
        | 
        | Try reactivating the package.
        | `dart pub global activate flutterfire_cli`
    FINE: Exception type: DataException
    FINE: package:pub/src/utils.dart 575:36                                dataError
        | package:pub/src/global_packages.dart 520:13                      GlobalPackages.runExecutable.<fn>
        | ===== asynchronous gap ===========================
        | dart:async                                                       Future.catchError
        | package:pub/src/utils.dart 140:10                                captureErrors.wrappedCallback
        | package:stack_trace                                              Chain.capture
        | package:pub/src/utils.dart 155:11                                captureErrors
        | package:pub/src/command.dart 196:13                              PubCommand.run
        | package:args/command_runner.dart 212:27                          CommandRunner.runCommand
        | package:dartdev/dartdev.dart 240:30                              DartdevRunner.runCommand
        | package:args/command_runner.dart 122:25                          CommandRunner.run.<fn>
        | dart:async                                                       new Future.sync
        | package:args/command_runner.dart 122:14                          CommandRunner.run
        | package:dartdev/dartdev.dart 47:29                               runDartdev
        | /Volumes/Work/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 13:11  main
 ```

Building directly within Xcode works fine.

Removing the related lines from `Runner.xcodeproj/project.pbxproj` resolves the build issue.

<img width="602" alt="Image" src="https://github.com/user-attachments/assets/3d8ac657-24a3-4594-a44b-927a22c25fde" />

<img width="1064" alt="Image" src="https://github.com/user-attachments/assets/974f86de-f5fe-4f36-94a9-3baa49841341" />

### Reproducing the issue

Run the command `flutterfire reconfigure` after adding firebase_crashlytics package.

### Firebase Core version

3.13.0

### Flutter Version

3.27.4

### Relevant Log Output

```shell
MSG :   dart_console 1.2.0 (4.1.1 available)
        | > ffi 2.1.4 (was 2.1.3)
        |   intl 0.18.1 (0.20.2 available)
        |   pub_updater 0.4.0 (0.5.0 available)
        | > win32 5.12.0 (was 5.10.1)
    MSG : Would change 2 dependencies in `/Users/paulwang/.pub-cache/global_packages/flutterfire_cli`.
    MSG : 3 packages have newer versions incompatible with dependency constraints.
        | Try `dart pub outdated` for more information.
    ERR : The current activation of `flutterfire_cli` cannot resolve to the same set of dependencies.
        |
        | Try reactivating the package.
        | `dart pub global activate flutterfire_cli`
    FINE: Exception type: DataException
    FINE: package:pub/src/utils.dart 575:36                                dataError
        | package:pub/src/global_packages.dart 520:13                      GlobalPackages.runExecutable.<fn>
        | ===== asynchronous gap ===========================
        | dart:async                                                       Future.catchError
        | package:pub/src/utils.dart 140:10                                captureErrors.wrappedCallback
        | package:stack_trace                                              Chain.capture
        | package:pub/src/utils.dart 155:11                                captureErrors
        | package:pub/src/command.dart 196:13                              PubCommand.run
        | package:args/command_runner.dart 212:27                          CommandRunner.runCommand
        | package:dartdev/dartdev.dart 240:30                              DartdevRunner.runCommand
        | package:args/command_runner.dart 122:25                          CommandRunner.run.<fn>
        | dart:async                                                       new Future.sync
        | package:args/command_runner.dart 122:14                          CommandRunner.run
        | package:dartdev/dartdev.dart 47:29                               runDartdev
        | /Volumes/Work/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 13:11  main
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
dependencies:
- app_links 6.4.0 [flutter app_links_linux app_links_platform_interface app_links_web]
- bloc 9.0.0 [meta]
- chewie 1.11.1 [cupertino_icons flutter provider video_player wakelock_plus]
- dio 5.8.0+1 [async collection http_parser meta path dio_web_adapter]
- duration_picker 1.2.0 [flutter]
- equatable 2.0.7 [collection meta]
- ffmpeg_kit_flutter_full_gpl 6.0.3 [ffmpeg_kit_flutter_platform_interface flutter]
- firebase_analytics 11.4.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.13.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.3.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_performance 0.10.1+5 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- flex_color_scheme 8.1.1 [flex_seed_scheme flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 9.1.0 [bloc flutter provider]
- flutter_image_gallery_saver 0.0.2 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_secure_storage 9.2.4 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_web_auth_2 4.1.0 [desktop_webview_window flutter flutter_web_auth_2_platform_interface flutter_web_plugins path_provider url_launcher web window_to_front]
- get_thumbnail_video 0.7.3 [flutter flutter_web_plugins web plugin_platform_interface cross_file]
- http 1.3.0 [async http_parser meta web]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_purchase 3.2.1 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- intl 0.19.0 [clock meta path]
- keep_screen_on 4.0.0 [flutter keep_screen_on_platform_interface]
- lottie 3.3.1 [archive flutter http path vector_math]
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- purchases_flutter 8.7.1 [flutter freezed_annotation json_annotation]
- purchases_ui_flutter 8.7.1 [purchases_flutter flutter plugin_platform_interface]
- share_plus 10.1.4 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- shared_preferences 2.5.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- video_compress 3.1.4 [flutter]
- video_player 2.9.5 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- wechat_assets_picker 9.5.0 [flutter wechat_picker_library extended_image photo_manager photo_manager_image_provider provider video_player visibility_detector]

dev dependencies:
- bloc_test 10.0.0 [bloc diff_match_patch meta mocktail test]
- change_app_package_name 1.5.0
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- mocktail 1.0.4 [collection matcher test_api]
- very_good_analysis 7.0.0

transitive dependencies:
- _fe_analyzer_shared 76.0.0 [meta]
- _flutterfire_internals 1.3.54 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.3
- analyzer 6.11.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- app_links_linux 1.0.3 [flutter app_links_platform_interface gtk]
- app_links_platform_interface 2.0.2 [flutter plugin_platform_interface]
- app_links_web 1.0.4 [flutter flutter_web_plugins app_links_platform_interface web]
- archive 4.0.5 [crypto path posix]
- args 2.7.0
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.19.0
- convert 3.1.2 [typed_data]
- coverage 1.11.1 [args glob logging meta package_config path source_maps stack_trace vm_service]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.6 [typed_data]
- csslib 1.0.2 [source_span]
- cupertino_icons 1.0.8
- dbus 0.7.11 [args ffi meta xml]
- desktop_webview_window 0.2.3 [flutter path]
- diff_match_patch 0.4.1
- dio_web_adapter 2.1.1 [dio http_parser meta web]
- extended_image 9.1.0 [extended_image_library flutter meta vector_math]
- extended_image_library 4.0.6 [crypto flutter http_client_helper js path path_provider web]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- ffmpeg_kit_flutter_platform_interface 0.2.1 [flutter plugin_platform_interface]
- file 7.0.1 [meta path]
- file_selector_linux 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+4 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 4.3.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+11 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.22.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.8.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_performance_platform_interface 0.1.5+5 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.7+11 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins]
- fixnum 1.1.1
- flex_seed_scheme 3.5.1 [collection flutter meta]
- flutter_plugin_android_lifecycle 2.0.27 [flutter]
- flutter_secure_storage_linux 1.2.2 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.1.3 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.1.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.2.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.1.2 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_web_auth_2_platform_interface 4.1.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.3 [async collection file path string_scanner]
- gtk 2.1.0 [ffi flutter meta]
- html 0.15.5 [csslib source_span]
- http_client_helper 3.0.0 [http]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.12+22 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.6 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+2 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+2 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.1 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_purchase_android 0.4.0+1 [collection flutter in_app_purchase_platform_interface]
- in_app_purchase_platform_interface 1.4.0 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.21 [collection flutter in_app_purchase_platform_interface json_annotation]
- io 1.0.5 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.9.0 [meta]
- keep_screen_on_platform_interface 3.0.0 [flutter plugin_platform_interface]
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- logging 1.3.0
- macros 0.1.3-main.0 [_macros]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 2.0.0
- nested 1.0.0 [flutter]
- node_preamble 2.0.2
- package_config 2.2.0 [path]
- package_info_plus 8.3.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- package_info_plus_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_provider_android 2.2.16 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.0.2 [meta]
- photo_manager 3.6.4 [flutter]
- photo_manager_image_provider 2.2.0 [flutter photo_manager]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- posix 6.0.1 [ffi meta path]
- provider 6.1.4 [collection flutter nested]
- pub_semver 2.2.0 [collection]
- share_plus_platform_interface 5.0.2 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.4.8 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.3 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.3 [convert http_parser mime path shelf]
- shelf_web_socket 2.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- source_map_stack_trace 2.1.2 [path source_maps stack_trace]
- source_maps 0.10.13 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.12.0 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.3.0 [source_span]
- term_glyph 1.2.1
- test 1.25.8 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.6.5 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- typed_data 1.4.0 [collection]
- url_launcher_android 6.3.15 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.3 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.4.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.4 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- video_player_android 2.8.2 [flutter video_player_platform_interface]
- video_player_avfoundation 2.7.0 [flutter video_player_platform_interface]
- video_player_platform_interface 6.3.0 [flutter plugin_platform_interface]
- video_player_web 2.3.4 [flutter flutter_web_plugins video_player_platform_interface web]
- visibility_detector 0.4.0+2 [flutter]
- vm_service 14.3.0
- wakelock_plus 1.2.11 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus web]
- wakelock_plus_platform_interface 1.2.2 [flutter plugin_platform_interface meta]
- watcher 1.1.1 [async path]
- web 1.1.1
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.2 [async crypto stream_channel web web_socket]
- webkit_inspection_protocol 1.2.1 [logging]
- wechat_picker_library 1.0.5 [flutter photo_manager]
- win32 5.10.1 [ffi]
- window_to_front 0.0.3 [flutter]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

```

</details>
