### ISSUE TITLE
VertexAI: Firebase Vertex AI's ImagenInlineImage Access Issues

### ISSUE THREAD

**Issue by mikalwessel** [firebase/flutterfire#17261]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

iOS, Android

### Description

**Issue Summary**

We're experiencing difficulties accessing image data from ImagenInlineImage objects generated by the Firebase Vertex AI Flutter SDK. Despite successful image generation, we cannot directly access or convert the raw image data for display or storage.

**Environment**

Platform: Flutter
SDK: Firebase Vertex AI
Model: imagen-3.0-generate-002
Object Type: ImagenInlineImage

**Available Properties**

Our investigation shows ImagenInlineImage has limited accessible properties:

✅ mimeType: Returns "image/png" (confirmed accessible)
❌ No direct access to image bytes/data properties

**Attempted Solutions**

1. Direct Property Access
We attempted to access various potential properties that might contain image data:

`final dynamic dynamicImage = image;
// Properties we tried accessing:
// data, bytes, content, imageData, raw, rawBytes, byteData, buffer, base64, dataUrl, png`

Result: No direct property contains accessible image data.

2. Method Access
We attempted to access potential methods:

`// Methods we tried accessing:
// toBytes(), asBytes(), toDataUrl(), decode(), toBitmap(), toImage(), saveToFile()`

Result: None of these methods exist on the object.

3. API-Specific Upload Method
We explored possible Firebase-specific methods:

```
try {
  if (dynamicImage.uploadToFirebaseStorage != null) {
    final String url = await dynamicImage.uploadToFirebaseStorage(ref);
    // Process URL
  }
} catch (e) {
  print('Error with VertexAI-specific upload: $e');
}
```

Result: No such method exists.

4. Cast/Type Conversion
We checked if the object implements standard Dart interfaces:

```
print('Is List<int>?: ${dynamicImage is List<int>}');
print('Is Uint8List?: ${dynamicImage is Uint8List}');
```

Result: Does not implement these interfaces.

5. JSON Serialization
We attempted to serialize to JSON for inspection:

```
try {
  final Map<String, dynamic>? jsonData = dynamicImage.toJson();
  // Process JSON
} catch (e) {
  print('No toJson method: $e');
}
```

Result: No serialization methods available.

**Documentation Gap**

The JavaScript SDK documentation (https://firebase.google.com/docs/reference/js/vertexai.imageninlineimage) suggests properties like base64 should exist, but these aren't implemented or accessible in the Flutter SDK version.

**Request**

We need guidance on:

1. How to properly access the raw image data from ImagenInlineImage objects
2. The recommended approach to display these images in Flutter applications
3. Documentation specific to the Flutter SDK implementation of ImagenInlineImage

Thank you for your assistance.

### Reproducing the issue

Create a new Flutter project
Connect it to Firebase using FlutterFire CLI
Enable Firebase Vertex AI in your Firebase console
Copy the above code
Run the app
Click "Generate Image"
Check the logs to observe the issue

 Expected Results
The app should be able to:

Generate an image using Vertex AI
Access the raw bytes or base64 data of the generated image
Display the image directly or save it to Firebase Storage

Actual Results
The app can only:

Generate the image
Access the mimeType property which is "image/png"
Cannot access any properties that would allow displaying or saving the actual image data

```
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_vertexai/firebase_vertexai.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Vertex AI Image Issue',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const VertexImageTest(),
    );
  }
}

class VertexImageTest extends StatefulWidget {
  const VertexImageTest({Key? key}) : super(key: key);

  @override
  State<VertexImageTest> createState() => _VertexImageTestState();
}

class _VertexImageTestState extends State<VertexImageTest> {
  bool _isLoading = false;
  List<ImagenInlineImage> _images = [];
  String _logOutput = '';
  
  // Add log output
  void _log(String message) {
    setState(() {
      _logOutput += '$message\n';
      print(message);
    });
  }
  
  // Generate an image
  Future<void> _generateImage() async {
    if (_isLoading) return;
    
    setState(() {
      _isLoading = true;
      _logOutput = '';
    });
    
    try {
      _log('Initializing Vertex AI...');
      
      // Initialize the model
      final ImagenModel model = FirebaseVertexAI.instance.imagenModel(
        model: 'imagen-3.0-generate-002',
        generationConfig: ImagenGenerationConfig(numberOfImages: 1),
      );
      
      _log('Generating image...');
      
      // Generate the image
      final response = await model.generateImages(
        'A simple red apple on a white background',
      );
      
      if (response.images.isEmpty) {
        _log('Error: No images were generated');
        return;
      }
      
      // Store the image and inspect it
      setState(() {
        _images = response.images;
      });
      
      // Log image details
      _inspectImage(response.images.first);
      
    } catch (e) {
      _log('Error: $e');
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }
  
  // Inspect the ImagenInlineImage properties
  void _inspectImage(ImagenInlineImage image) {
    try {
      _log('Image type: ${image.runtimeType}');
      _log('Image toString: ${image.toString()}');
      
      // Try to cast to dynamic to access properties
      dynamic dynamicImage = image;
      
      // Try to access basic properties
      try {
        final mimeType = dynamicImage.mimeType;
        _log('MimeType: $mimeType');
      } catch (e) {
        _log('No mimeType property: $e');
      }
      
      // Try to access potential image data properties
      final List<String> potentialProperties = [
        'data', 'bytes', 'content', 'imageData', 'raw', 'rawBytes', 
        'byteData', 'buffer', 'base64', 'dataUrl', 'png'
      ];
      
      for (final prop in potentialProperties) {
        try {
          final value = dynamicImage[prop];
          if (value != null) {
            String valueType = value.runtimeType.toString();
            String valueSummary = value is String 
                ? '${value.length} chars' 
                : value.toString();
            _log('Property $prop found: $valueType ($valueSummary)');
          }
        } catch (e) {
          // Property doesn't exist - skip silently
        }
      }
      
      // Try to check if it's a standard binary type
      _log('Is List<int>?: ${dynamicImage is List<int>}');
      _log('Is Uint8List?: ${dynamicImage is Uint8List}');
      
    } catch (e) {
      _log('Error inspecting image: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Vertex AI Image Issue'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            ElevatedButton(
              onPressed: _isLoading ? null : _generateImage,
              child: _isLoading 
                  ? const CircularProgressIndicator(color: Colors.white)
                  : const Text('Generate Image'),
            ),
            const SizedBox(height: 16),
            
            // Show image count
            if (_images.isNotEmpty)
              Text('Generated ${_images.length} images',
                  style: Theme.of(context).textTheme.titleMedium),
            
            const SizedBox(height: 16),
            
            // Image placeholder (since we can't display the actual image)
            if (_images.isNotEmpty)
              Container(
                height: 200,
                decoration: BoxDecoration(
                  color: Colors.grey.shade200,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: const Center(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(Icons.image, size: 48, color: Colors.grey),
                      SizedBox(height: 8),
                      Text('AI Generated Image'),
                      SizedBox(height: 4),
                      Text('(Cannot access image data)', 
                           style: TextStyle(fontSize: 12, color: Colors.grey)),
                    ],
                  ),
                ),
              ),
            
            const SizedBox(height: 16),
            
            // Log output
            Container(
              decoration: BoxDecoration(
                color: Colors.black87,
                borderRadius: BorderRadius.circular(8),
              ),
              padding: const EdgeInsets.all(8),
              child: Text(
                _logOutput.isEmpty 
                    ? 'Logs will appear here...' 
                    : _logOutput,
                style: const TextStyle(
                  color: Colors.green,
                  fontFamily: 'monospace',
                  fontSize: 12,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

### Firebase Core version

3.12.1

### Flutter Version

3.29.0

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.7.0
Flutter SDK 3.29.0
dream_app 1.0.0+1

dependencies:
- animated_splash_screen 1.3.0 [flutter page_transition]
- cloud_firestore 5.6.5 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.8
- dio 5.8.0+1 [async collection http_parser meta path dio_web_adapter]
- firebase_analytics 11.4.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.5.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.12.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_remote_config 5.4.2 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_storage 12.4.4 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- firebase_ui_auth 1.16.1 [email_validator firebase_auth firebase_core firebase_dynamic_links firebase_ui_localizations firebase_ui_oauth firebase_ui_shared flutter flutter_localizations meta]
- firebase_vertexai 1.4.0 [firebase_app_check firebase_auth firebase_core firebase_core_platform_interface flutter http]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_native_splash 2.4.4 [args flutter flutter_web_plugins html image meta path universal_io xml yaml ansicolor]
- go_router 14.8.1 [collection flutter flutter_web_plugins logging meta]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- http 1.3.0 [async http_parser meta web]
- intl 0.19.0 [clock meta path]
- lottie 2.7.0 [archive flutter path vector_math]
- path 1.9.1
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- provider 6.1.2 [collection flutter nested]
- purchases_flutter 8.6.0 [flutter freezed_annotation json_annotation]
- purchases_ui_flutter 8.6.0 [purchases_flutter flutter plugin_platform_interface]
- uuid 3.0.7 [crypto]

dev dependencies:
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.53 [collection firebase_core firebase_core_platform_interface flutter meta]
- ansicolor 2.0.3
- archive 3.6.1 [crypto path]
- args 2.6.0
- async 2.12.0 [collection meta]
- boolean_selector 2.1.2 [source_span string_scanner]
- characters 1.4.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.2 [meta path]
- clock 1.1.2
- cloud_firestore_platform_interface 6.6.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.4.5 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- collection 1.19.1
- crypto 3.0.6 [typed_data]
- csslib 1.0.2 [source_span]
- desktop_webview_auth 0.0.15 [crypto flutter http flutter_web_plugins plugin_platform_interface]
- dio_web_adapter 2.1.1 [dio http_parser meta web]
- email_validator 2.1.17
- fake_async 1.3.2 [clock collection]
- ffi 2.1.4
- firebase_analytics_platform_interface 4.3.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+10 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_app_check 0.3.2+4 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check_platform_interface 0.1.1+4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.2.0+8 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
- firebase_auth_platform_interface 7.6.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.14.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.21.1 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_dynamic_links 6.1.4 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.7+4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_platform_interface 1.5.2 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.8.2 [_flutterfire_internals firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- firebase_storage_platform_interface 5.2.4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.10.11 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http meta web]
- firebase_ui_localizations 1.13.1 [flutter flutter_localizations path]
- firebase_ui_oauth 1.6.1 [desktop_webview_auth firebase_auth firebase_ui_auth firebase_ui_shared flutter_svg flutter]
- firebase_ui_shared 1.4.1 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_svg 2.0.17 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- html 0.15.5 [csslib source_span]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- image 4.3.0 [archive meta xml]
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.8 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.1
- logging 1.3.0
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- nested 1.0.0 [flutter]
- page_transition 2.2.1 [flutter]
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.15 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.1.0 [meta collection]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.0
- source_span 1.10.1 [collection path term_glyph]
- stack_trace 1.12.1 [path]
- stream_channel 2.1.4 [async]
- string_scanner 1.4.1 [source_span]
- term_glyph 1.2.2
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.4.0 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- vector_graphics 1.1.18 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.16 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 14.3.1
- web 1.1.1
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

```

</details>
