### ISSUE TITLE
[firebase_code]: <YOUR TITLE HERE>

### ISSUE THREAD

**Issue by jersonal-com** [firebase/flutterfire#17275]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

iOS

### Description

I am facing issues building an app using firebase that runs perfectly fine on Android on iOS. When trying to narrow down the problem it seems that there is an incompatibility issue that I could not solve by following the documentation. 

I would expect that the application builds on macOS for iOS when following the docs. 

### Reproducing the issue

I am creating the simple flutter standard app and it is running without any problems:

```
flutter create fb_test
cd fb_test
flutter run
```

After adding the firebase package as a dependency and without changing the code:

```
flutter pub add firebase_core
cd ios
pod setup
cd ..
flutter run
```

the run fails as firebase requires iOS 13.0. In line with the documentation I am changing: 

Podfile:
```
platform :ios, '13.0'
```

ios/Flutter/AppFrameworkInfo.plist:
```
  <key>MinimumOSVersion</key>
  <string>13.0</string>
```

After these changes I run

```
pod repo update
pod install --repo-update
```

and set in XCode the configuration to `Pods-Runner.profile.xcconfig`

Running the app again results in the error message below.

### Firebase Core version

3.13.0

### Flutter Version

3.29.2

### Relevant Log Output

```shell
Launching lib/main.dart on iPhone 16 Plus in debug mode...
Running Xcode build...                                          
 └─Compiling, linking and signing...                      2,657ms
Xcode build done.                                            9.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/5n/nb08vdn15sn4yq0m22p2rfp00000gn/T/flutter_tools.m6NMQZ/flutter_ios_build_temp_dir5PbqqT/temporary_xcresult_bundle

    ld: warning: object file (/Users/oliver/fb_test/build/ios/Debug-iphonesimulator/firebase_core/firebase_core.framework/firebase_core[x86_64][4](firebase_core-dummy.o)) was built for newer 'iOS-simulator' version (13.0) than being linked (12.0)
    ld: warning: object file (/Users/oliver/fb_test/build/ios/Debug-iphonesimulator/firebase_core/firebase_core.framework/firebase_core[x86_64][5](FLTFirebaseCorePlugin.o)) was built for newer 'iOS-simulator' version (13.0) than being linked (12.0)
    ld: warning: object file (/Users/oliver/fb_test/build/ios/Debug-iphonesimulator/firebase_core/firebase_core.framework/firebase_core[x86_64][6](FLTFirebasePlugin.o)) was built for newer 'iOS-simulator' version (13.0) than being linked (12.0)
    ld: warning: object file (/Users/oliver/fb_test/build/ios/Debug-iphonesimulator/firebase_core/firebase_core.framework/firebase_core[x86_64][7](FLTFirebasePluginRegistry.o)) was built for newer 'iOS-simulator' version (13.0) than being linked (12.0)
    ld: warning: object file (/Users/oliver/fb_test/build/ios/Debug-iphonesimulator/firebase_core/firebase_core.framework/firebase_core[x86_64][8](messages.g.o)) was built for newer 'iOS-simulator' version (13.0) than being linked (12.0)
    ld: warning: object file (/Users/oliver/fb_test/build/ios/Debug-iphonesimulator/Pods_Runner.framework/Pods_Runner[x86_64][3](Pods-Runner-dummy.o)) was built for newer 'iOS-simulator' version (13.0) than being linked (12.0)
    Unhandled exception:
    Null check operator used on a null value
    #0      Context.embedFlutterFrameworks (file:///usr/local/Caskroom/flutter/3.29.2/flutter/packages/flutter_tools/bin/xcode_backend.dart:220:68)
    #1      Context.run (file:///usr/local/Caskroom/flutter/3.29.2/flutter/packages/flutter_tools/bin/xcode_backend.dart:58:9)
    #2      main (file:///usr/local/Caskroom/flutter/3.29.2/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
    #3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:313:33)
    #4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:12)
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.7.2
Flutter SDK 3.29.2
fb_test 1.0.0+1

dependencies:
- cupertino_icons 1.0.8
- firebase_core 3.13.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- async 2.12.0 [collection meta]
- boolean_selector 2.1.2 [source_span string_scanner]
- characters 1.4.0
- clock 1.1.2
- collection 1.19.1
- fake_async 1.3.2 [clock collection]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.22.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.8 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.1
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- path 1.9.1
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.0
- source_span 1.10.1 [collection path term_glyph]
- stack_trace 1.12.1 [path]
- stream_channel 2.1.4 [async]
- string_scanner 1.4.1 [source_span]
- term_glyph 1.2.2
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.3.1
- web 1.1.1

```

</details>
