### ISSUE TITLE
[cloud_firestore]: Missing PDB files during build

### ISSUE THREAD

**Issue by 0x456d7265** [firebase/flutterfire#17312]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core, Auth, Analytics, Other

### Which platforms are affected?

Windows

### Description

When integrating Firebase packages with a Flutter project on Windows, numerous linker warnings appear during build related to missing PDB files. These errors appear when trying to run the app on Windows. I don't know if it's related to all packages or just some of them. I've just added these dependencies to a fresh Flutter project.

```yaml
firebase_core: ^3.13.0
cloud_firestore: ^5.6.6
firebase_database: ^11.3.5
firebase_auth: ^5.5.2
firebase_analytics: ^11.4.5
firebase_messaging: ^15.2.5
```

### Reproducing the issue

1. Create a new Flutter project
2. Add Firebase packages to pubspec.yaml
3. Configure Firebase with `flutterfire `configure
4. Add `Firebase.initializeApp()` to `main`
4. Run the app on Windows desktop target

### Firebase Core version

3.13.0

### Flutter Version

3.29.3

### Relevant Log Output

```shell
Launching lib\main.dart on Windows in debug mode...
CMake Deprecation Warning at C:/Users/emrec/Documents/GitHub/project_g/build/windows/x64/extracted/firebase_cpp_sdk_windows/CMakeLists.txt:17 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_desktop.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_desktop.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_mutex_windows.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_mutex_windows.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_reference_counted_future_impl.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_reference_counted_future_impl.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_log.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_log.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_options.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_options.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_common.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_common.obj)' or at ''; linking object as if no debug info 
...
...
[C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_transfer.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_transfer.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_timeval.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_timeval.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_llist.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_llist.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_hash.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_hash.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_hostip6.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_hostip6.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_hostip.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_hostip.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_splay.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_splay.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_http.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_http.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_schannel.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_schannel.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_getenv.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_getenv.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_md5.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_md5.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_base64.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_base64.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_urlapi.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_urlapi.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_netrc.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_netrc.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_http_negotiate.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_http_negotiate.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_http_ntlm.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_http_ntlm.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_strerror.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_strerror.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_if2ip.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_if2ip.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_nonblock.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_nonblock.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_inet_ntop.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_inet_ntop.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_version_win32.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_version_win32.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_digest_sspi.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_digest_sspi.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_curl_sspi.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_curl_sspi.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_http_chunks.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_http_chunks.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_doh.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_doh.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_formdata.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_formdata.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_ntlm_sspi.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_ntlm_sspi.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_spnego_sspi.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_spnego_sspi.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_socks_sspi.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_socks_sspi.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_schannel_verify.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_schannel_verify.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_x509asn1.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_x509asn1.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_dotdot.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_dotdot.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_vauth.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_vauth.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_digest.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_digest.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_hostcheck.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_hostcheck.obj)' or at ''; linking object as if no debug info [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : error LNK2019: unresolved external symbol __std_find_last_trivial_1 referenced in function "char const * __cdecl std::_Find_last_vectorized<char const ,char>(char const * const,char const * const,char)" (??$_Find_last_vectorized@$$CBDD@std@@YAPEBDQEBD0D@Z) [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_util.obj) : error LNK2001: unresolved external symbol __std_find_last_trivial_1 [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : error LNK2019: unresolved external symbol __std_find_first_of_trivial_1 referenced in function "char const * __cdecl std::_Find_first_of_vectorized<char const ,char const >(char const * const,char const * const,char const * const,char const * const)" (??$_Find_first_of_vectorized@$$CBD$$CBD@std@@YAPEBDQEBD000@Z) [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : error LNK2019: unresolved external symbol __std_remove_8 referenced in function "struct f_b_flatbuffers::StructDef * * __cdecl std::_Remove_vectorized<struct f_b_flatbuffers::StructDef *,struct f_b_flatbuffers::StructDef *>(struct f_b_flatbuffers::StructDef * * const,struct f_b_flatbuffers::StructDef * * const,struct f_b_flatbuffers::StructDef * const)" (??$_Remove_vectorized@PEAUStructDef@f_b_flatbuffers@@PEAU12@@std@@YAPEAPEAUStructDef@f_b_flatbuffers@@QEAPEAU12@0QEAU12@@Z) [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_util.obj) : error LNK2019: unresolved external symbol __std_find_last_of_trivial_pos_1 referenced in function "unsigned __int64 __cdecl std::_Find_last_of_pos_vectorized<char,char>(char const * const,unsigned __int64,char const * const,unsigned __int64)" (??$_Find_last_of_pos_vectorized@DD@std@@YA_KQEBD_K01@Z) [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
firebase_auth.lib(a9003852461049443285ecfe94112265_firebase_auth.dir_Debug_error_codes.obj) : error LNK2019: unresolved external symbol __std_search_1 referenced in function "char const * __cdecl std::_Search_vectorized<char const ,char const >(char const * const,char const * const,char const * const,unsigned __int64)" (??$_Search_vectorized@$$CBD$$CBD@std@@YAPEBDQEBD00_K@Z) [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\Debug\project_g.exe : fatal error LNK1120: 5 unresolved externals [C:\Users\emrec\Documents\GitHub\project_g\build\windows\x64\runner\project_g.vcxproj]
Error: Build process failed.

Exited (1).
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.7.2
Flutter SDK 3.29.3
project_g 1.0.0+1

dependencies:
- cloud_firestore 5.6.6 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase_analytics 11.4.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.5.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.13.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 11.3.5 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_messaging 15.2.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- shadcn_ui 0.24.0 [boxy collection flutter flutter_animate flutter_localizations flutter_svg intl lucide_icons_flutter two_dimensional_scrollables universal_image vector_graphics]

dev dependencies:
- epi_analysis 1.0.1
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.54 [collection firebase_core firebase_core_platform_interface flutter meta]
- args 2.7.0
- async 2.12.0 [collection meta]
- boolean_selector 2.1.2 [source_span string_scanner]
- boxy 2.2.1 [flutter vector_math]
- characters 1.4.0
- clock 1.1.2
- cloud_firestore_platform_interface 6.6.6 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.4.6 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- collection 1.19.1
- crypto 3.0.6 [typed_data]
- extended_image 10.0.1 [extended_image_library flutter meta vector_math]
- extended_image_library 5.0.0 [crypto flutter http_client_helper js path path_provider web]
- fake_async 1.3.2 [clock collection]
- ffi 2.1.4
- firebase_analytics_platform_interface 4.3.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+11 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_auth_platform_interface 7.6.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.14.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.22.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_database_platform_interface 0.2.6+5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.6+11 [collection firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins]
- firebase_messaging_platform_interface 4.6.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.10.5 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- flutter_animate 4.5.2 [flutter flutter_shaders]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_shaders 0.1.3 [flutter vector_math]
- flutter_svg 2.1.0 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- http 1.3.0 [async http_parser meta web]
- http_client_helper 3.0.0 [http]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- intl 0.19.0 [clock meta path]
- js 0.7.2
- leak_tracker 10.0.8 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lucide_icons_flutter 1.3.0 [flutter]
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- path 1.9.1
- path_parsing 1.1.0 [meta vector_math]
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.17 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.1.0 [meta collection]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.0
- source_span 1.10.1 [collection path term_glyph]
- stack_trace 1.12.1 [path]
- stream_channel 2.1.4 [async]
- string_scanner 1.4.1 [source_span]
- term_glyph 1.2.2
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- two_dimensional_scrollables 0.3.3 [flutter]
- typed_data 1.4.0 [collection]
- universal_image 1.0.9 [flutter flutter_svg extended_image]
- vector_graphics 1.1.18 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.16 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 14.3.1
- web 1.1.1
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]


```

</details>

### Additional context and comments

The original logs output was much longer.
