### ISSUE TITLE
[firebase_auth]: `signOut` cannot sign out the Twitter Auth Provider

### ISSUE THREAD

**Issue by AlexV525** [firebase/flutterfire#17337]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android, iOS

### Description

Calling `FirebaseAuth.signOut` cannot sign out of Twitter from the opening web tab; it still automatically redirects to the previous logged-in Twitter account.

### Reproducing the issue

1. Use `TwitterAuthProvider` to sign in.
2. Call `FirebaseAuth.instance.signOut`.
3. Reauth with `TwitterAuthProvider`.

### Firebase Core version

3.13.0

### Flutter Version

3.27.4

### Relevant Log Output

```shell
No helpful information.
```

### Flutter dependencies

<details>
<summary>pubspec.lock</summary>
<br>

```yaml
  firebase_auth:
    version: "5.5.2"
  firebase_auth_platform_interface:
    version: "7.6.2"
  firebase_auth_web:
    version: "5.14.2"
  firebase_core:
    version: "3.13.0"
  firebase_core_platform_interface:
    version: "5.4.0"
  firebase_core_web:
    version: "2.22.0"
```

</details>
