### ISSUE TITLE
[FirebaseAnalytics]: Error installing FirebaseAnalytics with pod instal

### ISSUE THREAD

**Issue by daniel-g-favoreto-opl** [firebase/flutterfire#17335]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

iOS

### Description

Can't install firebase analytics with pod install, tried with CocoaPods 1.15.2 and 1.16.2, Xcode version 16.3

### Reproducing the issue

This is happening in the example folder 

### Firebase Core version

3.13.0

### Flutter Version

3.29.2

### Relevant Log Output

```shell
% pod install
Analyzing dependencies
firebase_analytics: Using Firebase SDK version '11.10.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '11.10.0' defined in 'firebase_core'
Downloading dependencies
Installing Firebase (11.10.0)
Installing FirebaseAnalytics (11.10.0)

[!] Error installing FirebaseAnalytics
[!] /usr/bin/curl -f -L -o /var/folders/bs/ffk3s00x6pg7krtbqyf9mxq40000gq/T/d20250506-69472-18au3fp/file.tgz https://dl.google.com/firebase/ios/analytics/f4ae251137d1f29b/FirebaseAnalytics-11.10.0.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.15.2 cocoapods-downloader/2.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  1613    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
curl: (56) The requested URL returned error: 502
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.7.2
Flutter SDK 3.29.2
firebase_analytics_example 0.0.0

dependencies:
- firebase_analytics 11.4.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.13.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

transitive dependencies:
- _flutterfire_internals 1.3.54 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.12.0 [collection meta]
- boolean_selector 2.1.2 [source_span string_scanner]
- characters 1.4.0
- clock 1.1.2
- collection 1.19.1
- fake_async 1.3.2 [clock collection]
- firebase_analytics_platform_interface 4.3.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+11 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.22.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- leak_tracker 10.0.8 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- path 1.9.1
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.0
- source_span 1.10.1 [collection path term_glyph]
- stack_trace 1.12.1 [path]
- stream_channel 2.1.4 [async]
- string_scanner 1.4.1 [source_span]
- term_glyph 1.2.2
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 14.3.1
- web 1.1.1

```

</details>
