### ISSUE TITLE
[firebase_remote_config]: [Flutter 3.29.3] com.google.firebase.components.MissingDependencyException when initialising on android

### ISSUE THREAD

**Issue by TDuffinNTU** [firebase/flutterfire#17346]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core, Remote Config

### Which platforms are affected?

Android

### Description

I'm running into issues when upgrading to Flutter 3.29.3 from 3.27.4.

When calling `Firebase.initializeApp` on android, the app hangs due to a platform exception. I'm using the latest version of all the firebase packages that we use in our app.

firebase packages in our pubspec.yaml:

```
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  firebase_remote_config: ^5.4.3
```

### Reproducing the issue

Call Firebase.initializeApp() during app startup.

### Firebase Core version

3.13.0

### Flutter Version

3.29.3

### Relevant Log Output

```shell
E/flutter ( 3711): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(com.google.firebase.components.MissingDependencyException: Unsatisfied dependency for component Component<[com.google.firebase.remoteconfig.interop.FirebaseRemoteConfigInterop, com.google.firebase.remoteconfig.RemoteConfigComponent]>{2, type=0, deps=[Dependency{anInterface=com.google.firebase.abt.component.AbtComponent, type=required, injection=direct}, Dependency{anInterface=android.content.Context, type=required, injection=direct}, Dependency{anInterface=com.google.firebase.installations.FirebaseInstallationsApi, type=required, injection=direct}, Dependency{anInterface=@com.google.firebase.annotations.concurrent.Blocking java.util.concurrent.ScheduledExecutorService, type=required, injection=direct}, Dependency{anInterface=com.google.firebase.FirebaseApp, type=required, injection=direct}, Dependency{anInterface=com.google.firebase.analytics.connector.AnalyticsConnector, type=optional, injection=provider}]}: com.google.firebase.abt.component.AbtComponent, MissingDependencyException, Cause: null, Stacktrace: com.google.firebase.components.MissingDependencyException: Unsatisfied dependency for component Component<[com.google.firebase.remoteconfig.interop.FirebaseRemoteConfigInterop, com.google.firebase.remoteconfig.RemoteConfigComponent]>{2, type=0, deps=[Dependency{anInterface=com.google.firebase.abt.component.AbtComponent, type=required, injection=direct}, Dependency{anInterface=android.content.Context, type=required, injection=direct}, Dependency{anInterface=com.google.firebase.installations.FirebaseInstallationsApi, type=required, injection=direct}, Dependency{anInterface=@com.google.firebase.annotations.concurrent.Blocking java.util.concurrent.ScheduledExecutorService, type=required, injection=direct}, Dependency{anInterface=com.google.firebase.FirebaseApp, type=required, injection=direct}, Dependency{anInterface=com.google.firebase.analytics.connector.AnalyticsConnector, type=optional, injection=provider}]}: com.google.firebase.abt.component.AbtComponent
```

### Flutter dependencies

Please accept my apologies for any [REDACTED] blocks, trying to reduce sharing identifiable or sensitive info unnecessarily. 

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.7.2
Flutter SDK 3.29.3
[REDACTED] 1.0.0+1

dependencies:
- accessibility_tools 2.4.1 [collection flutter flutter_test]
- animations 2.0.11 [flutter]
- app_icon_customisation 0.0.1 [flutter plugin_platform_interface]
- app_switcher_privacy 0.0.1 [flutter plugin_platform_interface]
- app_tracking_transparency 2.0.6+1 [flutter]
- [REDACTED] [flutter asn1lib crypto enum_to_string http logger pem shared_preferences mutex]
- [REDACTED] [flutter]
- auto_size_text 3.0.0 [flutter]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cancellation_token 2.0.1 [meta collection]
- cancellation_token_http 2.1.0 [async cancellation_token http_parser meta web]
- clock 1.1.2
- collection 1.19.1
- confetti 0.8.0 [flutter vector_math]
- cupertino_icons 1.0.8
- decimal 2.3.3 [rational]
- easy_mask 2.0.1 [flutter]
- equatable 2.0.7 [collection meta]
- extended_image 10.0.1 [extended_image_library flutter meta vector_math]
- file_picker 10.1.2 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file web]
- firebase_analytics 11.4.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.13.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.3.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 15.2.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 5.4.3 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_app_badge 2.0.2 [flutter]
- flutter_file_dialog 3.0.2 [flutter]
- flutter_image_compress 2.4.0 [flutter flutter_image_compress_platform_interface flutter_image_compress_common flutter_image_compress_web flutter_image_compress_macos flutter_image_compress_ohos]
- flutter_pdfview 1.4.0+1 [flutter]
- grouped_list 6.0.0 [flutter]
- hand_signature 3.0.3 [flutter]
- html 0.15.4 [csslib source_span]
- image_editor 1.6.0 [flutter image_editor_platform_interface image_editor_common image_editor_ohos]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_review 2.0.10 [flutter in_app_review_platform_interface]
- intercom_flutter 9.2.9 [flutter flutter_web_plugins intercom_flutter_platform_interface intercom_flutter_web]
- jiffy 6.3.2 [intl]
- modal_bottom_sheet 3.0.0 [flutter]
[REDACTED]
- open_file_platform_interface 1.0.3 [flutter plugin_platform_interface]
[REDACTED]
- permission_handler 12.0.0+1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- provider 6.1.5 [collection flutter nested]
- qr_flutter 4.1.0 [flutter qr]
- shake_flutter 17.1.0 [flutter path]
[REDACTED]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- [REDACTED][flutter [REDACTED] approov_service_flutter_httpclient cancellation_token cancellation_token_http json_annotation jiffy html]
- [REDACTED]0.0.1 [flutter [REDACTED] path_provider encrypt crypto pointycastle json_annotation]
- [REDACTED] 0.0.1 [flutter flutter_localizations [REDACTED] device_info_plus shared_preferences flutter_secure_storage flutter_custom_tabs url_launcher android_intent_plus path_provider open_file open_file_platform_interface share_plus connectivity_plus biometrics animations clock collection decimal equatable provider sliver_tools cupertino_icons cancellation_token easy_mask flutter_svg intl modal_bottom_sheet jiffy chart_sparkline fl_chart flutter_markdown dotted_border grouped_list get_it hand_signature cached_network_image flutter_html flutter_html_table html]
- [REDACTED] 0.0.1 [flutter decimal equatable html]
- [REDACTED] 4.11.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- build_runner 2.4.15 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web web_socket_channel yaml]
- fake_async 1.3.2 [clock collection]
- faker 2.2.0 [crypto]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- golden_toolkit 0.15.0 [flutter flutter_test meta]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math webdriver]
- mockito 5.4.6 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- [REDACTED] 0.0.1 [flutter [REDACTED] build_runner mockito]
- [REDACTED] 1.0.0 [clock faker [REDACTED] [REDACTED] build_runner]

transitive dependencies:
- _fe_analyzer_shared 82.0.0 [meta]
- _flutterfire_internals 1.3.54 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 7.4.4 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- android_intent_plus 5.3.0 [flutter platform meta]
- args 2.7.0
- asn1lib 1.6.4
- async 2.12.0 [collection meta]
- biometrics 0.0.1 [flutter flutter_plugin_android_lifecycle]
- boolean_selector 2.1.2 [source_span string_scanner]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.4 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.4 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.5 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- characters 1.4.0
- chart_sparkline 1.1.1 [flutter]
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- connectivity_plus 6.1.4 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.1.2 [typed_data]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.6 [typed_data]
- csslib 0.17.3 [source_span]
- dart_style 3.0.1 [analyzer args collection package_config path pub_semver source_span yaml]
- dbus 0.7.11 [args ffi meta xml]
- device_info_plus 11.4.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- device_info_plus_platform_interface 7.0.2 [flutter meta plugin_platform_interface]
- dotted_border 2.1.0 [flutter path_drawing]
- encrypt 5.0.3 [args asn1lib clock collection crypto pointycastle]
- enum_to_string 2.2.1
- extended_image_library 5.0.0 [crypto flutter http_client_helper js path path_provider web]
- ffi 2.1.4
- file 7.0.1 [meta path]
- file_selector_linux 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+4 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 4.3.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+11 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.22.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.8.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.6.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.10.5 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_remote_config_platform_interface 1.5.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.8.3 [_flutterfire_internals firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- fixnum 1.1.1
- fl_chart 0.71.0 [equatable flutter vector_math]
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_custom_tabs 2.4.0 [flutter flutter_custom_tabs_platform_interface flutter_custom_tabs_android flutter_custom_tabs_ios flutter_custom_tabs_web meta]
- flutter_custom_tabs_android 2.3.1 [flutter flutter_custom_tabs_platform_interface meta]
- flutter_custom_tabs_ios 2.4.0 [flutter flutter_custom_tabs_platform_interface meta]
- flutter_custom_tabs_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- flutter_custom_tabs_web 2.3.0 [flutter flutter_web_plugins flutter_custom_tabs_platform_interface meta url_launcher_web url_launcher_platform_interface]
- flutter_html 3.0.0-alpha.5 [html csslib collection numerus flutter]
- flutter_html_table 3.0.0-alpha.3 [flutter html flutter_html flutter_layout_grid]
- flutter_image_compress_common 1.0.6 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_macos 1.0.3 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_ohos 0.0.3 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_platform_interface 1.0.5 [flutter plugin_platform_interface cross_file]
- flutter_image_compress_web 0.1.5 [flutter flutter_web_plugins flutter_image_compress_platform_interface web]
- flutter_layout_grid 2.0.8 [flutter collection quiver]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_markdown 0.7.7 [flutter markdown meta path]
- flutter_plugin_android_lifecycle 2.0.28 [flutter]
- flutter_secure_storage 9.2.4 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_secure_storage_linux 1.2.3 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.1.3 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.1.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.2.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.1.2 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_svg 2.1.0 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- get_it 8.0.3 [async collection meta]
- glob 2.1.3 [async collection file path string_scanner]
- graphs 2.3.2 [collection]
- http 1.4.0 [async http_parser meta web]
- http_client_helper 3.0.0 [http]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- image_editor_common 1.2.0 [flutter image_editor_platform_interface]
- image_editor_ohos 0.0.9 [flutter image_editor_platform_interface]
- image_editor_platform_interface 1.1.0 [flutter platform plugin_platform_interface]
- image_picker_android 0.8.12+23 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.6 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+2 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+2 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.1 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_review_platform_interface 2.0.5 [flutter url_launcher plugin_platform_interface platform]
- intercom_flutter_platform_interface 2.0.2 [flutter plugin_platform_interface]
- intercom_flutter_web 1.1.5 [flutter flutter_web_plugins intercom_flutter_platform_interface uuid web]
- intl 0.19.0 [clock meta path]
- io 1.0.5 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.8 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- logger 2.5.0
- logging 1.3.0
- markdown 7.3.0 [args meta]
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- mime 2.0.0
- mutex 3.1.0
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- numerus 1.1.1
- octo_image 2.1.0 [flutter]
- open_file 3.5.10 [flutter open_file_android open_file_web open_file_ios open_file_mac open_file_windows open_file_linux open_file_platform_interface]
- open_file_android 1.0.6 [flutter open_file_platform_interface]
- open_file_ios 1.0.3 [flutter open_file_platform_interface]
- open_file_linux 0.0.5 [flutter ffi open_file_platform_interface]
- open_file_mac 1.0.3 [flutter open_file_platform_interface]
- open_file_web 0.0.4 [flutter flutter_web_plugins open_file_platform_interface web]
- open_file_windows 0.0.3 [flutter ffi open_file_platform_interface]
- package_config 2.2.0 [path]
- path 1.9.1
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.1.0 [meta vector_math]
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.17 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- pem 2.0.5 [petitparser]
- permission_handler_android 13.0.1 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.7 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+5 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.3.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.1.0 [meta collection]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.9.1 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 5.0.3 [file path platform]
- pub_semver 2.2.0 [collection]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.2 [meta]
- quiver 3.2.2 [matcher]
- rational 2.2.3
- rxdart 0.28.0
- share_plus 11.0.0 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- share_plus_platform_interface 6.0.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences 2.5.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.4.10 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.3 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 3.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- sliver_tools 0.2.12 [flutter]
- source_gen 2.0.0 [analyzer async build dart_style glob path pub_semver source_span yaml]
- source_span 1.10.1 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.2 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.1 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.5 [synchronized path meta]
- sqflite_darwin 2.4.2 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.12.1 [path]
- stream_channel 2.1.4 [async]
- stream_transform 2.1.1
- string_scanner 1.4.1 [source_span]
- sync_http 0.3.1
- synchronized 3.3.1
- term_glyph 1.2.2
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.2 [json_annotation]
- typed_data 1.4.0 [collection]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.3.16 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.3 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.4.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.4 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.18 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.16 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 14.3.1
- watcher 1.1.1 [async path]
- web 1.1.1
- web_socket 1.0.1 [web]
- web_socket_channel 3.0.3 [async crypto stream_channel web web_socket]
- webdriver 3.0.4 [matcher path stack_trace sync_http]
- webview_flutter_android 4.4.2 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.11.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.20.0 [flutter path webview_flutter_platform_interface]
- win32 5.12.0 [ffi]
- win32_registry 2.1.0 [ffi meta win32]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

```

</details>

### Additional context and comments

build.gradle (sensitive and identifiable info redacted)

```gradle
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id "com.google.gms.google-services"
    id "com.google.firebase.crashlytics"
}

android {
namespace = [REDACTED]
compileSdk = 35

compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
}

kotlinOptions {
    jvmTarget = JavaVersion.VERSION_17
}

defaultConfig {
    applicationId [REDACTED]
    minSdk = 24
    targetSdk = 34
    versionCode = flutterVersionCode.toInteger()
    versionName = flutterVersionName
    manifestPlaceholders.urlScheme = [REDACTED]
    manifestPlaceholders.siteHost = [REDACTED]
    buildConfigField([REDACTED])
    buildConfigField([REDACTED])
}

packaging {
    resources.excludes.add('META-INF/versions/9/OSGI-INF/MANIFEST.MF')
    resources.excludes.add('builddef.lst')
    resources.excludes.add('version.txt')
    resources.excludes.add('isoparser-default.properties')
}

buildFeatures {
    buildConfig true
}

buildReleaseTypes {
    [REDACTED]
}

productFlavours {
    [REDACTED]
}

flutter {
    source '../..'
}

dependencies {
    implementation "androidx.core:core-splashscreen:1.0.0"
    implementation "androidx.appcompat:appcompat:1.4.1"
    implementation platform('com.google.firebase:firebase-bom:28.2.0')
    implementation 'com.google.firebase:firebase-messaging'
}

}
```
