### ISSUE TITLE
[firebase_messaging] subscribeToTopic future never end

### ISSUE THREAD

**Issue by EArminjon** [firebase/flutterfire#17364]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

iOS

### Description

The `subscribeToTopic` future is never completed.

### Reproducing the issue

```dart
FirebaseMessaging _firebaseMessaging
print("Before");
await _firebaseMessaging.subscribeToTopic('test');
print("After);
```

### Firebase Core version

3.13.0

### Flutter Version

3.19.3

### Relevant Log Output

```shell
No log
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
  cloud_firestore: 5.6.7
  firebase_analytics: 11.4.5
  firebase_auth: 5.5.3
  firebase_core: 3.13.0
  firebase_crashlytics: 4.3.5
  firebase_storage: 12.4.5
  firebase_remote_config: 5.4.3
  firebase_messaging: 15.2.5
```

</details>
