### ISSUE TITLE
[firebase_core][firebase_messaging]: HTTP Client Error with status code: 500

### ISSUE THREAD

**Issue by mishkov** [firebase/flutterfire#17370]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core, Messaging

### Which platforms are affected?

iOS

### Description

From the Sentry reports I see a lot of errors like "HTTP Client Error with status code: 500". No user complaints have been reported, suggesting the error occurs silently, but it still needs to be fixed. The issue affects only Apple iPhone devices across all iOS versions. Over the last 90 days, approximately 4,000 error events have impacted 1,500 users. Sentry confirms that VPN is not being used. Here are the most frequently affected URLs:
- 79% https://www.googleapis.com/experimentsandconfigs/v1/getExperimentsAndConfigs
- 20% https://www.google.com/maps/vt/proto
- other URLs account for less than 1 percent

## Last time the error occurred

Below I will detail the one of the most recent occurrence of the 500 status code error

date and time of error: May 6, 2025 - 05:54:02.215 AM (UTC)

Prior to the error, I observed the application making requests to other endpoints, as shown in the screenshot below (this pattern is consistent across most instances)

<img width="1067" alt="Image" src="https://github.com/user-attachments/assets/cf742d29-03a0-4480-874d-08cd94996f39" />

Thread stack trace

```
CFNetwork 0x18e9b0adc -[__NSCFLocalSessionTask _onqueue_suspend]
CFNetwork 0x18e98d3a0 -[__NSCFLocalDataTask _onqueue_didReceiveRespo
CFNetwork 0x18ea08e64 __67-[__NSCFLocalSessionTask connection:didRece
CFNetwork 0x18ea08d90 -[__NSCFLocalSessionTask connection:didReceiveR
CFNetwork 0x18ea08c40 __59-[__NSCFURLLocalSessionConnection _sendRe
CFNetwork 0x18ea07824 -[__NSCFURLLocalSessionConnection withDelegate
CFNetwork 0x18ea09034 -[__NSCFURLLocalSessionConnection _didReceiveR
CFNetwork 0x18ea0c300 -[__NSCFURLLocalSessionConnection _tick_sniffNow
CFNetwork 0x18ea07578 -[__NSCFURLLocalSessionConnection _tick]
CFNetwork 0x18ea073fc -[__NSCFURLLocalSessionConnection _didReceiveDa
CFNetwork 0x18ea071e4 SessionConnectionLoadable::_loaderClientEvent_Did
CFNetwork 0x18ea0715c URLConnectionLoader::protocolDidLoadData
CFNetwork 0x18ea070d4 SessionConnectionLoadable::withLoaderClientAsync
libdispatch 0x1951d52e4 _dispatch_block_async_invoke2
libdispatch 0x1951c60cc _dispatch_client_callout
libdispatch 0x1951cd6d4 _dispatch_lane_serial_drain
libdispatch 0x1951ce210 _dispatch_lane_invoke
libdispatch 0x1951d9254 _dispatch_root_queue_drain_deferred_wlh
libdispatch 0x1951d8aa0 _dispatch_workloop_worker_thread
libsystem_pthread 0x2159cfc78 _pthread_wqthread
libsystem_pthread 0x2159cc484 start_wqthread
```

Also sentry shows following curl

```
curl \
-X POST \
--compressed \
-H "Accept: */*" \
-H "Accept-Encoding: gzip, deflate, br" \
-H "Accept-Language: ru" \
-H "Baggage: sentry-environment=production,sentry-public_key=691fc052b801443f9
-H "Content-Encoding: gzip" \
-H "Content-Length: 203" \
-H "Content-Type: application/x-protobuf" \
-H "Sentry-Trace: fd510853b82a4c338800182f5bccaafe-a9e4456c14444e9f-0" \
-H "User-Agent: by.allsports.holder/2.0.18 iPhone/18.1.1 hw/iPhone14_5" \
"https://www.googleapis.com/experimentsandconfigs/v1/getExperimentsAndConfigs
```

### Reproducing the issue

Not sure how to reproduce

### Firebase Core version

^2.4.0 (in pubspec.lock: both 2.7.1 & 2.32.0)

### Flutter Version

3.3.10 & 3.22.2

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> for latest version of my app where the error occurs</summary>
<br>

```yaml


  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ The Google Privacy Policy describes how data is handled in this service.   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ║                                                                            ║
  ║ To disable animations in this tool, use                                    ║
  ║ 'flutter config --no-cli-animations'.                                      ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Dart SDK 3.4.3
Flutter SDK 3.22.2
holder_app 2.0.21+400

dependencies:
- appmetrica_plugin 1.4.0 [flutter stack_trace logging decimal]
- auto_route 7.9.2 [flutter path collection meta]
- background_fetch 1.3.7 [flutter]
- basic_utils 5.7.0 [http logging json_annotation pointycastle]
- cached_network_image 3.4.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- connectivity_plus 6.1.2 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- cupertino_icons 1.0.8
- defer_pointer 0.0.2 [flutter equatable]
- device_info_plus 10.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]
- dio 5.8.0+1 [async collection http_parser meta path dio_web_adapter]
- dio_cache_interceptor 3.5.1 [dio uuid string_scanner]
- dio_cache_interceptor_hive_store 3.2.2 [dio_cache_interceptor hive]
- dio_cookie_manager 3.1.1 [cookie_jar dio]
- dio_http2_adapter 2.5.3 [dio http2 meta]
- encrypt 5.0.3 [args asn1lib clock collection crypto pointycastle]
- envied 0.5.4+1
- equatable 2.0.5 [collection meta]
- firebase_analytics 10.10.7 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.32.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.7.10 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- floor 1.5.0 [collection floor_annotation floor_common flutter meta path sqflite sqflite_common_ffi sqflite_common_ffi_web sqlparser]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.6 [bloc flutter provider]
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_flavorizr 2.2.3 [flutter archive args checked_yaml collection image io json_annotation sprintf xml yaml]
- flutter_local_notifications 17.2.3 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_map 6.1.0 [async collection flutter http latlong2 logger meta polylabel proj4dart vector_math]
- flutter_map_cache 1.5.1 [dio dio_cache_interceptor flutter flutter_map]
- flutter_map_location_marker 8.0.8 [flutter flutter_compass flutter_map geolocator latlong2]
- flutter_map_supercluster 5.0.0-dev.1 [async equatable flutter flutter_map flutter_map_marker_popup latlong2 provider supercluster]
- flutter_popup 3.3.4 [flutter]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_widget_from_html_core 0.15.2 [csslib flutter html logging]
- geojson_vi 2.2.3
- geolocator 11.1.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get_it 7.7.0 [async collection meta]
- google_api_availability 5.0.0 [flutter google_api_availability_android google_api_availability_platform_interface]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- huawei_hmsavailability 6.12.0+300 [flutter]
- huawei_push 6.12.0+302 [flutter]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.19.0 [clock meta path]
- latlong2 0.9.1 [intl]
- location 5.0.3 [flutter location_platform_interface location_web]
- logging 1.2.0
- mask_text_input_formatter 2.9.0 [flutter]
- material_symbols_icons 4.2785.1 [flutter]
- meta 1.12.0
- mobile_scanner 4.0.1 [flutter flutter_web_plugins js]
- modal_bottom_sheet 3.0.0 [flutter]
- native_flutter_proxy 0.1.15 [flutter]
- no_screenshot 0.3.1 [flutter plugin_platform_interface]
- package_info_plus 6.0.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32]
- path 1.9.0
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- provider 6.1.2 [collection flutter nested]
- punycode 1.0.0
- qr_flutter 4.1.0 [flutter qr]
- quiver 3.2.2 [matcher]
- sentry_flutter 8.14.2 [flutter flutter_web_plugins sentry package_info_plus meta ffi file collection]
- shared_preferences 2.2.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- skeletonizer 1.4.2 [collection flutter]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.1 [crypto sprintf meta fixnum]

dev dependencies:
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- app_error_lints 1.0.0 [analyzer analyzer_plugin custom_lint_builder]
- args 2.5.0
- auto_route_generator 7.3.2 [build source_gen analyzer path build_runner code_builder dart_style xml args glob auto_route]
- bloc_test 9.1.7 [bloc diff_match_patch meta mocktail test]
- build_runner 2.4.9 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- collection 1.18.0
- custom_lint 0.6.4 [analyzer analyzer_plugin args async ci cli_util collection custom_lint_core freezed_annotation json_annotation meta package_config path pub_semver pubspec_parse rxdart uuid yaml]
- envied_generator 0.5.4+1 [envied build code_builder dart_style source_gen analyzer recase equatable]
- floor_generator 1.5.0 [analyzer build build_config code_builder collection floor_annotation meta source_gen strings]
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- http 1.2.2 [async http_parser meta web]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math webdriver]
- mockito 5.4.4 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- patrol 3.8.0 [equatable flutter flutter_test http json_annotation meta patrol_finders shelf test_api]
- patrol_cli 2.7.0 [adb ansi_styles args ci cli_completion collection dispose_scope equatable file glob http mason_logger meta path platform process pub_updater uuid version yaml]
- qr_code_vision 0.1.2 [image collection dart_reed_solomon_nullsafety equatable]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.35 [collection firebase_core firebase_core_platform_interface flutter meta]
- adb 0.3.0
- analyzer_plugin 0.11.3 [analyzer collection dart_style pub_semver yaml]
- animated_stack_widget 0.0.4 [flutter]
- ansi_styles 0.3.2+1
- archive 3.6.1 [crypto path]
- asn1lib 1.5.5
- async 2.11.0 [collection meta]
- bloc 8.1.4 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- charcode 1.3.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- ci 0.1.0
- cli_completion 0.4.0 [args equatable mason_logger meta path]
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cookie_jar 4.0.8 [meta universal_io]
- coverage 1.11.1 [args glob logging meta package_config path source_maps stack_trace vm_service]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- custom_lint_builder 0.6.4 [analyzer analyzer_plugin collection custom_lint custom_lint_core glob hotreloader meta package_config path pubspec_parse rxdart]
- custom_lint_core 0.6.3 [analyzer analyzer_plugin collection glob matcher meta package_config path pubspec_parse source_span yaml]
- dart_reed_solomon_nullsafety 0.2.0
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- decimal 2.3.3 [rational]
- dev_build 1.0.0+3 [collection process_run pub_semver yaml path meta pool args synchronized]
- device_info_plus_platform_interface 7.0.2 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- dio_web_adapter 2.0.0 [dio http_parser meta web]
- dispose_scope 2.1.0 [meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.0 [meta path]
- file_selector_linux 0.9.3 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.10.8 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.7+7 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.3.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.5 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_messaging_platform_interface 4.5.37 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.18 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.1.0
- floor_annotation 1.5.0 [meta]
- floor_common 1.5.0 [collection floor_annotation meta path sqflite_common sqlparser]
- flutter_compass 0.8.0 [flutter]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math]
- flutter_local_notifications_linux 4.0.1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.2.0 [flutter plugin_platform_interface]
- flutter_map_marker_popup 6.1.2 [flutter animated_stack_widget flutter_map latlong2 provider]
- flutter_plugin_android_lifecycle 2.0.19 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- frontend_server_client 3.2.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- geolocator_android 4.6.1 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.4 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 3.0.0 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.2.3 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- google_api_availability_android 1.0.1 [flutter google_api_availability_platform_interface]
- google_api_availability_platform_interface 1.0.1 [flutter plugin_platform_interface meta]
- graphs 2.3.1 [collection]
- hive 2.2.3 [meta crypto]
- hotreloader 4.3.0 [collection logging path stream_transform vm_service watcher]
- html 0.15.4 [csslib source_span]
- http2 2.3.0
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.2.0 [archive meta xml]
- image_picker_android 0.8.12+1 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.5 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.9.0 [meta]
- kdbush 0.1.0
- leak_tracker 10.0.4 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.3 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 2.1.1
- lists 1.0.1 [meta]
- location_platform_interface 3.1.2 [flutter plugin_platform_interface]
- location_web 4.2.0 [flutter flutter_web_plugins http_parser js location_platform_interface]
- logger 2.4.0
- mason_logger 0.2.16 [ffi io win32]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- mgrs_dart 2.0.0 [unicode]
- mime 1.0.6
- mocktail 1.0.4 [collection matcher test_api]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- node_preamble 2.0.2
- octo_image 2.1.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.10 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- patrol_finders 2.1.2 [flutter flutter_test meta]
- permission_handler_android 12.0.12 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.5 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+2 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.2.3 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.9.1 [collection convert js]
- polylabel 1.0.1 [collection]
- pool 1.5.1 [async stack_trace]
- process 5.0.2 [file path platform]
- process_run 1.0.1 [path collection string_scanner yaml meta args pub_semver synchronized]
- proj4dart 2.1.0 [mgrs_dart wkt_parser meta]
- pub_semver 2.1.4 [collection meta]
- pub_updater 0.4.0 [http json_annotation process pub_semver]
- pubspec_parse 1.3.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.1 [meta]
- rational 2.2.3
- rbush 1.1.1
- recase 4.1.0
- rxdart 0.27.7
- sentry 8.14.2 [http meta stack_trace uuid collection]
- shared_preferences_android 2.2.2 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.3 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.1 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.3 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_map_stack_trace 2.1.2 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.3+1 [flutter sqflite_common path]
- sqflite_common 2.5.4 [synchronized path meta]
- sqflite_common_ffi 2.3.3 [sqlite3 sqflite_common synchronized path meta]
- sqflite_common_ffi_web 0.4.3+1 [path sqflite_common_ffi sqflite_common sqlite3 http web synchronized process_run dev_build pub_semver args meta]
- sqlite3 2.4.5 [collection ffi meta path web]
- sqlparser 0.34.1 [meta collection source_span charcode]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- strings 3.1.2 [characters unicode]
- supercluster 3.1.0 [freezed_annotation kdbush rbush uuid]
- sync_http 0.3.1
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test 1.25.2 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]
- test_api 0.7.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.6.0 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- timezone 0.9.4 [path]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- unicode 0.3.1 [lists]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.3.2 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.2 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- version 3.0.2
- vm_service 14.2.1
- watcher 1.1.0 [async path]
- web 0.5.1
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webdriver 3.0.3 [matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.2.1 [logging]
- win32 5.5.4 [ffi]
- win32_registry 1.1.5 [ffi win32]
- wkt_parser 2.0.0
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

### Why I included 2 versions of plugin and Flutter?

Because from the Sentry I see that the error occurs with multiple firebase_core/Flutter versions

### Did I tried to reach out the support of Firebase?

I know that this repo already contains similar [issue](https://github.com/firebase/flutterfire/issues/11333) and there was recommended to reach out the Firebase support. I reached but it didn't help

<details>
<summary>Firebase support response</summary>
<br>
Hi Nikita,

My name is Yel, and I'll be handling this case.

After some investigation with the team, we have confirmed that the particular APIs/URLs you have shared are not owned or maintained by Remote Config or Firebase. These logs appear to be an API may be an internal one used by Google Play Store or Play Services, as subsequent calls are directed to [play.googleapis.com](https://play.googleapis.com/). Given that, I suggest reaching out to the Google Play team through their [support channel](https://support.google.com/googleplay/?hl=en#topic=3364260), as they have the appropriate tools and knowledge to guide you on this matter. They should be able to shed light on the behavior of this API.

Hope you understand. Should you have any other Firebase questions or issues, please reach out to us again via our [support channel](https://firebase.google.com/support/).

Sincerely,
Yel
</details>

Shortly, they redirected me to the Google Play team but google play team say

<details>
<summary>Google Play team conversation</summary>
<br>
Hi Nikita,

Thank you for writing back to Google support.

We at Google play store app support only deals with the issues like app installations, purchases and  Gift cards and any issues faced by the users with the apps downloaded from Google play store app.

Could you please confirm, 
Are you looking for assistance from Google play store app support or Google play console ( developer support)?

Awaiting your response.

If you have any further questions, you can reply to this email or reach us through our [Help Center](http://support.google.com/).

Within 48 hours of our last interaction, you may receive a short survey through email. We’d love to hear your feedback about our interaction today and your overall experience with Google support.

Thanks!
Robbin W
The Google Support Team

---
Hi Robbin,
 
Thank you for your reply.
 
Yes, it looks like I'm looking for assistance from Google play console (developer support).

Thanks!
Nikita M

---

Hi Nikita,

Thank you for writing back to Google support.

Our team currently supports Google Play end users and deals with issues like app installations, purchases and Gift cards.

To get the best developer support, please go to the [Play Developer site](https://support.google.com/googleplay/android-developer/#topic=3450769&contact=1).

I hope this helps.

If you have any further questions, you can reply to this email or reach us through our [Help Center](http://support.google.com/).

Within 48 hours of our last interaction, you may receive a short survey through email. We’d love to hear your feedback about our interaction today and your overall experience with Google support.

Thanks!
Robbin W
The Google Support Team

</details>

I have filled the form https://support.google.com/googleplay/android-developer/#topic=3450769&contact=1 but again no result

<details>
<summary>Google Play Developer Support response</summary>
<br>
Hi Nikita,
Thanks for contacting Google Play Developer Support.

I’m happy to answer any questions about managing your apps on the Play Console. However, our team isn’t trained to provide technical support for app development questions.

For help developing Android apps, I recommend using our [Android Developers site](http://developer.android.com/). The site has technical documentation, the Android SDK, and tips for distributing your apps.

To help troubleshoot the issue further, I recommend using bug reports and logs.

You can capture a bug report by following the steps in our [Android Developers site](https://developer.android.com/studio/debug/bug-report). Once the report is complete, it will save as a ZIP file.

For log reporting, you can use the Android logging system which provides a mechanism for collecting and viewing system debug output.

To extract the logs you will need to use "logcat" command as an adb command or directly in a shell prompt of your emulator or connected device:

adb logcat -v time > applog.txt

In addition to that, most third parties have community forums available through their official website, plus we have our Developer Support communities listed in the [Android Developers site](http://developer.android.com/support.html).

Please don't hesitate to reply to this email if you need further assistance. We're happy to help. If we do not hear from you, we will consider the matter closed.

Regards,
Scarlet 
Google Play Developer Support

See [tips](https://support.google.com/googleplay/android-developer/answer/2543765) on how to protect yourself from email scams.

Did you know we offer chat support in English? You can [chat with us](https://support.google.com/googleplay/android-developer/?hl=en#contact=1) Monday through Friday, 12 a.m. to 12 a.m. Greenwich Time (GMT).
</details>
