### ISSUE TITLE
[cloud_firestore]: Random PlatformException error on first start

### ISSUE THREAD

**Issue by proninyaroslav** [firebase/flutterfire#17394]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Database

### Which platforms are affected?

Android

### Description

I'm using `getStream()` to listen to a document in the my `bloc` instance (`MyAppWidget`). The error occurs randomly when the app is first launched in the release mode: 

`PlatformException(channel-error, Unable to establish connection on channel., null, null)`. 

Moreover, restarting the app or killing the process doesn't help to get rid this error, only **reinstalling** the app itself.

Here's an example of how I listen to it:
```Dart
class AppCubit extends Cubit<AuthState> {
  final CollectionReference _collection;
 StreamSubscription? _streamSubscription;

  AppCubit(FirebaseFirestore firestore): 
     _accounts = firestore.collection('my_collection').withConverter(...);

  @override
  Future<void> close() {
    _streamSubscription?.cancel();
    return super.close();
  }

  void listen()  {
    if (_streamSubscription != null) {
      return;
    }

    _streamSubscription = _collection.snapshots().map((snapshop) => snapshop.data()).listen((
          data,
        ) {
          ...
        })..onError((e, stackTrace) {
          log.e('Unable to get data', error: e, stackTrace: stackTrace);
          emit(AppState.error(e));
        });
  }
}
```

### Reproducing the issue

1. Build the app in release mode
2. Freshly install on the device
3. Run the app
4. Randomly get an error

### Firebase Core version

3.13.0

### Flutter Version

3.32.0

### Relevant Log Output

```shell
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(channel-error, Unable to establish connection on channel., null, null)
       at FirebaseFirestoreHostApi.documentReferenceSnapshot(messages.pigeon.dart:1299)
       at MethodChannelDocumentReference.snapshots.<fn>(method_channel_document_reference.dart:123)
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.8.0
Flutter SDK 3.32.0

dependencies:
- auto_route 10.1.0 [flutter path web collection meta]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cloud_firestore 5.6.8 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- collection 1.19.1
- connectivity_plus 6.1.4 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- crypto 3.0.6 [typed_data]
- cupertino_icons 1.0.8
- dio 5.8.0+1 [async collection http_parser meta path dio_web_adapter]
- expandable_page_view 1.0.17 [flutter]
- firebase_analytics 11.4.6 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_installations 0.3.2+6 [firebase_app_installations_platform_interface firebase_app_installations_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.13.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.3.6 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_remote_config 5.4.4 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 9.1.1 [bloc flutter provider]
- flutter_dotenv 5.2.1 [flutter]
- flutter_form_builder 10.0.1 [flutter intl]
- flutter_html 3.0.0 [html csslib collection list_counter flutter]
- flutter_inappwebview 6.1.5 [flutter flutter_inappwebview_platform_interface flutter_inappwebview_android flutter_inappwebview_ios flutter_inappwebview_macos flutter_inappwebview_web flutter_inappwebview_windows]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_multi_formatter 2.13.7 [flutter collection base58check bech32]
- flutter_svg 2.1.0 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- form_builder_validators 11.1.2 [flutter flutter_localizations intl]
- freezed_annotation 3.0.0 [collection json_annotation meta]
- get_it 8.0.3 [async collection meta]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- injectable 2.5.0 [get_it meta]
- intl 0.20.2 [clock meta path]
- json_annotation 4.9.0 [meta]
- just_audio 0.10.3 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter synchronized]
- logger 2.5.0
- path 1.9.1
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- sembast 3.8.5+1 [meta path synchronized]
- shimmer_animation 2.2.2 [flutter]
- typed_data 1.4.0 [collection]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- auto_route_generator 10.1.0 [build source_gen analyzer path build_runner code_builder dart_style glob auto_route]
- bloc_test 10.0.0 [bloc diff_match_patch meta mocktail test]
- build_runner 2.4.15 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web web_socket_channel yaml]
- fake_cloud_firestore 3.1.0 [flutter cloud_firestore cloud_firestore_platform_interface collection plugin_platform_interface quiver rxdart mock_exceptions fake_firebase_security_rules rx equatable clock]
- flutter_lints 6.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- freezed 3.0.6 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- injectable_generator 2.7.0 [build source_gen path glob analyzer code_builder dart_style injectable collection recase meta]
- json_serializable 6.9.5 [analyzer async build build_config collection dart_style json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mocktail 1.0.4 [collection matcher test_api]

transitive dependencies:
- _fe_analyzer_shared 82.0.0 [meta]
- _flutterfire_internals 1.3.55 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 7.4.5 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- antlr4 4.13.2 [logging collection]
- args 2.7.0
- async 2.13.0 [collection meta]
- audio_session 0.2.2 [flutter flutter_web_plugins rxdart meta]
- base58check 2.0.0 [crypto collection]
- bech32 0.2.2 [convert]
- bloc 9.0.0 [meta]
- boolean_selector 2.1.2 [source_span string_scanner]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.4 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.4 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.10.1 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- cel 0.5.3 [antlr4 collection equatable]
- characters 1.4.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_config 0.2.0 [args yaml]
- clock 1.1.2
- cloud_firestore_platform_interface 6.6.8 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.4.8 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.1.2 [typed_data]
- coverage 1.14.0 [args cli_config glob logging meta package_config path pubspec_parse source_maps stack_trace vm_service]
- csslib 1.0.2 [source_span]
- dart_style 3.1.0 [analyzer args collection package_config path pub_semver source_span yaml]
- dbus 0.7.11 [args ffi meta xml]
- diff_match_patch 0.4.1
- dio_web_adapter 2.1.1 [dio http_parser meta web]
- equatable 2.0.7 [collection meta]
- fake_async 1.3.3 [clock collection]
- fake_firebase_security_rules 0.5.3 [antlr4 cel equatable logger tuple]
- ffi 2.1.4
- file 7.0.1 [meta path]
- firebase_analytics_platform_interface 4.3.6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+12 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_app_installations_platform_interface 0.1.4+54 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_installations_web 0.1.6+12 [_flutterfire_internals firebase_app_installations_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.23.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.8.6 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_platform_interface 1.5.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.8.4 [_flutterfire_internals firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- fixnum 1.1.1
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_inappwebview_android 1.1.3 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_internal_annotations 1.2.0
- flutter_inappwebview_ios 1.1.2 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_macos 1.1.2 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_platform_interface 1.3.0+1 [flutter flutter_inappwebview_internal_annotations plugin_platform_interface]
- flutter_inappwebview_web 1.1.2 [flutter flutter_web_plugins web flutter_inappwebview_platform_interface]
- flutter_inappwebview_windows 0.6.0 [flutter flutter_inappwebview_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.3 [async collection file path string_scanner]
- graphs 2.3.2 [collection]
- html 0.15.6 [csslib source_span]
- http 1.4.0 [async http_parser meta web]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- io 1.0.5 [meta path string_scanner]
- js 0.7.2
- just_audio_platform_interface 4.5.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.16 [just_audio_platform_interface flutter flutter_web_plugins web synchronized]
- leak_tracker 10.0.9 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 6.0.0
- list_counter 1.0.2
- logging 1.3.0
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- mime 2.0.0
- mock_exceptions 0.8.2 [matcher]
- more 4.5.0 [characters clock collection meta]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- node_preamble 2.0.2
- octo_image 2.1.0 [flutter]
- package_config 2.2.0 [path]
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.17 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.1.0 [meta collection]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- provider 6.1.5 [collection flutter nested]
- pub_semver 2.2.0 [collection]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.2 [matcher]
- recase 4.1.0
- rx 0.4.0 [collection matcher meta more]
- rxdart 0.28.0
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.3 [convert http_parser mime path shelf]
- shelf_web_socket 3.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- source_gen 2.0.0 [analyzer async build dart_style glob path pub_semver source_span yaml]
- source_helper 1.3.5 [analyzer collection source_gen]
- source_map_stack_trace 2.1.2 [path source_maps stack_trace]
- source_maps 0.10.13 [source_span]
- source_span 1.10.1 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.2 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.1 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.5 [synchronized path meta]
- sqflite_darwin 2.4.2 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.12.1 [path]
- stream_channel 2.1.4 [async]
- stream_transform 2.1.1
- string_scanner 1.4.1 [source_span]
- synchronized 3.3.1
- term_glyph 1.2.2
- test 1.25.15 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.6.8 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- timing 1.0.2 [json_annotation]
- tuple 2.0.2
- url_launcher_android 6.3.16 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.3 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.4.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.4 [flutter url_launcher_platform_interface]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- vector_graphics 1.1.18 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.17 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 15.0.0
- watcher 1.1.1 [async path]
- web 1.1.1
- web_socket 1.0.1 [web]
- web_socket_channel 3.0.3 [async crypto stream_channel web web_socket]
- webkit_inspection_protocol 1.2.1 [logging]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

```

</details>
