### ISSUE TITLE
[firebase_auth]: Operation hangs/disappear if not directly returned from the sign in view

### ISSUE THREAD

**Issue by AlexV525** [firebase/flutterfire#17393]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android

### Description

When leaving the sign-in flow without completing it or dismissing it, the operation will never end or disappear, and unable to cancel.

### Reproducing the issue

1. Using the example: https://github.com/firebase/flutterfire/tree/main/packages/firebase_auth/firebase_auth/example
2. Sign in with federated providers.
3. When the web tab/page opens, return to the home screen directly without using the back button or any back gestures.
4. Entering the recent tasks view
    1. If the auth is opening in a separate task, like in Chrome, enter Chrome, then press the back button.
    2. If the auth is opening as an in-app-webview, the task will disappear.
5. Returning to the app, the auth call hangs, and no way to cancel the previous.

### Firebase Core version

3.13.1

### Flutter Version

3.32.0

### Relevant Log Output

```shell
N/A
```

### Flutter dependencies

<details open>

```yaml
dependencies:
- firebase_auth 5.5.4
- firebase_core 3.13.1

transitive dependencies:
- firebase_auth_platform_interface 7.6.3
- firebase_auth_web 5.14.3
- firebase_core_platform_interface 5.4.0
- firebase_core_web 2.23.0
```

</details>

### Additional context and comments

The screen record for the example:

https://github.com/user-attachments/assets/b8255656-fb66-4134-985b-714eded0bcdf

The screen record for our production app:

https://github.com/user-attachments/assets/dcf6b46d-ca37-46b0-8fbd-5a65793c23c6

Also, I was wondering why the example has a different behavior when opening the auth page: the example launches the Chrome web page, while our app launches an in-app-browser view.
