### ISSUE TITLE
[firebase_data_connect]: Execute function is giving INVALID_ARGUMENT for no apparent reason

### ISSUE THREAD

**Issue by gabrielglbh** [firebase/flutterfire#17414]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

Web

### Description

**Expected**:

I have a query for getting and creating an user like so:

```
query GetUser @auth(level: USER) {
  user(first: { where: { auth: { eq_expr: "auth.uid" } } }) {
    auth
    email
    hasSeenTutorial
    balance
  }
}

mutation CreateUser($email: String!) @auth(level: PUBLIC) {
  user_insert(data: { email: $email })
}
```

where the schema is:

```
type User @table(key: "auth") {
  auth: String! @default(expr: "auth.uid")
  email: String!
  hasSeenTutorial: Boolean! @default(value: false)
  balance: Float! @default(value: 0)
}
```

When calling this query like the one below I am expecting it to fallback to the try clause and give an existing user in the database.

```
try {
      final queryResult = await _ginanceConnector.getUser().execute();
      return queryResult.data.user?.toDomain();
    } catch (err) {
      return null;
    }
```

When performing controlled tests in the Supervision console, the data query actually retrieves the user, so the user exists. The mutation also works.

**What actually happens**:

When the base code executes the `_ginanceConnector.getUser().execute()`, it falls back to the catch clause with an:

```
{ "error": { "code": 400, "message": "Request contains an invalid argument.", "status": "INVALID_ARGUMENT" } }
```

This error also pops up when executing `_ginanceConnector.createUser("test@test.com").execute()`.

### Reproducing the issue

1. Set up a basic web project for Flutter
2. Connect it to Firebase Auth and Data Connect 
3. Create a schema like: `type User @table(key: "auth") {
  auth: String! @default(expr: "auth.uid")
  email: String!
  hasSeenTutorial: Boolean! @default(value: false)
  balance: Float! @default(value: 0)
}`
4. Create a mutation like: `mutation CreateUser($email: String!) @auth(level: PUBLIC) {
  user_insert(data: { email: $email })
}`
5. Create a query like: `query GetUser @auth(level: USER) {
  user(first: { where: { auth: { eq_expr: "auth.uid" } } }) {
    auth
    email
    hasSeenTutorial
    balance
  }
}`
6. Create a basic login with email and password: when the user is authenticated, apply the mutation to create the user, and then retrieve the user with the query.

### Firebase Core version

3.13.1

### Flutter Version

3.27.1

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.6.0
Flutter SDK 3.27.1
ginances 1.3.3

dependencies:
- auto_route 10.1.0+1 [flutter path web collection meta]
- fade_shimmer 2.4.0 [flutter]
- firebase_auth 5.5.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.13.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_data_connect 0.1.5 [firebase_app_check firebase_auth firebase_core firebase_core_platform_interface flutter grpc http intl protobuf]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 9.1.1 [bloc flutter provider]
- flutter_launcher_icons 0.14.3 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 5.0.0 [lints]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_markdown 0.7.7+1 [flutter markdown meta path]
- flutter_native_splash 2.4.4 [args flutter flutter_web_plugins html image meta path universal_io xml yaml ansicolor]
- freezed 3.0.6 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- freezed_annotation 3.0.0 [collection json_annotation meta]
- get_it 8.0.3 [async collection meta]
- injectable 2.5.0 [get_it meta]
- intl 0.19.0 [clock meta path]
- package_info_plus 8.3.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- pdf 3.11.3 [archive barcode bidi crypto image meta path_parsing vector_math xml]
- shimmer 3.0.0 [flutter]
- syncfusion_flutter_charts 29.1.38 [flutter intl vector_math syncfusion_flutter_core]
- uuid 4.5.1 [crypto sprintf meta fixnum]

dev dependencies:
- auto_route_generator 10.0.1 [build source_gen analyzer path build_runner code_builder dart_style xml args glob package_config auto_route]
- build_runner 2.4.15 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- injectable_generator 2.7.0 [build source_gen path glob analyzer code_builder dart_style injectable collection recase meta]
- json_serializable 6.9.5 [analyzer async build build_config collection dart_style json_annotation meta path pub_semver pubspec_parse source_gen source_helper]

transitive dependencies:
- _fe_analyzer_shared 82.0.0 [meta]
- _flutterfire_internals 1.3.55 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 7.4.5 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- ansicolor 2.0.3
- archive 3.6.1 [crypto path]
- args 2.7.0
- async 2.11.0 [collection meta]
- barcode 2.2.9 [meta qr]
- bidi 2.0.13
- bloc 9.0.0 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.4 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.4 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.10.1 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.2 [meta path]
- clock 1.1.1
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- collection 1.19.0
- convert 3.1.2 [typed_data]
- crypto 3.0.6 [typed_data]
- csslib 1.0.2 [source_span]
- dart_style 3.0.1 [analyzer args collection package_config path pub_semver source_span yaml]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.1 [meta path]
- firebase_app_check 0.3.2+6 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check_platform_interface 0.1.1+6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.2.0+10 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
- firebase_auth_platform_interface 7.6.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.14.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.23.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- fixnum 1.1.1
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.3 [async collection file path string_scanner]
- google_identity_services_web 0.3.3+1 [meta web]
- googleapis_auth 1.6.0 [args crypto google_identity_services_web http http_parser]
- graphs 2.3.2 [collection]
- grpc 3.2.4 [archive async crypto fixnum googleapis_auth meta http http2 protobuf clock]
- html 0.15.6 [csslib source_span]
- http 1.4.0 [async http_parser meta web]
- http2 2.3.1
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- image 4.3.0 [archive meta xml]
- io 1.0.5 [meta path string_scanner]
- js 0.7.1
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.1
- logging 1.3.0
- markdown 7.3.0 [args meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 2.0.0
- nested 1.0.0 [flutter]
- package_config 2.2.0 [path]
- package_info_plus_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_parsing 1.1.0 [meta vector_math]
- petitparser 6.0.2 [meta]
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- protobuf 3.1.0 [collection fixnum meta]
- provider 6.1.5 [collection flutter nested]
- pub_semver 2.2.0 [collection]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.2 [meta]
- recase 4.1.0
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 3.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- source_gen 2.0.0 [analyzer async build dart_style glob path pub_semver source_span yaml]
- source_helper 1.3.5 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.12.0 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.1
- string_scanner 1.3.0 [source_span]
- syncfusion_flutter_core 29.1.38 [vector_math flutter]
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.2 [json_annotation]
- typed_data 1.4.0 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- vector_math 2.1.4
- vm_service 14.3.0
- watcher 1.1.1 [async path]
- web 1.1.1
- web_socket 1.0.1 [web]
- web_socket_channel 3.0.3 [async crypto stream_channel web web_socket]
- win32 5.10.1 [ffi]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

```

</details>

### Additional context and comments

Saturday morning was working perfectly and all of a sudden in the afternoon, it broke, while the base code was not modified at all for 4 days.
