### ISSUE TITLE
[firebase_crashlytics]: dSYM files needed after following the setups

### ISSUE THREAD

**Issue by Hamlet626** [firebase/flutterfire#17429]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

iOS

### Description

I just followed the setup guide here(https://firebase.google.com/docs/crashlytics/get-started?platform=flutter) for flutter, but it shows below after any Exception occurs.

![Image](https://github.com/user-attachments/assets/821b952f-276c-4601-8dfc-82d3a891bb3a)

### Reproducing the issue

SetUp by https://firebase.google.com/docs/crashlytics/get-started?platform=flutter.
I'm using:

  firebase_core: ^3.14.0
  firebase_analytics: ^11.5.0
  firebase_crashlytics: ^4.3.7

Xcode 16.3

### Firebase Core version

3.14.0

### Flutter Version

3.27.3

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.6.1
Flutter SDK 3.27.3
clients 1.0.3+2

dependencies:
- algolia_client_search 1.31.3 [algolia_client_core json_annotation collection]
- algolia_helper_flutter 1.2.0 [algolia_insights algoliasearch collection dio flutter logging meta rxdart]
- algolia_insights 1.0.2 [algolia_client_insights collection flutter hive logging meta path_provider rxdart uuid]
- align_positioned 5.0.1 [matrix4_transform flutter]
- app_links 6.4.0 [flutter app_links_linux app_links_platform_interface app_links_web]
- auto_route 9.3.0+1 [flutter path web collection meta]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- carousel_slider_plus 7.1.0 [flutter]
- chewie 1.11.3 [cupertino_icons flutter provider video_player wakelock_plus]
- cloud_firestore 5.6.9 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 5.5.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 1.0.8
- dotted_border 2.1.0 [flutter path_drawing]
- easy_localization 3.0.7+1 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- file_picker 8.3.7 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file web]
- firebase_ai 2.0.0 [firebase_app_check firebase_auth firebase_core firebase_core_platform_interface flutter http meta web_socket_channel]
- firebase_analytics 11.5.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.6.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.14.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.3.7 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 15.2.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 12.4.7 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_animate 4.5.2 [flutter flutter_shaders]
- flutter_chat_ui 1.6.15 [diffutil_dart equatable flutter flutter_chat_types flutter_link_previewer flutter_parsed_text intl meta photo_view scroll_to_index url_launcher visibility_detector]
- flutter_dropzone 4.2.1 [flutter flutter_dropzone_platform_interface flutter_dropzone_web web]
- flutter_fgbg 0.7.1 [flutter]
- flutter_firebase_chat_core 1.6.8 [cloud_firestore firebase_auth firebase_core flutter flutter_chat_types meta]
- flutter_form_builder 9.7.0 [flutter intl]
- flutter_hooks 0.20.5 [flutter]
- flutter_local_notifications 18.0.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_multi_formatter 2.13.7 [flutter collection base58check bech32]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_staggered_grid_view 0.7.0 [flutter]
- flutter_stripe 11.5.0 [flutter meta stripe_android stripe_ios stripe_platform_interface]
- flutter_stripe_web 6.5.0 [flutter flutter_web_plugins freezed_annotation stripe_platform_interface stripe_js web]
- flutter_svg 2.1.0 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_typeahead 5.2.0 [flutter flutter_keyboard_visibility pointer_interceptor]
- fluttertoast 8.2.12 [flutter flutter_web_plugins web]
- font_awesome_flutter 10.8.0 [flutter]
- form_builder_validators 11.1.2 [flutter flutter_localizations intl]
- geocode 1.0.3 [http]
- geocoding 3.0.0 [flutter geocoding_platform_interface geocoding_android geocoding_ios]
- geolocator 13.0.4 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get_thumbnail_video 0.7.3 [flutter flutter_web_plugins web plugin_platform_interface cross_file]
- google_maps_flutter 2.12.1 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- google_sign_in 6.3.0 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hooks_riverpod 2.6.1 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- infinite_scroll_pagination 5.0.0 [flutter flutter_staggered_grid_view sliver_tools collection meta]
- intl_phone_number_input_perci 0.7.5 [flutter dlibphonenumber equatable collection]
- just_audio 0.9.46 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- lottie 3.3.1 [archive flutter http path vector_math]
- maps_launcher 3.0.0+1 [flutter flutter_web_plugins url_launcher web]
- meta_seo 3.0.9 [flutter]
- mime 2.0.0
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- pinput 5.0.1 [flutter universal_platform]
- reorderables 0.6.0 [flutter]
- responsive_framework 1.5.1 [flutter collection]
- scrollable_positioned_list 0.3.8 [flutter collection]
- shared_preferences 2.5.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- skeletonizer 1.4.3 [flutter]
- sliver_tools 0.2.12 [flutter]
- smooth_page_indicator 1.2.1 [flutter]
- syncfusion_flutter_calendar 27.2.5 [flutter timezone syncfusion_flutter_core syncfusion_flutter_datepicker intl]
- timelines_plus 1.0.6 [flutter]
- tuple 2.0.2
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_strategy 0.3.0 [flutter_web_plugins]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- video_player 2.9.5 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_web 2.3.5 [flutter flutter_web_plugins video_player_platform_interface web]
- visibility_detector 0.4.0+2 [flutter]
- voo_shared 0.0.1 [flutter hooks_riverpod flutter_hooks responsive_framework cloud_firestore firebase_storage flutter_chat_ui tuple easy_localization intl geocode geocoding geolocator google_maps_flutter fluttertoast flutter_dropzone image_picker dotted_border video_player flutter_fgbg cached_network_image shared_preferences loading_icon_button]
- week_day_picker 1.1.3 [flutter intl collection]

dev dependencies:
- auto_route_generator 9.3.1 [build source_gen analyzer path build_runner code_builder dart_style xml args glob package_config auto_route]
- build_runner 2.4.15 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web web_socket_channel yaml]
- flutter_launcher_icons 0.14.3 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 5.0.0 [lints]
- flutter_native_splash 2.4.4 [args flutter flutter_web_plugins html image meta path universal_io xml yaml ansicolor]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- freezed 2.5.8 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation dart_style]
- json_annotation 4.9.0 [meta]
- json_serializable 6.9.5 [analyzer async build build_config collection dart_style json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- riverpod_generator 2.6.4 [analyzer build build_config collection crypto meta path riverpod_analyzer_utils riverpod_annotation source_gen]
- riverpod_lint 2.6.4 [analyzer analyzer_plugin collection custom_lint_builder meta path riverpod riverpod_analyzer_utils source_span yaml]

transitive dependencies:
- _fe_analyzer_shared 80.0.0 [meta]
- _flutterfire_internals 1.3.56 [collection firebase_core firebase_core_platform_interface flutter meta]
- algolia_client_core 1.31.3 [dio]
- algolia_client_insights 1.31.3 [algolia_client_core json_annotation collection]
- algoliasearch 1.31.3 [algolia_client_core algolia_client_search algolia_client_insights json_annotation collection]
- analyzer 7.3.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.12.0 [analyzer collection dart_style meta pub_semver yaml path]
- ansicolor 2.0.3
- app_links_linux 1.0.3 [flutter app_links_platform_interface gtk]
- app_links_platform_interface 2.0.2 [flutter plugin_platform_interface]
- app_links_web 1.0.4 [flutter flutter_web_plugins app_links_platform_interface web]
- archive 4.0.7 [crypto path posix]
- args 2.7.0
- async 2.11.0 [collection meta]
- audio_session 0.1.25 [flutter flutter_web_plugins rxdart meta]
- base58check 2.0.0 [crypto collection]
- bech32 0.2.2 [convert]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.4 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.4 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.5 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- ci 0.1.0
- cli_util 0.4.2 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.6.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 4.4.9 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]
- cloud_functions_platform_interface 5.7.0 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.11.0 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- collection 1.19.0
- convert 3.1.2 [typed_data]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.6 [typed_data]
- csslib 1.0.2 [source_span]
- custom_lint 0.7.3 [analyzer analyzer_plugin args async ci cli_util collection custom_lint_core freezed_annotation json_annotation meta package_config path pub_semver pubspec_parse rxdart uuid yaml]
- custom_lint_builder 0.7.3 [analyzer analyzer_plugin collection custom_lint custom_lint_core custom_lint_visitor glob hotreloader meta package_config path pubspec_parse rxdart]
- custom_lint_core 0.7.1 [analyzer analyzer_plugin collection custom_lint_visitor glob matcher meta package_config path pubspec_parse source_span uuid yaml]
- custom_lint_visitor 1.0.0+7.3.0 [analyzer]
- dart_style 3.0.1 [analyzer args collection package_config path pub_semver source_span yaml]
- dbus 0.7.11 [args ffi meta xml]
- diffutil_dart 4.0.1
- dio 5.8.0+1 [async collection http_parser meta path dio_web_adapter]
- dio_web_adapter 2.1.1 [dio http_parser meta web]
- dlibphonenumber 1.1.37 [protobuf meta fixnum]
- easy_logger 0.0.2 [flutter]
- equatable 2.0.7 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.1 [meta path]
- file_selector_linux 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+4 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 4.4.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+13 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_app_check 0.3.2+6 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check_platform_interface 0.1.1+6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.2.0+10 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]
- firebase_auth_platform_interface 7.7.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.15.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.23.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.8.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.6.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.10.5 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_storage_platform_interface 5.2.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.10.14 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http meta web]
- fixnum 1.1.1
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_chat_types 3.6.2 [equatable json_annotation meta]
- flutter_dropzone_platform_interface 2.2.0 [flutter plugin_platform_interface]
- flutter_dropzone_web 4.2.0 [flutter flutter_web_plugins flutter_dropzone_platform_interface web]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_link_previewer 3.2.2 [flutter flutter_chat_types flutter_linkify html http linkify meta url_launcher]
- flutter_linkify 6.0.0 [flutter linkify]
- flutter_local_notifications_linux 5.0.0 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 8.0.0 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_parsed_text 2.2.1 [flutter]
- flutter_plugin_android_lifecycle 2.0.28 [flutter]
- flutter_riverpod 2.6.1 [collection flutter meta riverpod state_notifier]
- flutter_shaders 0.1.3 [flutter vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- frontend_server_client 4.0.0 [async path]
- geocoding_android 3.3.1 [flutter geocoding_platform_interface]
- geocoding_ios 3.0.1 [flutter geocoding_platform_interface]
- geocoding_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- geolocator_android 4.6.2 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.13 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.6 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 4.1.3 [flutter flutter_web_plugins geolocator_platform_interface web]
- geolocator_windows 0.2.5 [flutter geolocator_platform_interface]
- glob 2.1.3 [async collection file path string_scanner]
- google_identity_services_web 0.3.3+1 [meta web]
- google_maps 8.1.1 [meta web]
- google_maps_flutter_android 2.16.1 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.15.2 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.11.1 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.12 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform web]
- google_sign_in_android 6.2.1 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.9.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.5.0 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4+4 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- graphs 2.3.2 [collection]
- gtk 2.1.0 [ffi flutter meta]
- hive 2.2.3 [meta crypto]
- hotreloader 4.3.0 [collection logging path stream_transform vm_service watcher]
- html 0.15.6 [csslib source_span]
- http 1.4.0 [async http_parser meta web]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- image 4.5.4 [archive meta xml]
- image_picker_android 0.8.12+23 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.6 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+2 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+2 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.1 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- intl 0.19.0 [clock meta path]
- io 1.0.5 [meta path string_scanner]
- js 0.7.1
- just_audio_platform_interface 4.5.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.15 [just_audio_platform_interface flutter flutter_web_plugins web]
- leak_tracker 10.0.7 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.8 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- linkify 5.0.0
- lints 5.1.1
- loading_icon_button 0.0.7 [flutter rxdart]
- logging 1.3.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- matrix4_transform 4.0.1 [flutter]
- meta 1.15.0
- nested 1.0.0 [flutter]
- octo_image 2.1.0 [flutter]
- package_config 2.2.0 [path]
- package_info_plus 8.3.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- package_info_plus_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.17 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.0.2 [meta]
- photo_view 0.15.0 [flutter]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pointer_interceptor 0.10.1+2 [flutter flutter_web_plugins pointer_interceptor_ios pointer_interceptor_platform_interface pointer_interceptor_web]
- pointer_interceptor_ios 0.10.1 [flutter plugin_platform_interface pointer_interceptor_platform_interface]
- pointer_interceptor_platform_interface 0.10.0+1 [flutter plugin_platform_interface]
- pointer_interceptor_web 0.10.2+1 [flutter flutter_web_plugins plugin_platform_interface pointer_interceptor_platform_interface web]
- pool 1.5.1 [async stack_trace]
- posix 6.0.2 [ffi meta path]
- protobuf 4.0.0 [collection fixnum meta]
- provider 6.1.5 [collection flutter nested]
- pub_semver 2.2.0 [collection]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- riverpod 2.6.1 [collection meta stack_trace state_notifier]
- riverpod_analyzer_utils 0.5.9 [analyzer collection crypto custom_lint_core freezed_annotation meta path source_span]
- riverpod_annotation 2.6.1 [meta riverpod]
- rxdart 0.28.0
- sanitize_html 2.1.0 [html meta]
- scroll_to_index 3.0.1 [flutter]
- shared_preferences_android 2.4.10 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.3 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 3.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- source_gen 2.0.0 [analyzer async build dart_style glob path pub_semver source_span yaml]
- source_helper 1.3.5 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.1 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.0 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.4+6 [synchronized path meta]
- sqflite_darwin 2.4.1+1 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.12.0 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.1
- string_scanner 1.3.0 [source_span]
- stripe_android 11.5.0 [flutter]
- stripe_ios 11.5.0 [flutter]
- stripe_js 6.4.0 [freezed_annotation json_annotation meta web]
- stripe_platform_interface 11.5.0 [flutter freezed_annotation json_annotation meta plugin_platform_interface]
- syncfusion_flutter_core 27.2.5 [vector_math flutter]
- syncfusion_flutter_datepicker 27.2.5 [flutter intl syncfusion_flutter_core]
- synchronized 3.3.0+3
- term_glyph 1.2.1
- test_api 0.7.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.4 [path]
- timing 1.0.2 [json_annotation]
- typed_data 1.4.0 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- universal_platform 1.1.0
- url_launcher_android 6.3.16 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.3 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.4.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.4 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.18 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.16 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- video_player_android 2.8.3 [flutter video_player_platform_interface]
- video_player_avfoundation 2.7.1 [flutter video_player_platform_interface]
- video_player_platform_interface 6.3.0 [flutter plugin_platform_interface]
- vm_service 14.3.0
- wakelock_plus 1.3.2 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus web]
- wakelock_plus_platform_interface 1.2.3 [flutter plugin_platform_interface meta]
- watcher 1.1.1 [async path]
- web 1.1.1
- web_socket 1.0.1 [web]
- web_socket_channel 3.0.3 [async crypto stream_channel web web_socket]
- win32 5.10.1 [ffi]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]



```

</details>

### Additional context and comments

I have 2 flutter apps using one firebase project (including this on with firebase_crashlytics error). The other app works fine on firebase_crashlytics by doing exactly same steps following https://firebase.google.com/docs/crashlytics/get-started?platform=flutter. I don't know if it's because there's already another app under the firebase project.
