### ISSUE TITLE
🐛 [firebase_auth] : Email Link Sign-In doesn't work with custom domains with path prefix

### ISSUE THREAD

**Issue by thearaks** [firebase/flutterfire#5051]
## Bug report

I configured a custom domain with a path prefix in Dynamic Links.
The Dynamic Links feature works fine, but if I try to use the custom domain with Firebase Authentication to login via email link the generated link is invalid.

### Steps to reproduce

1. Add a custom domain with path prefix in Firebase Dynamic Links console, i.e. `custom.domain/dl`
2. Add the `custom.domain`to the authorized domains under Firebase Authentication console (sign-in methods tab)
3. Request a login with email with the following code:
```dart
FirebaseAuth.instance.sendSignInLinkToEmail(
      email: 'example@email.com',
      actionCodeSettings: ActionCodeSettings(
        dynamicLinkDomain: 'custom.domain',
        url: 'https://custom.domain/dl/signIn',
        handleCodeInApp: true,
        iOSBundleId: 'com.example.app',
        androidPackageName: 'com.example.app',
        androidInstallApp: true,
        androidMinimumVersion: "0",
      ),
    )
```
4. The email is sent, the generated dynamic link is intercepted by the app but it's invalid and gets discarded

### Expected behavior

The generated sign in link should be using the custom domain **and** the path prefix.

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale it-IT)
```

</details>

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

Sorry, it's not working!

```
The ".dart_tool/package_config.json" file is not recognized by "pub" version, please run "pub get".
pub finished with exit code 65
```

</details>

**Comment by markusaksli-nc** [comment]
Hi @thearaks 
Please run `flutter pub get` and then `flutter pub deps -- --style=compact`
Thank you

**Comment by thearaks** [comment]
@markusaksli-nc as I've said... Unfortunately it's not working:
```shell
➜  app git:(develop) ✗ flutter pub get
Warning: You are using these overridden dependencies:                   
! flutter_svg 0.19.1                                                    
Running "flutter pub get" in app...                             1,2s
➜  app git:(develop) ✗ flutter pub deps -- --style=compact
The ".dart_tool/package_config.json" file is not recognized by "pub" version, please run "pub get".
pub finished with exit code 65
➜  app git:(develop) ✗ 
```

Anyway, I'm using the latest FlutterFire packages, with the only exception being `firebase_auth_platform_interface`:
```yaml
dependencies:
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  firebase_messaging: ^8.0.0-dev.14
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  firebase_crashlytics: ^0.4.0+1
  firebase_remote_config: ^0.6.0
  firebase_dynamic_links: ^0.7.0+1
dependency_overrides:
  firebase_auth_platform_interface:
    git:
      url: git://github.com/jyardin/flutterfire.git
      ref: email-link-signin-fix
      path: packages/firebase_auth/firebase_auth_platform_interface/
```
Because the login with email link is not working on Android using the current non-patched official plugin release (see #4711).
