### ISSUE TITLE
🐛 [firebase_analytics] page/screen views are not being sent for web

### ISSUE THREAD

**Issue by steebchen** [firebase/flutterfire#8403]
This is the same issue as #4910, but it was closed and locked. Ideally we could maybe re-open this one as it has more context and more people watching.

Basically, with the latest firebase_analytics: ^9.1.3 page/screen views are still not being sent properly. Yes, it might show in the debugger, but they never show up in Google Analytics, and you can verify this by running a Flutter app in the browser and not seeing any events sent to GA.

The best easy reproduction I can give is the project I'm working on, which is using the latest firebase_analytics version.

In the following video, you can see that:
1) On page load, there is a page_view event sent
2) When I navigate between pages, there are NO events send (this works on iOS+Android)
3) Other events, even custom ones, work, as shown towards the end of the video with the custom event 'connect'

https://user-images.githubusercontent.com/5013932/161806241-1d29c263-3ac1-436a-86c8-2f63e53d6a26.mov

I'm using the observer in the `navigatorObservers` parameter in the `MaterialApp` widget:

```dart
navigatorObservers: [
  FirebaseAnalyticsObserver(analytics: analytics),
],
```

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.0.1-beta.6
  intl: ^0.17.0
  syncfusion_flutter_charts: ^19.1.69+1
  provider: ^5.0.0
  cached_network_image: ^3.0.0
  infinite_scroll_pagination: ^3.1.0
  papercups_flutter: ^2.1.0+1
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.3
  firebase_dynamic_links: ^2.0.9
  firebase_performance: ^0.7.1
  flutter_custom_tabs: ^1.0.3
  sentry_flutter: ^6.0.1
  package_info_plus: ^1.0.6
  url_launcher: ^6.0.20
  purchases_flutter: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: ^7.0.0-beta.9
  build_runner: ^2.0.1
  json_serializable: ^4.1.0
  flutter_native_splash: ^1.2.0
  flutter_lints: ^1.0.4
```

```
❯ flutter doctor -v         
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.3 21E230 darwin-arm, locale en-DE)
    • Flutter version 2.10.0 at /opt/homebrew/Caskroom/flutter/2.10.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (9 weeks ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/steebchen/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.2.4
    • Dart plugin version 213.7306

[✓] Connected device (5 available)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
