### ISSUE TITLE
🐛 [Firebase_in_app_messaging] is not working if user update app. They need to delete and reinstall

### ISSUE THREAD

**Issue by utkudenis** [firebase/flutterfire#8504]
## Bug report

**Describe the bug**
We have an app with 20 thousand active users. We added the in app messaging part to the app 2 versions ago. However, when the campaign team wanted to use it 2 days ago, very few people received advertisements. When I checked I found that it worked when I deleted and reinstalled the app by chance. There seems to be a bug here that is beyond the developer's control. While push notifs went to 20 thousand users, the ones we sent via in app messaging only reached less than 500 users. Since my first version was updated from the play store, it did not come to me either. When we checked from analytics, the number of daily active users on the mobile side was 2 thousand.

### Steps to reproduce

Add firebase in app messaging to your app. Release it to play store over old version. Update it from play store. 

### Expected behavior

it should work with app update. User should not reinstall :( 
### Sample project

same approach with your documentation. 

---

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19044.1645], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)       
[√] Android Studio (version 2021.1)
[!] Android Studio (version 4.1)
    X Unable to determine bundled Java version.
[√] VS Code (version 1.66.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
version: 3.3.22+564

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  audioplayers: ^0.20.1
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.4
  device_info_plus: ^3.2.2
  dio: ^4.0.4
  double_back_to_close_app: ^2.1.0
  firebase_analytics: ^9.1.2
  firebase_core: ^1.13.1
  firebase_crashlytics: ^2.5.3
  firebase_in_app_messaging: ^0.6.0+8
  firebase_messaging: ^11.2.8
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.0.1
  flutter_cache_manager: ^3.3.0
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_facebook_auth: ^4.1.2
  flutter_html: ^3.0.0-alpha.2
  flutter_inappwebview: ^5.3.2
  flutter_local_notifications: ^9.3.3
  flutter_localizations:
    sdk: flutter
  flutter_native_image: ^0.0.6+1
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  flutter_switch: ^0.3.2
  flutter_typeahead: ^3.2.4
  fluttertoast: ^8.0.9
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.4
  http: ^0.13.4
  image_picker: ^0.8.4+10
  in_app_purchase: ^3.0.0
  intl: ^0.17.0
  intl_phone_field: ^3.0.1
  logger: ^1.1.0
  lottie: ^1.2.2
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.4.0
  path_provider: ^2.0.9
  provider: ^6.0.2
  rive: ^0.8.1
  sentry_flutter: ^6.3.0
  share_plus: ^3.1.0
  shared_preferences: ^2.0.13
  sign_in_with_apple: ^3.3.0
  smooth_star_rating_null_safety: ^1.0.4+2
  step_progress_indicator: ^1.0.2
  storyly_flutter: ^1.19.1
  syncfusion_flutter_datepicker: ^19.4.54
  upgrader: ^3.13.0
  url_launcher: ^6.0.20
  wakelock: ^0.6.1+1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "assets/icons/gradient_background.png"
  adaptive_icon_foreground: "assets/images/logo/launcher_icon_adaptive_fore.png"
  remove_alpha_ios: true
  image_path: "assets/images/logo/ios.png"

```

</details>

---
