### ISSUE TITLE
🐛 [firebase_messaging] Asking for push notifications on launch, poor UX

### ISSUE THREAD

**Issue by ollydixon** [firebase/flutterfire#9000]
```firebase_messaging: ^11.4.2```

It's asking for push notifications on app launch before we call ```Firebase.initializeApp```

Also it seems we cannot switch environments without fully restarting the device :-/

For example, we are trying to create an environment switcher but it fails.

```
 if (EnvironementProvider.isProd()) {
        await Firebase.initializeApp(
          options: ProdFirebaseOptions.currentPlatform,
        );
      } else {
        await Firebase.initializeApp(
          options: DevFirebaseOptions.currentPlatform,
        );
      }
```

**Comment by ollydixon** [comment]
@darshankawar for the ``firebase_options`` we got it working but you need to restart app for it to take effect. On Android you need to restart the device 🤦‍♂️ I'm honestly shocked this wasn't something that was included right at the beginning, most of us need to use different flavors for QA, Testing, etc. This is a huge issue.

Re-guarding the push notification, on iOS we don't get the chance to tell the user why we are asking for push notifications. Some app store reviewers will block your app update or release citing poor UX or Feature not-needed. This makes it impossible to use Flutter for iOS since we are forced to use FCM by Android and push notifications are essential.

![IMG_1325](https://user-images.githubusercontent.com/6940726/176626605-67bba236-119e-41b8-b3a9-4625c9ac2289.PNG)

**Comment by darshankawar** [comment]
It seems the push notification is being called before login which should ideally be called after user logs in, as in your case. This may be coming from Firebase / apple itself, as I am not sure if `firebase_messaging` would have control on this. Maybe you can check the usage of push notification and if there's a way to register it after your login implementation.

**Comment by darshankawar** [comment]
@ollydixon 
Can you provide sample code along with how are you calling push notification service ? 

> /if they are logged in without calling any firebase actions before hand

Can you provide an example of this ?

**Comment by ollydixon** [comment]
@darshankawar I don't understand, you want me to provide a Firebase account and full app setup?

**Comment by darshankawar** [comment]
From the screenshot you shared, it looks like the popup is displayed on login screen and not after user logs in which should be the expected behavior. I am trying to understand how is it being triggered and hence would like to see the code that triggers this push notification.
Are you also using flutter_local_notifications ? If not, you may want to take a look at it and implementation to see if it helps to  mitigate this ?

**Comment by ollydixon** [comment]
We tried removing ```flutter_local_notifications``` to see if that was the issue, as we only use it for MacOS and not iOS. Still had the same issue.

**Comment by salahamassi** [comment]
The notification request permission shows directly after you call `requestPermission` 

so for instance of course you can call this method after showing a screen with an explanation of why your app is asking for push notifications and when the user clicks on some button call this method

```dart
FirebaseMessaging.instance.requestPermission(
        alert: true,
        announcement: false,
        badge: true,
        carPlay: false,
        criticalAlert: false,
        provisional: false,
        sound: true,
      );
```

**Comment by ollydixon** [comment]
@salahamassi thanks for the input but we took this out and re-ran an app install from fresh; still getting the dialog :-/

**Comment by darshankawar** [comment]
check [this](https://github.com/firebase/flutterfire/issues/5897) issue and underlying comments and see if they help.

**Comment by ollydixon** [comment]
@darshankawar it's what @salahamassi recommended, but it didn't work; still getting asked on app launch.

**Comment by darshankawar** [comment]
@ollydixon 
Can you provide `pubspec.yaml` ? Are you using any other notification library like one signal ?

**Comment by ollydixon** [comment]
@darshankawar it's a fairly large project.

```
flutter:
    sdk: flutter
  sizer: ^2.0.15
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  flutter_bounce: ^1.1.0
  flutter_spinkit: ^5.1.0
  provider: ^6.0.2
  lottie: ^1.2.2
  pinput: ^2.1.4
  json_serializable: ^6.1.5
  build_runner: ^2.1.7
  json_annotation: ^4.4.0
  path_provider: ^2.0.9
  localstorage: ^4.0.0+1
  url_launcher: ^6.0.20
  flutter_svg: ^1.1.1
  universal_html: ^2.0.8
  dotted_border: ^2.0.0+2
  file_picker: ^4.6.1
  desktop_drop: ^0.3.3 
  dio: ^4.0.4
  image: ^3.1.3
  throttling: ^1.0.0
  syncfusion_flutter_sliders: ^20.1.59
  syncfusion_flutter_datepicker: ^20.1.59
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  mask_text_input_formatter: ^2.1.0
  uuid: ^3.0.6
  timeago: ^3.2.2
  flutter_markdown: ^0.6.9+1
  mime: ^1.0.1
  filesize: ^2.0.1
  share_plus: ^4.0.5
  metadata_fetch: ^0.4.1
  dart_emoji: ^0.2.0+2
  device_info_plus: ^3.2.3
  jwt_decode: ^0.3.1
  string_similarity: ^2.0.0
  package_info_plus: ^1.4.2
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.2
  file_saver:
    git:
      url: https://github.com/incrediblezayed/file_saver.git
      ref: main
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  flutter_keyboard_visibility: ^5.2.0
  encrypt: ^5.0.1
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  visibility_aware_state: ^1.0.3
  flutter_app_badger: ^1.4.0
  window_manager: ^0.2.3
  platform_device_id: ^1.0.1
  url_strategy: ^0.2.0
  flutter_local_notifications: ^9.5.3+1
  uni_links: ^0.5.1
  local_notifier: ^0.1.5
  windows_taskbar: ^1.0.0
  toggle_switch: ^2.0.1
  audioplayers: ^1.0.0-rc.4
  auto_updater: ^0.1.5
  share_handler: ^0.0.5
  better_player: ^0.0.83
  video_player: ^2.4.4
  chewie: ^1.3.3
  video_player_macos: 1.0.6
  stripe_checkout: ^1.0.0
  linkify: ^4.1.0
```
