### ISSUE TITLE
🐛 [firebase_core] Platform channel not working

### ISSUE THREAD

**Issue by BugsOverBugs** [firebase/flutterfire#9012]
## Bug report

**Describe the bug**
With the lastet `firebase_core 1.19.0` the error `MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)` is thrown.

### Steps to reproduce

I ran pub upgrade to the latest dependecies and after that firebase_core is not working on any platform. Before it works fine. I tested in two projects.

### Sample project

```
E/flutter (19610): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter (19610): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (19610): <asynchronous suspension>
E/flutter (19610): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:353:35)
E/flutter (19610): <asynchronous suspension>
E/flutter (19610): #2      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:31:23)
E/flutter (19610): <asynchronous suspension>
E/flutter (19610): #3      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter (19610): <asynchronous suspension>
E/flutter (19610): #4      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)
E/flutter (19610): <asynchronous suspension>
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- cloud_firestore_platform_interface 5.5.9 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.18 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_analytics_platform_interface 3.1.9 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+16 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_app_check_platform_interface 0.0.4+9 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.5+15 [firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.3.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.18 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.4.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_dynamic_links_platform_interface 0.2.3+5 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.5.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.4.3 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.9 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.2.18 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
```

</details>

---

**Comment by Zazo032** [comment]
I'm also getting an error on latest update:
```
Installing build/app/outputs/flutter-apk/app.apk...
E/flutter ( 7616): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
E/flutter ( 7616): #0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:173:5)
E/flutter ( 7616): #1      Firebase.app (package:firebase_core/src/firebase.dart:53:41)
E/flutter ( 7616): #2      FirebaseCrashlytics.instance (package:firebase_crashlytics/src/firebase_crashlytics.dart:33:55)
E/flutter ( 7616): #3      main.<anonymous closure> (package:craftos/main.dart:47:27)
E/flutter ( 7616): #4      _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter ( 7616): #5      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter ( 7616): #6      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1832:18)
E/flutter ( 7616): #7      _Zone._processUncaughtError (dart:async/zone.dart:1109:14)
E/flutter ( 7616): #8      _CustomZone.handleUncaughtError (dart:async/zone.dart:1312:5)
E/flutter ( 7616): #9      Future._propagateToListeners (dart:async/future_impl.dart:680:16)
E/flutter ( 7616): #10     Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter ( 7616): #11     _completeOnAsyncError (dart:async-patch/async_patch.dart:287:13)
E/flutter ( 7616): #12     main.<anonymous closure> (package:craftos/main.dart)
E/flutter ( 7616): <asynchronous suspension>
```
It worked fine before updating to latest version, though

**Comment by Chetan-Goyal** [comment]
Old version is working. 

If anybody facing this issue, they can downgrade their firebase_core version to `1.17.1` using this syntax: 
`firebase_core: 1.17.1`. 

It should work atleast for now until the patch is released in the latest version.

**Comment by Zazo032** [comment]
Version `1.18.0` also works, the broken one is `1.19.0`

**Comment by alelav79** [comment]
Same problem with

1.18.0

:(

**Comment by alelav79** [comment]
> Version `1.18.0` also works, the broken one is `1.19.0`

Same problem with

1.18.0

:(

**Comment by BugsOverBugs** [comment]
> > Version `1.18.0` also works, the broken one is `1.19.0`
> 
> Same problem with
> 
> 1.18.0
> 
> :(

I do not, it works for me: `flutter clean`, than add `1.18.0` without `^` and `pub get`

**Comment by alelav79** [comment]
> > > Version `1.18.0` also works, the broken one is `1.19.0`
> > 
> > 
> > Same problem with
> > 1.18.0
> > :(
> 
> I do not, it works for me: `flutter clean`, than add `1.18.0` without `^` and `pub get`

Edited pubcpec.yaml

with

  firebase_core: 1.18.0

and in CLI

flutter clean
flutter packages get

Question : What does mean "^" before major ?

**Comment by saileshbro** [comment]
@alelav79 try doing `flutter pub cache clean` and `flutter packages get` with v `1.18.0` I fixed mine that way

**Comment by alelav79** [comment]
Thanks fo all !!!

**Comment by darshankawar** [comment]
@BugsOverBugs and everyone in this thread facing this issue.

The latest plugin's changelog says `Bump Firebase iOS SDK to 9.2.0` , so in your ios/podfile, if you have below entry and is pointing to `8.15.0` for example, can you try to update it to `9.2.0` and try again ?

`git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag =>`

**Comment by Zazo032** [comment]
@darshankawar our app doesn't support iOS, but it's still not working on Android

**Comment by saileshbro** [comment]
@darshankawar the issue is with Android as well.

**Comment by Lyokone** [comment]
Hi, this error is probably due to the migration of Firebase Core to use Pigeon (and thus new MethodChannels).
Has anyone of you tried to run `flutter clean` before running the app?

**Comment by Lyokone** [comment]
Could you send a copy of your pubspec.yaml?

**Comment by Zazo032** [comment]
```yaml
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  aad_oauth:
    git:
      ref: flutter_web
      url: https://github.com/Zazo032/aad_oauth.git
  badges: ^2.0.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  camerawesome: ^0.3.3
  carousel_slider: ^4.1.1
  custom_image_picker:
    git:
      url: https://github.com/Zazo032/custom_image_picker.git
  dio: ^4.0.6
  dio_firebase_performance:
    git:
      ref: patch-1
      url: https://github.com/Zazo032/dio_firebase_performance.git
  dio_smart_retry: ^1.2.0
  equatable: ^2.0.3
  feedback: ^2.5.0
  firebase_analytics: ^9.1.11
  firebase_core: 1.18.0
  firebase_crashlytics: ^2.8.3
  firebase_performance: ^0.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_html: ^3.0.0-alpha.5
  flutter_image_slideshow: ^0.1.2
  flutter_localizations:
    sdk: flutter
  flutter_signature_pad: ^3.0.1
  flutter_tabler_icons: ^1.1.1
  font_awesome_flutter: ^10.1.0
  gallery_saver: ^2.3.2
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  mobile_scanner: ^2.0.0
  open_file: ^3.2.1
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  photo_view: ^0.14.0
  slide_to_act: ^2.0.1
  upgrader: ^4.4.0
  url_launcher: ^6.1.4
  url_strategy: ^0.2.0

dependency_overrides:
  flutter_webview_plugin:
    git: https://github.com/Zazo032/flutter_webview_plugin

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3+1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  very_good_analysis: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
```

**Comment by Zazo032** [comment]
This is the initialization part of the app:

```dart
void main() {
  runZonedGuarded(
    () async {
      WidgetsFlutterBinding.ensureInitialized();
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      if (!kIsWeb) {
        FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
      }
      BlocOverrides.runZoned(
        () => runApp(const FlutterApp()),
        blocObserver: AppBlocObserver(),
      );
    },
    (error, stack) {
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    },
  );
}
```

**Comment by Lyokone** [comment]
Could you try with 
```
  firebase_core: 1.19.0
```

and maybe If it doesn't work add this:
```
  firebase_core_platform_interface: 4.4.1
```

I thinks it's related to a transitive dependency not being updated

**Comment by Zazo032** [comment]
Same result after adding that platform interface to the pubspec. By checking the pubspec.yaml, seems like it's already using that version in 1.18

**Comment by Lyokone** [comment]
We have released version 1.19.1 of `firebase_core` that should solve the issue. Let us know if everything is good now :)

**Comment by Zazo032** [comment]
It seems to be working now. Thanks for the quick fix!

**Comment by Lyokone** [comment]
An unexpected issue with the release process, we'll try to keep an eye on that next time 👍

**Comment by dancamdev** [comment]
I'm still facing the issue with the following dependencies:

```yaml
cloud_firestore: ^3.2.1 
firebase_auth: ^3.4.1
firebase_core: ^1.19.1
```
