### ISSUE TITLE
🐛 [firebase_auth] Firebase Auth Web loses persistence after upgrading to the latest version

### ISSUE THREAD

**Issue by jomiplaz** [firebase/flutterfire#9089]
## Bug report

**Describe the bug**
Firebase Auth Web loses persistence after upgrading to the latest version.

**Steps to reproduce**
1. Login
2. Refresh the page

**Comment by sgehrman** [comment]
This is a show-stopper.  I can't release a new build until this is fixed.

$ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on Debian GNU/Linux 11 (bullseye) 5.10.0-16-amd64, locale en_US.UTF-8)
    • Flutter version 3.0.5 at /home/steve/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (31 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /home/steve/Android/Sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • Java binary at: /home/steve/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.15.2
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/steve/android-studio
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 11 (bullseye) 5.10.0-16-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by sgehrman** [comment]
Nothing fancy in my code.  I listen to the authStateChanges stream.  I get null user on browser refresh.  I can login, I see the user, then refresh and I get back null for user.

**Comment by fanchungchit** [comment]
Same issue found here.
I've also tried to downgrade the package.
Before:
firebase_core: ^1.19.2
firebase_auth: ^3.4.2
Now:
firebase_core: 1.19.0
firebase_auth: 3.4.0

The result is getting this error.
TypeError: Cannot read properties of undefined (reading 'auth')
Which only happen on web.

**Comment by cspyo** [comment]
I solved a issue similar to this, following steps.

1. Delete your `pubspec.lock` file

2. Edit `pubspec.yaml` to downgrade the packages
```
firebase_auth: 3.4.1
firebase_auth_platform_interface: 6.3.1
firebase_core: 1.19.1
firebase_core_web: 1.6.6
```
  
3. Add this line in your `main`
```
if (kIsWeb) {
    await FirebaseAuth.instance.authStateChanges().first;
  }
```

You can get auth also after pressing a refresh button on Web.

**Comment by sgehrman** [comment]
I'm waiting for the update.  Is this a high priority?

**Comment by darshankawar** [comment]
The root cause seems to be mentioned here: https://github.com/firebase/flutterfire/issues/9117#issuecomment-1187305487
A fix for this can be followed up here: https://github.com/firebase/flutterfire/pull/9138

**Comment by fballan93** [comment]
My web app broke after updating to this latest version . im glade to see this reported . any ETA for the fix

**Comment by mrleesin** [comment]
Same issue

**Comment by woutervanwijk** [comment]
Same here. I'm really amazed how bad QU apparently is that this bug is not catched in the process. It's a big one

**Comment by sgehrman** [comment]
Another good example of the more tests a code base has, the worse the quality. Coders spent too much time writing tests, and not enough time writing quality code. And they use the tests as an excuse for sloppiness as long as their tests pass. This bug is obvious. Should never have been released.

**Comment by mklepaczko** [comment]
Same here for web

**Comment by woutervanwijk** [comment]
> Another good example of the more tests a code base has, the worse the quality. Coders spent too much time writing tests, and not enough time writing quality code. And they use the tests as an excuse for sloppiness as long as their tests pass. This bug is obvious. Should never have been released.

Fully agree, it's a mess. And it's not the first time

**Comment by cedvdb** [comment]
> Another good example of the more tests a code base has, the worse the quality. Coders spent too much time writing tests, and not enough time writing quality code. And they use the tests as an excuse for sloppiness as long as their tests pass. This bug is obvious. Should never have been released.

I cannot disagree more. 
  - The tests are just written in a way that renders them useless.
  - Last time I checked, there was no integration test for phone authentication on the web
 

So the issue is: there is no test.

**Comment by organicinternet** [comment]
#9138 persists for me using these dependency_overrides:

```
  firebase_auth:
    git:
      url: https://github.com/firebase/flutterfire.git
      path: packages/firebase_auth/firebase_auth
      ref: "@russell/auth-9117"
  firebase_auth_platform_interface:
    git:
      url: https://github.com/firebase/flutterfire.git
      path: packages/firebase_auth/firebase_auth_platform_interface
      ref: "@russell/auth-9117"
  firebase_auth_web:
    git:
      url: https://github.com/firebase/flutterfire.git
      path: packages/firebase_auth/firebase_auth_web
      ref: "@russell/auth-9117"
  firebase_core_platform_interface:
    git:
      url: https://github.com/firebase/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: "@russell/auth-9117"

```
