### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] Caused by java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by ChurikiTenna** [firebase/flutterfire#9439]
## Bug report

**Describe the bug**
My app crashed immediately after launch when installed from Google Play.
This does not happen in development.

Error stack:
```

Fatal Exception: java.lang.ExceptionInInitializerError

keyboard_arrow_up
com.google.android.gms.measurement.internal.zzij.<init> (zzij.java:34)
com.google.android.gms.measurement.internal.zzge.<init> (zzge.java:3)
com.google.android.gms.measurement.internal.zzge.zzp (zzge.java:4)
com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize (AppMeasurementDynamiteService.java:2)
com.google.android.gms.internal.measurement.zzcx.zza (zzcx.java:4)
com.google.android.gms.internal.measurement.zzdt.run (zzdt.java:12)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923)

Caused by java.lang.RuntimeException
java.lang.NoSuchMethodException: com.google.android.gms.measurement.internal.i.values []

keyboard_arrow_up
java.lang.Enum.enumValues (Enum.java:270)
java.lang.Enum.access$000 (Enum.java:61)
java.lang.Enum$1.create (Enum.java:277)
java.lang.Enum$1.create (Enum.java:275)
libcore.util.BasicLruCache.get (BasicLruCache.java:63)
java.lang.Enum.getSharedConstants (Enum.java:289)
java.lang.Class.getEnumConstantsShared (Class.java:2428)
java.util.EnumMap.getKeyUniverse (EnumMap.java:755)
java.util.EnumMap.<init> (EnumMap.java:138)
com.google.android.gms.measurement.internal.zzai.<init> (zzai.java:7)
com.google.android.gms.measurement.internal.zzai.<clinit> (zzai.java:3)
com.google.android.gms.measurement.internal.zzij.<init> (zzij.java:34)
com.google.android.gms.measurement.internal.zzge.<init> (zzge.java:3)
com.google.android.gms.measurement.internal.zzge.zzp (zzge.java:4)
com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize (AppMeasurementDynamiteService.java:2)
com.google.android.gms.internal.measurement.zzcx.zza (zzcx.java:4)
com.google.android.gms.internal.measurement.zzdt.run (zzdt.java:12)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923)

Caused by java.lang.NoSuchMethodException
com.google.android.gms.measurement.internal.i.values []

keyboard_arrow_up
arrow_right
java.lang.Class.getMethod (Class.java:2072)
java.lang.Class.getDeclaredMethod (Class.java:2050)
java.lang.Enum.enumValues (Enum.java:267)
java.lang.Enum.access$000 (Enum.java:61)
java.lang.Enum$1.create (Enum.java:277)
java.lang.Enum$1.create (Enum.java:275)
libcore.util.BasicLruCache.get (BasicLruCache.java:63)
java.lang.Enum.getSharedConstants (Enum.java:289)
java.lang.Class.getEnumConstantsShared (Class.java:2428)
java.util.EnumMap.getKeyUniverse (EnumMap.java:755)
java.util.EnumMap.<init> (EnumMap.java:138)
com.google.android.gms.measurement.internal.zzai.<init> (zzai.java:7)
com.google.android.gms.measurement.internal.zzai.<clinit> (zzai.java:3)
com.google.android.gms.measurement.internal.zzij.<init> (zzij.java:34)
com.google.android.gms.measurement.internal.zzge.<init> (zzge.java:3)
com.google.android.gms.measurement.internal.zzge.zzp (zzge.java:4)
com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize (AppMeasurementDynamiteService.java:2)
com.google.android.gms.internal.measurement.zzcx.zza (zzcx.java:4)
com.google.android.gms.internal.measurement.zzdt.run (zzdt.java:12)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923)
```

### Steps to reproduce

install and open app from:
https://play.google.com/store/apps/details?id=com.hanahusa.actually_flutter

### Expected behavior

App works normally.

## Additional context

My pubspec.yaml:
```

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_staggered_grid_view: ^0.6.2
  firebase_core: ^1.21.1
  firebase_analytics: ^9.3.3
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  firebase_storage: ^10.3.7
  google_sign_in: ^5.1.0
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.1
  url_launcher: ^6.0.12
  image_picker: ^0.8.4
  cached_network_image: ^3.2.0
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0
  flutter_image_compress: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  transparent_image: ^2.0.0
  cupertino_icons: ^1.0.2
  zoom_widget: ^0.2.1
  advance_pdf_viewer: ^2.0.0
  permission_handler: ^10.0.0
  flutter_colorpicker: ^1.0.3
  dotted_border: ^2.0.0+2
  screenshot: ^1.2.3
  image: ^3.2.0
  pdf: ^3.8.1
  printing: ^5.9.1
  share_plus: ^4.0.10
  path_provider: ^2.0.11
  file_picker: ^5.0.1
  pdf_render: ^1.1.0
  webview_flutter: ^3.0.4
  google_mobile_ads: ^2.0.1
  firebase_crashlytics: ^2.8.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (6 available)
    ! Error: Sota’s iPad is busy: Fetching debug symbols for Sota’s iPad. Xcode will continue when Sota’s
      iPad is finished. (code -10)
    ! Error: tenna is not connected. Xcode will continue when tenna is connected. (code -13)
    ! Error: Tenna’s iPad is not connected. Xcode will continue when Tenna’s iPad is connected. (code
      -13)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---
