### ISSUE TITLE
🐛 [cloud_firestore_odm] sub-collections models generation which are a collection on its own is failing

### ISSUE THREAD

**Issue by Purus** [firebase/flutterfire#9617]
## Bug report

**Describe the bug**
Sub-collection models from separate dart file does not seems to be working fine in the root model.

### Steps to reproduce

The root model is below.

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_firestore_odm/cloud_firestore_odm.dart';
import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';

import 'group.dart';

part 'app_user.g.dart';

@JsonSerializable(converters: firestoreJsonConverters)
class AppUser extends Equatable {
  const AppUser({
    required this.id,
    required this.name,
    required this.email,
    required this.photoUrl,
    required this.joinDate,
    this.birthDate,
    this.country,
    this.age = 0,
    this.isOnline = false,
    this.lastOnline,
    this.isAdmin = false,
    this.isActive = true,
    this.gender,
    this.tokens,
  });

  final String id;
  final String name;
  final String email;
  final String photoUrl;
  final Timestamp joinDate;
  final Timestamp? birthDate;
  final int age;
  final bool? isAdmin;
  final bool? isOnline;
  final Timestamp? lastOnline;
  final bool? isActive;
  final String? country;
  final String? gender;
  final List<String>? tokens;

  factory AppUser.fromJson(Map<String, dynamic> json) =>
      _$AppUserFromJson(json);

  Map<String, dynamic> toJson() => _$AppUserToJson(this);

  @override
  List<Object?> get props => [name, email, photoUrl];
}

@Collection<AppUser>('users')
@Collection<AppUser>(
  'users/*/friends',
  prefix: 'Friends',
)
@Collection<Group>('users/*/groups')
final usersRef = AppUserCollectionReference();
```

The other model which has its own collection and also its part of the root model is shared below.

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_firestore_odm/cloud_firestore_odm.dart';
import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';

part 'group.g.dart';

@JsonSerializable(converters: firestoreJsonConverters)
class Group extends Equatable {
  const Group({
    required this.id,
    required this.name,
    required this.description,
    this.image,
    required this.createdTime,
    this.isPinned = false,
    this.isActive = true,
    this.isPrivate = false,
    this.usersCount = 0,
  });

  final String id;
  final String name;
  final String description;
  final String? image;
  final Timestamp createdTime;
  final bool? isPinned;
  final bool? isActive;
  final bool? isPrivate;
  final int usersCount;

  factory Group.fromJson(Map<String, dynamic> json) => _$GroupFromJson(json);

  Map<String, dynamic> toJson() => _$GroupToJson(this);

  @override
  List<Object?> get props => [name];
}

@Collection<Group>('groups')
final groupsRef = GroupCollectionReference();
```

Below is my `build.yml` content.
```yaml
targets:
  $default:
    builders:
      cloud_firestore_odm_generator:
        enabled: true
        generate_for:
          include:
            - lib/*
            - lib/**
            - test_driver/integration/*
            - test_driver/integration/**/*
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/*
            - lib/**
            - test_driver/integration/*
            - test_driver/integration/**/*
        options:
          create_field_map: true
          explicit_to_json: true
          create_factory: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - 'type=lint'
```

Below is the exception after the generation.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/1077735/192114355-771be5bf-df7e-4bcd-994d-67167d7729ac.png">

### Expected behavior

The models should be generated without any issues.

---
