### ISSUE TITLE
🐛  PlatformException when trying to use Firebase analytics from a flutter unit test

### ISSUE THREAD

**Issue by boneill42** [firebase/flutterfire#9622]
## Bug report

**Describe the bug**
When running a unit test via:
```flutter test```

I get the error:
```
Failed to load "/Users/brian/git/klozzit/test/analytics_test.dart": PlatformException(channel-error, Unable to establish connection on channel., null, null)
```

### Steps to reproduce

1.  Create a project with the above dependencies (hypothetically up to date).
2. Then, create a unit test that contains the following:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FFAppState(); // Initialize FFAppState
  runApp(MyApp());
  test('Test logging of a firebase event', () {
    var words = <String, dynamic>{'foo': 'sky'};
    logFirebaseEvent("foo", parameters: words);
  });
}
```

### Expected behavior

I'd expect firebase to initialize properly or give me more insight into what the issue is.

### Flutter doctor

Run `flutter doctor` and paste the output below:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] VS Code (version 1.71.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

### Flutter dependencies
```
➜  klozzit git:(main) ✗ grep firebase pubspec.yaml
  firebase_analytics: ^9.3.6
  firebase_analytics_platform_interface: ^3.3.5
  firebase_analytics_web: ^0.4.2+5
  firebase_auth: ^3.10.0
  firebase_auth_platform_interface: ^6.9.0
  firebase_auth_web: ^4.5.0
  firebase_core: ^1.23.0
  firebase_core_platform_interface: ^4.5.1
  firebase_core_web: ^1.7.2
  firebase_dynamic_links:
  firebase_storage: ^10.3.9
  firebase_storage_platform_interface: ^4.1.17
  firebase_storage_web: ^3.3.7
```
