### ISSUE TITLE
🐛 [FIREBASE_STORAGE] iOS not building application due to non-modular header inside framework

### ISSUE THREAD

**Issue by dshundal94** [firebase/flutterfire#9783]
![image](https://user-images.githubusercontent.com/16771047/197528501-9706b5bd-d77b-4aa1-9226-3e9ddfd7e34f.png)

```
Uncategorized
/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:23:29: error: could not build Objective-C module 'FirebaseCoreExtension'
@_implementationOnly import FirebaseCoreExtension
                            ^
Command EmitSwiftModule failed with a nonzero exit code

```
```
FIRAppInternal.h
#import <FirebaseCore/FIRApp.h>
Include of non-modular header inside framework module 'FirebaseCoreExtension.FIRAppInternal': '[...]/ios/Pods/Headers/Public/FirebaseCore/FIRApp.h'
```
```
Storage.swift
@_implementationOnly import FirebaseCoreExtension
Could not build Objective-C module 'FirebaseCoreExtension'
```

The bug occurs when I try building on a simulator either through VS code or Xcode an iOS app. 

I've tried the following as shown here as well [https://github.com/firebase/flutterfire/issues/9347](https://github.com/firebase/flutterfire/issues/9347): 

```
- Removing pod 'FirebaseFirestore
-  Deleting 1 by 1 the dependencies of pod 'Firebase', modular_headers => true
- flutter clean
- flutter pub get
- pod install
- Changing Build Phase setting from Project to Public for certain headers that were causing the error.
```

**Podfile**

```
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
use_modular_headers!
# # to solve the module maps problem
# pod 'Firebase', :modular_headers => true
# pod 'FirebaseCoreInternal', :modular_headers => true
# pod 'FirebaseCoreExtension', :modular_headers => true
# pod 'GoogleUtilities', :modular_headers => true
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  # might not need this as this causing the error
  # pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
     end
    flutter_additional_ios_build_settings(target)
  end
end

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

```
**pubspec.yaml**

```
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  camera: ^0.10.0+4
  characters: ^1.2.1
  circular_profile_avatar: ^2.0.5
  cloud_firestore: ^4.0.2
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  email_validator: ^2.1.17
  firebase_analytics: ^10.0.2
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  firebase_database: ^10.0.2
  firebase_dynamic_links: ^5.0.2
  firebase_storage: ^11.0.2
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  # flutter_facebook_auth: ^4.4.1+1
  flutter_spinkit: ^5.1.0
  flutter_statusbarcolor_ns: ^0.4.0
  flutter_svg: ^1.1.5
  google_fonts: ^ 3.0.1
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.4
  sign_in_with_apple: ^4.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/iconicNew.png"
  ios: true
  android: true
#  adaptive_icon_background: "assets/background.png"
#  adaptive_icon_foreground: "assets/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/
```

**Flutter doctor**

![image](https://user-images.githubusercontent.com/16771047/197530327-32c19597-baf5-4531-b88f-707a44a90522.png)

If I need to add any additional details let me know.
