### ISSUE TITLE
🐛 [cloud_firestore_odm] movie.dart example code not working

### ISSUE THREAD

**Issue by dark-chocolate** [firebase/flutterfire#9851]
## Bug report

**Describe the bug**

The generated file `movie.g.dart` doesn't generate `_$MovieFieldMap` and `_$CommentFieldMap`. But the [example's generated code](https://github.com/firebase/flutterfire/blob/master/packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.g.dart#L2603) shows these maps to be generated. 

### Steps to reproduce
1. Copy [movie.dart](https://github.com/firebase/flutterfire/blob/master/packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.dart) file. 
2. Run `flutter pub run build_runner build --delete-conflicting-outputs`

### Expected behavior

`_$MovieFieldMap` and `_$CommentFieldMap` should be generated. 

### Additional context

My generated `movie.g.dart` file has `2620` lines but the example one has `2638` lines. 

### Flutter doctor

<details>Flutter doctor<summary>
</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.5.0-10.0.pre.17, on macOS 12.6 21G115 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

My project is a simple hello world which has no file than a basic `main.dart` (untouched) and `movie.dart` (copied from example). 

`pubspec.yaml` file: 

```
environment:
  sdk: '>=2.19.0-81.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.0.3
  cloud_firestore_odm: ^1.0.0-dev.38
  json_annotation: ^4.7.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  cloud_firestore_odm_generator: ^1.0.0-dev.38

  flutter_lints: ^2.0.0
```
