### ISSUE TITLE
🐛 Firebase/Auth: CocoaPods could not find compatible versions for pod "Firebase/Auth":

### ISSUE THREAD

**Issue by Terranic** [firebase/flutterfire#9891]
## Bug report

**Describe the bug**
Build fails for iOS because of conflicting Pods

### Steps to reproduce

Use the following dependencies in flutter´s pubspec.yaml

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter         
  firebase_storage: ^11.0.4
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
```

Result: when typing pod install (even with pod repo update)

pod install
```
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "Firebase/Auth":
In snapshot (Podfile.lock):
Firebase/Auth (= 9.6.0)
```

In Podfile:
```
firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.1.1, which depends on
Firebase/Auth (= 10.0.0)


You have either:
* out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
* changed the constraints of dependency `Firebase/Auth` inside your development pod `firebase_auth`.
  You should run `pod update Firebase/Auth` to apply changes you've made.
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details>
<summary>
doctor --verbose </summary>

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-arm, locale de-DE)
• Flutter version 3.3.7 on channel stable at /Users/cw/dev/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision e99c9c7cd9 (8 days ago), 2022-11-01 16:59:00 -0700
• Engine revision 857bd6b74c
• Dart version 2.18.4
• DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
• Android SDK at /Users/cw/Library/Android/sdk
✗ cmdline-tools component is missing
Run `path/to/sdkmanager --install "cmdline-tools;latest"`
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run `flutter doctor --android-licenses` to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 14B47b
• CocoaPods version 1.11.3

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
• iPhone 14 Pro Max (mobile) • 8BDFFE4F-3D13-4EEC-A19B-183BD14881E5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
• macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
• Chrome (web)               • chrome                               • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
• All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

```

</details>

**Comment by dupuchba** [comment]
I have the same error but with firebase database

**Comment by darshankawar** [comment]
@Terranic 
As the error says:

```
firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.1.1, which depends on
Firebase/Auth (= 10.0.0)
```
Since you are using `firebase_auth` 's latest version ie, 4.1.1, it requires iOS sdk version to be 10.0.0. Can you provide your `pubspec.yaml` ?

Also, try the solutions mentioned in the error message:

```
You have either:
* out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
* changed the constraints of dependency `Firebase/Auth` inside your development pod `firebase_auth`.
  You should run `pod update Firebase/Auth` to apply changes you've made.
```

**Comment by Terranic** [comment]
Thanks. pod repo update does not help. I think because of this SDK dependency conflict, it is not surprising
my pubspec.yaml

```
name: tool3
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.4.0+59

environment:
  sdk: ">=2.18.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  google_fonts: ^3.0.1
  email_validator: ^2.1.17
  speech_to_text: ^6.1.0
  wakelock: ^0.6.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  flutter_tts: ^3.6.0
  webfeed: any
  grouped_list: ^5.1.2
  lottie: ^2.0.0
  path: ^1.8.2


  share_plus: ^6.2.0

  json_annotation: ^4.7.0

  #cached_network_image: any

  url_launcher: any

  firebase_storage: ^11.0.4
  firebase_auth: ^4.1.1
  fluttertoast: ^8.1.1
  cloud_firestore: ^4.0.4
  screen_brightness: ^0.2.2

  mobile_scanner: ^2.0.0
  image_picker: ^0.8.6
  uuid: ^3.0.6
  intl: ^0.17.0
  dots_indicator: ^2.1.0
  camera: ^0.10.0+4
  video_player: ^2.4.7
  led_bulb_indicator: ^0.0.1
  fl_chart: ^0.55.2
  flutter_svg: any
  qr_flutter: ^4.0.0
  #font_awesome_flutter: ^10.2.1
  introduction_screen: ^3.0.2

  string_similarity: ^2.0.0
  flutter_typeahead: ^4.1.1
  collection: any

  http: ^0.13.5
  tuple: ^2.0.1
  page_transition: ^2.0.9

  #chewie: ^1.3.4
  geolocator: ^9.0.2
  flex_color_picker: ^2.6.1
  package_info_plus: ^3.0.1
  #assets_audio_player: ^3.0.5

  adaptive_theme: ^3.1.1
  video_compress: ^3.1.1
  geocoding: ^2.0.5
  animations: ^2.0.7

  timeago: ^3.3.0
  auto_size_text: ^3.0.0
  json_path: ^0.4.2
  modal_bottom_sheet: ^2.1.2
  pdf: any
  receive_sharing_intent: ^1.4.5
  google_mlkit_text_recognition: 0.3.0
  flutter_animate: ^2.0.1
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.2.1
  badges: ^2.0.3
  cached_network_image: ^3.2.2
  flutter_reaction_button: ^2.0.1+2
  showcaseview: ^2.0.0+1
  flutter_cache_manager: ^3.3.0
  image: ^3.1.3
  crypto: ^3.0.2
  gradient_widgets: ^0.6.0

  flutter_image_compress: ^1.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.10.0

  pedantic: ^1.11.1
  # test: ^1.21.4


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo3.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/data/
    - assets/urls/rssfeeds.json
    - assets/media/
    - assets/licenses/
  #  - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Brazilia
      fonts:
        - asset: assets/fonts/Brazilia_Three_CG_Regular.otf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
